### ISSUE TITLE
FusionIO can't be claimed as backend disk

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1062]
When trying to claim a fusion IO device for the backend:

```
2016-10-19 12:02:09 58400 +0200 - all-flash - 11550/140324873807680 - lib/scheduled tasks - 144 - ERROR - Ensure single CHAINED mode - ID 1476871325_CjveuMdd5c - Task ovs.disk.sync_with_reality with params {'storagerouter_guid': u'ca4bade5-0455-4599-b540-ead60a2b918a'} failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 305, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/disk.py", line 161, in sync_with_reality
    disk_info = configuration.pop(alias_name_mapping[alias].replace('/dev/', ''))
KeyError: u'fioa1'
2016-10-19 12:02:09 58700 +0200 - all-flash - 11550/140324873807680 - lib/scheduled tasks - 145 - INFO - Ensure single CHAINED mode - ID 1476871325_CjveuMdd5c - Amount of jobs pending for key ovs_ensure_single_ovs.disk.sync_with_reality: 0
2016-10-19 12:02:09 63500 +0200 - all-flash - 11524/140324873807680 - celery/celery.worker.job - 118 - ERROR - Task albanode.initialize_disk[165b310d-3068-43c7-871b-9026189085d8] raised unexpected: KeyError(u'fioa1',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albanodecontroller.py", line 116, in initialize_disks
    DiskController.sync_with_reality(storagerouter_guid=node.storagerouter_guid)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 305, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/disk.py", line 161, in sync_with_reality
    disk_info = configuration.pop(alias_name_mapping[alias].replace('/dev/', ''))
KeyError: u'fioa1'
```

When trying to claim a NVMe for the backend: works but the disk is not visible in the flexible disk layout as claimed disk.

But this can be related to sync_with_reality not working:

```
2016-10-19 12:06:18 60200 +0200 - all-flash - 11524/140324873807680 - celery/celery.worker.job - 150 - ERROR - Task ovs.disk.sync_with_reality[6b5223b7-277e-4cd7-a97b-cc4a92c46bfb] raised unexpected: KeyError(u'fioa1',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 305, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/disk.py", line 161, in sync_with_reality
    disk_info = configuration.pop(alias_name_mapping[alias].replace('/dev/', ''))
KeyError: u'fioa1'
```

Looking at another backend SSD, I see that it has been claimed for an ASD but we can still assign roles to it.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1064  --> openvstorage-2.7.4-rev.4174.367a607
https://github.com/openvstorage/alba-asdmanager/pull/130 -->openvstorage-sdm-1.6.4-rev.392.1bf9d4b
https://github.com/openvstorage/framework-alba-plugin/pull/247 --> openvstorage-backend 1.7.4-rev.774.c3fdeb0

**Comment by kinvaris** [comment]
PASSED:

Claimed as backend disk:
![](https://i.imagebanana.com/img/eohdco1e/Selection_004.png)

Claimed as role disk:
![](https://i.imagebanana.com/img/qt5vbsu7/Selection_005.png)
