### ISSUE TITLE
Error when upgrading openvstorage-sdm

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1065]
Upgrade openvstorage-sdm did not work. Received the following error message in lib.log:

```
2016-10-19 15:19:04 02200 +0200 - stor-201.be-gen8-1 - 25153/139927081981760 - lib/update - 63 - ERROR - 10.106.2.33    : An unexpected error occurred: Missing fields on diskpartition: aliases

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/tmp/tmp.AEAAGe132f/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/tmp/tmp.AEAAGe132f/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/opt/OpenvStorage/ovs/dal/helpers.py", line 342, in migrate
    new_version = execute(method, base_version, 0)
  File "/opt/OpenvStorage/ovs/dal/helpers.py", line 317, in execute
    version = function(start)
  File "/opt/OpenvStorage/ovs/dal/migration/ovsmigrator.py", line 228, in migrate
    DiskController.sync_with_reality(storagerouter_guid=storagerouter.guid)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 305, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/disk.py", line 187, in sync_with_reality
    DiskController._update_partition(partition, {'state': 'MISSING'})
  File "/opt/OpenvStorage/ovs/lib/disk.py", line 238, in _update_partition
    partition.save()
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 504, in save
    raise MissingMandatoryFieldsException('Missing fields on {0}: {1}'.format(self._classname, ', '.join(invalid_fields)))
MissingMandatoryFieldsException: Missing fields on diskpartition: aliases
```

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1066 --> openvstorage-2.7.4-rev.4178.f4f3317

**Comment by JeffreyDevloo** [comment]
### Information

Bug was introduced due to the change of https://github.com/openvstorage/alba-asdmanager/pull/127.
The DAL disk objects got a new property called 'alias'.
This correct repository for this issue should have been alba-asdmanager repository.

### Steps
- Reverted an environment back to a snapshot running unstable of 26-09
- Added disk roles
- Added backend
- Added vpool
- Added vdisk
- Update packages (starting with SDM packages)

### Output

#### Previously installed packages
- openvstorage                       2.7.3-rev.4022.59fbd9b-1                                 amd64        openvStorage
- openvstorage-backend               1.7.3-rev.713.f2fab03-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.3-rev.713.f2fab03-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.3-rev.713.f2fab03-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.3-rev.4022.59fbd9b-1                                 amd64        openvStorage core
- openvstorage-hc                    1.7.3-rev.713.f2fab03-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-health-check          2.0.0-rev.134.9ef41c0-1                                  amd64        Open vStorage HealthCheck
- openvstorage-sdm                   1.6.3-rev.372.0cfe8a2-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-test                  2.7.3-rev.1012.608f550-1                                 amd64        openvStorage autotest suite
- openvstorage-webapps               2.7.3-rev.4022.59fbd9b-1                                 amd64        openvStorage Web Applications

#### Log

```
2016-11-03 10:55:56 50300 +0100 - ovs-node3 - 3192/140286679541568 - lib/update - 0 - INFO - +++ Starting volumedriver update +++
2016-11-03 10:55:56 50400 +0100 - ovs-node3 - 3192/140286679541568 - lib/update - 1 - INFO - Generating SSH client connections for each storage router
...
2016-11-03 10:56:06 27800 +0100 - ovs-node3 - 3192/140286679541568 - lib/update - 15 - INFO - Services which will be restarted --> ovs-volumedriver_myvpool01, ovs-dtl_myv
pool01, albaproxy_myvpool01, arakoon-voldrv
2016-11-03 10:56:06 27800 +0100 - ovs-node3 - 3192/140286679541568 - lib/update - 16 - INFO - Packages which will be installed --> alba, arakoon, volumedriver-no-dedup-ba
se, volumedriver-no-dedup-server
...
2016-11-03 10:59:07 34500 +0100 - ovs-node3 - 3192/140286679541568 - lib/update - 289 - INFO - +++ Finished updating +++
```

#### New packages

```
- openvstorage                       2.7.3-rev.4022.59fbd9b-1                                 amd64        openvStorage
- openvstorage-backend               1.7.3-rev.713.f2fab03-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.3-rev.713.f2fab03-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.3-rev.713.f2fab03-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.3-rev.4022.59fbd9b-1                                 amd64        openvStorage core
- openvstorage-hc                    1.7.3-rev.713.f2fab03-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-health-check          2.0.0-rev.134.9ef41c0-1                                  amd64        Open vStorage HealthCheck
- openvstorage-sdm                   1.6.4-rev.417.4458c4c-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-test                  2.7.3-rev.1012.608f550-1                                 amd64        openvStorage autotest suite
- openvstorage-webapps               2.7.3-rev.4022.59fbd9b-1                                 amd64        openvStorage Web Applications
```

### Test result

openvstorage-sdm has updated from 1.6.3-rev.372.0cfe8a2-1 to 1.6.4-rev.417.4458c4c-1 without any errors
Test passed.
