### ISSUE TITLE
volume_id is empty for vdisk

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1075]
## Problem description

The volume_id property of my vdisks is empty.

```
In [16]: for vd in VDiskList.get_vdisks():
   ....:     print vd.guid
   ....:     print vd.volume_id
   ....:     
495fbd09-65ba-4b75-8bec-f542cef4e8cf
None
d035bd64-5bb8-4c72-842e-370d3d466fbd
None
```

Both volumes were added using the API (using the gui)

Workers log:

```
2016-10-21 15:42:14 49700 +0200 - ovs-node1 - 17551/140370333439808 - celery/celery.worker.job - 372 - ERROR - Task ovs.vdisk.create_new[3c67db6f-a83d-4af3-a174-b3e6642a1e75] raised unexpected: RuntimeError('got fault response volumeCreate',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/vdisk.py", line 595, in create_new
    node_id=str(storagedriver.storagedriver_id))
RuntimeError: got fault response volumeCreate

```

Volumedriver log

```
2016-10-21 15:42:14 479605 +0200 - ovs-node1 - 941/0x00007f2f9affd700 - volumedriverfs/BackendConnectionInterfaceLogger - 00000000000036bc - error - ~Logger: Exiting write_tag for 3f70bd88-9806-4e2d-9f82-98c2b4b78556
2016-10-21 15:42:14 479630 +0200 - ovs-node1 - 941/0x00007f2f9affd700 - volumedriverfs/BackendInterface - 00000000000036bd - error - do_wrap_: Problem with connection 0x7f2f78002750: invalid inputstream
2016-10-21 15:42:14 479647 +0200 - ovs-node1 - 941/0x00007f2f9affd700 - volumedriverfs/BackendInterface - 00000000000036be - error - do_wrap_: Giving up connection 0x7f2f78002750
2016-10-21 15:42:14 479780 +0200 - ovs-node1 - 941/0x00007f2f9affd700 - volumedriverfs/VolManager - 00000000000036bf - notice - New Volume, VolumeId: 3f70bd88-9806-4e2d-9f82-98c2b4b78556, Namespace: 3f70bd88-9806-4e2d-9f82-98c2b4b7
8556, Size: 0, CreateNamespace: CreateNamespace::T, EXCEPTION
2016-10-21 15:42:14 479808 +0200 - ovs-node1 - 941/0x00007f2f9affd700 - volumedriverfs/VFSLocalNode - 00000000000036c0 - error - create_volume_: Failed to create volume 3f70bd88-9806-4e2d-9f82-98c2b4b78556: invalid inputstream
2016-10-21 15:42:14 479826 +0200 - ovs-node1 - 941/0x00007f2f9affd700 - volumedriverfs/ObjectRegistry - 00000000000036c1 - info - unregister: d7f57694-68c9-4569-bcb5-12032c87fcb7/myvpool01KMHE6QGehL4ftHhN: unregistering 3f70bd88-98
06-4e2d-9f82-98c2b4b78556
2016-10-21 15:42:14 488170 +0200 - ovs-node1 - 941/0x00007f2f9affd700 - volumedriverfs/LockedArakoon - 00000000000036c2 - info - run_sequence: unregister volume succeeded after 1 attempt(s)
2016-10-21 15:42:14 488251 +0200 - ovs-node1 - 941/0x00007f2f9affd700 - volumedriverfs/VFSLocalNode - 00000000000036c3 - error - create_volume_: 3f70bd88-9806-4e2d-9f82-98c2b4b78556: failed to create volume: invalid inputstream
2016-10-21 15:42:14 488351 +0200 - ovs-node1 - 941/0x00007f2f9affd700 - volumedriverfs/XMLRPCTimingWrapper - 00000000000036c4 - error - execute: volumeCreate Caught std::exception: invalid inputstream
2016-10-21 15:42:14 488443 +0200 - ovs-node1 - 941/0x00007f2f9affd700 - volumedriverfs/XMLRPCConnection - 00000000000036c5 - info - operator(): Closing socket 21
2016-10-21 15:42:20 027550 +0200 - ovs-node1 - 941/0x00007f2fbb7fe700 - volumedriverfs/ScrubManager - 00000000000036c6 - info - work_: inspecting parent scrub queue
2016-10-21 15:42:20 027965 +0200 - ovs-node1 - 941/0x00007f2fbb7fe700 - volumedriverfs/ScrubManager - 00000000000036c7 - info - work_: inspecting clone scrub queue
2016-10-21 15:42:20 028091 +0200 - ovs-node1 - 941/0x00007f2fbb7fe700 - volumedriverfs/ScrubManager - 00000000000036c8 - info - collect_scrub_garbage_: collecting garbage
2016-10-21 15:42:20 030665 +0200 - ovs-node1 - 941/0x00007f2fbb7fe700 - volumedriverfs/LockedArakoon - 00000000000036c9 - info - run_sequence: collect garbage succeeded after 1 attempt(s)
2016-10-21 15:42:34 484320 +0200 - ovs-node1 - 941/0x00007f2fb2ffd700 - volumedriverfs/MTServer - 00000000000036ca - info - work: You have 3 connections running 
2016-10-21 15:42:34 484385 +0200 - ovs-node1 - 941/0x00007f2fb2ffd700 - volumedriverfs/MTServer - 00000000000036cb - info - cleanup_threads_locked: Trying to join 3 threads
2016-10-21 15:42:34 484480 +0200 - ovs-node1 - 941/0x00007f2f99ffb700 - volumedriverfs/XMLRPCTimingWrapper - 00000000000036cc - info - execute: Arguments for ListClientConnections are {[vrouter_cluster_id:d7f57694-68c9-4569-bcb5-12032c87fcb7,vrouter_id:myvpool01KMHE6QGehL4ftHhN]}
```

The volumedriver has logged an error (as did framework) whilest creating a vdisk, but the vdisk remains.
## Possible solution

When errors occur during the creation of a vdisk, remove them physically and from the model.
Logging could be improved.

**Comment by JeffreyDevloo** [comment]
### Information

This was an operator error.
The fragment_size for alba backend was set to 1 byte, causing Alba to loop.
Due to the loop, the volumedriver couldn't fetch the necessary information.

Alba team is tackling the issue:
https://github.com/openvstorage/alba/issues/413
