### ISSUE TITLE
vPool creation failed: The mountpoint for vPool already exists

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1080]
During the integration testing we saw this problem:

**In short:** a vpool was being created on node02, while it was being executed on node03. When checking node02, the vpool was not yet created. 

After looking further in the code we saw that this check was performed: https://github.com/openvstorage/framework/blob/1ded3395fcf08e4e1c21fcd39658d2d0e7724ea9/ovs/lib/storagerouter.py#L1420

**Problem:** If the `add_vpool` task is ran on a node where the vpool is already created, it will always fail. 

```
Oct 24 13:42:47 ovs-node03-1604 celery[15718]: 2016-10-24 13:42:47 13700 +0200 - ovs-node03-1604 - 15718/140505165571840 - celery/celery.pool - 3962 - DEBUG - TaskPool: Apply <function _fast_trace_task at 0x7fc9e4407320> (args:('ov
s.storagerouter.add_vpool', 'c32f5c2c-55be-4bda-bf4f-3867b1f689f5', ({u'vpool_name': u'myvpool01', u'fragment_cache_on_write': True, u'storage_ip': u'10.100.199.172', u'readcache_size': 0, u'storagerouter_ip': u'10.100.199.172', u'
config_params': {u'write_buffer': 512, u'sco_size': 4, u'cache_strategy': u'none', u'dedupe_mode': u'non_dedupe', u'cluster_size': 4, u'dtl_transport': u'tcp', u'dtl_mode': u'a_sync'}, u'writecache_size': 4, u'backend_connection_in
fo': {u'username': 'fe166257-a039-4dd0-b6b0-25dc3dbdbddc', u'host': u'10.100.199.171', u'password': u'B@7<*}R\'nQ1vuh2p!l\'y5A:[>l8ba<53[FUu9-b5p*5lp~.N4cjb2kR"A:5qA{=M~N{tKQT9Ye|O2bNe-{,jf6N5xLh-,SIKGb*~B1Uy{s7wiWL|Y,}J569k\';L"N!
U1', 'local': True, u'port': 443, u'backend': {u'metadata': u'mypreset', u'backend': u'ab623ada-55c2-4649-bc05-82656601d73c'}}, u'fragment_cache_on_read': True, u'type': u'alba'},), {}, {'utc': True, u'is_eager': False, 'chord': No
ne, u'group': None, 'args': ({u'vpool_name': u'myvpool01', u'fragment_cache_on_write': True,... kwargs:{})
Oct 24 13:42:47 ovs-node03-1604 celery[15718]: 2016-10-24 13:42:47 13900 +0200 - ovs-node03-1604 - 15718/140505165571840 - celery/celery.worker.job - 3963 - DEBUG - Task accepted: ovs.storagerouter.add_vpool[c32f5c2c-55be-4bda-bf4f-3867b1f689f5] pid:15782
Oct 24 13:42:48 ovs-node03-1604 celery[15718]: 2016-10-24 13:42:48 83900 +0200 - ovs-node03-1604 - 15718/140505165571840 - celery/celery.worker.job - 3964 - ERROR - Task ovs.storagerouter.add_vpool[c32f5c2c-55be-4bda-bf4f-3867b1f689f5] raised unexpected: RuntimeError('The mountpoint for vPool myvpool01 already exists',)
Oct 24 13:42:48 ovs-node03-1604 celery[15718]: Traceback (most recent call last):
Oct 24 13:42:48 ovs-node03-1604 celery[15718]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Oct 24 13:42:48 ovs-node03-1604 celery[15718]:     R = retval = fun(*args, **kwargs)
Oct 24 13:42:48 ovs-node03-1604 celery[15718]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Oct 24 13:42:48 ovs-node03-1604 celery[15718]:     return self.run(*args, **kwargs)
Oct 24 13:42:48 ovs-node03-1604 celery[15718]:   File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 313, in add_vpool
Oct 24 13:42:48 ovs-node03-1604 celery[15718]:     raise RuntimeError('The mountpoint for vPool {0} already exists'.format(vpool_name))
Oct 24 13:42:48 ovs-node03-1604 celery[15718]: RuntimeError: The mountpoint for vPool myvpool01 already exists
Oct 24 13:43:02 ovs-node03-1604 celery[15718]: 2016-10-24 13:43:02 27900 +0200 - ovs-node03-1604 - 15718/140505165571840 - celery/celery.worker.strategy - 3965 - INFO - Received task: ovs.storagerouter.ping[ef255ea2-abfe-4463-9c17-b99eba5ddde9]
```

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1078 --> openvstorage-2.7.4-rev.4193.aa0ed1c
https://github.com/openvstorage/alba-asdmanager/pull/131 --> openvstorage-sdm-1.6.4-rev.394.22c93f2
https://github.com/openvstorage/framework-alba-plugin/pull/250 --> openvstorage-backend-1.7.4-rev.784.647dd17

**Comment by kvanhijf** [comment]
This issue was fixed while making changes regarding the removal of nodes, because i ran into the same issue during my tests

**Comment by JeffreyDevloo** [comment]
### Information

This error occurred when extending a vpool to a different node. The code would check locally if the mountpoint was in use. Due to the nature of extending (that the vpool is present on the creator node) the code would fail.
Verifying if vpool can now extend.

### Steps
- Installed latest cluster
- Ran latest setup suite

### Output

Found

```
2016-10-25 16:51:58 10800 +0200 - ovs-node1 - 2739/139996237236032 - workflow/ci_workflow - 116 - INFO - Setup vpools
2016-10-25 16:52:55 16800 +0200 - ovs-node1 - 2739/139996237236032 - setup/ci_vpool_setup - 117 - INFO - Creation of vPool `myvpool01` should have succeeded on storagerouter `10.100.199.153`
2016-10-25 16:53:17 05500 +0200 - ovs-node1 - 2739/139996237236032 - setup/ci_vpool_setup - 118 - INFO - Creation of vPool `myvpool02` should have succeeded on storagerouter `10.100.199.152`
2016-10-25 16:53:41 01200 +0200 - ovs-node1 - 2739/139996237236032 - setup/ci_vpool_setup - 119 - INFO - Creation of vPool `myvpool01` should have succeeded on storagerouter `10.100.199.152`
2016-10-25 16:54:11 15300 +0200 - ovs-node1 - 2739/139996237236032 - setup/ci_vpool_setup - 120 - INFO - Creation of vPool `myvpool01` should have succeeded on storagerouter `10.100.199.151`
```

Meaning that the vpools can be extended where it previously failed.

### Test result

Test passed.
