### ISSUE TITLE
Scrubbing fails with error when a volume is unreachable from the volumedriver:

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1086]
This occured on a environment with ubuntu 16.04

When a volume is unreachable, e.g. it is not started from the backend. The scrubbing is throwing this error:

```
Oct 26 11:00:00 stor-01.be-g8-4 celery[4048]: 2016-10-26 11:00:00 29200 +0200 - stor-01.be-g8-4 - 853/140576120203008 - lib/scheduled tasks - 6270 - ERROR - Error snapshotting vDisk feb6970b-42c3-4dfb-a2fe-26f2855b8236
Oct 26 11:00:00 stor-01.be-g8-4 celery[4048]: Traceback (most recent call last):
Oct 26 11:00:00 stor-01.be-g8-4 celery[4048]:   File "/opt/OpenvStorage/ovs/lib/scheduledtask.py", line 76, in snapshot_all_vdisks
Oct 26 11:00:00 stor-01.be-g8-4 celery[4048]:     metadata=metadata)
Oct 26 11:00:00 stor-01.be-g8-4 celery[4048]:   File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
Oct 26 11:00:00 stor-01.be-g8-4 celery[4048]:     return self._get_current_object()(*a, **kw)
Oct 26 11:00:00 stor-01.be-g8-4 celery[4048]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
Oct 26 11:00:00 stor-01.be-g8-4 celery[4048]:     return orig(self, *args, **kwargs)
Oct 26 11:00:00 stor-01.be-g8-4 celery[4048]:   File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
Oct 26 11:00:00 stor-01.be-g8-4 celery[4048]:     return self.run(*args, **kwargs)
Oct 26 11:00:00 stor-01.be-g8-4 celery[4048]:   File "/opt/OpenvStorage/ovs/lib/vdisk.py", line 325, in create_snapshot
Oct 26 11:00:00 stor-01.be-g8-4 celery[4048]:     raise RuntimeError(vdisk_result[1])
Oct 26 11:00:00 stor-01.be-g8-4 celery[4048]: RuntimeError: snapshotCreate
```

**Comment by khenderick** [comment]
The important thing here is that apparently the scrub proxy was not cleaned up.

**Comment by kvanhijf** [comment]
Stacktrace is completely unrelated to title of issue
The error in the stacktrace is something which does not need changes
The scheduled task will try to create snapshots for all vDisks and if 1 or more fails, it'll continue with the other vDisks and throw an error for the failed vDisks
So no changes needed here

Edit: The actual problem with the scrubbing is reported here: https://github.com/openvstorage/framework/issues/1087
