### ISSUE TITLE
Ensure MDS vdisk safety fails when a vdisk is unreachable on the volumedriver:

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1088]
This occured on a environment with ubuntu 16.04

Ensure MDS vdisk safety fails when a vdisk is unreachable on the volumedriver:

```
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]: 2016-10-26 10:30:00 97600 +0200 - stor-01.be-g8-4 - 4048/140576120203008 - celery/celery.worker.job - 6066 - ERROR - Task ovs.mds.mds_checkup[b324f6b2-0872-453e-811d-c73abfc4bf3c] raise
d unexpected: Exception('\n - Ensure safety for vDisk test001_6 with guid 209916ae-c5b4-47d9-9abf-956640021046 failed\n - Ensure safety for vDisk test001_8 with guid 2d760b55-0a13-4417-8b8b-46785e3a4683 failed\n - Ensure safety for
 vDisk test001_1 with guid 3685ecc2-91ae-4281-83f7-1d76f102cce6 failed\n - Ensure safety for vDisk test001_7 with guid 457ce8c5-0b68-405b-ac31-bacd954ebd69 failed\n - Ensure safety for vDisk test001_5 with guid 5ce9a196-8805-4a40-b
0d8-2e72053b6032 failed\n - Ensure safety for vDisk test001_10 with guid 81b1bad3-f5f0-4239-af1e-886e0675ee33 failed\n - Ensure safety for vDisk test001_2 with guid 8888914c-7484-49ba-8d64-f38278cc85b8 failed\n - Ensure safety for 
vDisk test001_3 with guid beedcbf3-9e12-407f-9317-653afa98f1c8 failed\n - Ensure safety for vDisk test001_4 with guid c58de0ee-9565-46bb-870d-5a47a13d1ae2 failed\n - Ensure safety for vDisk ubuntu1604 with guid eeb9d6a2-f043-4c35-a
89b-fe9996f3f2b5 failed\n - Ensure safety for vDisk test001_9 with guid feb6970b-42c3-4dfb-a2fe-26f2855b8236 failed',)
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]: Traceback (most recent call last):
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:     R = retval = fun(*args, **kwargs)
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:     return self.run(*args, **kwargs)
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 305, in new_function
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:     output = function(*args, **kwargs)
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:   File "/opt/OpenvStorage/ovs/lib/mdsservice.py", line 819, in mds_checkup
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:     raise Exception('\n - ' + '\n - '.join(failures))
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]: Exception:
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:  - Ensure safety for vDisk test001_6 with guid 209916ae-c5b4-47d9-9abf-956640021046 failed
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:  - Ensure safety for vDisk test001_8 with guid 2d760b55-0a13-4417-8b8b-46785e3a4683 failed
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:  - Ensure safety for vDisk test001_1 with guid 3685ecc2-91ae-4281-83f7-1d76f102cce6 failed
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:  - Ensure safety for vDisk test001_7 with guid 457ce8c5-0b68-405b-ac31-bacd954ebd69 failed
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:  - Ensure safety for vDisk test001_5 with guid 5ce9a196-8805-4a40-b0d8-2e72053b6032 failed
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:  - Ensure safety for vDisk test001_10 with guid 81b1bad3-f5f0-4239-af1e-886e0675ee33 failed
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:  - Ensure safety for vDisk test001_2 with guid 8888914c-7484-49ba-8d64-f38278cc85b8 failed
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:  - Ensure safety for vDisk test001_3 with guid beedcbf3-9e12-407f-9317-653afa98f1c8 failed
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:  - Ensure safety for vDisk test001_4 with guid c58de0ee-9565-46bb-870d-5a47a13d1ae2 failed
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:  - Ensure safety for vDisk ubuntu1604 with guid eeb9d6a2-f043-4c35-a89b-fe9996f3f2b5 failed
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:  - Ensure safety for vDisk test001_9 with guid feb6970b-42c3-4dfb-a2fe-26f2855b8236 failed

Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]: 2016-10-26 10:30:00 81200 +0200 - stor-01.be-g8-4 - 30383/140576120203008 - lib/mds - 6122 - ERROR - Ensure safety for vDisk ubuntu1604 with guid eeb9d6a2-f043-4c35-a89b-fe9996f3f2b5 fa
iled
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]: Traceback (most recent call last):
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:   File "/opt/OpenvStorage/ovs/lib/mdsservice.py", line 813, in mds_checkup
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:     MDSServiceController.ensure_safety(vdisk)
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:   File "/opt/OpenvStorage/ovs/lib/mdsservice.py", line 637, in ensure_safety
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]:     metadata_backend_config=MDSMetaDataBackendConfig(configs_all))
Oct 26 10:30:00 stor-01.be-g8-4 celery[4048]: MaxRedirectsExceededException: updateMetaDataBackendConfig
```

**Comment by kvanhijf** [comment]
In this specific case its logic that the MDS check fails because the volume is unavailable on the volumedriver
The error thrown has been adjusted and is more clear
Fixed by https://github.com/openvstorage/framework/issues/1089

**Comment by wimpers** [comment]
Closed by PM.
