### ISSUE TITLE
DTL checkup fails when a volume is unreachable on the volumedriver:

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1089]
This occured on a environment with ubuntu 16.04

DTL checkup fails when a volume is unreachable on the volumedriver:

```
Oct 26 10:15:00 stor-01.be-g8-4 celery[4048]: 2016-10-26 10:15:00 27100 +0200 - stor-01.be-g8-4 - 4048/140576120203008 - celery/celery.worker.job - 5971 - ERROR - Task ovs.vdisk.dtl_checkup[d8faec09-a3eb-4c01-acfe-fb97740fa238] rai
sed unexpected: MaxRedirectsExceededException('getFailOverCacheConfig ',)
Oct 26 10:15:00 stor-01.be-g8-4 celery[4048]: Traceback (most recent call last):
Oct 26 10:15:00 stor-01.be-g8-4 celery[4048]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Oct 26 10:15:00 stor-01.be-g8-4 celery[4048]:     R = retval = fun(*args, **kwargs)
Oct 26 10:15:00 stor-01.be-g8-4 celery[4048]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Oct 26 10:15:00 stor-01.be-g8-4 celery[4048]:     return self.run(*args, **kwargs)
Oct 26 10:15:00 stor-01.be-g8-4 celery[4048]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 239, in new_function
Oct 26 10:15:00 stor-01.be-g8-4 celery[4048]:     output = function(*args, **kwargs)
Oct 26 10:15:00 stor-01.be-g8-4 celery[4048]:   File "/opt/OpenvStorage/ovs/lib/vdisk.py", line 902, in dtl_checkup
Oct 26 10:15:00 stor-01.be-g8-4 celery[4048]:     current_dtl_config = vdisk.storagedriver_client.get_dtl_config(volume_id)
Oct 26 10:15:00 stor-01.be-g8-4 celery[4048]: MaxRedirectsExceededException: getFailOverCacheConfig
```

**Comment by wimpers** [comment]
Linked with https://github.com/openvstorage/framework/issues/1088

**Comment by wimpers** [comment]
@khenderick  maybe this also caused https://github.com/openvstorage/framework/issues/803 ?

**Comment by wimpers** [comment]
Linked with  https://github.com/openvstorage/framework/issues/1086

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1092 --> openvstorage-2.7.4-rev.4204.f4c4cb8

**Comment by kvanhijf** [comment]
@QA: vdisk.storagedriver_client.stop_object(str(vdisk.volume_id), False)
This causes the MaxRedirectsExceededException to be thrown and thus easy to verify whether DTL checkup continues with the next disks when such error is thrown

**Comment by wimpers** [comment]
Closed by PM.
