### ISSUE TITLE
Scrubbing fails during mds_checkup fase - unmatched C++ signature

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#1121]
```
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/mdsservice.py", line 635, in ensure_safety
    metadata_backend_config=MDSMetaDataBackendConfig(configs_no_ex_master))
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
Boost.Python.ArgumentError: Python argument types in
    StorageRouterClient.update_metadata_backend_config(StorageRouterClient)
did not match C++ signature:
    update_metadata_backend_config(volumedriverfs::PythonClient {lvalue}, std::string volume_id, boost::shared_ptr<volumedriver::MetaDataBackendConfig> metadata_backend_config)

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/tmp/tmp.GKLL2zRD6f/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/tmp/tmp.GKLL2zRD6f/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
ArgumentError: Python argument types in
    StorageRouterClient.update_metadata_backend_config(StorageRouterClient)
did not match C++ signature:
    update_metadata_backend_config(volumedriverfs::PythonClient {lvalue}, std::string volume_id, boost::shared_ptr<volumedriver::MetaDataBackendConfig> metadata_backend_config)

2016-11-04 11:38:44 61900 +0100 - e192-1 - 29099/139643691640576 - lib/scheduled tasks - 23 - ERROR - Scrubber - vPool jessica - StorageRouter e192-1 - vDisk scrubdisk - Scrubbing failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/scheduledtask.py", line 379, in execute_scrub_work
    MDSServiceController.ensure_safety(vdisk)
  File "/opt/OpenvStorage/ovs/lib/mdsservice.py", line 640, in ensure_safety
    raise Exception('Volume {0} with guid {1} is not running'.format(vdisk.name, vdisk.guid))
Exception: Volume scrubdisk with guid 59e5ddde-d8da-4f7b-b913-72cfec466a00 is not running
```

**Comment by pploegaert** [comment]
Related QA test:
http://testrail.openvstorage.com/index.php?/tests/view/1104673&group_by=cases:section_id&group_order=asc&group_id=29866

**Comment by khenderick** [comment]
Fixed by #1122, packaged in openvstorage-2.7.4-rev.4260.a10eba3

**Comment by khenderick** [comment]
Fixed by #1122, packaged in openvstorage-2.7.4-rev.4260.a10eba3

**Comment by khenderick** [comment]
Information for QA: The issue occurred when a vDisk was scrubbed that has its MDS master on a different node than the one assigned by the scrubbing. This triggers an MDS master switch and caused this particular bug. The issue was that remoted structures/classes from two nodes were used in the same flow, and the volumedriver's python client's type checking didn't allow this.

**Comment by pploegaert** [comment]
PASSED: http://testrail.openvstorage.com/index.php?/tests/view/1106213
UPDATE TEST: https://github.com/openvstorage/integrationtests/issues/338
