### ISSUE TITLE
File contains parsing errors: /opt/OpenvStorage/config/arakoon_cacc.ini during extend

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1147]
During the setup of the second node on one of our CI environments:
```
2016-11-13 23:12:27 76700 +0100 - ovsnode02-198 - 22773/139921333040896 - lib/setup - 45 - INFO - Running "extranode" hooks
2016-11-13 23:12:27 76700 +0100 - ovsnode02-198 - 22773/139921333040896 - lib/setup - 46 - INFO - Executing albacontroller._add_base_configuration
2016-11-13 23:12:27 81900 +0100 - ovsnode02-198 - 22773/139921333040896 - lib/setup - 47 - INFO - Executing albanodecontroller.model_albanodes
2016-11-13 23:12:27 83300 +0100 - ovsnode02-198 - 22773/139921333040896 - lib/setup - 48 - DEBUG - Avahi installed
2016-11-13 23:12:27 83400 +0100 - ovsnode02-198 - 22773/139921333040896 - lib/setup - 49 - INFO - Announcing service
2016-11-13 23:12:27 86500 +0100 - ovsnode02-198 - 22773/139921333040896 - lib/setup - 50 - DEBUG -   10.100.198.2    - Restarting service avahi-daemon
2016-11-13 23:12:27 91100 +0100 - ovsnode02-198 - 22773/139921333040896 - lib/setup - 51 - DEBUG -   10.100.198.2    - Service avahi-daemon restarted
2016-11-13 23:12:27 97600 +0100 - ovsnode02-198 - 22773/139921333040896 - lib/setup - 52 - INFO - Extra node complete
2016-11-13 23:12:27 97600 +0100 - ovsnode02-198 - 22773/139921333040896 - lib/setup - 53 - INFO - Analyzing cluster layout
2016-11-13 23:12:27 97800 +0100 - ovsnode02-198 - 22773/139921333040896 - lib/setup - 54 - DEBUG - 1 nodes for cluster ovsdb found
2016-11-13 23:12:27 98000 +0100 - ovsnode02-198 - 22773/139921333040896 - lib/setup - 55 - INFO - Promoting node
2016-11-13 23:12:28 03900 +0100 - ovsnode02-198 - 22773/139921333040896 - lib/setup - 56 - INFO - Joining Arakoon configuration cluster
2016-11-13 23:12:36 41100 +0100 - ovsnode02-198 - 22773/139921333040896 - lib/setup - 88 - INFO - Joining Arakoon OVS DB cluster
2016-11-13 23:12:38 47600 +0100 - ovsnode02-198 - 22773/139921333040896 - lib/setup - 99 - ERROR - 
Failed to promote node, rolling back
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/setup.py", line 419, in setup_node
    configure_rabbitmq=configure_rabbitmq)
  File "/opt/OpenvStorage/ovs/lib/setup.py", line 1269, in _promote_node
    base_dir=Configuration.get('/ovs/framework/paths|ovsdb'))
  File "/opt/OpenvStorage/ovs/extensions/db/arakoon/ArakoonInstaller.py", line 435, in extend_cluster
    ArakoonInstaller._deploy(config, filesystem=filesystem)
  File "/opt/OpenvStorage/ovs/extensions/db/arakoon/ArakoonInstaller.py", line 629, in _deploy
    config_path = Configuration.get_configuration_path(config.config_path)
  File "/opt/OpenvStorage/ovs/extensions/generic/configuration.py", line 101, in get_configuration_path
    key=key)
  File "/opt/OpenvStorage/ovs/extensions/generic/configuration.py", line 414, in _passthrough
    return getattr(ArakoonConfiguration, method)(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/extensions/db/arakoon/configuration.py", line 51, in get_configuration_path
    parser.readfp(config_file)
  File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 546, in _read
    raise e
ParsingError: File contains parsing errors: /opt/OpenvStorage/config/arakoon_cacc.ini
        [line 20]: 'on/config/tlogs\n'
2016-11-13 23:12:38 48300 +0100 - ovsnode02-198 - 22773/139921333040896 - lib/setup - 100 - ERROR - File contains parsing errors: /opt/OpenvStorage/config/arakoon_cacc.ini
        [line 20]: 'on/config/tlogs\n'
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/setup.py", line 419, in setup_node
    configure_rabbitmq=configure_rabbitmq)
  File "/opt/OpenvStorage/ovs/lib/setup.py", line 1269, in _promote_node
    base_dir=Configuration.get('/ovs/framework/paths|ovsdb'))
  File "/opt/OpenvStorage/ovs/extensions/db/arakoon/ArakoonInstaller.py", line 435, in extend_cluster
    ArakoonInstaller._deploy(config, filesystem=filesystem)
  File "/opt/OpenvStorage/ovs/extensions/db/arakoon/ArakoonInstaller.py", line 629, in _deploy
    config_path = Configuration.get_configuration_path(config.config_path)
  File "/opt/OpenvStorage/ovs/extensions/generic/configuration.py", line 101, in get_configuration_path
    key=key)
  File "/opt/OpenvStorage/ovs/extensions/generic/configuration.py", line 414, in _passthrough
    return getattr(ArakoonConfiguration, method)(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/extensions/db/arakoon/configuration.py", line 51, in get_configuration_path
    parser.readfp(config_file)
  File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 546, in _read
    raise e
ParsingError: File contains parsing errors: /opt/OpenvStorage/config/arakoon_cacc.ini
        [line 20]: 'on/config/tlogs\n'
```

**Comment by wimpers** [comment]
Is this one related to https://github.com/openvstorage/framework/issues/1069 ?

**Comment by kinvaris** [comment]
@wimpers, no this is not related. This CI environment is blocked until further investigation what went wrong during the extend. #1069 is related to a full filesystem, resulting in a empty config arakoon file.

**Comment by domsj** [comment]
fwiw #1069 could also be related to e.g. power loss or the sudden death of the relevant process.
(and that might also result in this file being partially written iso completely empty)

**Comment by wimpers** [comment]
@khenderick can you have a quick look so we can unblock the CI environment?

**Comment by khenderick** [comment]
Wrt this ticket, feel free to re-use the environment. It duplicates #1069 and is a known issue. Like @domsj states, there are tons of cases where configuration files can end up inconsistent.

**Comment by wimpers** [comment]
After discussion between BAM and @khenderick : All cases for corrupt ini will be covered in https://github.com/openvstorage/framework/issues/1069 .
