### ISSUE TITLE
During vpool removal: AttributeError: 'int' object has no attribute 'replace'

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#1162]
```
Nov 16 11:24:41 e191-1 celery[27082]:   File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1009, in remove_storagedriver
Nov 16 11:24:41 e191-1 celery[27082]:     client.run(['alba', 'proxy-statistics', '--host', storage_driver.storage_ip, '--port', port])


Nov 16 11:24:41 e191-1 celery[27082]: 2016-11-16 11:24:41 16500 +0100 - e191-1 - 27082/140215829919488 - celery/celery.worker.job - 2509 - ERROR - Task ovs.storagerouter
Nov 16 11:24:41 e191-1 celery[27082]: Traceback (most recent call last):
Nov 16 11:24:41 e191-1 celery[27082]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Nov 16 11:24:41 e191-1 celery[27082]:     R = retval = fun(*args, **kwargs)
Nov 16 11:24:41 e191-1 celery[27082]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Nov 16 11:24:41 e191-1 celery[27082]:     return self.run(*args, **kwargs)
Nov 16 11:24:41 e191-1 celery[27082]:   File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1009, in remove_storagedriver
Nov 16 11:24:41 e191-1 celery[27082]:     client.run(['alba', 'proxy-statistics', '--host', storage_driver.storage_ip, '--port', port])
Nov 16 11:24:41 e191-1 celery[27082]:   File "/opt/OpenvStorage/ovs/extensions/generic/sshclient.py", line 59, in inner_function
Nov 16 11:24:41 e191-1 celery[27082]:     return outer_function(self, *args, **kwargs)
Nov 16 11:24:41 e191-1 celery[27082]:   File "/opt/OpenvStorage/ovs/extensions/generic/sshclient.py", line 278, in run
Nov 16 11:24:41 e191-1 celery[27082]:     command = ' '.join([self.shell_safe(entry) for entry in command])
Nov 16 11:24:41 e191-1 celery[27082]:   File "/opt/OpenvStorage/ovs/extensions/generic/sshclient.py", line 203, in shell_safe
Nov 16 11:24:41 e191-1 celery[27082]:     return "'{0}'".format(argument.replace(r"'", r"'\''"))
Nov 16 11:24:41 e191-1 celery[27082]: AttributeError: 'int' object has no attribute 'replace'

```

**Comment by JeffreyDevloo** [comment]
I suspect that the port you supplied was an integer and not a string.
This can be avoided by casting the integer to a string (like we did previously with .format):
client.run(['alba', 'proxy-statistics', '--host', storage_driver.storage_ip, '--port', str(port)])

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1163 --> 
https://github.com/openvstorage/alba-asdmanager/pull/159 -->

**Comment by JeffreyDevloo** [comment]
### Steps
- Configured latest cluster
- Added vpool
- Deleted vpool

### Output

```
Nov 17 17:39:16 ovs-node-3 celery[26107]: 2016-11-17 17:39:16 11200 +0100 - ovs-node-3 - 26107/140152455190272 - celery/celery.pool - 167 - DEBUG - TaskPool: Apply <function _fast_trace_task at 0x7f77c5132230> (args:('ovs.storagerouter.remove_storagedriver', '79f4be69-5d0a-4b07-afe8-e981ba72f5df', ('a8ba5ed9-254b-4ae2-a062-947406020694',), {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': ('a8ba5ed9-254b-4ae2-a062-947406020694',), 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': False, u'routing_key': u'generic.#', u'exchange': u'generic'}, 'expires': None, u'hostname': 'celery@ovs-node-3', 'task': 'ovs.storagerouter.remove_storagedriver', 'callbacks': None, u'correlation_id': u'79f4be69-5d0a-4b07-afe8-e981ba72f5df', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': u'62212313-de2b-3562-8417-a17c906facf8', 'id': '79f4be69-5d0a-4b07-afe8-e981ba72f5df', u'headers': {}}) kwargs:{})
Nov 17 17:39:16 ovs-node-3 celery[26107]: 2016-11-17 17:39:16 11600 +0100 - ovs-node-3 - 26217/140152455190272 - lib/storagerouter - 23 - INFO - Remove Storage Driver - Guid a8ba5ed9-254b-4ae2-a062-947406020694 - Deleting Storage Driver myvpool01yIMP45NIcWSaWh92
Nov 17 17:39:16 ovs-node-3 celery[26107]: 2016-11-17 17:39:16 11400 +0100 - ovs-node-3 - 26107/140152455190272 - celery/celery.worker.job - 168 - DEBUG - Task accepted: ovs.storagerouter.remove_storagedriver[79f4be69-5d0a-4b07-afe8-e981ba72f5df] pid:26217
Nov 17 17:39:16 ovs-node-3 celery[26107]: 2016-11-17 17:39:16 11800 +0100 - ovs-node-3 - 26217/140152455190272 - lib/storagerouter - 24 - INFO - Remove Storage Driver - Guid a8ba5ed9-254b-4ae2-a062-947406020694 - Checking availability of related Storage Routers
Nov 17 17:39:18 ovs-node-3 celery[26107]: 2016-11-17 17:39:18 20300 +0100 - ovs-node-3 - 26217/140152455190272 - lib/storagerouter - 25 - INFO - Remove Storage Driver - Guid a8ba5ed9-254b-4ae2-a062-947406020694 - Available Storage Driver for migration - myvpool01yIMP45NIcWSaWh92
Nov 17 17:39:18 ovs-node-3 celery[26107]: 2016-11-17 17:39:18 25600 +0100 - ovs-node-3 - 26217/140152455190272 - lib/storagerouter - 26 - INFO - Remove Storage Driver - Guid a8ba5ed9-254b-4ae2-a062-947406020694 - Storage Router ovs-node-1 with IP 10.100.199.151 is online
...
Nov 17 17:39:38 ovs-node-3 celery[26107]: 2016-11-17 17:39:38 86400 +0100 - ovs-node-3 - 26107/140152455190272 - celery/celery.worker.job - 169 - INFO - Task ovs.storagerouter.remove_storagedriver[79f4be69-5d0a-4b07-afe8-e981ba72f5df] succeeded in 22.751621157s: None

``

### Test result
Test passed.

### Packages 
- openvstorage                         2.7.6-rev.4311.9e78cea-1        amd64        openvStorage
- openvstorage-backend                 1.7.6-rev.817.91abb7c-1         amd64        openvStorage Backend plugin
- openvstorage-backend-core            1.7.6-rev.817.91abb7c-1         amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps         1.7.6-rev.817.91abb7c-1         amd64        openvStorage Backend plugin Web Applications
- openvstorage-core                    2.7.6-rev.4311.9e78cea-1        amd64        openvStorage core
- openvstorage-hc                      1.7.6-rev.817.91abb7c-1         amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                     1.6.6-rev.445.4216f7e-1         amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps                 2.7.6-rev.4311.9e78cea-1        amd64        openvStorage Web Applications
```
