### ISSUE TITLE
KeyError: 'fs_dtl_host' after upgrading environment

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1166]
After upgrading OVH (installed half-september) we noticed the following problem: 
```
2016-11-15 18:36:58 63800 +0100 - ctrl-roub-01 - 115575/139663746499920 - api/middleware - 26 - ERROR - An unhandled exception occurred: 'fs_dtl_host'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 78, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 399, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 396, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 519, in new_function
    return_value = f(*args, **kwargs)
  File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 84, in new_function
    return f(*args, **kw)
  File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 312, in new_function
    data = FullSerializer(object_type, contents=contents, instance=data_list, many=True).data
  File "/usr/lib/python2.7/dist-packages/rest_framework/serializers.py", line 571, in data
    self._data = [self.to_native(item) for item in obj]
  File "/usr/lib/python2.7/dist-packages/rest_framework/serializers.py", line 349, in to_native
    value = field.field_to_native(obj, field_name)
  File "/usr/lib/python2.7/dist-packages/rest_framework/fields.py", line 198, in field_to_native
    value = get_component(value, component)
  File "/usr/lib/python2.7/dist-packages/rest_framework/fields.py", line 56, in get_component
    val = getattr(obj, attr_name)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 344, in <lambda>
    fget = lambda s: s._get_dynamic_property(dynamic)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 413, in _get_dynamic_property
    return self._backend_property(data_loader, dynamic)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 953, in _backend_property
    dynamic_data = function()
  File "/opt/OpenvStorage/ovs/dal/hybrids/vpool.py", line 93, in _configuration
    dtl_host = file_system['fs_dtl_host']
KeyError: 'fs_dtl_host'
```

After some digging we saw that new environments do have that parameter by default:
```
root@ovs-node01-1604:~# for i in $(ovs config list /ovs/vpools); do for j in $(ovs config list /ovs/vpools/${i}/hosts); do echo ${i}-${j}; ovs config get /ovs/vpools/${i}/hosts/${j}/config | grep fs_dtl_host; done; done
53640a02-990c-45a4-97f9-864c2308f379-myvpool01ROHsrjgp37fLG0y6
        "fs_dtl_host": ""
53640a02-990c-45a4-97f9-864c2308f379-myvpool01rJFW3pTs7f72ZkZC
        "fs_dtl_host": ""
53640a02-990c-45a4-97f9-864c2308f379-myvpool01sIOkxFkvuedwJveT
        "fs_dtl_host": ""
9daac0cf-73f9-4618-9558-a43b2210d324-myvpool02ROHsrjgp37fLG0y6
        "fs_dtl_host": ""
```

But old environments don't have that flag because it was not mandatory at the time:
```
root@perf-roub-01:~# for i in $(ovs config list /ovs/vpools); do for j in $(ovs config list /ovs/vpools/${i}/hosts); do echo ${i}-${j}; ovs config get /ovs/vpools/${i}/hosts/${j}/config | grep fs_dtl_host; done; done
02d1790b-2ee4-4379-b8ab-55a3b303f466-local-flash-straskjhI5AjLbcfQZ61n
188b045a-4c8a-4bce-9cad-1e7dd4e05177-local-flash-roub5st9gvgyydrpDdDz
188b045a-4c8a-4bce-9cad-1e7dd4e05177-local-flash-roub6Y6ufS8mfZaoZOCu
188b045a-4c8a-4bce-9cad-1e7dd4e05177-local-flash-roubHiq6DNEMFIPxHMsJ
188b045a-4c8a-4bce-9cad-1e7dd4e05177-local-flash-roubTNKd0Cr7sDv6GHOG
2587ba8d-57b7-4fb1-91a0-60fc035986b6-local-flash-gravRfBxrlgz3H4BRSzm
2a9a24e1-0cb0-4f87-aca2-e0ae0d967469-local-hdd-roub5st9gvgyydrpDdDz
2a9a24e1-0cb0-4f87-aca2-e0ae0d967469-local-hdd-roub6Y6ufS8mfZaoZOCu
2a9a24e1-0cb0-4f87-aca2-e0ae0d967469-local-hdd-roubHiq6DNEMFIPxHMsJ
2a9a24e1-0cb0-4f87-aca2-e0ae0d967469-local-hdd-roubTNKd0Cr7sDv6GHOG
8455b0ac-6466-40b3-ad82-985cffb2f226-geo-accel-alba5st9gvgyydrpDdDz
8455b0ac-6466-40b3-ad82-985cffb2f226-geo-accel-alba6Y6ufS8mfZaoZOCu
8455b0ac-6466-40b3-ad82-985cffb2f226-geo-accel-albaHiq6DNEMFIPxHMsJ
8455b0ac-6466-40b3-ad82-985cffb2f226-geo-accel-albaRfBxrlgz3H4BRSzm
8455b0ac-6466-40b3-ad82-985cffb2f226-geo-accel-albaTNKd0Cr7sDv6GHOG
8455b0ac-6466-40b3-ad82-985cffb2f226-geo-accel-albakjhI5AjLbcfQZ61n
98dcbca3-f19d-4952-a6cd-ca0cc0598dde-local-hdd-gravRfBxrlgz3H4BRSzm
fd9c6385-6164-459c-903f-9d2b4fd57299-local-hdd-straskjhI5AjLbcfQZ61n
```

**Comment by wimpers** [comment]
@khenderick This will not be an issue in upgrades from Fargo RC1? 
Did we patch the env or did we fix this in code?

**Comment by wimpers** [comment]
@kinvaris , please make sure OPS knows about what you did to fix this.

**Comment by khenderick** [comment]
@wimpers, I have not looked at this issue, so I have no idea about whether this is an issue or not. And since it's closed, I think we'll never know.
