### ISSUE TITLE
Errors while removing a node. The demote did run without any errors.

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1177]
Node (stor-01) crashed and got reinstalled by GIG. After that they did run a mark as offline in the GUI and tried to remove the node with 'ovs remove node <ip>'. The demote worked fine but the remove afterwards crashed with 'Authentication failed'.

```
2016-11-18 11:28:33 18600 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 0 - INFO - Remove node
2016-11-18 11:28:33 18700 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 1 - INFO - WARNING: Some of these steps may take a very long time, please check the logs for more information
2016-11-18 11:28:33 20900 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 2 - INFO - Creating SSH connections to remaining master nodes
2016-11-18 11:28:33 21800 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 4 - INFO -   Node with IP 10.21.2.21      is unreachable
2016-11-18 11:28:33 75500 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 5 - INFO -   Node with IP 10.21.2.22      successfully connected to
2016-11-18 11:28:34 31700 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 6 - INFO -   Node with IP 10.21.2.24      successfully connected to
2016-11-18 11:28:34 89000 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 7 - INFO -   Node with IP 10.21.2.23      successfully connected to
2016-11-18 11:28:37 76600 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 8 - INFO - Starting removal of node stor-01 - 10.21.2.21
2016-11-18 11:28:37 76700 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 9 - INFO -   Marking all Storage Drivers served by Storage Router 10.21.2.21 as offline
2016-11-18 11:28:37 76800 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 10 - INFO -   Removing vPools from node
2016-11-18 11:28:37 76900 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 11 - INFO -     Stopping and removing services
2016-11-18 11:28:37 76900 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 12 - INFO -     Removing node from model
2016-11-18 11:28:37 78000 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 13 - INFO - Running "remove" hooks
2016-11-18 11:28:37 78000 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 14 - INFO - Executing storagedriver.on_remove
2016-11-18 11:28:38 03900 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 15 - INFO - 

2016-11-18 11:28:38 03900 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 16 - ERROR - An unexpected error occurred:
Traceback (most recent call last):
  File "ovs/lib/setup.py", line 743, in remove_node
    SetupController._run_hooks('remove', storage_router_to_remove.ip, complete_removal=remove_asd_manager)
  File "ovs/lib/setup.py", line 1822, in _run_hooks
    function(cluster_ip=cluster_ip, **kwargs)
  File "ovs/lib/helpers/..//storagedriver.py", line 136, in on_remove
    client = SSHClient(endpoint=cluster_ip, username='root')
  File "ovs/extensions/generic/sshclient.py", line 152, in __init__
    self._connect()
  File "ovs/extensions/generic/sshclient.py", line 173, in _connect
    self._client.connect(self.ip, username=self.username, password=self.password)
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 337, in connect
    self._auth(username, password, pkey, key_filenames, allow_agent, look_for_keys)
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 528, in _auth
    raise saved_exception
AuthenticationException: Authentication failed.
2016-11-18 11:28:38 04000 +0100 - stor-02.cl-g8-uk1 - 33507/139713389479744 - lib/setup - 17 - ERROR - Authentication failed.
Traceback (most recent call last):
  File "ovs/lib/setup.py", line 743, in remove_node
    SetupController._run_hooks('remove', storage_router_to_remove.ip, complete_removal=remove_asd_manager)
  File "ovs/lib/setup.py", line 1822, in _run_hooks
    function(cluster_ip=cluster_ip, **kwargs)
  File "ovs/lib/helpers/..//storagedriver.py", line 136, in on_remove
    client = SSHClient(endpoint=cluster_ip, username='root')
  File "ovs/extensions/generic/sshclient.py", line 152, in __init__
    self._connect()
  File "ovs/extensions/generic/sshclient.py", line 173, in _connect
    self._client.connect(self.ip, username=self.username, password=self.password)
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 337, in connect
    self._auth(username, password, pkey, key_filenames, allow_agent, look_for_keys)
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 528, in _auth
    raise saved_exception
AuthenticationException: Authentication failed.
```

This problem got solved by shutting down the stor-01 and remove the node.

**Comment by khenderick** [comment]
Remove node is supported when:
- A node is offline (means: offline - "mark a node offline" doesn't make the node offline, it's just a confusing name to inform a volumedriver a node won't be used anymore and a volume can be stolen)
- A node is offline and still part of the cluster.

The scenario - where a node was reinstalled and _after_ that removed - is not supported.

However, this ticket was created because apparently the demote logic can handle the scenario and it shouldn't take too much time to support it correctly.

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1330 --> openvstorage-2.7.10-dev.1484125907.1889922
