### ISSUE TITLE
ovs remove node does not work on node that is offline

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1199]
While performing the `ovs remove node` on a node that was offline:
```
2016-11-23 10:30:24 09300 +0100 - ctrl-roub-01 - 109786/140116299626240 - lib/setup - 382 - INFO - Demote complete
2016-11-23 10:30:24 09300 +0100 - ctrl-roub-01 - 109786/140116299626240 - lib/setup - 383 - INFO -     Stopping and removing services
2016-11-23 10:30:24 09300 +0100 - ctrl-roub-01 - 109786/140116299626240 - lib/setup - 384 - INFO -     Removing node from model
2016-11-23 10:30:24 10000 +0100 - ctrl-roub-01 - 109786/140116299626240 - lib/scheduled tasks - 385 - INFO - Send data task scheduling started
2016-11-23 10:30:24 11200 +0100 - ctrl-roub-01 - 109786/140116299626240 - lib/setup - 386 - INFO - Running "remove" hooks
2016-11-23 10:30:24 11200 +0100 - ctrl-roub-01 - 109786/140116299626240 - lib/setup - 387 - INFO - Executing storagedriver.on_remove
2016-11-23 10:30:26 42000 +0100 - ctrl-roub-01 - 109786/140116299626240 - lib/setup - 388 - INFO - 

2016-11-23 10:30:26 42100 +0100 - ctrl-roub-01 - 109786/140116299626240 - lib/setup - 389 - ERROR - An unexpected error occurred:
Traceback (most recent call last):
  File "ovs/lib/setup.py", line 743, in remove_node
    SetupController._run_hooks('remove', storage_router_to_remove.ip, complete_removal=remove_asd_manager)
  File "ovs/lib/setup.py", line 1814, in _run_hooks
    function(cluster_ip=cluster_ip, **kwargs)
  File "ovs/lib/helpers/..//storagedriver.py", line 136, in on_remove
    client = SSHClient(endpoint=cluster_ip, username='root')
  File "ovs/extensions/generic/sshclient.py", line 152, in __init__
    self._connect()
  File "ovs/extensions/generic/sshclient.py", line 173, in _connect
    self._client.connect(self.ip, username=self.username, password=self.password)
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 311, in connect
    raise NoValidConnectionsError(errors)
NoValidConnectionsError: [Errno None] Unable to connect to port 22 on  or 172.20.20.7
2016-11-23 10:30:26 42200 +0100 - ctrl-roub-01 - 109786/140116299626240 - lib/setup - 390 - ERROR - [Errno None] Unable to connect to port 22 on  or 172.20.20.7
Traceback (most recent call last):
  File "ovs/lib/setup.py", line 743, in remove_node
    SetupController._run_hooks('remove', storage_router_to_remove.ip, complete_removal=remove_asd_manager)
  File "ovs/lib/setup.py", line 1814, in _run_hooks
    function(cluster_ip=cluster_ip, **kwargs)
  File "ovs/lib/helpers/..//storagedriver.py", line 136, in on_remove
    client = SSHClient(endpoint=cluster_ip, username='root')
  File "ovs/extensions/generic/sshclient.py", line 152, in __init__
    self._connect()
  File "ovs/extensions/generic/sshclient.py", line 173, in _connect
    self._client.connect(self.ip, username=self.username, password=self.password)
  File "/usr/lib/python2.7/dist-packages/paramiko/client.py", line 311, in connect
    raise NoValidConnectionsError(errors)
NoValidConnectionsError: [Errno None] Unable to connect to port 22 on  or 172.20.20.7
```

After activating the nodes again, I reran the `ovs remove node` and it worked.

**Comment by kinvaris** [comment]
After running this code, I tried to remove a external LOCAL backend. And saw this problem:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albacontroller.py", line 1467, in unlink_alba_backends
    child = AlbaBackend(linked_guid)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 233, in __init__
    self.__class__.__name__, self._guid
ObjectNotFoundException: AlbaBackend with guid 'e50491d6-bb4d-408c-aedd-bb94363c827f' could not be found
```

**Comment by kinvaris** [comment]
This is the observed output of ovs:
```
root@ctrl-roub-01:~# ovs remove node 172.20.20.7
+++++++++++++++++++++
+++  Remove node  +++
+++++++++++++++++++++
WARNING: Some of these steps may take a very long time, please check the logs for more information


Creating SSH connections to remaining master nodes
  Node with IP 172.20.20.201   successfully connected to
  Node with IP 172.20.20.101   successfully connected to
  Node with IP 172.20.20.131   successfully connected to
  Node with IP 172.20.20.7     is unreachable
  Node with IP 172.20.20.231   successfully connected to
  Node with IP 172.20.20.1     successfully connected to
  Node with IP 172.20.20.31    successfully connected to
  Node with IP 172.20.20.103   successfully connected to
  Node with IP 172.20.20.32    successfully connected to
Are you sure you want to remove node ctrl-roub-02? (y/[n]): y
Starting removal of node ctrl-roub-02 - 172.20.20.7
  Marking all Storage Drivers served by Storage Router 172.20.20.7 as offline
  Removing vPools from node

+++ Demoting node +++

Leaving Arakoon ovsdb cluster
Leaving Arakoon config cluster
Update configurations
Restarting master node services
Removing/unconfiguring offline RabbitMQ node
Update existing vPools
Restarting services
  [172.20.20.201] watcher-framework stopped
  [172.20.20.101] watcher-framework stopped
  [172.20.20.1] watcher-framework stopped
  [172.20.20.103] watcher-framework stopped
  [172.20.20.131] watcher-framework stopped
  [172.20.20.231] watcher-framework stopped
  [172.20.20.31] watcher-framework stopped
  [172.20.20.32] watcher-framework stopped
  [172.20.20.201] memcached restarted
  [172.20.20.101] memcached restarted
  [172.20.20.1] memcached restarted
  [172.20.20.103] memcached restarted
  [172.20.20.201] watcher-framework started
  [172.20.20.101] watcher-framework started
  [172.20.20.1] watcher-framework started
  [172.20.20.103] watcher-framework started
  [172.20.20.131] watcher-framework started
  [172.20.20.231] watcher-framework started
  [172.20.20.31] watcher-framework started
  [172.20.20.32] watcher-framework started

+++ Running "demote" hooks +++

Executing storagedriver.on_demote
Executing albacontroller.on_demote
Restarting services
  [172.20.20.201] watcher-framework stopped
  [172.20.20.101] watcher-framework stopped
  [172.20.20.1] watcher-framework stopped
  [172.20.20.103] watcher-framework stopped
  [172.20.20.131] watcher-framework stopped
  [172.20.20.231] watcher-framework stopped
  [172.20.20.31] watcher-framework stopped
  [172.20.20.32] watcher-framework stopped
  [172.20.20.201] memcached restarted
  [172.20.20.101] memcached restarted
  [172.20.20.1] memcached restarted
  [172.20.20.103] memcached restarted
  [172.20.20.201] watcher-framework started
  [172.20.20.101] watcher-framework started
  [172.20.20.1] watcher-framework started
  [172.20.20.103] watcher-framework started
  [172.20.20.131] watcher-framework started
  [172.20.20.231] watcher-framework started
  [172.20.20.31] watcher-framework started
  [172.20.20.32] watcher-framework started
Demote complete
    Stopping and removing services
    Removing node from model

+++ Running "remove" hooks +++

Executing storagedriver.on_remove


++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++  An unexpected error occurred:                                 +++
+++  [Errno None] Unable to connect to port 22 on  or 172.20.20.7  +++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Comment by khenderick** [comment]
Odd, the code running is kinda "try to do this, but ignore any ```UnableToConnectException``` exception" since that node might be offline, but we don't care in that particular case.

However, the ```NoValidConnectionsError``` is something we've never seen before.

**Comment by khenderick** [comment]
Wrapped exception to expected one

```
In [1]: from ovs.extensions.generic.sshclient import SSHClient

In [2]: c = SSHClient('10.100.169.101')
---------------------------------------------------------------------------
UnableToConnectException                  Traceback (most recent call last)
<ipython-input-2-a20bc2e22991> in <module>()
----> 1 c = SSHClient('10.100.169.101')

/opt/OpenvStorage/ovs/extensions/generic/sshclient.py in __init__(self, endpoint, username, password)
    152                 SSHClient.client_cache[key] = client
    153             self._client = SSHClient.client_cache[key]
--> 154         self._connect()
    155 
    156     def __del__(self):

/opt/OpenvStorage/ovs/extensions/generic/sshclient.py in _connect(self)
    187             if 'No route to host' in message or 'Unable to connect' in message:
    188                 SSHClient._logger.error(message)
--> 189                 raise UnableToConnectException(message)
    190             raise
    191 

UnableToConnectException: [Errno None] Unable to connect to port 22 on  or 10.100.169.101
```

**Comment by khenderick** [comment]
Fixed by #1206, openvstorage-2.7.6-rev.4352.cc448bd

**Comment by kinvaris** [comment]
PASSED:
```
root@ovs-node02-1604:~# ovs remove node 10.100.199.181
+++++++++++++++++++++
+++  Remove node  +++
+++++++++++++++++++++
WARNING: Some of these steps may take a very long time, please check the logs for more information


Creating SSH connections to remaining master nodes
  Node with IP 10.100.199.183  successfully connected to
  Node with IP 10.100.199.182  successfully connected to
  Node with IP 10.100.199.181  is unreachable
Are you sure you want to remove node ovs-node01-1604? (y/[n]): y
The removal of these StorageRouters brings data at risk on backend mybackend02. Loosing more disks will cause data loss.
Are you sure you want to continue? (y/[n]): y
Starting removal of node ovs-node01-1604 - 10.100.199.181
  Marking all Storage Drivers served by Storage Router 10.100.199.181 as offline
  Removing vPools from node
    Removing vPool myvpool01 from node

+++ Demoting node +++

Leaving Arakoon ovsdb cluster
Leaving Arakoon config cluster
Update configurations
Restarting master node services
Removing/unconfiguring offline RabbitMQ node
ERROR: 
Failed to forget RabbitMQ cluster node
ERROR: Command ''rabbitmqctl' 'forget_cluster_node' 'rabbit@ovs-node01-1604'' returned non-zero exit status 2
Update existing vPools
Restarting services
  [10.100.199.183] watcher-framework stopped
  [10.100.199.182] watcher-framework stopped
  [10.100.199.183] memcached restarted
  [10.100.199.182] memcached restarted
  [10.100.199.183] watcher-framework started
  [10.100.199.182] watcher-framework started

+++ Running "demote" hooks +++

Executing albacontroller.on_demote
Executing storagedriver.on_demote
Restarting services
  [10.100.199.183] watcher-framework stopped
  [10.100.199.182] watcher-framework stopped
  [10.100.199.183] memcached restarted
  [10.100.199.182] memcached restarted
  [10.100.199.183] watcher-framework started
  [10.100.199.182] watcher-framework started

+++ Demote complete +++

Stopping and removing services

+++ Running "remove" hooks +++

Executing albacontroller.on_remove
Executing storagedriver.on_remove
Removing node from model
  [10.100.199.183] watcher-framework stopped
  [10.100.199.182] watcher-framework stopped
  [10.100.199.183] memcached restarted
  [10.100.199.182] memcached restarted
  [10.100.199.183] watcher-framework started
  [10.100.199.182] watcher-framework started
Successfully removed node


+++ Remove nodes finished +++
```

**Comment by kinvaris** [comment]
Currently this is in master but can this also be merged in `Fargo` ? @khenderick

**Comment by khenderick** [comment]
@wimpers, can you confirm we need to cherry-pick this to the fargo branch? If so, can we somehow add an extra milestone or keep using RC1 to indicate where a fix needs to be applied?

**Comment by wimpers** [comment]
We are a few days away from a 3rd promote, so no cherry picking is needed.
