### ISSUE TITLE
Failed to remove external local backend from a global backend

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1200]
When you have 2 OVS clusters, that share a backend as a linked local backend. You can add the backend, but you cannot remove the external local backend from the global backend.

Steps to reproduce:
* Setup cluster A
* Setup cluster B
* Setup local backend C on cluster A
* Setup global backend D on cluster B
* Link external local backend on cluster B with cluster A
* Try to remove it.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albacontroller.py", line 1467, in unlink_alba_backends
    child = AlbaBackend(linked_guid)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 233, in __init__
    self.__class__.__name__, self._guid
ObjectNotFoundException: AlbaBackend with guid 'e50491d6-bb4d-408c-aedd-bb94363c827f' could not be found
```

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework-alba-plugin/pull/276 --> openvstorage-backend-1.7.5-fargo.2

**Comment by kinvaris** [comment]
PASSED: Updated OVH environment, tried to remove backend. Succes!
