### ISSUE TITLE
Correctly process 'Ensure safety' for vdisks

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1203]
This tasks should complete correctly and just report that it did not process it correctly for that vdisk. 

Params `ovs.vdisk.migrate_from_voldrv`:
`{'new_owner_id': u'globaljlKIkrmtTHLINeSg', 'volume_id': u'2b45a75c-6a40-4bf3-93c8-087f949f411f'}`

As seen here in the `ovs.vdisk.migrate_from_voldrv` task:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 69, in new_function
    return function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/vdisk.py", line 220, in migrate_from_voldrv
    MDSServiceController.mds_checkup()
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 305, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/mdsservice.py", line 822, in mds_checkup
    raise Exception('\n - ' + '\n - '.join(failures))
Exception: 
 - Ensure safety for vDisk KVM13-fio-rou-d1 with guid ff16eae1-5f25-49a8-8465-77be71e9b983 failed
```

**Comment by khenderick** [comment]
Please provide full logs.

**Comment by wimpers** [comment]
After 11 days still no logs, back to BAM

**Comment by wimpers** [comment]
@kinvaris After 11 days still no logs? Is this still relevant?

**Comment by wimpers** [comment]
Please re-open if we have logs or can reproduce.
