### ISSUE TITLE
VDiskController.create_new fails because of leftover volumes on volumedriver

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1247]
Related to: http://tickets.openvstorage.com/browse/OVSSUP-129

Expected behavior on `VDiskController.create_new`:

```
In [2]: VDiskController.create_new("test", 52428800, "5009a03a-cf93-476c-ae18-b8268e18edbf")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-109f0adb795b> in <module>()
----> 1 VDiskController.create_new("test", 52428800, "5009a03a-cf93-476c-ae18-b8268e18edbf")

/usr/lib/python2.7/dist-packages/celery/local.pyc in __call__(self, *a, **kw)
    186 
    187     def __call__(self, *a, **kw):
--> 188         return self._get_current_object()(*a, **kw)
    189 
    190     def __len__(self):

/usr/lib/python2.7/dist-packages/celery/app/task.pyc in __call__(self, *args, **kwargs)
    418             if self.__self__ is not None:
    419                 return self.run(self.__self__, *args, **kwargs)
--> 420             return self.run(*args, **kwargs)
    421         finally:
    422             self.pop_request()

/opt/OpenvStorage/ovs/lib/vdisk.pyc in create_new(volume_name, volume_size, storagedriver_guid)
    596         vpool = storagedriver.vpool
    597         if VDiskList.get_by_devicename_and_vpool(devicename, vpool) is not None:
--> 598             raise RuntimeError('A vDisk with this name already exists on vPool {0}'.format(vpool.name))
    599         if volume_size > 64 * 1024 ** 4:
    600             raise ValueError('Maximum volume size of 64TiB exceeded')

RuntimeError: A vDisk with this name already exists on vPool myvpool01
```

Seen result on `VDiskController.create_new`:

```
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 35, in <module>
    class HealthCheckController(object):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 411, in HealthCheckController
    HealthCheckController.run_method(*arguments)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 398, in run_method
    getattr(cl, option['function'])(logger)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/volumedriver/volumedriver_health_check.py", line 141, in check_volumedrivers
    if VolumedriverHealthCheck._check_volumedriver(name, storagedriver_guid, vp.name):
  File "/usr/local/lib/python2.7/dist-packages/timeout_decorator/timeout_decorator.py", line 69, in new_function
    return function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/volumedriver/volumedriver_health_check.py", line 84, in _check_volumedriver
    VDiskController.create_new(vdisk_name, vdisk_size, storagedriver_guid)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/vdisk.py", line 615, in create_new
    node_id=str(storagedriver.storagedriver_id))
volumedriver.storagerouter.storagerouterclient.FileExistsException: Dynamic exception type: volumedriverfs::FileExistsException
std::exception::what: Path already exists /ovs-healthcheck-test-sYmy4MwmPhdUK2zJ.raw File exists (17)
```

After discussion with @khenderick he thinks the `VDiskController.delete()` has not deleted the VDisk in reality. This because of the following: This exception would occur if the vdisk would be gone in the model but still be present in the volumedriver.

**Comment by pploegaert** [comment]
Related to: http://tickets.openvstorage.com/browse/OVSSUP-129

**Comment by khenderick** [comment]
After some more checking code, the ```VDiskController.delete``` is most likely not the issue, as it first removes the volume from the volumedriver, and after that succeeds removes the vDisk from the model. While here, the volume is not in the model, but it is in reality.

**Comment by khenderick** [comment]
I truly have no idea what is going on here. However, I'm sure there is a race condition possible in most of our create methods, so I'll fix that, assuming that the above report is somehow a result of this race condition.

**Comment by khenderick** [comment]
Made a change by #1265, packaged in openvstorage-2.7.8-rev.4433.ad64456

**Comment by JeffreyDevloo** [comment]
Currently investigating why this behavior occurs

**Comment by pploegaert** [comment]
Related PR: https://github.com/openvstorage/integrationtests/pull/421

**Comment by pploegaert** [comment]
@JeffreyDevloo : can you please rerun the test in the PR and update the status ... thx!

**Comment by JeffreyDevloo** [comment]
### Validation
All current builds are no longer failing on the specified test.
Classifying this as resolved

A little sidenote: the healthcheck should not bump into this anymore aswell.
