### ISSUE TITLE
Update of refresh_package_information is not threadsafe

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#1257]
As observed on OVH environment during update and via code snippet:

```
152 - WARNING - 172.20.20.231: Failed to find a version file in /opt/OpenvStorage/run for service arakoon-voldrv
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "ovs/lib/update.py", line 643, in execute_update
    services_to_start_again=services_stop_start)
  File "ovs/lib/update.py", line 703, in _recover_from_failed_update
    UpdateController._refresh_package_information(local_ip=local_client_ip)
  File "ovs/lib/update.py", line 688, in _refresh_package_information
    GenericController.refresh_package_information()
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in call
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in call
    return self.run(*args, **kwargs)
  File "ovs/lib/helpers/decorators.py", line 239, in new_function
    output = function(*args, **kwargs)
  File "ovs/lib/helpers/..//generic.py", line 534, in refresh_package_information
    raise Exception(' - {0}'.format('\n - '.join(errors)))
Exception:  - 172.20.20.103: Authentication failed.

```

Code snippet:

```
from ovs.lib.update import UpdateController
for x in xrange(10):
    UpdateController._refresh_package_information()
```

**Comment by khenderick** [comment]
The code snippet won't work, but I think the issue is that the SSHClient isn't thread-safe, which does make sense. So we should reduce the number of threads used.

**Comment by kvanhijf** [comment]
Code snippet i used in order to reproduce:
```
def test():
    from ovs.lib.generic import GenericController
    import time
    attempts = 50
    for x in range(attempts):
        print x
        start = time.time()
        GenericController.refresh_package_information()
        print time.time() - start
        print ''
```

**Comment by kvanhijf** [comment]
```
In [2]: test()
0
8.5633430481

1
6.89185500145

2
6.80949091911

3
6.84956097603

4
6.79776716232

5
6.94766998291

6
6.7781188488

7
6.74318599701

8
6.72256708145

9
6.78440499306

10
6.78925609589

11
6.76898193359

12
6.7696928978

13
6.82977795601

14
7.02029395103

15
6.86195397377

16
6.91676092148

17
6.83101701736

18
6.99339199066

19
7.13648891449

20
6.87986898422

21
6.98911309242

22
6.89877915382

23
7.15571212769

24
6.85368609428

25
6.91456198692

26
7.02276611328

27
6.96315002441

28
6.96083593369

29
6.88629007339

30
6.95032787323

31
6.99810481071

32
7.05532884598

33
6.93406796455

34
7.04604911804

35
14.2624258995

36
7.00783586502

37
7.01231813431

38
6.90216708183

39
7.0805721283

40
6.98465800285

41
6.88490915298

42
7.14834094048

43
6.96485900879

44
6.84237790108

45
7.03290605545

46
6.99360585213

47
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-2-ea594c21b25d> in <module>()
----> 1 test()

<ipython-input-1-9809975050be> in test()
      5                 print x
      6                 start = time.time()
----> 7                 GenericController.refresh_package_information()
      8                 print time.time() - start
      9                 print ''

/usr/lib/python2.7/dist-packages/celery/local.pyc in __call__(self, *a, **kw)
    186
    187     def __call__(self, *a, **kw):
--> 188         return self._get_current_object()(*a, **kw)
    189
    190     def __len__(self):

/usr/lib/python2.7/dist-packages/celery/app/task.pyc in __call__(self, *args, **kwargs)
    418             if self.__self__ is not None:
    419                 return self.run(self.__self__, *args, **kwargs)
--> 420             return self.run(*args, **kwargs)
    421         finally:
    422             self.pop_request()

/opt/OpenvStorage/ovs/lib/helpers/decorators.pyc in new_function(*args, **kwargs)
    237                                                                                                                          params_info,
    238                                                                                                                          current_time - starting_time))
--> 239                                 output = function(*args, **kwargs)
    240                                 log_message('Task {0} finished successfully'.format(task_name))
    241                                 return output

/opt/OpenvStorage/ovs/lib/generic.pyc in refresh_package_information()
    533         if len(errors) > 0:
    534             errors = [str(error) for error in set(errors)]
--> 535             raise Exception(' - {0}'.format('\n - '.join(errors)))
    536
    537     @staticmethod

Exception:  - 10.100.193.151: Authentication failed.
```

It took me 47 attempts (on a 4-node env) to reproduce it
On environments with more nodes, it should be easier to reproduce

**Comment by kvanhijf** [comment]
Executing the same code, but with use of file_mutex lock per StorageRouter, i came down to an average of 21-22 sec per call, which is an increase of +/- 14sec --> not good
Executing the same code without locks and without threads, i came down to an average of 30-31 sec per call, so even worse

Now testing making use of a different SSHClient per function call in the threads, currently i'm at an average of 8-9 seconds (so only 1-2 seconds slower) and not running into any non-threadsafe issues

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1261 --> openvstorage-2.7.8-rev.4429.a90f470

@QA: GenericController.refresh_package_information now makes use of a new client instance per thread that is spawned. Executing the code snippet pasted earlier by me, should no longer introduce any issues

**Comment by pploegaert** [comment]
VALIDATED OK using code snipper
