### ISSUE TITLE
Config gone in config manager of abm arakoon

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1270]
**On all our CI test environments** we noticed the following exception:
```
[EXCEPTION] Error during execution of <alba_health_check.AlbaHealthCheck object at 0x7fd74ab24510>.run
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 35, in <module>
    class HealthCheckController(object):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 419, in HealthCheckController
    HealthCheckController.run_method(*arguments)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 403, in run_method
    getattr(cl, option['function'])(logger)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/alba/alba_health_check.py", line 675, in run
    AlbaHealthCheck.get_disk_safety(logger)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/alba/alba_health_check.py", line 537, in get_disk_safety
    namespaces = AlbaCLI.run(command="get-disk-safety", config=config)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/helpers/albacli.py", line 156, in run
    raise RuntimeError(output['error']['message'])
RuntimeError: Arakoon_exc.Exception(4, "Not_found")
```

After looking into why the exception occurs I noticed the following:
```
root@ovs-node01-1604:~# alba get-disk-safety --config=arakoon://config/ovs/arakoon/arakoon-mybackend02-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini
2016-12-14 11:55:08 899347 +0100 - ovs-node01-1604 - 9033/0 - alba/cli - 0 - warning - Arakoon_exc.Exception(4, "Not_found")
root@ovs-node01-1604:~# ovs config get /ovs/arakoon/arakoon-mybackend02-abm/config
root@ovs-node01-1604:~# 
```

Apparently the arakoon ABM config is gone from the config manager.

**Comment by kinvaris** [comment]
After looking into the issue we saw that the `arakoon` prefix has been deleted from the config param: `/ovs/arakoon/arakoon-mybackend-abm/config` --> `/ovs/arakoon/mybackend-abm/config`

So the config does exists but just under another name
