### ISSUE TITLE
Error when adding backend

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1382]
Problem:
Got following error when creating a backend with the ovs gui. (already created 2 backend without an issues)

Error ovs-workers:
```
Jan 27 14:45:00 pocops-voldrv03 celery[22389]: 2017-01-27 14:45:00 83900 +0100 - pocops-voldrv03 - 22570/139674526828288 - lib/alba - 98 - DEBUG - Ensuring NSM safety for backend flash-12-abm
Jan 27 14:45:01 pocops-voldrv03 celery[22389]: 2017-01-27 14:45:01 02000 +0100 - pocops-voldrv03 - 22570/139674526828288 - lib/alba - 99 - ERROR - NSM Checkup failed for backend flash-12
Jan 27 14:45:01 pocops-voldrv03 celery[22389]: Traceback (most recent call last):
Jan 27 14:45:01 pocops-voldrv03 celery[22389]:   File "/opt/OpenvStorage/ovs/lib/alba.py", line 842, in nsm_checkup
Jan 27 14:45:01 pocops-voldrv03 celery[22389]:     load_ok = min(nsm_loads.values()) < maxload
Jan 27 14:45:01 pocops-voldrv03 celery[22389]: ValueError: min() arg is an empty sequence
Jan 27 14:45:01 pocops-voldrv03 celery[22389]: 2017-01-27 14:45:01 02600 +0100 - pocops-voldrv03 - 22570/139674526828288 - lib/alba - 100 - DEBUG - Ensuring NSM safety for backend flash-11-abm
Jan 27 14:45:01 pocops-voldrv03 celery[22389]: 2017-01-27 14:45:01 70900 +0100 - pocops-voldrv03 - 22570/139674526828288 - lib/alba - 101 - DEBUG - Processing NSM 0
Jan 27 14:45:01 pocops-voldrv03 celery[22389]: 2017-01-27 14:45:01 70900 +0100 - pocops-voldrv03 - 22570/139674526828288 - lib/alba - 102 - DEBUG - Currently 1 NSM hosts
Jan 27 14:45:01 pocops-voldrv03 celery[22389]: 2017-01-27 14:45:01 71000 +0100 - pocops-voldrv03 - 22570/139674526828288 - lib/alba - 103 - DEBUG - NSM load OK
Jan 27 14:45:01 pocops-voldrv03 celery[22389]: 2017-01-27 14:45:01 71000 +0100 - pocops-voldrv03 - 22570/139674526828288 - lib/ensure single - 104 - ERROR - Ensure single CHAINED mode - ID 1485524700_pL4Aj6olCr - Task alba.nsm_checkup with default params failed
Jan 27 14:45:01 pocops-voldrv03 celery[22389]: Traceback (most recent call last):
Jan 27 14:45:01 pocops-voldrv03 celery[22389]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 305, in new_function
Jan 27 14:45:01 pocops-voldrv03 celery[22389]:     output = function(*args, **kwargs)
Jan 27 14:45:01 pocops-voldrv03 celery[22389]:   File "/opt/OpenvStorage/ovs/lib/alba.py", line 939, in nsm_checkup
Jan 27 14:45:01 pocops-voldrv03 celery[22389]:     raise RuntimeError('Checking NSM failed for ALBA backends: {0}'.format(', '.join(failed_backends)))
Jan 27 14:45:01 pocops-voldrv03 celery[22389]: RuntimeError: Checking NSM failed for ALBA backends: flash-12
Jan 27 14:45:01 pocops-voldrv03 celery[22389]: 2017-01-27 14:45:01 71200 +0100 - pocops-voldrv03 - 22570/139674526828288 - lib/ensure single - 105 - INFO - Ensure single CHAINED mode - ID 1485524700_pL4Aj6olCr - Amount of jobs pending for key ovs_ensure_single_alba.nsm_checkup: 0
Jan 27 14:45:01 pocops-voldrv03 celery[22389]: 2017-01-27 14:45:01 90100 +0100 - pocops-voldrv03 - 22389/139674526828288 - celery/celery.worker.job - 202 - ERROR - Task alba.nsm_checkup[b81343aa-5e50-4de3-b448-cbda1b5e3ebf] raised unexpected: RuntimeError('Checking NSM failed for ALBA backends: flash-12',)
Jan 27 14:45:01 pocops-voldrv03 celery[22389]: Traceback (most recent call last):
Jan 27 14:45:01 pocops-voldrv03 celery[22389]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Jan 27 14:45:01 pocops-voldrv03 celery[22389]:     R = retval = fun(*args, **kwargs)
Jan 27 14:45:01 pocops-voldrv03 celery[22389]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Jan 27 14:45:01 pocops-voldrv03 celery[22389]:     return self.run(*args, **kwargs)
Jan 27 14:45:01 pocops-voldrv03 celery[22389]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 305, in new_function
Jan 27 14:45:01 pocops-voldrv03 celery[22389]:     output = function(*args, **kwargs)
Jan 27 14:45:01 pocops-voldrv03 celery[22389]:   File "/opt/OpenvStorage/ovs/lib/alba.py", line 939, in nsm_checkup
Jan 27 14:45:01 pocops-voldrv03 celery[22389]:     raise RuntimeError('Checking NSM failed for ALBA backends: {0}'.format(', '.join(failed_backends)))
Jan 27 14:45:01 pocops-voldrv03 celery[22389]: RuntimeError: Checking NSM failed for ALBA backends: flash-12
```

Version:
```
root@pocops-voldrv03:~# dpkg -l | grep openvstorage
ii  openvstorage                         2.7.9.2-1                       amd64        openvStorage
ii  openvstorage-backend                 1.7.9.1-1                       amd64        openvStorage Backend plugin
ii  openvstorage-backend-core            1.7.9.1-1                       amd64        openvStorage Backend plugin core
ii  openvstorage-backend-webapps         1.7.9.1-1                       amd64        openvStorage Backend plugin Web Applications
ii  openvstorage-core                    2.7.9.2-1                       amd64        openvStorage core
ii  openvstorage-hc                      1.7.9.1-1                       amd64        openvStorage Backend plugin HyperConverged
ii  openvstorage-sdm                     1.6.9.1-1                       amd64        Open vStorage Backend ASD Manager
ii  openvstorage-webapps                 2.7.9.2-1                       amd64        openvStorage Web Applications

```

**Comment by wimpers** [comment]
@khenderick if this would be a hard one to fix. let me know.

**Comment by khenderick** [comment]
@wimpers, I've looked into this one before and I have no sane answer on how this could be possible. It means an nsm checkup fails because there's no nsm yet at this point. That's something that should be created a few lines above. If the first nsm fails, it should stop and remove the backend again (rollback). So I really don't have a clue yet, and I thus have no idea how hard it will be to fix.

**Comment by wimpers** [comment]
Can Qa try to reproduce and add somemore logging?

**Comment by khenderick** [comment]
Based on the first log snippet, this was _not_ executed when adding a backend. The stacktraces are different and it looks like it was processing multiple backends, something that won't happen in an add_cluster.

This however makes sense. The above error is indeed possible if an nsm checkup was scheduled and running while a given backend is being set up. It might then indeed fail because the backend wasn't setup completely yet. However, it will have no impact on the backend being set up.

**Comment by khenderick** [comment]
Reproduced

```
...
Feb 09 10:51:11 ovs-100 celery[29181]: Traceback (most recent call last):
Feb 09 10:51:11 ovs-100 celery[29181]:   File "/opt/OpenvStorage/ovs/lib/alba.py", line 887, in nsm_checkup
Feb 09 10:51:11 ovs-100 celery[29181]:     load_ok = min(nsm_loads.values()) < maxload
Feb 09 10:51:11 ovs-100 celery[29181]: ValueError: min() arg is an empty sequence
Feb 09 10:51:11 ovs-100 celery[29181]: 2017-02-09 10:51:11 75100 +0100 - ovs-100 - 29195/140563367610112 - lib/ensure single - 28 - ERROR - Ensure single CHAINED mode - ID 1486633871_BLwuWuhhPp - Task alba.nsm_checkup with default params failed
Feb 09 10:51:11 ovs-100 celery[29181]: Traceback (most recent call last):
Feb 09 10:51:11 ovs-100 celery[29181]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 305, in new_function
Feb 09 10:51:11 ovs-100 celery[29181]:     output = function(*args, **kwargs)
Feb 09 10:51:11 ovs-100 celery[29181]:   File "/opt/OpenvStorage/ovs/lib/alba.py", line 985, in nsm_checkup
Feb 09 10:51:11 ovs-100 celery[29181]:     raise RuntimeError('Checking NSM failed for ALBA backends: {0}'.format(', '.join(failed_backends)))
Feb 09 10:51:11 ovs-100 celery[29181]: RuntimeError: Checking NSM failed for ALBA backends: backend3
```

**Comment by khenderick** [comment]
openvstorage/framework-alba-plugin#360 -> openvstorage-backend-1.7.12-dev.1486633973.896809e

**Comment by khenderick** [comment]
openvstorage-backend-1.7.12.1

**Comment by pploegaert** [comment]
Validation continued in:
https://github.com/openvstorage/integrationtests/issues/455
