### ISSUE TITLE
vPool with 2 proxies fails to deploy with 20+10 GB write disk

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1393]
We have a environment that has a 2 write disks (20GB and 10GB). This should be sufficient to deploy 1 vPool with fragment cache enabled on disk:
```
/dev/vdb1        20G   44M   19G   1% /mnt/ssd2
/dev/vdd1       9.8G   23M  9.2G   1% /mnt/ssd3
```

* 2 proxies: min. 2 GB fragment cache
* 20GB sco cache

So this should be seperated in 18 GB sco cache and 2 GB fragment cache.

But we get the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 408, in add_vpool
    raise ValueError('Errors validating the specified parameters:\n - {0}'.format('\n - '.join(set(error_messages))))
ValueError: Errors validating the specified parameters:
 - Fragment cache is too small to deploy 2 proxies. 1GiB is required per proxy and with an available size of 1.34GiB, 1 proxy can be deployed
```

Because the framework favors the biggest disk first instead of load balancing the proxies and/or sco cache across the WRITE disks.

This also results in the fact that if 1 disk with WRITE role should fail in a node with 2 WRITE disks, the node will fail.

**Comment by JeffreyDevloo** [comment]
Trying to understand the current flow: it goes something like this:

When adding caching to the proxies (either fragment or block) we ask to reserve at least 1GiB for every proxy for every cache type
so 1 proxy with local frag caching --> 1 GiB
2 proxies with local frag caching --> 2 GiB
1 proxy with local frag + block caching --> 2 GiB
2 proxies with local frag + block caching --> 4 GiB

The sco cache requested (write buffer) will be proportionally divided across both write partitions: the 20GiB one will be used for 2/3 of the sco cache and the 10GiB one will be used 1/3

The caching size is now calculated on the would-be used part of the biggest write partition. This translates into 20GiB * 2/3 * 10%. Which results in 1.3 ish GiB.
However the required size for caching is 2GiB and thus we cannot deploy the proxies that way

The proposed solution is to use the second partitions sco cache size to cache for the proxies (which would result in 0.7ish GiB) (this would still be too small to have the 1GIB requirement though)

Another solution is to leverage this off to alba. Let them know they can use path X for X KiBs of caching and path Y for Y amounts of caching

A third solution would to use LVM to create a combined partition of both write caches and no longer calculate the proportions?

@wimpers Throwing this back to BAM to decide

**Comment by wimpers** [comment]
Since it is  only an issue for local block/fragment cache and this isn't use; let's postpone to after J.
