### ISSUE TITLE
add_vpool failed: RuntimeError: Could not load metadata from environment

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1427]
When I tried to add a vPool the status stayed on `INSTALLING`. After investigation we found this in the logs:
```
eb 08 16:05:54 ovs-node01-1604 celery[3212]: 2017-02-08 16:05:54 88000 +0100 - ovs-node01-1604 - 3362/140582164952832 - lib/storagerouter - 84 - INFO - Add vPool myvpool02 started
Feb 08 16:05:56 ovs-node01-1604 celery[3212]: 2017-02-08 16:05:56 24700 +0100 - ovs-node01-1604 - 3212/140582164952832 - celery/celery.worker.job - 568 - ERROR - Task ovs.storagerouter.add_vpool[fcfe2a91-12a7-4f7e-a95f-b6dab4d104
Feb 08 16:05:56 ovs-node01-1604 celery[3212]: Traceback (most recent call last):
Feb 08 16:05:56 ovs-node01-1604 celery[3212]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Feb 08 16:05:56 ovs-node01-1604 celery[3212]:     R = retval = fun(*args, **kwargs)
Feb 08 16:05:56 ovs-node01-1604 celery[3212]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Feb 08 16:05:56 ovs-node01-1604 celery[3212]:     return self.run(*args, **kwargs)
Feb 08 16:05:56 ovs-node01-1604 celery[3212]:   File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 425, in add_vpool
Feb 08 16:05:56 ovs-node01-1604 celery[3212]:     arakoon_config = StorageRouterController._retrieve_alba_arakoon_config(backend_guid=alba_backend_guid, ovs_client=ovs_client)
Feb 08 16:05:56 ovs-node01-1604 celery[3212]:   File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1494, in _retrieve_alba_arakoon_config
Feb 08 16:05:56 ovs-node01-1604 celery[3212]:     raise RuntimeError('Could not load metadata from environment {0}'.format(ovs_client.ip))
Feb 08 16:05:56 ovs-node01-1604 celery[3212]: RuntimeError: Could not load metadata from environment 10.100.199.171
```

**Comment by kinvaris** [comment]
We've observed the following on our environment from node B to node A:
```
	
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 103, in get_metadata
    client = SSHClient(storagerouter)
  File "/opt/OpenvStorage/ovs/extensions/generic/sshclient.py", line 169, in __init__
    self._connect()
  File "/opt/OpenvStorage/ovs/extensions/generic/sshclient.py", line 205, in _connect
    raise NotAuthenticatedException('Authentication failed to {0} with username {1} and password {2}'.format(self.ip, self.username, self.password))
NotAuthenticatedException: Authentication failed to 10.100.199.171 with username ovs
```

**Comment by kinvaris** [comment]
It seems to be a ssh key deployment problem, we cannot ssh from node 2 to node 1.

**Comment by kinvaris** [comment]
This SSH key problem is not consistent because other environments do not seem to have the problem. 

More details about the setup:
* 3 node setup
=======================
* ovs@A - > ovs@B: ok
* ovs@A - > ovs@C: ok
* ovs@A - > ovs@A: **nok**
=======================
* ovs@B -> ovs@A: **nok**
* ovs@B - > ovs@C: ok
* ovs@B - > ovs@B: ok
=======================
* ovs@C - > ovs@B: ok
* ovs@C - > ovs@A: **nok**
* ovs@C - > ovs@C: ok

The connection problems seem to occur towards node A

**Comment by khenderick** [comment]
I can't reproduce it on my 3-node setup atm, will try a few others.

**Comment by khenderick** [comment]
Cannot reproduce it on my 4-node test environment either.

```
2017-02-09 09:50:03 48800 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 0 - INFO - Connection from root@10.100.169.100 to root@10.100.169.100... OK
2017-02-09 09:50:03 93100 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 1 - INFO - Connection from root@10.100.169.100 to ovs@10.100.169.100... OK
2017-02-09 09:50:04 30300 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 2 - INFO - Connection from root@10.100.169.100 to root@10.100.169.101... OK
2017-02-09 09:50:04 71100 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 3 - INFO - Connection from root@10.100.169.100 to ovs@10.100.169.101... OK
2017-02-09 09:50:05 08300 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 4 - INFO - Connection from root@10.100.169.100 to root@10.100.169.252... OK
2017-02-09 09:50:05 49100 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 5 - INFO - Connection from root@10.100.169.100 to ovs@10.100.169.252... OK
2017-02-09 09:50:05 87600 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 6 - INFO - Connection from root@10.100.169.100 to root@10.100.169.251... OK
2017-02-09 09:50:06 28700 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 7 - INFO - Connection from root@10.100.169.100 to ovs@10.100.169.251... OK
2017-02-09 09:50:10 64000 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 8 - INFO - Connection from ovs@10.100.169.100 to root@10.100.169.100... OK
2017-02-09 09:50:10 66500 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 9 - INFO - Connection from ovs@10.100.169.100 to ovs@10.100.169.100... OK
2017-02-09 09:50:13 25500 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 10 - INFO - Connection from ovs@10.100.169.100 to root@10.100.169.101... OK
2017-02-09 09:50:15 87500 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 11 - INFO - Connection from ovs@10.100.169.100 to ovs@10.100.169.101... OK
2017-02-09 09:50:18 47200 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 12 - INFO - Connection from ovs@10.100.169.100 to root@10.100.169.252... OK
2017-02-09 09:50:21 09900 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 13 - INFO - Connection from ovs@10.100.169.100 to ovs@10.100.169.252... OK
2017-02-09 09:50:23 69100 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 14 - INFO - Connection from ovs@10.100.169.100 to root@10.100.169.251... OK
2017-02-09 09:50:26 31100 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 15 - INFO - Connection from ovs@10.100.169.100 to ovs@10.100.169.251... OK
2017-02-09 09:50:29 46300 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 16 - INFO - Connection from root@10.100.169.101 to root@10.100.169.100... OK
2017-02-09 09:50:30 80000 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 17 - INFO - Connection from root@10.100.169.101 to ovs@10.100.169.100... OK
2017-02-09 09:50:30 82200 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 18 - INFO - Connection from root@10.100.169.101 to root@10.100.169.101... OK
2017-02-09 09:50:32 17600 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 19 - INFO - Connection from root@10.100.169.101 to ovs@10.100.169.101... OK
2017-02-09 09:50:33 49100 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 20 - INFO - Connection from root@10.100.169.101 to root@10.100.169.252... OK
2017-02-09 09:50:34 84700 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 21 - INFO - Connection from root@10.100.169.101 to ovs@10.100.169.252... OK
2017-02-09 09:50:36 16700 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 22 - INFO - Connection from root@10.100.169.101 to root@10.100.169.251... OK
2017-02-09 09:50:37 52300 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 23 - INFO - Connection from root@10.100.169.101 to ovs@10.100.169.251... OK
2017-02-09 09:50:39 54800 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 24 - INFO - Connection from ovs@10.100.169.101 to root@10.100.169.100... OK
2017-02-09 09:50:39 90700 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 25 - INFO - Connection from ovs@10.100.169.101 to ovs@10.100.169.100... OK
2017-02-09 09:50:40 22400 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 26 - INFO - Connection from ovs@10.100.169.101 to root@10.100.169.101... OK
2017-02-09 09:50:40 24600 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 27 - INFO - Connection from ovs@10.100.169.101 to ovs@10.100.169.101... OK
2017-02-09 09:50:40 55900 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 28 - INFO - Connection from ovs@10.100.169.101 to root@10.100.169.252... OK
2017-02-09 09:50:40 92000 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 29 - INFO - Connection from ovs@10.100.169.101 to ovs@10.100.169.252... OK
2017-02-09 09:50:41 23100 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 30 - INFO - Connection from ovs@10.100.169.101 to root@10.100.169.251... OK
2017-02-09 09:50:41 69200 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 31 - INFO - Connection from ovs@10.100.169.101 to ovs@10.100.169.251... OK
2017-02-09 09:50:44 33100 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 32 - INFO - Connection from root@10.100.169.252 to root@10.100.169.100... OK
2017-02-09 09:50:45 02300 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 33 - INFO - Connection from root@10.100.169.252 to ovs@10.100.169.100... OK
2017-02-09 09:50:45 64300 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 34 - INFO - Connection from root@10.100.169.252 to root@10.100.169.101... OK
2017-02-09 09:50:46 29100 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 35 - INFO - Connection from root@10.100.169.252 to ovs@10.100.169.101... OK
2017-02-09 09:50:46 31400 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 36 - INFO - Connection from root@10.100.169.252 to root@10.100.169.252... OK
2017-02-09 09:50:46 97300 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 37 - INFO - Connection from root@10.100.169.252 to ovs@10.100.169.252... OK
2017-02-09 09:50:47 60700 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 38 - INFO - Connection from root@10.100.169.252 to root@10.100.169.251... OK
2017-02-09 09:50:48 28300 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 39 - INFO - Connection from root@10.100.169.252 to ovs@10.100.169.251... OK
2017-02-09 09:50:50 52000 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 40 - INFO - Connection from ovs@10.100.169.252 to root@10.100.169.100... OK
2017-02-09 09:50:50 95100 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 41 - INFO - Connection from ovs@10.100.169.252 to ovs@10.100.169.100... OK
2017-02-09 09:50:51 38700 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 42 - INFO - Connection from ovs@10.100.169.252 to root@10.100.169.101... OK
2017-02-09 09:50:51 82300 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 43 - INFO - Connection from ovs@10.100.169.252 to ovs@10.100.169.101... OK
2017-02-09 09:50:52 21100 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 44 - INFO - Connection from ovs@10.100.169.252 to root@10.100.169.252... OK
2017-02-09 09:50:52 23300 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 45 - INFO - Connection from ovs@10.100.169.252 to ovs@10.100.169.252... OK
2017-02-09 09:50:52 63500 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 46 - INFO - Connection from ovs@10.100.169.252 to root@10.100.169.251... OK
2017-02-09 09:50:53 07500 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 47 - INFO - Connection from ovs@10.100.169.252 to ovs@10.100.169.251... OK
2017-02-09 09:50:55 38400 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 48 - INFO - Connection from root@10.100.169.251 to root@10.100.169.100... OK
2017-02-09 09:50:55 97300 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 49 - INFO - Connection from root@10.100.169.251 to ovs@10.100.169.100... OK
2017-02-09 09:50:56 49700 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 50 - INFO - Connection from root@10.100.169.251 to root@10.100.169.101... OK
2017-02-09 09:50:57 03300 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 51 - INFO - Connection from root@10.100.169.251 to ovs@10.100.169.101... OK
2017-02-09 09:50:57 55800 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 52 - INFO - Connection from root@10.100.169.251 to root@10.100.169.252... OK
2017-02-09 09:50:58 11800 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 53 - INFO - Connection from root@10.100.169.251 to ovs@10.100.169.252... OK
2017-02-09 09:50:58 14900 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 54 - INFO - Connection from root@10.100.169.251 to root@10.100.169.251... OK
2017-02-09 09:50:58 70400 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 55 - INFO - Connection from root@10.100.169.251 to ovs@10.100.169.251... OK
2017-02-09 09:51:01 09900 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 56 - INFO - Connection from ovs@10.100.169.251 to root@10.100.169.100... OK
2017-02-09 09:51:01 98400 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 57 - INFO - Connection from ovs@10.100.169.251 to ovs@10.100.169.100... OK
2017-02-09 09:51:02 62600 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 58 - INFO - Connection from ovs@10.100.169.251 to root@10.100.169.101... OK
2017-02-09 09:51:03 18100 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 59 - INFO - Connection from ovs@10.100.169.251 to ovs@10.100.169.101... OK
2017-02-09 09:51:03 71400 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 60 - INFO - Connection from ovs@10.100.169.251 to root@10.100.169.252... OK
2017-02-09 09:51:04 28100 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 61 - INFO - Connection from ovs@10.100.169.251 to ovs@10.100.169.252... OK
2017-02-09 09:51:04 79000 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 62 - INFO - Connection from ovs@10.100.169.251 to root@10.100.169.251... OK
2017-02-09 09:51:04 81400 +0100 - ovs-100 - 31621/140562972256000 - lib/quality - 63 - INFO - Connection from ovs@10.100.169.251 to ovs@10.100.169.251... OK
```

**Comment by khenderick** [comment]
@kinvaris, please try to reproduce on your env and double check there isn't anything else interfering with exchanged keys.

**Comment by kinvaris** [comment]
We've observed the same problem again today on a CI environment. When looking into it some ssh deamons refused to use the keys in `/opt/OpenvStorage` because the rights were incorrectly configured.

On some nodes it worked with rights `755` on some nodes we had to change them to `700`. 
After applying rights `700` for `/opt/OpenvStorage` on every node, it worked again.

@khenderick:
```
chmod 700 /opt/OpenvStorage/.ssh
chmod 600 /opt/OpenvStorage/.ssh/authorized_keys 
```

**Comment by khenderick** [comment]
@kinvaris, thanks. Apparently our more recent images had this issue while I had based my changes on my own (slightly older) image.

**Comment by khenderick** [comment]
#1432 -> openvstorage-2.7.12-dev.1486650333.7687b25

**Comment by khenderick** [comment]
openvstorage-2.7.12.1

**Comment by JeffreyDevloo** [comment]
### Test description
Adding, extending and shrinking the vpool.
Put some load on the vpool.
https://github.com/openvstorage/integrationtests/blob/master/ci/scenarios/vPool/add_remove_alba_vpool_test/main.py

This test has been running for a while and we did not encounter this issue any longer.
