### ISSUE TITLE
Error when removing disk from backend

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/framework#1430]
2 ASDs / disk, both ASDs were removed. When trying to remove the disk from the backend following error is encountered.

```
Feb  9 11:51:26 stor-02 gunicorn[991]:  "false", "contents": "node_id,_relations"}}
Feb  9 11:51:26 stor-02 celery[17065]: 2017-02-09 11:51:26 72000 +0100 - stor-02.be-g8-3 - 1316/139914956220160 - lib/ensure single - 30711 - ERROR - Ensure single CHAINED mode - ID 1486637486_Tel1S
o5jLu - Task albanode.remove_disk with params {'node_guid': '0a25e46f-c928-4629-b83a-99daee5d1139', 'device_alias': u'/dev/disk/by-id/ata-Maximus-512GB_E20150714150065'} failed
Feb  9 11:51:26 stor-02 celery[17065]: Traceback (most recent call last):
Feb  9 11:51:26 stor-02 celery[17065]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 305, in new_function
Feb  9 11:51:26 stor-02 celery[17065]:     output = function(*args, **kwargs)
Feb  9 11:51:26 stor-02 celery[17065]:   File "/opt/OpenvStorage/ovs/lib/albanode.py", line 226, in remove_disk
Feb  9 11:51:26 stor-02 celery[17065]:     result = node.client.remove_disk(disk_id=device_id, partition_aliases=disk_to_clear.partitions[0].aliases if len(disk_to_clear.partitions) > 0 else [])
Feb  9 11:51:26 stor-02 celery[17065]: AttributeError: 'NoneType' object has no attribute 'partitions'
Feb  9 11:51:26 stor-02 celery[17065]: 2017-02-09 11:51:26 72100 +0100 - stor-02.be-g8-3 - 1316/139914956220160 - lib/ensure single - 30712 - INFO - Ensure single CHAINED mode - ID 1486637486_Tel1So5jLu - Amount of jobs pending for key ovs_ensure_single_albanode.remove_disk: 0
Feb  9 11:51:26 stor-02 celery[17065]: 2017-02-09 11:51:26 73700 +0100 - stor-02.be-g8-3 - 17065/139914956220160 - celery/celery.worker.job - 30713 - ERROR - Task albanode.remove_disk[e517681a-fdcf-488b-a120-d07f6ece69cf] raised unexpected: AttributeError("'NoneType' object has no attribute 'partitions'",)
Feb  9 11:51:26 stor-02 celery[17065]: Traceback (most recent call last):
Feb  9 11:51:26 stor-02 celery[17065]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Feb  9 11:51:26 stor-02 celery[17065]:     R = retval = fun(*args, **kwargs)
Feb  9 11:51:26 stor-02 celery[17065]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Feb  9 11:51:26 stor-02 celery[17065]:     return self.run(*args, **kwargs)
Feb  9 11:51:26 stor-02 celery[17065]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 305, in new_function
Feb  9 11:51:26 stor-02 celery[17065]:     output = function(*args, **kwargs)
Feb  9 11:51:26 stor-02 celery[17065]:   File "/opt/OpenvStorage/ovs/lib/albanode.py", line 226, in remove_disk
Feb  9 11:51:26 stor-02 celery[17065]:     result = node.client.remove_disk(disk_id=device_id, partition_aliases=disk_to_clear.partitions[0].aliases if len(disk_to_clear.partitions) > 0 else [])
Feb  9 11:51:26 stor-02 celery[17065]: AttributeError: 'NoneType' object has no attribute 'partitions'
```

Environment = be-g8-3

Open vStorage packages
```
gig@stor-02:/var/log$ dpkg -l | grep openvstorage
ii  openvstorage                         2.7.10.1-1                              amd64        openvStorage
ii  openvstorage-backend                 1.7.10.1-1                              amd64        openvStorage Backend plugin
ii  openvstorage-backend-core            1.7.10.1-1                              amd64        openvStorage Backend plugin core
ii  openvstorage-backend-webapps         1.7.10.1-1                              amd64        openvStorage Backend plugin Web Applications
ii  openvstorage-core                    2.7.10.1-1                              amd64        openvStorage core
ii  openvstorage-hc                      1.7.10.1-1                              amd64        openvStorage Backend plugin HyperConverged
ii  openvstorage-health-check            3.2.0-fargo.2-1                         amd64        Open vStorage HealthCheck
ii  openvstorage-sdm                     1.6.10.1-1                              amd64        Open vStorage Backend ASD Manager
ii  openvstorage-webapps                 2.7.10.1-1                              amd64        openvStorage Web Applications
gig@stor-02:/var/log$ dpkg -l | grep volumedriver
ii  libovsvolumedriver                   6.9.0-0                                 amd64        VolumeDriver client library
ii  volumedriver-no-dedup-base           6.9.0-0                                 amd64        VolumeDriver common infrastructure
ii  volumedriver-no-dedup-server         6.9.0-0                                 amd64        VolumeDriver daemon and helpers
gig@stor-02:/var/log$ dpkg -l | grep alba
ii  alba                                 1.3.4                                   amd64        the ALternative BAckend
gig@stor-02:/var/log$ 
```

**Comment by kvanhijf** [comment]
@openvstorage/qa : No idea how to reproduce, think out of the box ;)

https://github.com/openvstorage/framework-alba-plugin/pull/361 --> openvstorage-backend-1.7.12-dev.1486650204.209a042

**Comment by khenderick** [comment]
openvstorage-backend-1.7.12.1

**Comment by saelbrec** [comment]
Related to https://github.com/openvstorage/framework-alba-plugin/issues/315
