### ISSUE TITLE
vPool failed to create because some alba disks are not mounted

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1448]
I tried to create a vPool and it failed with the following error:
```
Feb 14 15:28:47 ovs-node02-1604 celery[27349]: 2017-02-14 15:28:47 14300 +0100 - ovs-node02-1604 - 27349/140142403942144 - celery/celery.pool - 7038 - DEBUG - TaskPool: Apply <function _fast_trace_task at 0x7f756df932a8> (args:('ovs.
storagerouter.add_vpool', '3b7d8418-41bb-4483-a2e7-4eee413cab1e', ({u'vpool_name': u'bla', u'fragment_cache_on_write': False, u'storage_ip': u'10.100.199.181', u'connection_info': {u'client_secret': u'sPcBSW?9I~H\'<h|u{#.~w7C/4>;a>D\
'h}OY_#Co}nvMc!"*bZ|Bj\'YUmeMPCptV?fo1f9uD.l8yYc><Cs[5sev!LVS"b~rsA#~++S}j0sYhW_T8]ZShle!O:x:bO]2lH', u'host': u'10.100.199.181', u'local': True, u'port': 443, u'client_id': '26f2172b-6e4e-444a-b11d-ab2803495aa7'}, u'backend_info': {
u'alba_backend_guid': u'8fff9c5f-59e3-46aa-8a64-bbcc982c7975', u'preset': u'default'}, u'storagerouter_ip': u'10.100.199.181', u'config_params': {u'dtl_mode': u'no_sync', u'sco_size': 4, u'write_buffer': 128, u'cluster_size': 4, u'dt
l_transport': u'tcp'}, u'writecache_size': 2, u'parallelism': {u'proxies': 1}, u'fragment_cache_on_read': False},), {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': ({u'vpool_name': u'bla', u'fragment_cach
e_on_write': False, u'storage_ip': u'10.100.199.181', u'connection_info':... kwargs:{})

Feb 14 15:28:52 ovs-node02-1604 celery[27349]: 2017-02-14 15:28:52 76700 +0100 - ovs-node02-1604 - 27349/140142403942144 - celery/celery.worker.job - 7040 - ERROR - Task ovs.storagerouter.add_vpool[3b7d8418-41bb-4483-a2e7-4eee413cab1e] raised unexpected: ValueError('Errors validating the specified parameters:\n - Mountpoint /mnt/alba-asd/FqpBShsaB3HY5lCo is not mounted\n - Mountpoint /mnt/alba-asd/d8QgYwTsUwSEJI1F is not mounted',)
Feb 14 15:28:52 ovs-node02-1604 celery[27349]: Traceback (most recent call last):
Feb 14 15:28:52 ovs-node02-1604 celery[27349]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Feb 14 15:28:52 ovs-node02-1604 celery[27349]:     R = retval = fun(*args, **kwargs)
Feb 14 15:28:52 ovs-node02-1604 celery[27349]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Feb 14 15:28:52 ovs-node02-1604 celery[27349]:     return self.run(*args, **kwargs)
Feb 14 15:28:52 ovs-node02-1604 celery[27349]:   File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 401, in add_vpool
Feb 14 15:28:52 ovs-node02-1604 celery[27349]:     raise ValueError('Errors validating the specified parameters:\n - {0}'.format('\n - '.join(set(error_messages))))
Feb 14 15:28:52 ovs-node02-1604 celery[27349]: ValueError: Errors validating the specified parameters:
Feb 14 15:28:52 ovs-node02-1604 celery[27349]:  - Mountpoint /mnt/alba-asd/FqpBShsaB3HY5lCo is not mounted
Feb 14 15:28:52 ovs-node02-1604 celery[27349]:  - Mountpoint /mnt/alba-asd/d8QgYwTsUwSEJI1F is not mounted
```

**Comment by khenderick** [comment]
#1459 -> openvstorage-2.7.13-dev.1487578008.d50f5cd

**Comment by khenderick** [comment]
openvstorage-2.7.13.1
