### ISSUE TITLE
Create snapshot on template Runtime error

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1455]
In the ovs-workers the create snapshot job throws a Runtime error when the vdisk is a template.

ovs version:
```
root@pocops-voldrv02:~# dpkg -l | grep openvstorage
ii  openvstorage                         2.7.10.1-1                      amd64        openvStorage
ii  openvstorage-backend                 1.7.10.1-1                      amd64        openvStorage Backend plugin
ii  openvstorage-backend-core            1.7.10.1-1                      amd64        openvStorage Backend plugin core
ii  openvstorage-backend-webapps         1.7.10.1-1                      amd64        openvStorage Backend plugin Web Applicati
```

Error:
```
Feb 16 16:00:01 pocops-voldrv02 celery[18323]: 2017-02-16 16:00:01 60400 +0100 - pocops-voldrv02 - 16115/140484570220288 - lib/vdisk - 235675 - INFO - Create snapshot for vDisk Xubuntu16.04TestMatthias
Feb 16 16:00:01 pocops-voldrv02 celery[18323]: 2017-02-16 16:00:01 74700 +0100 - pocops-voldrv02 - 16115/140484570220288 - lib/vdisk - 235676 - INFO - Create snapshot for vDisk Win10_template
Feb 16 16:00:01 pocops-voldrv02 celery[18323]: 2017-02-16 16:00:01 75800 +0100 - pocops-voldrv02 - 16115/140484570220288 - lib/generic tasks - 235677 - ERROR - Error taking snapshot for vDisk db84e489-ab17-4fbb-8401-7c895d6f15f8
Feb 16 16:00:01 pocops-voldrv02 celery[18323]: Traceback (most recent call last):
Feb 16 16:00:01 pocops-voldrv02 celery[18323]:   File "/opt/OpenvStorage/ovs/lib/generic.py", line 77, in snapshot_all_vdisks
Feb 16 16:00:01 pocops-voldrv02 celery[18323]:     metadata=metadata)
Feb 16 16:00:01 pocops-voldrv02 celery[18323]:   File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
Feb 16 16:00:01 pocops-voldrv02 celery[18323]:     return self._get_current_object()(*a, **kw)
Feb 16 16:00:01 pocops-voldrv02 celery[18323]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
Feb 16 16:00:01 pocops-voldrv02 celery[18323]:     return orig(self, *args, **kwargs)
Feb 16 16:00:01 pocops-voldrv02 celery[18323]:   File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
Feb 16 16:00:01 pocops-voldrv02 celery[18323]:     return self.run(*args, **kwargs)
Feb 16 16:00:01 pocops-voldrv02 celery[18323]:   File "/opt/OpenvStorage/ovs/lib/vdisk.py", line 346, in create_snapshot
Feb 16 16:00:01 pocops-voldrv02 celery[18323]:     raise RuntimeError(vdisk_result[1])
Feb 16 16:00:01 pocops-voldrv02 celery[18323]: RuntimeError: Templated Volume, snapshot creation forbidden
Feb 16 16:00:01 pocops-voldrv02 celery[18323]: 2017-02-16 16:00:01 76000 +0100 - pocops-voldrv02 - 16115/140484570220288 - lib/vdisk - 235678 - INFO - Create snapshot for vDisk CentOS7_Matthias_disk2
Feb 16 16:00:01 pocops-voldrv02 celery[18323]: 2017-02-16 16:00:01 80700 +0100 - pocops-voldrv02 - 16115/140484570220288 - lib/vdisk - 235679 - INFO - Create snapshot for vDisk Ubuntu_Jeroen
Feb 16 16:00:01 pocops-voldrv02 celery[18323]: 2017-02-16 16:00:01 86800 +0100 - pocops-voldrv02 - 16115/140484570220288 - lib/vdisk - 235680 - INFO - Create snapshot for vDisk Ubuntu1604_Jonas
```

**Comment by khenderick** [comment]
@redlicha, is it allowed to take snapshots from a volume which has been set as template? I was always under the impression that this should indeed not be possible as setting a volume as template will delete all but the selected snapshots as far as I understand.

**Comment by redlicha** [comment]
@khenderick, you're right. snapshotting on a template is not permitted.

**Comment by khenderick** [comment]
All vDisks are snapshotted and all vTemplates fail and are skipped. But let's filter upfront so we don't have the logging overhead.

**Comment by khenderick** [comment]
#1460 -> openvstorage-2.7.13-dev.1487578550.b6bbc5a

**Comment by khenderick** [comment]
openvstorage-2.7.13.1
