### ISSUE TITLE
Alba update not possible after remove node of  a down node

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1458]
### Problem description
Due to the DAL entry, the alba update prerequisite is not met.

Also during update of other packages:
```
2017-02-17 11:00:32 35400 +0100 - jef-node1 - 16842/140548734236416 - update/core - 56 - DEBUG - Refreshing package information
2017-02-17 11:00:37 35900 +0100 - jef-node1 - 16842/140548734236416 - update/core - 58 - DEBUG - Attempt 1: Could not refresh the update information, trying again
2017-02-17 11:00:48 39900 +0100 - jef-node1 - 16842/140548734236416 - update/core - 60 - DEBUG - Attempt 2: Could not refresh the update information, trying again
2017-02-17 11:00:59 43700 +0100 - jef-node1 - 16842/140548734236416 - update/core - 62 - DEBUG - Attempt 3: Could not refresh the update information, trying again
2017-02-17 11:01:10 65600 +0100 - jef-node1 - 16842/140547956135680 - update/alba-plugin - 70 - WARNING - Update information for Alba Node with IP 10.100.69.121 could not be updated
2017-02-17 11:01:14 70700 +0100 - jef-node1 - 16842/140548734236416 - update/core - 73 - DEBUG - Attempt 4: Could not refresh the update information, trying again
2017-02-17 11:01:25 93200 +0100 - jef-node1 - 16842/140548323804928 - update/alba-plugin - 81 - WARNING - Update information for Alba Node with IP 10.100.69.121 could not be updated
2017-02-17 11:01:30 20900 +0100 - jef-node1 - 16842/140548734236416 - update/core - 84 - DEBUG - Attempt 5: Could n
ot refresh the update information, trying again
2017-02-17 11:01:36 24100 +0100 - jef-node1 - 16842/140548734236416 - update/core - 85 - ERROR - Error during update: Could not refresh the update information
Traceback (most recent call last):
  File "ovs/lib/update.py", line 703, in execute_update
    ssh_clients=ssh_clients,
  File "ovs/lib/update.py", line 766, in _refresh_package_information
    UpdateController._logger.debug('Attempt {0}: Could not refresh the update information, trying again'.format(counter))
Exception: Could not refresh the update information
2017-02-17 11:01:36 79900 +0100 - jef-node1 - 16842/140548734236416 - update/core - 86 - DEBUG - Refreshing package information
2017-02-17 11:01:41 79500 +0100 - jef-node1 - 16842/140547956135680 - update/alba-plugin - 94 - WARNING - Update information for Alba Node with IP 10.100.69.121 could not be updated
2017-02-17 11:01:45 99600 +0100 - jef-node1 - 16842/140548734236416 - update/core - 97 - DEBUG - Attempt 1: Could not refresh the update information, trying again
2017-02-17 11:01:58 03600 +0100 - jef-node1 - 16842/140547964528384 - update/alba-plugin - 105 - WARNING - Update information for Alba Node with IP 10.100.69.121 could not be updated
2017-02-17 11:02:03 21900 +0100 - jef-node1 - 16842/140548734236416 - update/core - 108 - DEBUG - Attempt 2: Could not refresh the update information, trying again
2017-02-17 11:02:14 31700 +0100 - jef-node1 - 16842/140548323804928 - update/alba-plugin - 116 - WARNING - Update information for Alba Node with IP 10.100.69.121 could not be updated
2017-02-17 11:02:18 52800 +0100 - jef-node1 - 16842/140548734236416 - update/core - 119 - DEBUG - Attempt 3: Could not refresh the update information, trying again
2017-02-17 11:02:29 58200 +0100 - jef-node1 - 16842/140547964528384 - update/alba-plugin - 127 - WARNING - Update information for Alba Node with IP 10.100.69.121 could not be updated
2017-02-17 11:02:33 63700 +0100 - jef-node1 - 16842/140548734236416 - update/core - 130 - DEBUG - Attempt 4: Could not refresh the update information, trying again
2017-02-17 11:02:44 82500 +0100 - jef-node1 - 16842/140548323804928 - update/alba-plugin - 138 - WARNING - Update information for Alba Node with IP 10.100.69.121 could not be updated
2017-02-17 11:02:48 98900 +0100 - jef-node1 - 16842/140548734236416 - update/core - 141 - DEBUG - Attempt 5: Could not refresh the update information, trying again

```
### Proposed solution
Fix the root cause: https://github.com/openvstorage/framework/issues/1457
### Packages
```
ii  openvstorage                         2.7.12.1-1                          amd64        openvStorage
ii  openvstorage-backend                 1.7.12.1-1                          amd64        openvStorage Backend plugin
ii  openvstorage-backend-core            1.7.12.1-1                          amd64        openvStorage Backend plugin core
ii  openvstorage-backend-webapps         1.7.12.1-1                          amd64        openvStorage Backend plugin Web Applications
ii  openvstorage-core                    2.7.12.1-1                          amd64        openvStorage core
ii  openvstorage-hc                      1.7.12.1-1                          amd64        openvStorage Backend plugin HyperConverged
ii  openvstorage-sdm                     1.6.11.1-1                          amd64        Open vStorage Backend ASD Manager
ii  openvstorage-webapps                 2.7.12.1-1                          amd64        openvStorage Web Applications

```

**Comment by wimpers** [comment]
please validate once #1457 is fixed.
