### ISSUE TITLE
Unsupported label-type detected: loop

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1481]
Wanted to select this disk but had the following error: 
```
Feb 24 14:18:58 ov-02 celery[49114]: 2017-02-24 14:18:58 95200 +0000 - ov-02 - 49114/139973557487360 - celery/celery.worker.job - 81 - ERROR - Task ovs.storagerouter.configure_disk[fd4ec668-f8a0-4835-8239-d435cb7183d1] raised unexpected: ValueError('Unsupported label-typ
Feb 24 14:18:58 ov-02 celery[49114]: Traceback (most recent call last):
Feb 24 14:18:58 ov-02 celery[49114]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Feb 24 14:18:58 ov-02 celery[49114]:     R = retval = fun(*args, **kwargs)
Feb 24 14:18:58 ov-02 celery[49114]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Feb 24 14:18:58 ov-02 celery[49114]:     return self.run(*args, **kwargs)
Feb 24 14:18:58 ov-02 celery[49114]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 305, in new_function
Feb 24 14:18:58 ov-02 celery[49114]:     output = function(*args, **kwargs)
Feb 24 14:18:58 ov-02 celery[49114]:   File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1375, in configure_disk
Feb 24 14:18:58 ov-02 celery[49114]:     partition_size=size)
Feb 24 14:18:58 ov-02 celery[49114]:   File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
Feb 24 14:18:58 ov-02 celery[49114]:     return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
Feb 24 14:18:58 ov-02 celery[49114]:   File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
Feb 24 14:18:58 ov-02 celery[49114]:     return conn.sync_request(handler, oid, *args)
Feb 24 14:18:58 ov-02 celery[49114]:   File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
Feb 24 14:18:58 ov-02 celery[49114]:     raise obj
Feb 24 14:18:58 ov-02 celery[49114]: Exception: Unsupported label-type detected: loop
```

We are not supporting this label right now. Shouldn't we support this?

**Comment by khenderick** [comment]
This most likely indicates that the disk is (or was) used by something like LVM or btrfs.

**Comment by wimpers** [comment]
@matthiasdeblock can you shed some light on the environment where you saw this (ping me on skype about it.)

**Comment by jeroenmaelbrancke** [comment]
I see this on IITB atm.
I build a software raid 5 with 3 disks and the partition table was loop.
Not sure if this is something from mdadm or not...
```
2018-02-27 15:35:20 67400 +0530 - SR01 - 43095/139861965547264 - lib/decorators.py - log_message - 3918 - INFO - Ensure single CHAINED mode - ID 1519725920_iJ3HpyhYBC - New task ovs.storagerouter.configure_disk with params {'partition_guid': None, 'roles': [u'DB'], 'disk_guid': u'3f7cabc0-064a-4cc1-8784-ff00e98d13e2', 'storagerouter_guid': '5147a6c9-da91-4434-a837-0571add920b6', 'offset': 0, 'size': 1920123011072} scheduled for execution
2018-02-27 15:35:22 49800 +0530 - SR01 - 43095/139861965547264 - celery/log.py - log - 3919 - WARNING - 2018-02-27 15:35:22 49800 +0530 - SR06 - 83641/140277156394752 - extensions-generic/disk.py - create_partition - 0 - INFO - Checking partition label-type with command: parted '/dev/disk/by-id/md-uuid-b237779b:02490d4d:2e480c45:5709225c' print | grep 'Partition Table'
2018-02-27 15:35:22 63700 +0530 - SR01 - 43073/139861965547264 - celery/log.py - log - 14296 - ERROR - Task ovs.storagerouter.configure_disk[5fc128c7-65b9-46b7-a135-3f54a2c4912a] raised unexpected: ValueError('Unsupported label-type detected: loop',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 461, in new_function
    output = f(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1712, in configure_disk
    partition_size=size)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
Exception: Unsupported label-type detected: loop
```
```
root@SR06:~# ls -alh /dev/disk/by-id/md-uuid-b237779b:02490d4d:2e480c45:5709225c
lrwxrwxrwx 1 root root 9 Feb 27 15:49 /dev/disk/by-id/md-uuid-b237779b:02490d4d:2e480c45:5709225c -> ../../md5
root@SR06:~# parted '/dev/disk/by-id/md-uuid-b237779b:02490d4d:2e480c45:5709225c' print | grep 'Partition Table'
Partition Table: loop
root@SR06:~# parted -s /dev/md5 mklabel gpt
root@SR06:~# parted '/dev/disk/by-id/md-uuid-b237779b:02490d4d:2e480c45:5709225c' print | grep 'Partition Table'
Partition Table: gpt
```
raid 5 build:
```
parted -s /dev/sdc mklabel gpt; parted -s /dev/sdc mkpart member1 0% 100%
parted -s /dev/sdd mklabel gpt; parted -s /dev/sdd mkpart member2 0% 100%
parted -s /dev/sde mklabel gpt; parted -s /dev/sde mkpart member3 0% 100%
mdadm --create --verbose /dev/md5 --level=5 --raid-devices=3 /dev/sdc1 /dev/sdd1 /dev/sde1
```

md config:
```
root@SR06:~# cat /proc/mdstat 
Personalities : [raid1] [linear] [multipath] [raid0] [raid6] [raid5] [raid4] [raid10] 
md5 : active raid5 sde1[3] sdd1[1] sdc1[0]
      1875120128 blocks super 1.2 level 5, 512k chunk, algorithm 2 [3/2] [UU_]
      [===========>.........]  recovery = 55.3% (518639232/937560064) finish=33.1min speed=210295K/sec
      bitmap: 2/7 pages [8KB], 65536KB chunk
```
