### ISSUE TITLE
add_vpool times out because of due to alba.get_arakoon_config call

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#1495]
We are seeing vpool creations sporadic failing (on node 2) in the field  and during the autotests with the following error:
```
Mar 03 13:27:12 ovs-node02-1604 celery[2609]: Traceback (most recent call last):
Mar 03 13:27:12 ovs-node02-1604 celery[2609]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Mar 03 13:27:12 ovs-node02-1604 celery[2609]:     R = retval = fun(*args, **kwargs)
Mar 03 13:27:12 ovs-node02-1604 celery[2609]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Mar 03 13:27:12 ovs-node02-1604 celery[2609]:     return self.run(*args, **kwargs)
Mar 03 13:27:12 ovs-node02-1604 celery[2609]:   File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 430, in add_vpool
Mar 03 13:27:12 ovs-node02-1604 celery[2609]:     arakoon_config = StorageRouterController._retrieve_alba_arakoon_config(backend_guid=alba_backend_guid, ovs_client=ovs_client)
Mar 03 13:27:12 ovs-node02-1604 celery[2609]:   File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1498, in _retrieve_alba_arakoon_config
Mar 03 13:27:12 ovs-node02-1604 celery[2609]:     successful, arakoon_config = ovs_client.wait_for_task(task_id, timeout=300)
Mar 03 13:27:12 ovs-node02-1604 celery[2609]:   File "/opt/OpenvStorage/ovs/extensions/api/client.py", line 257, in wait_for_task
Mar 03 13:27:12 ovs-node02-1604 celery[2609]:     raise RuntimeError('Waiting for task {0} has timed out.'.format(task_id))
Mar 03 13:27:12 ovs-node02-1604 celery[2609]: RuntimeError: Waiting for task 08f3baf5-d2ac-4509-899f-da10a15bd2d3 has timed out.
```

after inspection of the logs we've seen this call being executed on node 1:
```
root@ovs-node01-1604:~# journalctl -u ovs-workers.service | grep 08f3baf5-d2ac-4509-899f-da10a15bd2d3
Mar 03 13:22:10 ovs-node01-1604 celery[15195]: 2017-03-03 13:22:10 99600 +0100 - ovs-node01-1604 - 15195/140228293342976 - celery/celery.worker.strategy - 26832 - INFO - Received task: alba.get_arakoon_config[08f3baf5-d2ac-4509-899f-da10a15bd2d3]
Mar 03 13:22:10 ovs-node01-1604 celery[15195]: 2017-03-03 13:22:10 99700 +0100 - ovs-node01-1604 - 15195/140228293342976 - celery/celery.pool - 26833 - DEBUG - TaskPool: Apply <function _fast_trace_task at 0x7f896d6160c8> (args:('alba.get_arakoon_config', '08f3baf5-d2ac-4509-899f-da10a15bd2d3', ('d300ca14-623a-4cd4-921c-f95ff135702f',), {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': ('d300ca14-623a-4cd4-921c-f95ff135702f',), 'retries': 0, u'delivery_info': {u'priority': 0, u'redelivered': False, u'routing_key': u'generic.#', u'exchange': u'generic'}, 'expires': None, u'hostname': 'celery@ovs-node01-1604', 'task': 'alba.get_arakoon_config', 'callbacks': None, u'correlation_id': u'08f3baf5-d2ac-4509-899f-da10a15bd2d3', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': u'67d2030e-7924-3fe6-b453-ed1137ddbc88', 'id': '08f3baf5-d2ac-4509-899f-da10a15bd2d3', u'headers': {}}) kwargs:{})
Mar 03 13:22:10 ovs-node01-1604 celery[15195]: 2017-03-03 13:22:10 99700 +0100 - ovs-node01-1604 - 15195/140228293342976 - celery/celery.worker.job - 26834 - DEBUG - Task accepted: alba.get_arakoon_config[08f3baf5-d2ac-4509-899f-da10a15bd2d3] pid:20279
Mar 03 13:22:11 ovs-node01-1604 celery[15195]: 2017-03-03 13:22:11 61700 +0100 - ovs-node01-1604 - 15195/140228293342976 - celery/celery.worker.job - 26835 - INFO - Task alba.get_arakoon_config[08f3baf5-d2ac-4509-899f-da10a15bd2d3] succeeded in 0.619836870988s: {'Of4MUax2NmbJfJ3Z': {'crash_log_sinks': 'console:', 'ip': '10.100.199.192', 'tlog_compression': 'snappy', 'client_port':...
```

**Comment by khenderick** [comment]
Added some more logging. Let's see if that will give some more information why an apparently normal executing/finished task was not noticed.

#1499 -> openvstorage-2.7.13-dev.1488787577.f17e206

**Comment by kvanhijf** [comment]
@kinvaris : Can you validate whether this is still an issue? And if you can find anything more using the new logs

**Comment by khenderick** [comment]
Logging in openvstorage-2.7.13.1

**Comment by JeffreyDevloo** [comment]
This happened periodically with our setup and extend/ shrink test. First results do not show this error but it only happened sometimes. When we see the same issue again, I will freeze the environment to investigate.

**Comment by wimpers** [comment]
@JeffreyDevloo , @khenderick do we want to keep this one open as I believe we haven't seen this lately right? I suggest we close it and re-open if needed.

**Comment by JeffreyDevloo** [comment]
Last incident of the same issue was yesterday. But I agree to reopen with more input.

**Comment by wimpers** [comment]
Well in that case, let's keep it open and update with the necessary info.

**Comment by JeffreyDevloo** [comment]
Hehe, the keyword was yesterday as in I lost the info :)

**Comment by JeffreyDevloo** [comment]
Happened once more:

Got these logs

```
10.100.199.213 - ovs-workers.service: 2017-03-30 22:34:02 83100 +0200 - ovs03-211 - 28679/139988494976768 - celery/celery.worker.job - 210 - INFO - Task ovs.storagerouter.ping[1220a2de-169f-4588-a448-d093077a0eb8] succeeded in 0.0971998520001s: None
10.100.199.213 - ovs-workers.service: 2017-03-30 22:34:32 13600 +0200 - ovs03-211 - 28679/139988494976768 - celery/celery.worker.strategy - 211 - INFO - Received task: ovs.storagerouter.add_vpool[be2d19f4-50aa-442f-8d1d-bd4cb72fdace]
10.100.199.213 - ovs-workers.service: 2017-03-30 22:34:32 13700 +0200 - ovs03-211 - 28679/139988494976768 - celery/celery.pool - 212 - DEBUG - TaskPool: Apply <function fasttrace_task at 0x7f51984832a8> (args:('ovs.storagerouter.add_vpool', 'be2d19f4-50aa-442f-8d1d-bd4cb72fdace', ({u'vpool_name': u'integrationtests-vpool', u'fragment_cache_on_write': False, u'storage_ip': u'10.100.199.211', u'connection_info': {u'client_secret': u"m|tvy!vH?YOyNQ?,MopUN;]uaNJ|j'?5H[Q4h5[ozq0{6gWLLquKwHd51go8Gg>h{5/wjLST+G.3XW}FAH@7ue1w3C/@:m0/dKyQ7:uKkyON5+A1mDGJ<T2VWb,@U1zI", u'host': u'10.100.199.211', 'local': True, u'port': 443, u'client_id': '452139c6-ad52-43c4-a5e2-6956e62b1b45'}, u'backend_info': {u'alba_backend_guid': u'298d4fbf-204f-4036-a6a5-064aa55b31ff', u'preset': u'ciaddremovevpool'}, u'storagerouter_ip': u'10.100.199.211', u'connection_info_aa': {u'client_secret': u"m|tvy!vH?YOyNQ?,MopUN;]uaNJ|j'?5H[Q4h5[ozq0{6gWLLquKwHd51go8Gg>h{5/wjLST+G.3XW}FAH@7ue1w3C/@:m0/dKyQ7:uKkyON5+A1mDGJ<T2VWb,@U1zI", u'host': u'10.100.199.211', 'local': True, u'port': 443, u'client_id': '452139c6-ad52-43c4-a5e2-6956e62b1b45'}, u'writecache_size': 2, u'backend_info_aa': {u'alba_backend_guid': u'60d1a15a-0cf8-4a48-9675-c5be175ab208',... kwargs:{})
10.100.199.213 - ovs-workers.service: 2017-03-30 22:34:32 14100 +0200 - ovs03-211 - 28679/139988494976768 - celery/celery.worker.job - 213 - DEBUG - Task accepted: ovs.storagerouter.add_vpool[be2d19f4-50aa-442f-8d1d-bd4cb72fdace] pid:28691
10.100.199.213 - ovs-workers.service: 2017-03-30 22:34:32 79300 +0200 - ovs03-211 - 28679/139988494976768 - celery/celery.worker.job - 214 - ERROR - Task ovs.storagerouter.add_vpool[be2d19f4-50aa-442f-8d1d-bd4cb72fdace] raised unexpected: ValueError('VPool should be in RUNNING status',)
10.100.199.213 - ovs-workers.service: Traceback (most recent call last):
10.100.199.213 - ovs-workers.service: File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
10.100.199.213 - ovs-workers.service: R = retval = fun(*args, **kwargs)
10.100.199.213 - ovs-workers.service: File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protectedcall__ 10.100.199.213 - ovs-workers.service: return self.run(*args, **kwargs) 10.100.199.213 - ovs-workers.service: File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 225, in addvpool
10.100.199.213 - ovs-workers.service: raise ValueError('VPool should be in {0} status'.format(VPool.STATUSES.RUNNING))
10.100.199.213 - ovs-workers.service: ValueError: VPool should be in RUNNING status
```

**Comment by JeffreyDevloo** [comment]
Closing as it was a fault on our end and we made wrong assumption.

**Comment by khenderick** [comment]
Opening up again, as this issue isn't resolved yet.

**Comment by khenderick** [comment]
From @wimpers 
> @JeffreyDevloo , @khenderick do we want to keep this one open as I believe we haven't seen this lately right? I suggest we close it and re-open if needed.

Sorry, closing again.
