### ISSUE TITLE
XMLRPC timeout when creating clone from template

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1513]
GIG was complaining about an XMLRPC timeout on create_clone_from_template. This was due to some network issues and the fact that the tlogs had to be fetched from the hdd backend instead of the cache backend which was unreachable (network issue). 

But what we did see was that the code from the create_clone and create_clone_from_template is different in a way that there is no timeout on create_clone but there is in create_clone_from_template. 

_Code for create_clone_from_template:_
```
volume_id = vdisk.storagedriver_client.create_clone_from_template(target_path=devicename,
                                                                metadata_backend_config=MDSMetaDataBackendConfig([backend_config]),
                                                                parent_volume_id=str(vdisk.volume_id),
                                                                node_id=str(storagedriver.storagedriver_id),
                                                                req_timeout_secs=30)
```

_Code for create_clone:_
```
volume_id = vdisk.storagedriver_client.create_clone(target_path=devicename,
                                                    metadata_backend_config=backend_config,
                                                    parent_volume_id=str(vdisk.volume_id),
                                                    parent_snapshot_id=str(snapshot_id),
                                                    node_id=str(storagedriver.storagedriver_id))
```

If you have an old volume, possibly not scrubbed, with a lot of data / overwrites, or even just many empty tlogs, then fetching all of these can take long.

**Comment by kvanhijf** [comment]
@openvstorage/qa : Timeout has been removed for create_clone_from_template

https://github.com/openvstorage/framework/pull/1544 --> openvstorage-2.8.0-dev.1490089007.e2e4906

**Comment by matthiasdeblock** [comment]
Create_new is also suffering on this:
```
            volume_id = vpool.storagedriver_client.create_volume(target_path=devicename,
                                                                 metadata_backend_config=backend_config,
                                                                 volume_size="{0}B".format(volume_size),
                                                                 node_id=str(storagedriver.storagedriver_id),
                                                                 req_timeout_secs=30)
```

**Comment by jeroenmaelbrancke** [comment]
ovs-workers:
```
March 24th 2017, 21:33:51.136	ovs05	ovs-workers.service	lib/vdisk	ERROR	Creating new vDisk TMPL-CentOS-6-8-flat_337cc4fe-bc77-45a2-a223-3d3c2779d85b failed: failed to send XMLRPC request volumeCreate
March 24th 2017, 21:33:51.187	ovs05	ovs-workers.service	celery/celery.worker.job	ERROR	Task ovs.vdisk.create_new[344ddf95-d90f-48d2-8c1d-97ef92bde984] raised unexpected: RuntimeError('failed to send XMLRPC request volumeCreate',)
March 24th 2017, 21:33:51.187	ovs05	ovs-workers.service	 - 	 - 	Traceback (most recent call last):
March 24th 2017, 21:33:51.187	ovs05	ovs-workers.service	 - 	 - 	    R = retval = fun(*args, **kwargs)
March 24th 2017, 21:33:51.187	ovs05	ovs-workers.service	 - 	 - 	  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
March 24th 2017, 21:33:51.187	ovs05	ovs-workers.service	 - 	 - 	    return self.run(*args, **kwargs)
March 24th 2017, 21:33:51.187	ovs05	ovs-workers.service	 - 	 - 	  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
March 24th 2017, 21:33:51.188	ovs05	ovs-workers.service	 - 	 - 	  File "/opt/OpenvStorage/ovs/lib/vdisk.py", line 645, in create_new
March 24th 2017, 21:33:51.188	ovs05	ovs-workers.service	 - 	 - 	    req_timeout_secs=30)
March 24th 2017, 21:33:51.188	ovs05	ovs-workers.service	 - 	 - 	RuntimeError: failed to send XMLRPC request volumeCreate
```

volumedriver logging:
```
March 24th 2017, 21:32:51.168	ovs03	ovs-volumedriver_vpool01.service	volumedriverfs/VolManager	NOTICE	New Volume, VolumeId: e2c419fc-5846-4905-9682-7fd7fd3b37fb, Namespace: e2c419fc-5846-4905-9682-7fd7fd3b37fb, Size: 0, CreateNamespace: CreateNamespace::T, START
March 24th 2017, 21:32:51.239	ovs03	ovs-volumedriver_vpool01.service	volumedriverfs/BackendConnectionInterfaceLogger	INFO	~Logger: Exiting namespaceExists for e2c419fc-5846-4905-9682-7fd7fd3b37fb
March 24th 2017, 21:32:51.240	ovs03	ovs-volumedriver_vpool01.service	volumedriverfs/BackendConnectionInterfaceLogger	INFO	Logger: Entering createNamespace e2c419fc-5846-4905-9682-7fd7fd3b37fb
March 24th 2017, 21:32:54.339	ovs03	ovs-volumedriver_vpool01.service	volumedriverfs/BackendConnectionInterfaceLogger	INFO	~Logger: Exiting createNamespace for e2c419fc-5846-4905-9682-7fd7fd3b37fb
March 24th 2017, 21:33:26.704	ovs03	ovs-volumedriver_vpool01.service	volumedriverfs/PeriodicActionPoolTask	INFO	operator(): mds-poll-namespace-e2c419fc-5846-4905-9682-7fd7fd3b37fb: timer cancelled
March 24th 2017, 21:33:26.705	ovs03	ovs-volumedriver_vpool01.service	volumedriverfs/PeriodicActionPoolTask	INFO	operator(): mds-poll-namespace-e2c419fc-5846-4905-9682-7fd7fd3b37fb: bailing out
March 24th 2017, 21:33:26.706	ovs03	ovs-volumedriver_vpool01.service	volumedriverfs/VolumeFactory	WARNING	make_metadata_store: e2c419fc-5846-4905-9682-7fd7fd3b37fb: no scrub ID present in MetaDataStore - did we crash before writing it out?
March 24th 2017, 21:33:31.561	ovs03	ovs-volumedriver_vpool01.service	volumedriverfs/VolManager	NOTICE	New Volume, VolumeId: e2c419fc-5846-4905-9682-7fd7fd3b37fb, Namespace: e2c419fc-5846-4905-9682-7fd7fd3b37fb, Size: 0, CreateNamespace: CreateNamespace::T, FINISHED
```

**Comment by kvanhijf** [comment]
An older comment of @openvstorage/operations was: 

> If you have an old volume, possibly not scrubbed, with a lot of data / overwrites, or even just many empty tlogs, then fetching all of these can take long.

But this can't be the case for `create_volume` right? So i'd assume the reason for the timeout being reached is something else?

**Comment by khenderick** [comment]
@matthiasdeblock, @jeroenmaelbrancke, if this is an issue and you want it to be fixed, better create a new ticket as this one is already completed. Just adding comments about possible other issues on an already implemented ticket can cause confusion.

**Comment by khenderick** [comment]
openvstorage-2.8.0
