### ISSUE TITLE
KeyError operation when running vpool.statistics

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1531]
When running vpool.statistics with the famous statsmonkey i received the following error.
This is on the OVH env with following patch #1486

```
Mar 16 15:42:02 ovs01 celery[7610]: 2017-03-16 15:42:02 44000 +0100 - ovs01 - 182900/140633259894528 - lib/statsmonkey - 961 - ERROR - Exception in get_vpool_stats. Check ovs-worker for stacktrace.
Mar 16 15:42:02 ovs01 celery[7610]: Traceback (most recent call last):
Mar 16 15:42:02 ovs01 celery[7610]:   File "/opt/OpenvStorage/ovs/lib/statsmonkey.py", line 605, in get_vpool_stats
Mar 16 15:42:02 ovs01 celery[7610]:     StatsmonkeyController.get_key_values(vpool.statistics))
Mar 16 15:42:02 ovs01 celery[7610]:   File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 344, in <lambda>
Mar 16 15:42:02 ovs01 celery[7610]:     fget = lambda s: s._get_dynamic_property(dynamic)
Mar 16 15:42:02 ovs01 celery[7610]:   File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 413, in _get_dynamic_property
Mar 16 15:42:02 ovs01 celery[7610]:     return self._backend_property(data_loader, dynamic)
Mar 16 15:42:02 ovs01 celery[7610]:   File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 1001, in _backend_property
Mar 16 15:42:02 ovs01 celery[7610]:     dynamic_data = function(dynamic=dynamic)  # Load data from backend
Mar 16 15:42:02 ovs01 celery[7610]:   File "/opt/OpenvStorage/ovs/dal/hybrids/vpool.py", line 145, in _statistics
Mar 16 15:42:02 ovs01 celery[7610]:     VDisk.calculate_delta(self._key, dynamic, statistics)
Mar 16 15:42:02 ovs01 celery[7610]:   File "/opt/OpenvStorage/ovs/dal/hybrids/vdisk.py", line 346, in calculate_delta
Mar 16 15:42:02 ovs01 celery[7610]:     current_stats['{0}_ps'.format(key)] = max(0, (current_stats[key] - previous_stats[key]) / delta)
Mar 16 15:42:02 ovs01 celery[7610]: KeyError: 'operations'
```

On the Webapp-api service i saw the same error:

```
Mar 16 15:42:01 ovs01 gunicorn[7544]: 2017-03-16 15:42:01 86000 +0100 - ovs01 - 7982/140613044734384 - api/middleware - 2594 - ERROR - An unhandled exception occurred: 'operations'
Mar 16 15:42:01 ovs01 gunicorn[7544]: Traceback (most recent call last):
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
Mar 16 15:42:01 ovs01 gunicorn[7544]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/usr/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 78, in view
Mar 16 15:42:01 ovs01 gunicorn[7544]:     return self.dispatch(request, *args, **kwargs)
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/usr/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
Mar 16 15:42:01 ovs01 gunicorn[7544]:     return view_func(*args, **kwargs)
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 399, in dispatch
Mar 16 15:42:01 ovs01 gunicorn[7544]:     response = self.handle_exception(exc)
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 396, in dispatch
Mar 16 15:42:01 ovs01 gunicorn[7544]:     response = handler(request, *args, **kwargs)
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 519, in new_function
Mar 16 15:42:01 ovs01 gunicorn[7544]:     return_value = f(*args, **kwargs)
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 84, in new_function
Mar 16 15:42:01 ovs01 gunicorn[7544]:     return f(*args, **kw)
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 312, in new_function
Mar 16 15:42:01 ovs01 gunicorn[7544]:     data = FullSerializer(object_type, contents=contents, instance=data_list, many=True).data
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/usr/lib/python2.7/dist-packages/rest_framework/serializers.py", line 571, in data
Mar 16 15:42:01 ovs01 gunicorn[7544]:     self._data = [self.to_native(item) for item in obj]
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/usr/lib/python2.7/dist-packages/rest_framework/serializers.py", line 349, in to_native
Mar 16 15:42:01 ovs01 gunicorn[7544]:     value = field.field_to_native(obj, field_name)
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/usr/lib/python2.7/dist-packages/rest_framework/fields.py", line 198, in field_to_native
Mar 16 15:42:01 ovs01 gunicorn[7544]:     value = get_component(value, component)
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/usr/lib/python2.7/dist-packages/rest_framework/fields.py", line 56, in get_component
Mar 16 15:42:01 ovs01 gunicorn[7544]:     val = getattr(obj, attr_name)
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 344, in <lambda>
Mar 16 15:42:01 ovs01 gunicorn[7544]:     fget = lambda s: s._get_dynamic_property(dynamic)
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 413, in _get_dynamic_property
Mar 16 15:42:01 ovs01 gunicorn[7544]:     return self._backend_property(data_loader, dynamic)
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 1001, in _backend_property
Mar 16 15:42:01 ovs01 gunicorn[7544]:     dynamic_data = function(dynamic=dynamic)  # Load data from backend
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/opt/OpenvStorage/ovs/dal/hybrids/vpool.py", line 145, in _statistics
Mar 16 15:42:01 ovs01 gunicorn[7544]:     VDisk.calculate_delta(self._key, dynamic, statistics)
Mar 16 15:42:01 ovs01 gunicorn[7544]:   File "/opt/OpenvStorage/ovs/dal/hybrids/vdisk.py", line 346, in calculate_delta
Mar 16 15:42:01 ovs01 gunicorn[7544]:     current_stats['{0}_ps'.format(key)] = max(0, (current_stats[key] - previous_stats[key]) / delta)
Mar 16 15:42:01 ovs01 gunicorn[7544]: KeyError: 'operations'
```

**Comment by kvanhijf** [comment]
@openvstorage/qa : 
Creating a vPool using the GUI and keeping the developer tools console open always showed this KeyError, so this should no longer show any issues

https://github.com/openvstorage/framework/pull/1546 --> openvstorage-2.8.0-dev.1490103650.b2ff39b

**Comment by khenderick** [comment]
openvstorage-2.8.0
