### ISSUE TITLE
storagrouter is not part of vpool error

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1533]
On OVH we received this error for the last 3 vpool installation.

packages (some scripts are manually patched:
```
^Croot@ovs05:~# dpkg -l | grep openvstorage
ii  openvstorage                         2.7.10.1-1                      amd64        openvStorage
ii  openvstorage-backend                 1.7.10.1-1                      amd64        openvStorage Backend plugin
ii  openvstorage-backend-core            1.7.10.1-1                      amd64        openvStorage Backend plugin core
ii  openvstorage-backend-webapps         1.7.10.1-1                      amd64        openvStorage Backend plugin Web Applications
ii  openvstorage-core                    2.7.10.1-1                      amd64        openvStorage core
ii  openvstorage-hc                      1.7.10.1-1                      amd64        openvStorage Backend plugin HyperConverged
ii  openvstorage-health-check            3.2.1-rev.508.11ecdd9-1         amd64        Open vStorage HealthCheck
ii  openvstorage-sdm                     1.6.10.1-1                      amd64        Open vStorage Backend ASD Manager
ii  openvstorage-webapps                 2.7.10.1-1                      amd64        openvStorage Web Applications
```

ovs worker error:
```
March 18th 2017, 11:52:18.289	ovs03	ovs-workers.service	celery/celery.worker.job	ERROR	Task ovs.storagerouter.add_vpool[c3708db7-437f-44f0-8722-3325c795c40f] raised unexpected: ValueError('StorageRouter ovs05 is not part of vPool nvmeonly',)
March 18th 2017, 11:52:18.290	ovs03	ovs-workers.service	 - 	 - 	Traceback (most recent call last):
March 18th 2017, 11:52:18.290	ovs03	ovs-workers.service	 - 	 - 	  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 787, in add_vpool
March 18th 2017, 11:52:18.290	ovs03	ovs-workers.service	 - 	 - 	    fresh_only=True)
March 18th 2017, 11:52:18.290	ovs03	ovs-workers.service	 - 	 - 	  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
March 18th 2017, 11:52:18.290	ovs03	ovs-workers.service	 - 	 - 	    R = retval = fun(*args, **kwargs)
March 18th 2017, 11:52:18.290	ovs03	ovs-workers.service	 - 	 - 	  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
March 18th 2017, 11:52:18.290	ovs03	ovs-workers.service	 - 	 - 	    return self.run(*args, **kwargs)
March 18th 2017, 11:52:18.291	ovs03	ovs-workers.service	 - 	 - 	    raise ValueError('StorageRouter {0} is not part of vPool {1}'.format(storagerouter.name, vpool.name))
March 18th 2017, 11:52:18.291	ovs03	ovs-workers.service	 - 	 - 	  File "/opt/OpenvStorage/ovs/lib/mdsservice.py", line 87, in prepare_mds_service
March 18th 2017, 11:52:18.291	ovs03	ovs-workers.service	 - 	 - 	ValueError: StorageRouter ovs05 is not part of vPool nvmeonly
```

**Comment by wimpers** [comment]
fixed in 2.7.13-ish
