### ISSUE TITLE
Attribute error of paramiko after ovs setup

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1536]
### Problem description
After the setup had been fully completed on my last node of the 3 node setup, I got the following exception:
```
Found exactly one choice: 10.100.69.122
Select the port to be used for the API [8500]:
Select an IP address to be used for the ASDs or 'All' (All current and future interfaces: 0.0.0.0). Make a selection please:
    1: 10.100.69.122
    2: All
  Select Nr:  [2]:
Select the port to be used for the ASDs [8600]:
- Starting watcher service
+++++++++++++++++++++++++++++++++++++
+++  ASD Manager setup completed  +++
+++++++++++++++++++++++++++++++++++++
Exception in thread Thread-27 (most likely raised during interpreter shutdown):Exception in thread Thread-23 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1777, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
Exception in thread Thread-37 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
 
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1777, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error
```
Other than that I have no idea why it went wrong. I've done the setup many times over and over using my VMs snapshots and it is the first time I have seen it.

The install was complete, asd manager aswell. 
The error just seems to scare me as it had no impact.

### Packages
```
ii  openvstorage                         2.7.13.2-1                      amd64        openvStorage
ii  openvstorage-backend                 1.7.13.1-1                      amd64        openvStorage Backend plugin
ii  openvstorage-backend-core            1.7.13.1-1                      amd64        openvStorage Backend plugin core
ii  openvstorage-backend-webapps         1.7.13.1-1                      amd64        openvStorage Backend plugin Web Applications
ii  openvstorage-core                    2.7.13.2-1                      amd64        openvStorage core
ii  openvstorage-hc                      1.7.13.1-1                      amd64        openvStorage Backend plugin HyperConverged
ii  openvstorage-sdm                     1.6.13.1-1                      amd64        Open vStorage Backend ASD Manager
ii  openvstorage-webapps                 2.7.13.2-1                      amd64        openvStorage Web Applications

```

**Comment by kvanhijf** [comment]
https://github.com/paramiko/paramiko/issues/17
On the 8th of May 2015 @Kenneth replied to above issue and apparently its still not fixed.

**Comment by kvanhijf** [comment]
Putting this in state question for now, so its no longer in our 'Open issues', because we're depending on a fix in paramiko

**Comment by JeffreyDevloo** [comment]
This no longer occurs.
