### ISSUE TITLE
vPool in installing state when unable to find requested nr of free ports

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1553]
When installing a vPool and there are no free ports the vPool is still in installing status.
Can you please check this before installing the vPool and return an error to the gui with the issue?

```
Mar 23 12:12:23 ovs05 celery[39598]: 2017-03-23 12:12:23 27600 +0100 - ovs05 - 39598/139836606109440 - celery/celery.worker.job - 13983 - ERROR - Task ovs.storagerouter.add_vpool[74e63d35-340a-4190-99cd-b23a66ea9d72] raised unexpected: ValueError('Unable to find requested nr of free ports',)
Mar 23 12:12:23 ovs05 celery[39598]: Traceback (most recent call last):
Mar 23 12:12:23 ovs05 celery[39598]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Mar 23 12:12:23 ovs05 celery[39598]:     R = retval = fun(*args, **kwargs)
Mar 23 12:12:23 ovs05 celery[39598]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Mar 23 12:12:23 ovs05 celery[39598]:     return self.run(*args, **kwargs)
Mar 23 12:12:23 ovs05 celery[39598]:   File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 499, in add_vpool
Mar 23 12:12:23 ovs05 celery[39598]:     ports = StorageRouterController._get_free_ports(client, model_ports_in_use, 4)
Mar 23 12:12:23 ovs05 celery[39598]:   File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1441, in _get_free_ports
Mar 23 12:12:23 ovs05 celery[39598]:     ports = System.get_free_ports(port_range, ports_in_use, number, client)
Mar 23 12:12:23 ovs05 celery[39598]:   File "/opt/OpenvStorage/ovs/extensions/generic/system.py", line 171, in get_free_ports
Mar 23 12:12:23 ovs05 celery[39598]:     raise ValueError('Unable to find requested nr of free ports')
Mar 23 12:12:23 ovs05 celery[39598]: ValueError: Unable to find requested nr of free ports
```

**Comment by jeroenmaelbrancke** [comment]
Check also the free ports for the proxies before creating the vpool.
https://github.com/openvstorage/framework/blob/2.7.10.1/ovs/lib/storagerouter.py#L623

Maybe you can lock the ports when you install the vpool to prevent other processes taking the ports.
