### ISSUE TITLE
XMLRPC timeout when creating new volume

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1557]
Same issue as #1513 but now for creating a new volume.

Code:
```
            volume_id = vpool.storagedriver_client.create_volume(target_path=devicename,
                                                                 metadata_backend_config=backend_config,
                                                                 volume_size="{0}B".format(volume_size),
                                                                 node_id=str(storagedriver.storagedriver_id),
                                                                 req_timeout_secs=30)
```

ovs-workers logging:
```
March 24th 2017, 21:33:51.136	ovs05	ovs-workers.service	lib/vdisk	ERROR	Creating new vDisk TMPL-CentOS-6-8-flat_337cc4fe-bc77-45a2-a223-3d3c2779d85b failed: failed to send XMLRPC request volumeCreate
March 24th 2017, 21:33:51.187	ovs05	ovs-workers.service	celery/celery.worker.job	ERROR	Task ovs.vdisk.create_new[344ddf95-d90f-48d2-8c1d-97ef92bde984] raised unexpected: RuntimeError('failed to send XMLRPC request volumeCreate',)
March 24th 2017, 21:33:51.187	ovs05	ovs-workers.service	 - 	 - 	Traceback (most recent call last):
March 24th 2017, 21:33:51.187	ovs05	ovs-workers.service	 - 	 - 	    R = retval = fun(*args, **kwargs)
March 24th 2017, 21:33:51.187	ovs05	ovs-workers.service	 - 	 - 	  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
March 24th 2017, 21:33:51.187	ovs05	ovs-workers.service	 - 	 - 	    return self.run(*args, **kwargs)
March 24th 2017, 21:33:51.187	ovs05	ovs-workers.service	 - 	 - 	  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
March 24th 2017, 21:33:51.188	ovs05	ovs-workers.service	 - 	 - 	  File "/opt/OpenvStorage/ovs/lib/vdisk.py", line 645, in create_new
March 24th 2017, 21:33:51.188	ovs05	ovs-workers.service	 - 	 - 	    req_timeout_secs=30)
March 24th 2017, 21:33:51.188	ovs05	ovs-workers.service	 - 	 - 	RuntimeError: failed to send XMLRPC request volumeCreate
```

volumedriver logging:
```
March 24th 2017, 21:32:51.168	ovs03	ovs-volumedriver_vpool01.service	volumedriverfs/VolManager	NOTICE	New Volume, VolumeId: e2c419fc-5846-4905-9682-7fd7fd3b37fb, Namespace: e2c419fc-5846-4905-9682-7fd7fd3b37fb, Size: 0, CreateNamespace: CreateNamespace::T, START
March 24th 2017, 21:32:51.239	ovs03	ovs-volumedriver_vpool01.service	volumedriverfs/BackendConnectionInterfaceLogger	INFO	~Logger: Exiting namespaceExists for e2c419fc-5846-4905-9682-7fd7fd3b37fb
March 24th 2017, 21:32:51.240	ovs03	ovs-volumedriver_vpool01.service	volumedriverfs/BackendConnectionInterfaceLogger	INFO	Logger: Entering createNamespace e2c419fc-5846-4905-9682-7fd7fd3b37fb
March 24th 2017, 21:32:54.339	ovs03	ovs-volumedriver_vpool01.service	volumedriverfs/BackendConnectionInterfaceLogger	INFO	~Logger: Exiting createNamespace for e2c419fc-5846-4905-9682-7fd7fd3b37fb
March 24th 2017, 21:33:26.704	ovs03	ovs-volumedriver_vpool01.service	volumedriverfs/PeriodicActionPoolTask	INFO	operator(): mds-poll-namespace-e2c419fc-5846-4905-9682-7fd7fd3b37fb: timer cancelled
March 24th 2017, 21:33:26.705	ovs03	ovs-volumedriver_vpool01.service	volumedriverfs/PeriodicActionPoolTask	INFO	operator(): mds-poll-namespace-e2c419fc-5846-4905-9682-7fd7fd3b37fb: bailing out
March 24th 2017, 21:33:26.706	ovs03	ovs-volumedriver_vpool01.service	volumedriverfs/VolumeFactory	WARNING	make_metadata_store: e2c419fc-5846-4905-9682-7fd7fd3b37fb: no scrub ID present in MetaDataStore - did we crash before writing it out?
March 24th 2017, 21:33:31.561	ovs03	ovs-volumedriver_vpool01.service	volumedriverfs/VolManager	NOTICE	New Volume, VolumeId: e2c419fc-5846-4905-9682-7fd7fd3b37fb, Namespace: e2c419fc-5846-4905-9682-7fd7fd3b37fb, Size: 0, CreateNamespace: CreateNamespace::T, FINISHED
```

**Comment by redlicha** [comment]
VolumeDriver issue: cancellation of the MDS slave (started on volume creation) as part of promoting it to master takes long: https://github.com/openvstorage/volumedriver/issues/298

**Comment by wimpers** [comment]
Still to be discussed in BAM if anything on the framework needs top happen.

**Comment by kvanhijf** [comment]
Putting in state question for reason @wimpers said

**Comment by wimpers** [comment]
Back to BAM.

**Comment by wimpers** [comment]
Nothing to do.
