### ISSUE TITLE
Unable to create a backend with external arakoons

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1612]
I tried to created a Backend with external Arakoons and registered the nsms already on the ABM.
Before we create a backend, all the Arakoons were installed on the env.

Error ovs-workers:
```
Apr 26 11:05:07 ovs-node03-1604 celery[16898]: 2017-04-26 11:05:07 16600 +0200 - ovs-node03-1604 - 17021/139806334920448 - lib/alba - 15 - INFO - Model service: arakoon-hddbackend-abm
Apr 26 11:05:07 ovs-node03-1604 celery[16898]: 2017-04-26 11:05:07 21900 +0200 - ovs-node03-1604 - 17021/139806334920448 - lib/alba - 16 - INFO - Creating Arakoon cluster: hddbackend-nsm_0
Apr 26 11:05:07 ovs-node03-1604 celery[16898]: 2017-04-26 11:05:07 23800 +0200 - ovs-node03-1604 - 17021/139806334920448 - lib/ensure single - 17 - INFO - Ensure single DEFAULT mode - ID 1493197503_DmwTLvDVhS - Deleting key ovs_ensure_single_alba.manual_alba_arakoon_checkup
Apr 26 11:05:07 ovs-node03-1604 celery[16898]: 2017-04-26 11:05:07 24100 +0200 - ovs-node03-1604 - 17021/139806334920448 - lib/alba - 18 - ERROR - Failed manual Alba Arakoon checkup during add cluster for Backend 5d9ed39c-cbbf-49b6-ad05-1c5f8a193a11. An Arakoon cluster with name "hddbackend-nsm_0" already exists
Apr 26 11:05:07 ovs-node03-1604 celery[16898]: Traceback (most recent call last):
Apr 26 11:05:07 ovs-node03-1604 celery[16898]:   File "/opt/OpenvStorage/ovs/lib/alba.py", line 196, in add_cluster
Apr 26 11:05:07 ovs-node03-1604 celery[16898]:     nsm_clusters=nsm_clusters) is True:
Apr 26 11:05:07 ovs-node03-1604 celery[16898]:   File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
Apr 26 11:05:07 ovs-node03-1604 celery[16898]:     return self._get_current_object()(*a, **kw)
Apr 26 11:05:07 ovs-node03-1604 celery[16898]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
Apr 26 11:05:07 ovs-node03-1604 celery[16898]:     return orig(self, *args, **kwargs)
Apr 26 11:05:07 ovs-node03-1604 celery[16898]:   File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
Apr 26 11:05:07 ovs-node03-1604 celery[16898]:     return self.run(*args, **kwargs)
Apr 26 11:05:07 ovs-node03-1604 celery[16898]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 239, in new_function
Apr 26 11:05:07 ovs-node03-1604 celery[16898]:     output = function(*args, **kwargs)
Apr 26 11:05:07 ovs-node03-1604 celery[16898]:   File "/opt/OpenvStorage/ovs/lib/alba.py", line 414, in manual_alba_arakoon_checkup
Apr 26 11:05:07 ovs-node03-1604 celery[16898]:     nsm_clusters=nsm_clusters)
Apr 26 11:05:07 ovs-node03-1604 celery[16898]:   File "/opt/OpenvStorage/ovs/lib/alba.py", line 521, in _alba_arakoon_checkup
Apr 26 11:05:07 ovs-node03-1604 celery[16898]:     plugins={AlbaController.NSM_PLUGIN: AlbaController.ALBA_VERSION_GET})
Apr 26 11:05:07 ovs-node03-1604 celery[16898]:   File "/opt/OpenvStorage/ovs/extensions/db/arakoon/ArakoonInstaller.py", line 344, in create_cluster
Apr 26 11:05:07 ovs-node03-1604 celery[16898]:     raise ValueError('An Arakoon cluster with name "{0}" already exists'.format(cluster_name))
Apr 26 11:05:07 ovs-node03-1604 celery[16898]: ValueError: An Arakoon cluster with name "hddbackend-nsm_0" already exists
```

example output:
```
In [2]: from ovs.extensions.generic.configuration import ConfigurationIn [3]: Configuration.dir_exists('/ovs/arakoon/hddbackend-nsm_01')
Out[3]: True
In [4]: Configuration.dir_exists('/ovs/arakoon/hddbackend-nsm_0')
Out[4]: True
In [5]: Configuration.dir_exists('/ovs/arakoon/hddbackend-nsm_')
Out[5]: True
```

**Comment by kvanhijf** [comment]
As witnessed in the example output above, the problem exists in the fact that no backends can be created with a name shorter than any other already existing backend

Eg: Create backend 'backend1'
It will be impossible to create a backend with name 'backend' for example

**Comment by kvanhijf** [comment]
@openvstorage/qa : Execute code from 'example output' above to verify

https://github.com/openvstorage/framework/pull/1614 --> openvstorage-2.9.1-dev.1493276801.219a741
https://github.com/openvstorage/alba-asdmanager/pull/247 --> openvstorage-sdm-1.9.0-dev.1493276594.c2db63f
