### ISSUE TITLE
ovs remove nodes doesn't work

### ISSUE THREAD

**Issue by khenderick** [openvstorage/framework#1657]
ovs remove nodes doesn't work. It turns out the config arakoon is in a state where the clients can't find the master anymore they need to finish up the shrink sequence.

**Comment by khenderick** [comment]
```
2017-06-06 10:28:14 64500 +0200 - kh002 - 23911/140333992249088 - lib/node-type - 188 - ERROR - 
Failed to leave configuration cluster
Traceback (most recent call last):
  File "ovs/lib/nodetype.py", line 395, in demote_node
    offline_nodes=offline_node_ips)
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/arakooninstaller.py", line 600, in shrink_cluster
    service_name=self.get_service_name_for_cluster(cluster_name=self.cluster_name))
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/services/interfaces/systemd.py", line 428, in unregister_service
    self._configuration.delete(key=self.service_config_key.format(node_name, ExtensionsToolbox.remove_prefix(service_name, 'ovs-')))
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/generic/configuration.py", line 159, in delete
    cls._delete(key_entries[0], recursive=True)
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/generic/configuration.py", line 272, in _delete
    key=key, recursive=recursive)
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/generic/configuration.py", line 330, in _passthroFailed to update configurations
ERROR: Could not determine the Arakoon master node
```

**Comment by JeffreyDevloo** [comment]
Does not work when downscaling from 2 to 1 master node

Following configurations do work however:
4 -> 3
3 -> 2

**Comment by wimpers** [comment]
@saelbrec is this  a use case we want to support, shrink from 2 to 1? I tend to say to not fix this one.
