### ISSUE TITLE
Error while removing asd from already physically removed disk

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1693]
Got the following stacktrace after removing the asd. The disk got replaced before it was removed from the GUI.

```
2017-06-30 08:11:35 41400 -0400 - NY1SRV0019 - 24198/140118751631104 - celery/celery.worker.job - 570617 - ERROR - Task albanode.reset_asd[5daf5393-8b32-4b29-88a2-aeaed37c1e97] raised unexpected: RuntimeError(u'Disk with alias scsi-35000cca25d1a29d4 not available',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albanode.py", line 374, in reset_asd
    result = node.client.add_asd(disk_id=disk_aliases[0].split('/')[-1])
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 206, in add_asd
    return self._call(requests.post, 'disks/{0}/asds'.format(disk_id), timeout=30)
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 107, in _call
    raise RuntimeError(error_message)
RuntimeError: Disk with alias scsi-35000cca25d1a29d4 not available
```

**Comment by wimpers** [comment]
Duplicates https://github.com/openvstorage/framework/issues/1694

**Comment by JeffreyDevloo** [comment]
Not a duplicate. This ticket handles about the asds not the disks 
The error raised is the same, code path is slightly different

**Comment by JeffreyDevloo** [comment]
This issue was moved to openvstorage/alba-asdmanager#300

**Comment by JeffreyDevloo** [comment]
This issue was moved to openvstorage/framework-alba-plugin#522
