### ISSUE TITLE
Error while removing disk from already physically removed disk

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1694]
Got the following stacktrace after removing the disk. The disk got replaced before it was removed from the GUI.

```
2017-06-30 08:25:16 72500 -0400 - NY1SRV0019 - 24198/140118751631104 - celery/celery.worker.job - 570987 - ERROR - Task albanode.remove_disk[51baaab0-adc3-4504-86f0-e4b1a6303ea2] raised unexpected: RuntimeError(u'Disk with alias scsi-35000cca25d1a29d4 not available',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 460, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albanode.py", line 209, in remove_disk
    asds_in_use = node.client.get_claimed_asds(disk_id=device_id)
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 194, in get_claimed_asds
    asd_info = self._call(requests.get, 'disks/{0}/get_claimed_asds'.format(disk_id), clean=True, timeout=60)
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 107, in _call
    raise RuntimeError(error_message)
RuntimeError: Disk with alias scsi-35000cca25d1a29d4 not available
```

**Comment by JeffreyDevloo** [comment]
This issue was moved to openvstorage/alba-asdmanager#301

**Comment by JeffreyDevloo** [comment]
This issue was moved to openvstorage/framework-alba-plugin#521
