### ISSUE TITLE
Scrubbing fails with RuntimeError: scrubber returned with nonzero exit status 256

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#1697]
Branch: develop
Env: 10.100.199.191-194
Testrun: http://testrail.openvstorage.com/index.php?/plans/view/38040
Failed test(s):
- check_scrubbing_test
- mds_regression

Scenario:
- create at least 1 vdisk
- run:
```


```

Stacktrace:
```
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/generic.py", line 353, in _execute_scrub
    backend_config=Configuration.get_configuration_path(backend_config_key))
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
RuntimeError: scrubber returned with nonzero exit status 256
```

Scrubber.log:
```
2017-07-04 09:21:20 985568 +0200 - ovs-node01-1604 - 5148/0x00007f7fc6246900 - scrubber/ovs_scrubber - 0000000000000000 - notice - print_version_data: version: ee-6.15.2
version revision: b64518d5772ce03d2c9a6b1144112812ff77f8eb
repository URL: git@github.com:openvstorage/volumedriver-ee.git
branch: master
md5 support: no
revision: 93ed213d19390f4d21bcd220c6a9d1732d795dd5
build time: Mon May 22 09:32:15 UTC 2017

2017-07-04 09:21:20 985789 +0200 - ovs-node01-1604 - 5148/0x00007f7fc6246900 - scrubber/ovs_scrubber - 0000000000000001 - notice - print_version_data: Command Line Options
2017-07-04 09:21:20 987255 +0200 - ovs-node01-1604 - 5148/0x00007f7fc6246900 - scrubber/ArakoonConfigFetcher - 0000000000000002 - info - operator(): Fetching config from arakoon://config/ovs/vpools/a2b75bb3-5f93-4784-a187-4bbac60ed95b/proxies/scrub/backend_config_9925b0f6-ad38-4548-892c-7f8a3f06ff35?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini
2017-07-04 09:21:20 988327 +0200 - ovs-node01-1604 - 5148/0x00007f7fc6246900 - scrubber/Cluster - 0000000000000003 - info - Cluster: Cluster ID config, proto version 0
2017-07-04 09:21:20 988399 +0200 - ovs-node01-1604 - 5148/0x00007f7fc6246900 - scrubber/Cluster - 0000000000000004 - info - add_node_: config: adding arakoon node 2YZ11YQoMg5425iR, host 10.100.199.192, service 26400
2017-07-04 09:21:20 988440 +0200 - ovs-node01-1604 - 5148/0x00007f7fc6246900 - scrubber/Cluster - 0000000000000005 - info - add_node_: config: adding arakoon node KUzErUS1G4iiXfNi, host 10.100.199.191, service 26400
2017-07-04 09:21:20 988454 +0200 - ovs-node01-1604 - 5148/0x00007f7fc6246900 - scrubber/Cluster - 0000000000000006 - info - add_node_: config: adding arakoon node M5rootGLOTpqkRg3, host 10.100.199.193, service 26400
2017-07-04 09:21:21 020166 +0200 - ovs-node01-1604 - 5148/0x00007f7fb9600700 - scrubber/SignalThread - 0000000000000007 - info - run_: exiting signal handler thread
2017-07-04 09:21:21 020518 +0200 - ovs-node01-1604 - 5148/0x00007f7fc6246900 - scrubber/ovs_scrubber - 0000000000000008 - fatal - operator(): caught exception: Not found
2017-07-04 09:21:21 020577 +0200 - ovs-node01-1604 - 5148/0x00007f7fc6246900 - scrubber/ovs_scrubber - 0000000000000009 - notice - at_exit: Time spent executing user instructions (seconds): 0.16000
Time spent in operating system code (seconds): 0.8000
The maximum resident set size used, in kilobytes. 23436
The number of page faults which were serviced without requiring any I/O: 1040
The number of page faults which were serviced by doing I/O: 57
The number of times PROCESSES was swapped entirely out of main memory: 0
The number of times the file system had to read from the disk: 15440
The number of times the file system had to write to the disk: 8
The number of signals received: 0
The number of times PROCESSES voluntarily invoked a context switch: 77
The number of times an involuntary context switch took place: 15
```

**Comment by pploegaert** [comment]
Input from @redlicha:

The "Not found" looks like an arakoon lookup that didn't return a key / value
and since that's pretty early in the game, it looks like the config key was wrong
arakoon://config/ovs/vpools/2aedec2c-2c90-4dfc-a0e8-ad7ed0deeb83/proxies/scrub/backend_config_3644414c-e12d-4f08-8b74-2933e7233246?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini

^^^ that looks odd (the "proxies" component)

**Comment by khenderick** [comment]
Fixed by #1698, packaged in openvstorage-2.9.6-dev.1499153279.7a2b4ab

**Comment by JeffreyDevloo** [comment]
openvstorage_2.9.6-1_amd64.deb

**Comment by pploegaert** [comment]
Validated ok:
http://testrail.openvstorage.com/index.php?/plans/view/38218
