### ISSUE TITLE
NoneType error while creating backend with API

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#1775]
```
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]: 2017-09-14 17:45:28 45200 +0200 - ovs-node01-1604 - 30937/140064870431632 - api/middleware.py - 510 - ERROR - An unhandled exception occurred: 'NoneType' object has no attribute
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]: Traceback (most recent call last):
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:   File "/usr/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 78, in view
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:     return self.dispatch(request, *args, **kwargs)
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:   File "/usr/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:     return view_func(*args, **kwargs)
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:   File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 399, in dispatch
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:     response = self.handle_exception(exc)
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:   File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 396, in dispatch
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:     response = handler(request, *args, **kwargs)
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:   File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 591, in new_function
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:     return_value = f(*args, **kwargs)
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:   File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 87, in new_function
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:     result = f(*args, **kw)
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:   File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 414, in new_function
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:     data = FullSerializer(object_type, contents=contents, instance=obj).data
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:   File "/usr/lib/python2.7/dist-packages/rest_framework/serializers.py", line 573, in data
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:     self._data = self.to_native(obj)
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:   File "/usr/lib/python2.7/dist-packages/rest_framework/serializers.py", line 349, in to_native
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:     value = field.field_to_native(obj, field_name)
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:   File "/usr/lib/python2.7/dist-packages/rest_framework/fields.py", line 198, in field_to_native
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:     value = get_component(value, component)
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:   File "/usr/lib/python2.7/dist-packages/rest_framework/fields.py", line 56, in get_component
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:     val = getattr(obj, attr_name)
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:   File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 349, in <lambda>
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:     fget = lambda s: s._get_dynamic_property(dynamic)
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:   File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 418, in _get_dynamic_property
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:     return self._backend_property(data_loader, dynamic)
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:   File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 1031, in _backend_property
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:     dynamic_data = fct()
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:   File "/opt/OpenvStorage/ovs/dal/hybrids/albabackend.py", line 150, in _usages
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]:     config = Configuration.get_configuration_path(self.abm_cluster.config_location)
Sep 14 17:45:28 ovs-node01-1604 gunicorn[30911]: AttributeError: 'NoneType' object has no attribute 'config_location'
```

**Comment by matthiasdeblock** [comment]
Wrong repo
