### ISSUE TITLE
Framework set logging to file produces some errors

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#1777]
### Problem description
Specifically setting the framework logging to file, so that all components log to a file instead of stdout, causes a bug that backends can no longer be made

```
Sep 18 10:10:30 jef-node01 celery[20645]: 2017-09-18 10:10:30 40800 +0200 - jef-node01 - 20657/140183918237440 - lib/alba.py - 70 - ERROR - Failed manual ALBA Arakoon checkup during add cluster for Backend dc26659b-120f-4fee-8ecd-6
Sep 18 10:10:30 jef-node01 celery[20645]: Traceback (most recent call last):
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/opt/OpenvStorage/ovs/lib/alba.py", line 545, in add_cluster
Sep 18 10:10:30 jef-node01 celery[20645]:     nsm_clusters=nsm_clusters) is True:
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
Sep 18 10:10:30 jef-node01 celery[20645]:     return self._get_current_object()(*a, **kw)
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
Sep 18 10:10:30 jef-node01 celery[20645]:     return orig(self, *args, **kwargs)
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
Sep 18 10:10:30 jef-node01 celery[20645]:     return self.run(*args, **kwargs)
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 242, in new_function
Sep 18 10:10:30 jef-node01 celery[20645]:     output = f(*args, **kwargs)
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/opt/OpenvStorage/ovs/lib/alba.py", line 769, in manual_alba_arakoon_checkup
Sep 18 10:10:30 jef-node01 celery[20645]:     nsm_clusters=nsm_clusters)
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/opt/OpenvStorage/ovs/lib/alba.py", line 827, in _alba_arakoon_checkup
Sep 18 10:10:30 jef-node01 celery[20645]:     plugins={AlbaController.ABM_PLUGIN: AlbaController.ALBA_VERSION_GET})
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/arakooninstaller.py", line 468, in create_cluster
Sep 18 10:10:30 jef-node01 celery[20645]:     log_sinks=log_sinks or self.get_log_sink_path(),
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/arakooninstaller.py", line 978, in get_log_sink_path
Sep 18 10:10:30 jef-node01 celery[20645]:     return self._logger.get_sink_path('arakoon-server_{0}'.format(self.cluster_name))
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/log/logger.py", line 171, in get_sink_path
Sep 18 10:10:30 jef-node01 celery[20645]:     target_params = cls._load_target_parameters(source=source, forced_target_type=forced_target_type)
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/log/logger.py", line 226, in _load_target_parameters
Sep 18 10:10:30 jef-node01 celery[20645]:     'filename': cls.load_path(source)}
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/log/logger.py", line 156, in load_path
Sep 18 10:10:30 jef-node01 celery[20645]:     open(log_filename, 'a').close()
Sep 18 10:10:30 jef-node01 celery[20645]: IOError: [Errno 13] Permission denied: '/var/log/ovs/arakoon-server_mybackend02-abm.log'
Sep 18 10:10:30 jef-node01 celery[20645]: 2017-09-18 10:10:30 74400 +0200 - jef-node01 - 20657/140183918237440 - lib/alba.py - 71 - DEBUG - Deleting ALBA Backend entry /ovs/alba/backends/dc26659b-120f-4fee-8ecd-69f24ac7a5c4 from co
Sep 18 10:10:30 jef-node01 celery[20645]: 2017-09-18 10:10:30 75100 +0200 - jef-node01 - 20657/140183918237440 - lib/alba.py - 72 - DEBUG - Deleting ALBA Backend from model
Sep 18 10:10:30 jef-node01 celery[20645]: 2017-09-18 10:10:30 79300 +0200 - jef-node01 - 20645/140183918237440 - celery/log.py - 73 - ERROR - Task alba.add_cluster[9b8b7102-de6b-4a25-82f2-d38089ca4801] raised unexpected: IOError(13
Sep 18 10:10:30 jef-node01 celery[20645]: Traceback (most recent call last):
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Sep 18 10:10:30 jef-node01 celery[20645]:     R = retval = fun(*args, **kwargs)
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Sep 18 10:10:30 jef-node01 celery[20645]:     return self.run(*args, **kwargs)
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/opt/OpenvStorage/ovs/lib/alba.py", line 545, in add_cluster
Sep 18 10:10:30 jef-node01 celery[20645]:     nsm_clusters=nsm_clusters) is True:
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
Sep 18 10:10:30 jef-node01 celery[20645]:     return self._get_current_object()(*a, **kw)
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
Sep 18 10:10:30 jef-node01 celery[20645]:     return orig(self, *args, **kwargs)
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
Sep 18 10:10:30 jef-node01 celery[20645]:     return self.run(*args, **kwargs)
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 242, in new_function
Sep 18 10:10:30 jef-node01 celery[20645]:     output = f(*args, **kwargs)
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/opt/OpenvStorage/ovs/lib/alba.py", line 769, in manual_alba_arakoon_checkup
Sep 18 10:10:30 jef-node01 celery[20645]:     nsm_clusters=nsm_clusters)
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/opt/OpenvStorage/ovs/lib/alba.py", line 827, in _alba_arakoon_checkup
Sep 18 10:10:30 jef-node01 celery[20645]:     plugins={AlbaController.ABM_PLUGIN: AlbaController.ALBA_VERSION_GET})
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/arakooninstaller.py", line 468, in create_cluster
Sep 18 10:10:30 jef-node01 celery[20645]:     log_sinks=log_sinks or self.get_log_sink_path(),
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/arakooninstaller.py", line 978, in get_log_sink_path
Sep 18 10:10:30 jef-node01 celery[20645]:     return self._logger.get_sink_path('arakoon-server_{0}'.format(self.cluster_name))
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/log/logger.py", line 171, in get_sink_path
Sep 18 10:10:30 jef-node01 celery[20645]:     target_params = cls._load_target_parameters(source=source, forced_target_type=forced_target_type)
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/log/logger.py", line 226, in _load_target_parameters
Sep 18 10:10:30 jef-node01 celery[20645]:     'filename': cls.load_path(source)}
Sep 18 10:10:30 jef-node01 celery[20645]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/log/logger.py", line 156, in load_path
Sep 18 10:10:30 jef-node01 celery[20645]:     open(log_filename, 'a').close()
Sep 18 10:10:30 jef-node01 celery[20645]: IOError: [Errno 13] Permission denied: '/var/log/ovs/arakoon-server_mybackend02-abm.log'
```

**Comment by wimpers** [comment]
relates to https://github.com/openvstorage/framework/issues/1816 and https://github.com/openvstorage/framework/issues/1817

**Comment by JeffreyDevloo** [comment]
Fixed by: https://github.com/openvstorage/framework/pull/2251
