### ISSUE TITLE
[External Arakoon] Running ovs setup with wrong external arakoon info results in the creation of a locally managed arakoon

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1813]
I made a mistake in my test environment with the external managed rabbitmq ('/ovs/framework/messagequeue')

After fixing the issue i tried to run the ovs setup again and ended up with an error ovsdb already exists...

I do not understand why the framework try to create an ovsdb arakoon that:
1) already have been deployed by us
2) creating a new one (remember arakoons are externally managed...)

I think some of the steps like claiming the ovsdb was successful before the first error occurred. (rabbitmq key)

Couple of things you could do:
1) When an error occurred revert the steps
2) When run ovs setup again check if some steps already have proceed and skip those steps

Below the logging of the first ovs setup and the second one:
```
2017-10-03 15:32:48 45300 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 0 - INFO - Open vStorage Setup
2017-10-03 15:32:48 45300 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 1 - INFO - Setting up connections
2017-10-03 15:32:48 49100 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 2 - INFO - Collecting cluster information
2017-10-03 15:32:48 50500 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 3 - DEBUG - Current host: LC1SRV0008
2017-10-03 15:32:48 50500 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 4 - DEBUG - Automated installation
2017-10-03 15:32:48 50500 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 5 - INFO - Detected a 1st node installation
2017-10-03 15:32:48 54500 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 6 - INFO - Preparing node
2017-10-03 15:32:48 54500 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 7 - INFO - Setting up and exchanging SSH keys
2017-10-03 15:32:49 31900 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 8 - INFO - Updating hosts file
2017-10-03 15:32:49 36100 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 9 - INFO - Setting up first node
2017-10-03 15:32:49 36800 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 10 - INFO - Setting up configuration management
2017-10-03 15:32:49 37700 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 11 - INFO - Setting up configuration Arakoon
2017-10-03 15:32:50 19700 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 12 - INFO - Adding service watcher-config
2017-10-03 15:32:50 39400 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 13 - DEBUG - 10.100.50.18: Starting service watcher-config
2017-10-03 15:32:50 76900 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 14 - DEBUG - 10.100.50.18: Started service watcher-config
2017-10-03 15:32:50 86900 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 15 - INFO - Externally managed Arakoon cluster of type FWK found with name ovsdb
2017-10-03 15:32:50 87300 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 16 - INFO - Adding services
2017-10-03 15:32:50 88200 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 17 - INFO - Adding service volumerouter-consumer
2017-10-03 15:32:51 09000 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 18 - INFO - Adding service scheduled-tasks
2017-10-03 15:32:51 28700 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 19 - INFO - Adding service watcher-framework
2017-10-03 15:32:51 46000 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 20 - INFO - Adding service webapp-api
2017-10-03 15:32:51 60600 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 21 - INFO - Adding service workers
2017-10-03 15:32:51 79400 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 22 - INFO - Build configuration files
2017-10-03 15:32:51 79500 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 23 - ERROR - Failed to setup first node
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/nodeinstallation.py", line 473, in setup_node
    rdma=rdma)
  File "/opt/OpenvStorage/ovs/lib/nodeinstallation.py", line 801, in _setup_first_node
    configure_rabbitmq = Toolbox.is_service_internally_managed(service='rabbitmq')
  File "/opt/OpenvStorage/ovs/lib/helpers/toolbox.py", line 325, in is_service_internally_managed
    internal = metadata['internal']
TypeError: string indices must be integers
2017-10-03 15:32:51 79600 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 24 - ERROR - string indices must be integers
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/nodeinstallation.py", line 473, in setup_node
    rdma=rdma)
  File "/opt/OpenvStorage/ovs/lib/nodeinstallation.py", line 801, in _setup_first_node
    configure_rabbitmq = Toolbox.is_service_internally_managed(service='rabbitmq')
  File "/opt/OpenvStorage/ovs/lib/helpers/toolbox.py", line 325, in is_service_internally_managed
    internal = metadata['internal']
TypeError: string indices must be integers
2017-10-03 15:32:51 79800 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 25 - INFO - 

2017-10-03 15:32:51 79800 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 26 - ERROR - An unexpected error occurred:
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/nodeinstallation.py", line 473, in setup_node
    rdma=rdma)
  File "/opt/OpenvStorage/ovs/lib/nodeinstallation.py", line 801, in _setup_first_node
    configure_rabbitmq = Toolbox.is_service_internally_managed(service='rabbitmq')
  File "/opt/OpenvStorage/ovs/lib/helpers/toolbox.py", line 325, in is_service_internally_managed
    internal = metadata['internal']
TypeError: string indices must be integers
2017-10-03 15:32:51 79800 +0200 - LC1SRV0008 - 32559/140129813964544 - lib/node-installation - 27 - ERROR - string indices must be integers
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/nodeinstallation.py", line 473, in setup_node
    rdma=rdma)
  File "/opt/OpenvStorage/ovs/lib/nodeinstallation.py", line 801, in _setup_first_node
    configure_rabbitmq = Toolbox.is_service_internally_managed(service='rabbitmq')
  File "/opt/OpenvStorage/ovs/lib/helpers/toolbox.py", line 325, in is_service_internally_managed
    internal = metadata['internal']
TypeError: string indices must be integers
```

second run:
```
2017-10-03 15:34:58 53800 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 0 - INFO - Open vStorage Setup
2017-10-03 15:34:58 53800 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 1 - INFO - Setting up connections
2017-10-03 15:34:58 57300 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 2 - INFO - Collecting cluster information
2017-10-03 15:34:58 58500 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 3 - DEBUG - Current host: LC1SRV0008
2017-10-03 15:34:58 58600 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 4 - DEBUG - Automated installation
2017-10-03 15:34:58 58600 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 5 - INFO - Detected a 1st node installation
2017-10-03 15:34:58 62900 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 6 - INFO - Preparing node
2017-10-03 15:34:58 63000 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 7 - INFO - Setting up and exchanging SSH keys
2017-10-03 15:34:59 40000 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 8 - INFO - Updating hosts file
2017-10-03 15:34:59 44700 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 9 - INFO - Setting up first node
2017-10-03 15:34:59 45400 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 10 - INFO - Setting up configuration management
2017-10-03 15:34:59 46500 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 11 - INFO - Setting up configuration Arakoon
2017-10-03 15:35:00 34200 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 12 - INFO - Setting up Arakoon cluster ovsdb
2017-10-03 15:35:00 53300 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 13 - ERROR - Failed to setup first node
Traceback (most recent call last):
  File "ovs/lib/nodeinstallation.py", line 473, in setup_node
    rdma=rdma)
  File "ovs/lib/nodeinstallation.py", line 789, in _setup_first_node
    locked=False)
  File "ovs/extensions/db/arakoon/arakooninstaller.py", line 408, in create_cluster
    raise ValueError('An Arakoon cluster with name "{0}" already exists'.format(cluster_name))
ValueError: An Arakoon cluster with name "ovsdb" already exists
2017-10-03 15:35:00 53500 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 14 - ERROR - An Arakoon cluster with name "ovsdb" already exists
Traceback (most recent call last):
  File "ovs/lib/nodeinstallation.py", line 473, in setup_node
    rdma=rdma)
  File "ovs/lib/nodeinstallation.py", line 789, in _setup_first_node
    locked=False)
  File "ovs/extensions/db/arakoon/arakooninstaller.py", line 408, in create_cluster
    raise ValueError('An Arakoon cluster with name "{0}" already exists'.format(cluster_name))
ValueError: An Arakoon cluster with name "ovsdb" already exists
2017-10-03 15:35:00 54700 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 15 - INFO - 

2017-10-03 15:35:00 54800 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 16 - ERROR - An unexpected error occurred:
Traceback (most recent call last):
  File "ovs/lib/nodeinstallation.py", line 473, in setup_node
    rdma=rdma)
  File "ovs/lib/nodeinstallation.py", line 789, in _setup_first_node
    locked=False)
  File "ovs/extensions/db/arakoon/arakooninstaller.py", line 408, in create_cluster
    raise ValueError('An Arakoon cluster with name "{0}" already exists'.format(cluster_name))
ValueError: An Arakoon cluster with name "ovsdb" already exists
2017-10-03 15:35:00 54800 +0200 - LC1SRV0008 - 1460/140021773997824 - lib/node-installation - 17 - ERROR - An Arakoon cluster with name "ovsdb" already exists
Traceback (most recent call last):
  File "ovs/lib/nodeinstallation.py", line 473, in setup_node
    rdma=rdma)
  File "ovs/lib/nodeinstallation.py", line 789, in _setup_first_node
    locked=False)
  File "ovs/extensions/db/arakoon/arakooninstaller.py", line 408, in create_cluster
    raise ValueError('An Arakoon cluster with name "{0}" already exists'.format(cluster_name))
ValueError: An Arakoon cluster with name "ovsdb" already exists
```

**Comment by JeffreyDevloo** [comment]
The mistake was that the metadata property was a string instead of a dict.
When the setup was run again, the framework created an internally managed arakoon instead of using the externally one which was requested

**Comment by jeroenmaelbrancke** [comment]
@JeffreyDevloo This error was not caused by a wrong external arakoon config but a rabbitmq config.

**Comment by wimpers** [comment]
After discussion with @jeroenmaelbrancke : this one can be closed as it should be tackled when taking up https://github.com/openvstorage/framework/issues/1370 (allow actions to be rolled back/rerun)
