### ISSUE TITLE
watcher-framework went down due to extending the ovsdb arakoon

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1848]
After extending the ovsdb from 4 Arakoon nodes to 5 Arakoon nodes with the ArakoonInstaller module.

For some reason the ovs-watcher-framework, ovs-workers and ovs-webapp-api went down during the extension. The ovs-watcher-framework recovered but not the workers and webapp-api. I thought the watcher-framework monitored those processes and try to restart them x times...

I think the way the framework extend is not the correct one.

What i heard from @kvanhijf:
Cluster with max 3 nodes:
- restart one node at the time and wait until a nop'ke works.

Cluster with more than 3 nodes:
- extend to the new node.
- wait until the node catch up.
- restart one node without moving the master.

@domsj  can you give the input how they need to extend an Arakoon?

```
2017-10-24 08:04:50 14700 -0400 - NY1SRV0018 - 5808/140053717686016 - arakoon_client/pyrakoon - 1482 - ERROR - 'roLR7yTDk9hMdPGK' : Message exchange with node roLR7yTDk9hMdPGK failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1137, in _send_message
    connection = self._get_connection(node_id)
  File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1227, in _get_connection
    node_location = self._config.getNodeLocation(node_id)
  File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1014, in getNodeLocation
    ips, port = self.getNodeLocations(nodeId)
  File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 999, in getNodeLocations
    return self._nodes[nodeId]
KeyError: 'roLR7yTDk9hMdPGK'
2017-10-24 08:04:50 14700 -0400 - NY1SRV0018 - 5808/140053717686016 - arakoon_client/pyrakoon - 1483 - ERROR - 'roLR7yTDk9hMdPGK': Unable to validate master on node roLR7yTDk9hMdPGK
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1185, in determine_master
    self._validate_master_id(self.master_id):
  File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1216, in _validate_master_id
    other_master_id = self._get_master_id_from_node(master_id)
  File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1207, in _get_master_id_from_node
    connection = self._send_message(node_id, data)
  File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1146, in _send_message
    self._connections.pop(node_id).close()
KeyError: 'roLR7yTDk9hMdPGK'
2017-10-24 08:04:50 14700 -0400 - NY1SRV0018 - 5808/140053717686016 - arakoon_client/pyrakoon - 1484 - ERROR - Unable to determine master node
2017-10-24 08:04:50 14700 -0400 - NY1SRV0018 - 5808/140053717686016 - extensions/watcher - 1485 - DEBUG - [framework]   Error during volatile store test: 'PyrakoonClient' object has no attribute 'identifier'
2017-10-24 08:04:51 14900 -0400 - NY1SRV0018 - 5808/140053717686016 - extensions/watcher - 1486 - DEBUG - [framework]   Volatile store not working correctly
2017-10-24 08:04:51 14900 -0400 - NY1SRV0018 - 5808/140053717686016 - extensions/watcher - 1487 - DEBUG - [framework] One of the master services is unavailable
ovs-watcher-framework.service: Main process exited, code=exited, status=1/FAILURE
ovs-watcher-framework.service: Unit entered failed state.
ovs-watcher-framework.service: Failed with result 'exit-code'.
ovs-watcher-framework.service: Service hold-off time over, scheduling restart.
Stopped Watcher for Open vStorage master services.
Starting Watcher for Open vStorage master services...
2017-10-24 08:04:52 21700 -0400 - NY1SRV0018 - 18143/139978106222336 - extensions/watcher - 0 - DEBUG - [framework] Starting service
2017-10-24 08:04:52 21700 -0400 - NY1SRV0018 - 18143/139978106222336 - extensions/watcher - 1 - DEBUG - [framework] Waiting for master services
2017-10-24 08:04:52 32400 -0400 - NY1SRV0018 - 18143/139978106222336 - extensions/watcher - 2 - DEBUG - [framework] Master services available
Started Watcher for Open vStorage master services.
2017-10-24 08:04:52 42100 -0400 - NY1SRV0018 - 18152/140068540266240 - extensions/watcher - 0 - DEBUG - [framework] Starting service
2017-10-24 08:04:52 42100 -0400 - NY1SRV0018 - 18152/140068540266240 - extensions/watcher - 1 - DEBUG - [framework] Checking master services
2017-10-24 08:12:40 81100 -0400 - NY1SRV0018 - 18152/140068540266240 - arakoon_client/pyrakoon - 3 - ERROR - Unable to determine master node
2017-10-24 08:12:41 01500 -0400 - NY1SRV0018 - 18152/140068540266240 - arakoon_client/pyrakoon - 5 - ERROR - Unable to determine master node
2017-10-24 08:12:41 42000 -0400 - NY1SRV0018 - 18152/140068540266240 - arakoon_client/pyrakoon - 7 - ERROR - Unable to determine master node

```

**Comment by wimpers** [comment]
Is this somehow related to https://github.com/openvstorage/framework/issues/1709 ?

**Comment by jeroenmaelbrancke** [comment]
@wimpers I did not verify this but it looks the same issue.
@domsj The way they extend is this the correct way or not?
If so we can close the ticket.

**Comment by JeffreyDevloo** [comment]
The #1709 does not show this Arakoon exception

**Comment by domsj** [comment]
The way to extend looks correct.

The problem inside the ovs-watcher-framework looks like it is due to the old ovsdb config there still being cached.
The caching is fine, but upon detecting that the config is outdated (here it does so with the key error - admittedly not the most elegant way), this process should reload the config and just try again.
What happened instead is that the process went down, which also cleared the (invalid) cached config, and then it worked again as it should.
( @JeffreyDevloo claims a new client is built before each call, ensuring this scenario can't happen ... but I seem to recall things differently from earlier discussions with @khenderick though.)

#1709 is indeed related, as the going down of ovs-watcher-framework resulted in ovs-workers and ovs-web-api, and after ovs-watcher-framework starts again for some reason these other services are not restarted automatically. (As mentioned by @JeffreyDevloo the reason for ovs-watcher-framework to go down is indeed different, but as far as I understand the exact reason of the service going down does not seem really relevant for what is described there.)

**Comment by wimpers** [comment]
@JeffreyDevloo might this be caused by a master switch. We haven't seen this anywhere else.

**Comment by wimpers** [comment]
Fixed
