### ISSUE TITLE
ovs-worker consumer lost connection to broker

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1874]
For some reason the celelry consumer lost his connection to rabbitmq and was not able to re-established the connection. Yesterday i added the statsmonkey again on the global environment.
This is the second time on this storagerouter.
Not observed on other nodes.

```
2017-11-17 10:16:12 38700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.worker.consumer - 2977 - WARNING - consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/worker/consumer.py", line 279, in start
    blueprint.start(self)
  File "/usr/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/lib/python2.7/dist-packages/celery/worker/consumer.py", line 838, in start
    c.loop(*c.loop_args())
  File "/usr/lib/python2.7/dist-packages/celery/worker/loops.py", line 73, in asynloop
    update_qos()
  File "/usr/lib/python2.7/dist-packages/kombu/common.py", line 400, in update
    return self.set(self.value)
  File "/usr/lib/python2.7/dist-packages/kombu/common.py", line 393, in set
    self.callback(prefetch_count=new_value)
  File "/usr/lib/python2.7/dist-packages/celery/worker/consumer.py", line 615, in set_prefetch_count
    apply_global=qos_global,
  File "/usr/lib/python2.7/dist-packages/kombu/messaging.py", line 533, in qos
    apply_global)
  File "/usr/lib/python2.7/dist-packages/amqp/channel.py", line 2200, in basic_qos
    self._send_method((60, 10), args)
  File "/usr/lib/python2.7/dist-packages/amqp/abstract_channel.py", line 56, in _send_method
    self.channel_id, method_sig, args, content,
  File "/usr/lib/python2.7/dist-packages/amqp/method_framing.py", line 221, in write_method
    write_frame(1, channel, payload)
  File "/usr/lib/python2.7/dist-packages/amqp/transport.py", line 182, in write_frame
    frame_type, channel, size, payload, 0xce,
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer
2017-11-17 10:16:13 15000 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2978 - DEBUG - | Consumer: Restarting event loop...
2017-11-17 10:16:13 15000 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2979 - DEBUG - | Consumer: Restarting Heart...
2017-11-17 10:16:13 15100 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2980 - DEBUG - | Consumer: Restarting Gossip...
2017-11-17 10:16:13 15100 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2981 - DEBUG - | Consumer: Restarting Control...
2017-11-17 10:16:13 15200 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2982 - DEBUG - | Consumer: Restarting Tasks...
2017-11-17 10:16:13 15200 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.worker.consumer - 2983 - DEBUG - Canceling task consumer...
2017-11-17 10:16:13 15200 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2984 - DEBUG - | Consumer: Restarting Mingle...
2017-11-17 10:16:13 15200 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2985 - DEBUG - | Consumer: Restarting Events...
2017-11-17 10:16:13 15200 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2986 - DEBUG - | Consumer: Restarting Connection...
2017-11-17 10:16:13 15200 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2987 - DEBUG - | Consumer: Starting Connection
2017-11-17 10:16:15 35500 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.worker.consumer - 2988 - INFO - Connected to amqp://ovs:**@172.17.16.19:5672//
2017-11-17 10:16:15 35500 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2989 - DEBUG - ^-- substep ok
2017-11-17 10:16:15 35600 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2990 - DEBUG - | Consumer: Starting Events
2017-11-17 10:16:15 37800 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2991 - DEBUG - ^-- substep ok
2017-11-17 10:16:15 37900 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2992 - DEBUG - | Consumer: Starting Mingle
2017-11-17 10:16:15 37900 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.worker.consumer - 2993 - INFO - mingle: searching for neighbors
2017-11-17 10:16:16 56200 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.worker.consumer - 2994 - INFO - mingle: sync with 24 nodes
2017-11-17 10:16:16 56700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.worker.consumer - 2995 - INFO - mingle: sync complete
2017-11-17 10:16:16 56700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2996 - DEBUG - ^-- substep ok
2017-11-17 10:16:16 56700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2997 - DEBUG - | Consumer: Starting Tasks
2017-11-17 10:16:16 57600 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2998 - DEBUG - ^-- substep ok
2017-11-17 10:16:16 57600 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 2999 - DEBUG - | Consumer: Starting Control
2017-11-17 10:16:16 58500 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3000 - DEBUG - ^-- substep ok
2017-11-17 10:16:16 58500 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3001 - DEBUG - | Consumer: Starting Gossip
2017-11-17 10:16:16 59600 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3002 - DEBUG - ^-- substep ok
2017-11-17 10:16:16 59600 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3003 - DEBUG - | Consumer: Starting Heart
2017-11-17 10:16:16 59700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3004 - DEBUG - ^-- substep ok
2017-11-17 10:16:16 59700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3005 - DEBUG - | Consumer: Starting event loop
2017-11-17 10:16:16 59900 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3006 - DEBUG - | Worker: Hub.register Autoscaler...
2017-11-17 10:16:16 59900 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3007 - DEBUG - | Worker: Hub.register Pool...
2017-11-17 10:16:16 60400 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.worker.consumer - 3008 - WARNING - consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/worker/consumer.py", line 279, in start
    blueprint.start(self)
  File "/usr/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/lib/python2.7/dist-packages/celery/worker/consumer.py", line 838, in start
    c.loop(*c.loop_args())
  File "/usr/lib/python2.7/dist-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "/usr/lib/python2.7/dist-packages/kombu/async/hub.py", line 279, in create_loop
    item()
  File "/usr/lib/python2.7/dist-packages/amqp/utils.py", line 42, in __call__
    self.set_error_state(exc)
  File "/usr/lib/python2.7/dist-packages/amqp/utils.py", line 39, in __call__
    **dict(self.kwargs, **kwargs) if self.kwargs else kwargs
  File "/usr/lib/python2.7/dist-packages/kombu/transport/base.py", line 144, in _read
    raise RecoverableConnectionError('Socket was disconnected')
RecoverableConnectionError: Socket was disconnected
2017-11-17 10:16:16 66500 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3009 - DEBUG - | Consumer: Restarting event loop...
2017-11-17 10:16:16 66600 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3010 - DEBUG - | Consumer: Restarting Heart...
2017-11-17 10:16:16 66600 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3011 - DEBUG - | Consumer: Restarting Gossip...
2017-11-17 10:16:16 66600 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3012 - DEBUG - | Consumer: Restarting Control...
2017-11-17 10:16:16 66700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3013 - DEBUG - | Consumer: Restarting Tasks...
2017-11-17 10:16:16 66700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.worker.consumer - 3014 - DEBUG - Canceling task consumer...
2017-11-17 10:16:16 66700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3015 - DEBUG - | Consumer: Restarting Mingle...
2017-11-17 10:16:16 66700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3016 - DEBUG - | Consumer: Restarting Events...
2017-11-17 10:16:16 66700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3017 - DEBUG - | Consumer: Restarting Connection...
2017-11-17 10:16:16 66700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3018 - DEBUG - | Consumer: Starting Connection
2017-11-17 10:16:16 67700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.worker.consumer - 3019 - INFO - Connected to amqp://ovs:**@172.17.16.19:5672//
2017-11-17 10:16:16 67700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3020 - DEBUG - ^-- substep ok
2017-11-17 10:16:16 67700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3021 - DEBUG - | Consumer: Starting Events
2017-11-17 10:16:16 69000 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3022 - DEBUG - ^-- substep ok
2017-11-17 10:16:16 69000 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3023 - DEBUG - | Consumer: Starting Mingle
2017-11-17 10:16:16 69000 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.worker.consumer - 3024 - INFO - mingle: searching for neighbors
2017-11-17 10:16:17 73400 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.worker.consumer - 3025 - INFO - mingle: sync with 24 nodes
2017-11-17 10:16:17 73800 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.worker.consumer - 3026 - INFO - mingle: sync complete
2017-11-17 10:16:17 73800 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3027 - DEBUG - ^-- substep ok
2017-11-17 10:16:17 73900 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3028 - DEBUG - | Consumer: Starting Tasks
2017-11-17 10:16:17 74700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3029 - DEBUG - ^-- substep ok
2017-11-17 10:16:17 74700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3030 - DEBUG - | Consumer: Starting Control
2017-11-17 10:16:17 75600 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3031 - DEBUG - ^-- substep ok
2017-11-17 10:16:17 75700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3032 - DEBUG - | Consumer: Starting Gossip
2017-11-17 10:16:17 76700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3033 - DEBUG - ^-- substep ok
2017-11-17 10:16:17 76700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3034 - DEBUG - | Consumer: Starting Heart
2017-11-17 10:16:17 76800 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3035 - DEBUG - ^-- substep ok
2017-11-17 10:16:17 76800 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3036 - DEBUG - | Consumer: Starting event loop
2017-11-17 10:16:17 76900 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3037 - DEBUG - | Worker: Hub.register Autoscaler...
2017-11-17 10:16:17 76900 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3038 - DEBUG - | Worker: Hub.register Pool...
2017-11-17 10:16:17 77800 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.worker - 3039 - ERROR - Unrecoverable error: AttributeError("'NoneType' object has no attribute 'drain_events'",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/worker/__init__.py", line 206, in start
    self.blueprint.start(self)
  File "/usr/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/lib/python2.7/dist-packages/celery/bootsteps.py", line 374, in start
    return self.obj.start()
  File "/usr/lib/python2.7/dist-packages/celery/worker/consumer.py", line 279, in start
    blueprint.start(self)
  File "/usr/lib/python2.7/dist-packages/celery/bootsteps.py", line 123, in start
    step.start(parent)
  File "/usr/lib/python2.7/dist-packages/celery/worker/consumer.py", line 838, in start
    c.loop(*c.loop_args())
  File "/usr/lib/python2.7/dist-packages/celery/worker/loops.py", line 76, in asynloop
    next(loop)
  File "/usr/lib/python2.7/dist-packages/kombu/async/hub.py", line 279, in create_loop
    item()
  File "/usr/lib/python2.7/dist-packages/amqp/utils.py", line 42, in __call__
    self.set_error_state(exc)
  File "/usr/lib/python2.7/dist-packages/amqp/utils.py", line 39, in __call__
    **dict(self.kwargs, **kwargs) if self.kwargs else kwargs
  File "/usr/lib/python2.7/dist-packages/kombu/connection.py", line 275, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/usr/lib/python2.7/dist-packages/kombu/transport/pyamqp.py", line 95, in drain_events
    return connection.drain_events(**kwargs)
AttributeError: 'NoneType' object has no attribute 'drain_events'
2017-11-17 10:16:18 29600 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3040 - DEBUG - | Worker: Closing Hub...
2017-11-17 10:16:18 29700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3041 - DEBUG - | Worker: Closing Pool...
2017-11-17 10:16:18 29700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3042 - DEBUG - | Worker: Closing Autoscaler...
2017-11-17 10:16:18 29700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3043 - DEBUG - | Worker: Closing Consumer...
2017-11-17 10:16:18 29700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3044 - DEBUG - | Worker: Stopping Consumer...
2017-11-17 10:16:18 29700 -0500 - NY1SRV0005 - 19206/139799403362048 - celery/celery.bootsteps - 3045 - DEBUG - | Consumer: Closing Connection...
```

**Comment by wimpers** [comment]
Possibly related to https://github.com/celery/celery/issues/3932
