### ISSUE TITLE
[DEVELOP] update succeeds but logs errors

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/framework#1901]
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/albamigration.py", line 224, in migrate_sdm
    alba_node.client.update_execute_migration_code()
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 234, in update_execute_migration_code
    return self._call(requests.post, 'update/execute_migration_code')
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 89, in _call
    raise RuntimeError(error_message)

-------------------
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/albamigration.py", line 224, in migrate_sdm
    alba_node.client.update_execute_migration_code()
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 234, in update_execute_migration_code
    return self._call(requests.post, 'update/execute_migration_code')
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 89, in _call
    raise RuntimeError(error_message)
RuntimeError: UNIQUE constraint failed: setting.code

----------------
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/albamigration.py", line 224, in migrate_sdm
    alba_node.client.update_execute_migration_code()
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 234, in update_execute_migration_code
    return self._call(requests.post, 'update/execute_migration_code')
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 89, in _call
    raise RuntimeError(error_message)
RuntimeError: UNIQUE constraint failed: setting.code

---------------
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/albamigration.py", line 224, in migrate_sdm
    alba_node.client.update_execute_migration_code()
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 234, in update_execute_migration_code
    return self._call(requests.post, 'update/execute_migration_code')
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 89, in _call
    raise RuntimeError(error_message)
RuntimeError: UNIQUE constraint failed: setting.code

**Comment by wimpers** [comment]
@simonOpenV  between which versions do these errors  pop up?

**Comment by JeffreyDevloo** [comment]
This is on the current development branch

**Comment by wimpers** [comment]
@JeffreyDevloo  is this still an issue?

**Comment by JeffreyDevloo** [comment]
Yes, should still be tackled
Note: this does not impact anything. It's to track a development issue
