### ISSUE TITLE
Scrubber proxy not removed when finished.

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1916]
After scrubbing some vdisks we see some inactive scrub proxies on the node.
The error message is following:

```
alba: internal error, uncaught exception:
      Arakoon_exc.Exception(4, "Not_found")
      Raised at file "src/core/lwt.ml", line 805, characters 16-23
      Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
      Called from file "src/cmdliner_term.ml", line 27, characters 19-24
      Called from file "src/cmdliner.ml", line 106, characters 32-39
```

multiple scrub process in activating state:
```
Non-running processes
=====================

ovs-albaproxy_os-g-02_NY1SRV1000_f73ca939-52e6-4cf4-a011-2c542cf7b501_scrub      activating
ovs-albaproxy_os-ny1-01_NY1SRV1000_e185e083-10bd-4574-a0a8-20af92f13d4e_scrub    activating
ovs-albaproxy_os-ny2-02_NY1SRV1000_9a0ed68e-1a6c-4fa8-a2a3-0143efbc19cc_scrub    activating
```

I try to search for _Removing service_ on the celery.log but was not able to find any info about this. (logfiles are rotated).
At this point we do not have any logs of this problem.

We are using 2.9.9 on Nuvolat so i tried to search by myself what went wrong.

2 options we have why the service was not been removed.

1. The has_service method doesn't find the correct service on the client. (maybe the name or client is wrong) (https://github.com/openvstorage/framework/blob/2.9.9/ovs/lib/generic.py#L493)
2. The remove_service doesn't throw an exception when this failed... (https://github.com/openvstorage/framework/blob/2.9.9/ovs/lib/generic.py#L495)

I think option 1 is more likely than option 2 as the service try to activate himself and is not stopped. The arakoon config will not been removed if one of these methods fails.(https://github.com/openvstorage/framework/blob/2.9.9/ovs/lib/generic.py#L496)

GIG also having this problem that on a regular base the scrub proxy was not removed.

**Comment by jeroenmaelbrancke** [comment]
```
"result": "Errors occurred while scrubbing: - 
Scrubber - vPool ss-ny2-01 - StorageRouter NY1SRV1000 - vDisk kNFS01ss01_83c047f5-ec24-4f72-bcc1-bc2725e556d5 - Scrubbing failed - 
Scrubber - vPool ss-ny2-01 - StorageRouter NY1SRV1001 - vDisk kNFS01ss01_11fc0ed3-fd6d-4cef-8e2c-6d051393ee75 - Scrubbing failed - 
Scrubber - vPool ss-ny2-01 - StorageRouter NY1SRV1001 - Removing service ovs-albaproxy_c871eb89-9747-415a-b6e6-250c4197f023_scrub failed",
```

**Comment by JeffreyDevloo** [comment]
The workers should tell you which part actually raised. it could be that stopping failed or the remove failed

**Comment by jeroenmaelbrancke** [comment]
@JeffreyDevloo 
What happens if the deployment of a scrubber failed?
Do you remove the service afterwards?

What we see in the celery.log

```
Jan  4 06:00:12 ds1-stor-03 celery[18252]: 2018-01-04 06:00:12 80500 +0300 - ds1-stor-03.msk.decs.local - 21954/139941828720384 - lib/generic tasks - 42269 - ERROR - Scrubber - vPool data01 - StorageRouter stor-06 - An error occurred depl
oying ALBA proxy ovs-albaproxy_1921674d-0e61-480e-9f34-0baac399fa7a_scrub
Jan  4 06:00:12 ds1-stor-03 celery[18252]: Traceback (most recent call last):
Jan  4 06:00:12 ds1-stor-03 celery[18252]:   File "/opt/OpenvStorage/ovs/lib/generic.py", line 442, in _deploy_stack_and_scrub
Jan  4 06:00:12 ds1-stor-03 celery[18252]:     service_manager.start_service(name=alba_proxy_service, client=client)
Jan  4 06:00:12 ds1-stor-03 celery[18252]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/services/interfaces/systemd.py", line 234, in start_service
Jan  4 06:00:12 ds1-stor-03 celery[18252]:     raise RuntimeError('Did not manage to start service {0} on node with IP {1}'.format(name, client.ip))
Jan  4 06:00:12 ds1-stor-03 celery[18252]: RuntimeError: Did not manage to start service ovs-albaproxy_1921674d-0e61-480e-9f34-0baac399fa7a_scrub on node with IP 10.210.3.66
Jan  4 06:00:12 ds1-stor-03 celery[18252]: [2018-01-04 06:00:12,947: WARNING/Worker-8019] Oops, unhandled type 3

```

The alba log: (this occurs multiple times)
```
Jan  4 06:00:04 ds1-stor-06 alba[29772]: 2018-01-04 06:00:04 872613 +0300 - ds1-stor-06.msk.decs.local - 29772/0000 - alba/proxy - 14 - info - server for ADDR_INET(127.0.0.1,26235) going down: (Unix.Unix_error "Address already in use" bind "")
Jan  4 06:00:04 ds1-stor-06 alba[29772]: 2018-01-04 06:00:04 872663 +0300 - ds1-stor-06.msk.decs.local - 29772/0000 - alba/proxy - 15 - fatal - Going down after unexpected exception in proxy process: (Unix.Unix_error "Address already in use" bind ""); backtrace:; Raised by primitive operation at file "src/zone.ml", line 410, characters 33-56
Jan  4 06:00:04 ds1-stor-06 alba[29772]: 2018-01-04 06:00:04 872709 +0300 - ds1-stor-06.msk.decs.local - 29772/0000 - alba/proxy - 16 - info - connect_with : 10.210.3.61 26468 None Net_fd.TCP (fd:15)
Jan  4 06:00:04 ds1-stor-06 alba[29772]: 2018-01-04 06:00:04 872769 +0300 - ds1-stor-06.msk.decs.local - 29772/0000 - alba/proxy - 17 - info - connect_with : 10.210.3.61 26468 None Net_fd.TCP (fd:16)
Jan  4 06:00:04 ds1-stor-06 alba[29772]: 2018-01-04 06:00:04 872844 +0300 - ds1-stor-06.msk.decs.local - 29772/0000 - alba/proxy - 18 - info - connect_with : 10.210.3.61 26468 None Net_fd.TCP (fd:14)
Jan  4 06:00:04 ds1-stor-06 alba[29772]: alba: internal error, uncaught exception:
Jan  4 06:00:04 ds1-stor-06 alba[29772]:       (Unix.Unix_error "Address already in use" bind "")
Jan  4 06:00:04 ds1-stor-06 alba[29772]:       Raised at file "src/core/lwt.ml", line 805, characters 16-23
Jan  4 06:00:04 ds1-stor-06 alba[29772]:       Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Jan  4 06:00:04 ds1-stor-06 alba[29772]:       Called from file "src/cmdliner_term.ml", line 27, characters 19-24
Jan  4 06:00:04 ds1-stor-06 alba[29772]:       Called from file "src/cmdliner.ml", line 106, characters 32-39
```

**Comment by JeffreyDevloo** [comment]
When an error occurs during the deployment of the scrubbing proxy, we will try and remove the service there

**Comment by wimpers** [comment]
@JeffreyDevloo  this is related to https://github.com/openvstorage/framework/issues/1920 ?

**Comment by JeffreyDevloo** [comment]
Yes, the exception seen here is also mentioned in that ticket but this one handles more about certain proxy files not being removed.
Both would be tackled at the same time though

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/framework/releases/tag/2.9.10 release
