### ISSUE TITLE
add vpool write_buffer default on 32MiB on develop

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#1959]
# Problem
Via the setup.sjon we try to add a vpool with a write buffer of 512MiB.
This is not allowed because the vpool was already been deployed with 32MiB...

I changed the write buffer to 32MiB in my setup.json and ended with another error that the value should be in range: 128 - 10240...

I tested this on Bighorn-rc-1 and no problems seen.
With the same setup.json file.

```
6a-2d73c2518ec4', (<class 'ovs.lib.storagerouter.StorageRouterController'>, {u'vpool_name': u'myvpool01', u'fragment_cache_on_write': True, u'storage_ip': u'10.100.50.19', 'backend_info_fc': {u'alba_backend_guid': u'351978ea-fc3c-4866-9ec
8-4e2290a2b230', u'preset': u'cache_no_encrypt'}, u'connection_info': {u'client_secret': u'_jy0BuS#~d4P=9eWA!8qL\'_{ZxB,>[\'_VH!|vUp4uUf"nnu95W]LI@VJW8U}H#R*tDlQ|\'z8J,iH#9q9=W]m@:W=9_kt9b#j>n,]DKY"KT9:3cjDa0bRhLyyczgQc*n,', u'host': u'10
.100.50.18', 'local': True, u'port': 443, u'client_id': 'bd678c7c-2c41-480a-8028-27977f26bc8d'}, u'mds_config_params': {u'mds_safety': 2}, u'backend_info': {u'alba_backend_guid': u'7a9fb6ef-18e0-4d73-9df4-0b29f4ca5fda', u'preset': u'defau
lt'}, u'storagerouter_ip': u'10.100.50.19', u'config_params': {u'dtl_mode': u'sync', u'dtl_transport': u'tcp', u'write_buffer': 512, u'cluster_size': 4, u'sco_size': 4}, u'writecache_size': 5, 'block_cache_on_write': False, u'parallelism'
: {u'proxies':... kwargs:{})
2018-02-06 15:01:18 61000 +0100 - LC1SRV0008 - 14396/140154218919680 - celery/job.py - on_accepted - 398 - DEBUG - Task accepted: ovs.storagerouter.add_vpool[209fe93d-fe55-4202-ad6a-2d73c2518ec4] pid:24575
2018-02-06 15:01:21 40500 +0100 - LC1SRV0008 - 24575/140154218919680 - lib/storagerouter.py - get_metadata - 375 - INFO - Verifying disk partition usage by checking path /dev/disk/by-partlabel/cfd4cb87-793c-44eb-be0d-88403c34caa7
2018-02-06 15:01:21 57800 +0100 - LC1SRV0008 - 24575/140154218919680 - lib/storagerouter.py - get_metadata - 376 - INFO - Verifying disk partition usage by checking path /dev/disk/by-id/dm-uuid-LVM-ETH3IKM36C8c1hxLGtXhtgmXbp1G09XxMztIzly5
t513prxW3qt3kR93mBRGQr95
2018-02-06 15:01:21 71200 +0100 - LC1SRV0008 - 24575/140154218919680 - lib/storagerouter.py - get_metadata - 377 - INFO - Verifying disk partition usage by checking path /dev/disk/by-partlabel/818bb813-fb29-4715-a6d2-334f23d65b1e
2018-02-06 15:01:21 85500 +0100 - LC1SRV0008 - 24575/140154218919680 - lib/storagerouter.py - get_metadata - 378 - INFO - Verifying disk partition usage by checking path /dev/disk/by-id/dm-uuid-LVM-ETH3IKM36C8c1hxLGtXhtgmXbp1G09Xx0oU5PQLH
95k5KZSUIB6i0FdUCYZElAui
2018-02-06 15:01:21 97000 +0100 - LC1SRV0008 - 24575/140154218919680 - lib/storagerouter.py - get_metadata - 379 - INFO - Verifying disk partition usage by checking path /dev/disk/by-path/pci-0000:00:01.1-ata-2-part1
2018-02-06 15:01:22 49000 +0100 - LC1SRV0008 - 24575/140154218919680 - lib/storagerouter.py - get_metadata - 380 - INFO - Verifying disk partition usage by checking path /dev/disk/by-partlabel/770b8f2b-3b9f-49cc-9a87-2777a76d6a99
2018-02-06 15:01:23 93300 +0100 - LC1SRV0008 - 24575/140154218919680 - lib/storagerouter.py - add_vpool - 381 - ERROR - Something went wrong during the validation or modeling of vPool myvpool01 on StorageRouter LC1SRV0009
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 479, in add_vpool
    raise ValueError('Errors validating the specified parameters:\n - {0}'.format('\n - '.join(set(error_messages))))
ValueError: Errors validating the specified parameters:
 - Specified StorageDriver config "write_buffer" with value 512 does not match the value 32
2018-02-06 15:01:23 94800 +0100 - LC1SRV0008 - 24575/140154218919680 - extensions-generic/volatilemutex.py - release - 382 - WARNING - A lock on ovs_lock_add_vpool_partitions_06af1027-3cd7-4e2e-a0a4-8b5aa6c84c4e was kept for 3.45029997826 sec
2018-02-06 15:01:24 05000 +0100 - LC1SRV0008 - 14396/140154218919680 - celery/log.py - log - 399 - ERROR - Task ovs.storagerouter.add_vpool[209fe93d-fe55-4202-ad6a-2d73c2518ec4] raised unexpected: ValueError('Errors validating the specified parameters:\n - Specified StorageDriver config "write_buffer" with value 512 does not match the value 32',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 479, in add_vpool
    raise ValueError('Errors validating the specified parameters:\n - {0}'.format('\n - '.join(set(error_messages))))
ValueError: Errors validating the specified parameters:
 - Specified StorageDriver config "write_buffer" with value 512 does not match the value 32

```

```
2018-02-06 15:19:13 49400 +0100 - LC1SRV00019 - 24106/139933249914624 - workflow-ci_workflow/main.py - _run_with_retry - 191 - WARNING - <bound method Workflow.setup of <ci.main.Workflow object at 0x7f44bd7b34d0>> failed with vPool myvpool01 has failed to create on storagerouter 10.100.50.19 because: Invalid parameters detected
Mandatory param "write_buffer" with value "32" should be in range: 128 - 10240.
Traceback (most recent call last):
  File "setupRunner.py", line 43, in <module>
    Workflow().run()
  File "/opt/OpenvStorage/ci/main.py", line 79, in run
    Workflow._run_with_retry(self.setup, self.config['ci']['setup_retries'])
  File "/opt/OpenvStorage/ci/main.py", line 69, in _run_with_retry
    target(*args, **kwargs)
  File "/opt/OpenvStorage/ci/main.py", line 241, in setup
    VPoolSetup.add_vpool(vpool_name=vpool_name, vpool_details=vpool_details, api=self.api, albabackend_name=albabackends, storagerouter_ip=storagerouter_ip, proxy_amount=proxy_amount)
  File "/opt/OpenvStorage/ci/api_lib/validate/decorators.py", line 227, in validate
    return func(*args, **kwargs)
  File "/opt/OpenvStorage/ci/api_lib/validate/decorators.py", line 56, in validate
    return func(*args, **kwargs)
  File "/opt/OpenvStorage/ci/api_lib/setup/vpool.py", line 123, in add_vpool
    raise RuntimeError(error_msg)
RuntimeError: vPool myvpool01 has failed to create on storagerouter 10.100.50.19 because: Invalid parameters detected
Mandatory param "write_buffer" with value "32" should be in range: 128 - 10240
```

**Comment by sjovdnbos** [comment]
Restriction on the minimal size seems to have been around since september 2015. This restriction seems to be intended.

**Comment by jeroenmaelbrancke** [comment]
@simonOpenV correct about the minimal size but on bighorn-rc-1 i do not see these errors with the setup.json. Only develop throws these errors.
So something has been change in the framework.

Yesterday i tried again with develop and saw that my first vpool was created with 512MB write buffer until i extend the vpool to another node.

The second vpool with only one storagerouter was installed with 128MB...

**Comment by wimpers** [comment]
Can we validate if this is still an issue once @JeffreyDevloo has merged his reconfigure vPool branch

**Comment by JeffreyDevloo** [comment]
@wimpers the branch that I merged does not yet include any of the advanced configuration options. So this issue will still be there
The ticket that would handle this is: https://github.com/openvstorage/framework/issues/1687

**Comment by wimpers** [comment]
To be checked if fixed.
