### ISSUE TITLE
[develop] Update broken

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/framework#1977]
## Issue
Cannot update between develop releases.
2 node cluster, iscsi plugin and manager installed

### initial logging message
```
2018-02-20 16:50:17 00500 +0100 - kvh195-5 - 25504/140279749592832 - update/albaupdate.py - _package_install_plugin_alba - 14 - INFO - Updating packages for ALBA plugin
2018-02-20 16:50:17 02900 +0100 - kvh195-5 - 25504/140279749592832 - update/albaupdate.py - _package_install_plugin_alba - 15 - INFO - Updated packages for ALBA plugin
2018-02-20 16:50:17 02900 +0100 - kvh195-5 - 25504/140279749592832 - update/iscsiupdate.py - _package_install_plugin_iscsi - 16 - INFO - Updating packages for iSCSI plugin
2018-02-20 16:50:17 21300 +0100 - kvh195-5 - 25504/140279749592832 - update/iscsiupdate.py - _package_install_plugin_iscsi - 17 - ERROR - iSCSI Node 10.100.195.1: Failed to update package iscsi-manager
Traceback (most recent call last):
  File "ovs/lib/helpers/..//iscsiupdate.py", line 325, in _package_install_plugin_iscsi
    iscsi_node.client.update_execute(package_name)
  File "ovs/extensions/plugins/iscsimanager.py", line 317, in update_execute
    return self._call(requests.post, 'update/install/{0}'.format(package_name), timeout=300)
  File "ovs/extensions/plugins/iscsimanager.py", line 99, in _call
    raise RuntimeError(error_message)
RuntimeError: signal only works in main thread
2018-02-20 16:50:17 21500 +0100 - kvh195-5 - 25504/140279749592832 - update/update.py - execute_update - 18 - ERROR - Error during update: Installing the packages failed on 1 or more nodes
Traceback (most recent call last):
  File "ovs/lib/update.py", line 643, in execute_update
    raise Exception('Installing the packages failed on 1 or more nodes')
Exception: Installing the packages failed on 1 or more nodes
```

**Comment by sjovdnbos** [comment]
Appeared to be a temporary issue, no problem anymore.
