### ISSUE TITLE
tab completion does not work if not root

### ISSUE THREAD

**Issue by toolslive** [openvstorage/framework#2011]
```
stx@R25U19:~$ ovs monit<tab> Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/generic/configuration.py", line 211, in list
    return cls._list(key, recursive=recursive)
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/generic/configuration.py", line 260, in _list
    recursive=recursive)
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/generic/configuration.py", line 334, in _passthrough
    from ovs_extensions.db.arakoon.configuration import ArakoonConfiguration
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/configuration.py", line 22, in <module>
    from ovs_extensions.db.arakoon.pyrakoon.client import PyrakoonClient
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 49, in <module>
    class PyrakoonClient(object):
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 55, in PyrakoonClient
    _logger = Logger('extensions')
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/log/logger.py", line 99, in __init__
    handler = self.get_handler(forced_target_type=forced_target_type)
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/log/logger.py", line 126, in get_handler
    handler = logging.FileHandler(target_params['filename'])
  File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/var/log/ovs/extensions.log'

```

**Comment by JeffreyDevloo** [comment]
Related to https://github.com/openvstorage/framework/issues/1817

**Comment by wimpers** [comment]
Lot's of work if we need to fix this one
