### ISSUE TITLE
Install Paramiko race vs garbage collection

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/framework#2014]
### Description
New installs now and then result in a paramiko failure. Discussion with @JeffreyDevloo learned that this might be due to sys.exit calls: 
``` 
This might be you had exit the shell before the ssh client exit
This usually happens when you don't close() your ssh connection(s) before the main thread exits 
```

### stacktrace
```
+++++++++++++++++++++++++++
+++  ASD Manager setup  +++
+++++++++++++++++++++++++++
 - Store settings in DB
 - Deploying and starting services
 - Starting watcher service

+++++++++++++++++++++++++++++++++++++
+++  ASD Manager setup completed  +++
+++++++++++++++++++++++++++++++++++++
Exception in thread Thread-15 (most likely raised during interpreter shutdown):
Traceback (most recent call last):Exception in thread Thread-35 (most likely raised during interpreter shutdown):Exception in thread Thread-11 (most likely raised during interpreter shutdown):Exception in thread Thread-23 (most likely raised during interpreter shutdown):

Traceback (most recent call last):
Traceback (most recent call last):  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner


  File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1819, in run
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_innerTraceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1819, in run
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1819, in run

<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
  File "/usr/lib/python2.7/dist-packages/paramiko/transport.py", line 1819, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'

<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'
```

**Comment by wimpers** [comment]
This is a dirty error, doesn't break anything.

**Comment by sjovdnbos** [comment]
### Should be fixed by:
https://github.com/openvstorage/alba-asdmanager/pull/361
