### ISSUE TITLE
[Bighorn]Verify vdisk cache quota job failing

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#2044]
```
May 04 17:15:00 jef-node01 celery[27962]: 2018-05-04 17:15:00 44600 +0200 - jef-node01 - 27962/139776639551232 - celery/log.py - log - 60 - ERROR - Task ovs.monitoring.verify_vdisk_cache_quota[3439440b-fbb2-4a19-b201-d0c9b96347f7] 
May 04 17:15:00 jef-node01 celery[27962]: Traceback (most recent call last):
May 04 17:15:00 jef-node01 celery[27962]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
May 04 17:15:00 jef-node01 celery[27962]:     R = retval = fun(*args, **kwargs)
May 04 17:15:00 jef-node01 celery[27962]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
May 04 17:15:00 jef-node01 celery[27962]:     return self.run(*args, **kwargs)
May 04 17:15:00 jef-node01 celery[27962]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 242, in new_function
May 04 17:15:00 jef-node01 celery[27962]:     output = f(*args, **kwargs)
May 04 17:15:00 jef-node01 celery[27962]:   File "/opt/OpenvStorage/ovs/lib/monitoring.py", line 82, in verify_vdisk_cache_quota
May 04 17:15:00 jef-node01 celery[27962]:     connection_info = cache_type_data.get('backend_info',
```

**Comment by wimpers** [comment]
Somehow related to https://github.com/openvstorage/framework/issues/2025 ?

**Comment by sjovdnbos** [comment]
```May 08 15:15:00 svdb_01 celery[29957]: Traceback (most recent call last):
May 08 15:15:00 svdb_01 celery[29957]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
May 08 15:15:00 svdb_01 celery[29957]:     R = retval = fun(*args, **kwargs)
May 08 15:15:00 svdb_01 celery[29957]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
May 08 15:15:00 svdb_01 celery[29957]:     return self.run(*args, **kwargs)
May 08 15:15:00 svdb_01 celery[29957]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 242, in new_function
May 08 15:15:00 svdb_01 celery[29957]:     output = f(*args, **kwargs)
May 08 15:15:00 svdb_01 celery[29957]:   File "/opt/OpenvStorage/ovs/lib/monitoring.py", line 82, in verify_vdisk_cache_quota
May 08 15:15:00 svdb_01 celery[29957]:     connection_info = cache_type_data.get('backend_info', {}).get('connection_info', None)
May 08 15:15:00 svdb_01 celery[29957]: AttributeError: 'NoneType' object has no attribute 'get'
```
This one is frequently occurring too. 

@wimpers The ticket you mentioned should have been fixed, as Jef labelled it```statecodecomplete```. The errors are related though, indeed.

**Comment by sjovdnbos** [comment]
### Fixed by: 
https://github.com/openvstorage/framework/pull/2046
### Package information:
openvstorage-2.12.0-dev.1525789298.a515378

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.12.0
Packaged in openvstorage-core_2.12.0-1_amd64.deb
