### ISSUE TITLE
Log stack deployment failures of scrubber

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#2068]
```
Jun  3 07:57:51 SV1SRV0001 celery[25871]: 2018-06-03 07:57:51 03500 -0700 - SV1SRV0001 - 25882/139654477113088 - lib/generic tasks scrub - 88 - INFO - Scrubber a4515ce5-63ab-4a6f-bcdb-91124da323e3 - vPool data-sv4-02 - StorageRouter SV1SRV0001 - Stack 0 - Backend config was set up
Jun  3 07:57:51 SV1SRV0001 celery[25871]: 2018-06-03 07:57:51 15700 -0700 - SV1SRV0001 - 25882/139654477113088 - celery/celery.redirected - 89 - WARNING - Exception in thread Thread-39:
Jun  3 07:57:51 SV1SRV0001 celery[25871]: Traceback (most recent call last):
Jun  3 07:57:51 SV1SRV0001 celery[25871]:   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
Jun  3 07:57:51 SV1SRV0001 celery[25871]:     self.run()
Jun  3 07:57:51 SV1SRV0001 celery[25871]:   File "/usr/lib/python2.7/threading.py", line 754, in run
Jun  3 07:57:51 SV1SRV0001 celery[25871]:     self.__target(*self.__args, **self.__kwargs)
Jun  3 07:57:51 SV1SRV0001 celery[25871]:   File "/opt/OpenvStorage/ovs/lib/helpers/generic/scrubber.py", line 435, in deploy_stack_and_scrub
Jun  3 07:57:51 SV1SRV0001 celery[25871]:     amount_threads = Configuration.get(key=threads_key, default=2)
Jun  3 07:57:51 SV1SRV0001 celery[25871]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/generic/configuration.py", line 113, in get
Jun  3 07:57:51 SV1SRV0001 celery[25871]:     temp_data = temp_data[entry]
Jun  3 07:57:51 SV1SRV0001 celery[25871]: TypeError: 'int' object has no attribute '__getitem__'
```
went by unnoticed. Since no stack could be deployed no scrubbing was done. The scrubber exited without any errors.

**Comment by simonOpenV** [comment]
#### Will be fixed by: 
https://github.com/openvstorage/framework/pull/2110

**Comment by sjovdnbos** [comment]
#### Fixed by:
https://github.com/openvstorage/framework/pull/2116
#### Package information:
openvstorage-2.13.0-dev.1531378769.7283a64

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/2.13.0
