### ISSUE TITLE
mds_safety timeout received after errors

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#2112]
# Problem
I ran a manually mds_checkup on Nuvolat and ran into a timeout problem.
Restarting the ovs-workers did the trick to start the mds_checkup again.
After x amount mds checks i see following error messages and mds_checkup stopped with processing the other vdisks. (back to the timeout)

Before restarting the ovs-workers:
```
2018-06-29 05:19:12 54700 -0400 - NY1SRV0001 - 24159/140671605868288 - lib/ensure single - 273 - INFO - Ensure single CHAINED mode - ID 1530263952_0oU9afCDVn - New task ovs.mds.ensure_safety with params {'vdisk_guid': '001326a2-8c1b-4c7f-9023-214451a231b7'} scheduled for execution
2018-06-29 05:24:13 07400 -0400 - NY1SRV0001 - 24159/140671605868288 - lib/ensure single - 274 - ERROR - Ensure single CHAINED mode - ID 1530263952_0oU9afCDVn - Could not start task ovs.mds.ensure_safety with params {'vdisk_guid': '001326a2-8c1b-4c7f-9023-214451a231b7'}, within expected time (300s). Removed it from queue
2018-06-29 05:24:13 07400 -0400 - NY1SRV0001 - 24159/140671605868288 - lib/mds - 275 - ERROR - Ensure safety for vDisk tgt-hprm-test10 with guid 001326a2-8c1b-4c7f-9023-214451a231b7 failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/mdsservice.py", line 410, in mds_checkup
    MDSServiceController.ensure_safety(vdisk_guid=vdisk.guid)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 491, in new_function
    timeout))
EnsureSingleTimeoutReached: Ensure single CHAINED mode - ID 1530263952_0oU9afCDVn - Task ovs.mds.ensure_safety could not be started within timeout of 300s
```

Error after restarting the ovs-workers:
```
2018-06-29 05:49:51 08800 -0400 - NY1SRV0001 - 28998/139845377779456 - lib/mds - 21631 - ERROR - Ensure safety for vDisk pcd_ad07b096-d25f-4c81-9ce0-b054bfdda036 with guid 50bb37a2-52e5-4a1f-810f-11afe7b1b497 failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/mdsservice.py", line 410, in mds_checkup
    MDSServiceController.ensure_safety(vdisk_guid=vdisk.guid)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 469, in new_function
    append=False)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 189, in update_value
    if vals[0] is not None:
IndexError: list index out of range
2018-06-29 05:49:51 53000 -0400 - NY1SRV0001 - 28998/139845377779456 - lib/mds - 21632 - ERROR - Ensure safety for vDisk ARRDSM05-flat_20ff989d-373a-499b-b6f1-d8fa6866ceb2 with guid 50e096c2-abbd-4111-92fe-942d3de50f69 failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/mdsservice.py", line 410, in mds_checkup
    MDSServiceController.ensure_safety(vdisk_guid=vdisk.guid)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 391, in new_function
    append=True)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 188, in update_value
    vals = list(persistent_client.get_multi([key], must_exist=False))
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/storage/persistent/pyrakoonstore.py", line 66, in get_multi
    for item in self._client.get_multi(keys, must_exist=must_exist):
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 86, in get_multi
    keys):
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 214, in _try
    return_value = method(*args, **kwargs)
  File "<update_argspec>", line 5, in multiGetOption
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 160, in wrapped
    return fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 143, in wrapped
    return fun(*new_args)
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 511, in multiGetOption
    return self._client.multi_get_option(keys, consistency = consistency_)
  File "<update_argspec>", line 5, in multi_get_option
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/pyrakoon/client/utils.py", line 99, in wrapped
    return self._process(message) #pylint: disable=W0212
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1125, in _process
    connection.read)
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/pyrakoon/utils.py", line 342, in read_blocking
    value = read_fun(request.count)
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1360, in read
    reads, _, _ = select.select([self._socket], [], [], self._timeout)
error: (4, 'Interrupted system call')
2018-06-29 05:49:51 58300 -0400 - NY1SRV0001 - 28998/139845377779456 - lib/ensure single - 21633 - INFO - Ensure single CHAINED mode - ID 1530265791_FETekoYLzv - New task ovs.mds.ensure_safety with params {'vdisk_guid': '50e2ca0a-4185-4a11-96cf-955c8b3c764d'} scheduled for execution
2018-06-29 05:54:52 10000 -0400 - NY1SRV0001 - 28998/139845377779456 - lib/mds - 21635 - ERROR - Ensure safety for vDisk pcd_774ef4e7-10ae-4509-97ef-1776fc25249f with guid 50e2ca0a-4185-4a11-96cf-955c8b3c764d failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/mdsservice.py", line 410, in mds_checkup
    MDSServiceController.ensure_safety(vdisk_guid=vdisk.guid)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 491, in new_function
    timeout))
EnsureSingleTimeoutReached: Ensure single CHAINED mode - ID 1530265791_FETekoYLzv - Task ovs.mds.ensure_safety could not be started within timeout of 300s
```

# Versions
```
ii  openvstorage                         2.9.14-1                                   amd64        OpenvStorage
ii  openvstorage-backend                 1.9.2-1                                    amd64        OpenvStorage Backend plugin
ii  openvstorage-backend-core            1.9.2-1                                    amd64        OpenvStorage Backend plugin core
ii  openvstorage-backend-webapps         1.9.2-1                                    amd64        OpenvStorage Backend plugin Web Applications
ii  openvstorage-core                    2.9.14-1                                   amd64        OpenvStorage core
ii  openvstorage-extensions              0.1.2-1                                    amd64        Extensions for Open vStorage
ii  openvstorage-health-check            3.4.10-1                                   amd64        Open vStorage HealthCheck
ii  openvstorage-sdm                     1.9.1-1                                    amd64        Open vStorage Backend ASD Manager
ii  openvstorage-webapps                 2.9.14-1                                   amd64        OpenvStorage Web Applications
```

**Comment by JeffreyDevloo** [comment]
Something must have held up the lock.
The EnsureSafetyTimeout is raised when another task with the same parameters is still running.

**Comment by wimpers** [comment]
It is believed a second one was still ongoing. Re-open if it happens again.
