### ISSUE TITLE
[Bighorn] Changing vdisk configuration no longer possible

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#2120]
#### GUI
The GUI no longer registers any changes within the configuration. Unable to save the current layout
#### API
```
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]: 2018-07-12 13:34:45 82900 +0200 - DEV-4N-199-211 - 18314/140480860092160 - celery/job.py - on_accepted - 2026 - DEBUG - Task accepted: ovs.vdisk.set_config_params[f0153da0-db89-4d96-ac2
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]: 2018-07-12 13:34:45 87300 +0200 - DEV-4N-199-211 - 18314/140480860092160 - celery/log.py - log - 2027 - ERROR - Task ovs.vdisk.set_config_params[f0153da0-db89-4d96-ac20-bb4541343dc2] ra
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]: Traceback (most recent call last):
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]:     R = retval = fun(*args, **kwargs)
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]:     return self.run(*args, **kwargs)
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]:   File "/opt/OpenvStorage/ovs/lib/vdisk.py", line 1013, in set_config_params
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]:     old_config_params = VDiskController.get_config_params(vdisk.guid)
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]:   File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]:     return self._get_current_object()(*a, **kw)
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]:     return orig(self, *args, **kwargs)
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]:   File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]:     return self.run(*args, **kwargs)
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]:   File "/opt/OpenvStorage/ovs/lib/vdisk.py", line 962, in get_config_params
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]:     metadata = vpool.metadata['backend']['caching_info'].get(vdisk.storagerouter_guid, {})
Jul 12 13:34:45 DEV-4N-199-211 celery[18314]: KeyError: 'caching_info'
```

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/framework/pull/2122
Packaged in openvstorage-core_2.13.0-dev.1531469136.9a2dda1-1_amd64.deb

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/framework/releases/tag/2.13.0
