### ISSUE TITLE
[Scrubber] Handle exceptions during work generation

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#2147]
Scrubber failed during the work generation loop. This resulted in certain vpools being entirely skipped.
Stack threads that were deployed continued scrubbing and died of when they were done.
Scrubber failed with:
```
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]: 2018-08-10 19:02:22 25700 -0400 - NY2SRV0003 - 29462/140353676519168 - celery/celery.worker.job - 82222 - ERROR - Task ovs.generic.execute_scrub[aea34e77-f22f-4837-a686-e085d55d49aa] raised unexpected: RuntimeError('Network error in client',)
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]: Traceback (most recent call last):
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     R = retval = fun(*args, **kwargs)
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     return self.run(*args, **kwargs)
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 346, in new_function
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     output = f(*args, **kwargs)
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/opt/OpenvStorage/ovs/lib/generic.py", line 214, in execute_scrub
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     return scrubber.execute_scrubbing()
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/opt/OpenvStorage/ovs/lib/helpers/generic/scrubber.py", line 1080, in execute_scrubbing
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     vpool_queue = stack_work_handler.generate_save_scrub_work()
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/opt/OpenvStorage/ovs/lib/helpers/generic/scrubber.py", line 238, in generate_save_scrub_work
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     work_queue = self._generate_save_work()
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/opt/OpenvStorage/ovs/lib/helpers/generic/scrubber.py", line 321, in _generate_save_work
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     self._safely_store(self._key, get_value_and_expected_value=_get_value_and_expected_value, logging_start=self._log)
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/opt/OpenvStorage/ovs/lib/helpers/generic/scrubber.py", line 129, in _safely_store
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     self._persistent.apply_callback_transaction(build_transaction, max_retries=max_retries, retry_wait_function=retry_callback)
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/storage/persistent/pyrakoonstore.py", line 44, in new_function
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     return f(self, *args, **kw)
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/storage/persistent/pyrakoonstore.py", line 204, in apply_callback_transaction
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     return self._client.apply_callback_transaction(transaction_callback, max_retries, retry_wait_function)
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 49, in new_function
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     return f(self, *args, **kw)
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 474, in apply_callback_transaction
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     return apply_callback_transaction(self)
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 86, in wrapped
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     result = f(self, *args, **kwargs)
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/usr/lib/python2.7/dist-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 460, in apply_callback_transaction
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     transaction = transaction_callback()
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/opt/OpenvStorage/ovs/lib/helpers/generic/scrubber.py", line 118, in build_transaction
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     value, expected_value = get_value_and_expected_value()
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/opt/OpenvStorage/ovs/lib/helpers/generic/scrubber.py", line 317, in _get_value_and_expected_value
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     work_queue, total_items, fetched_work_items = self._generate_scrub_work()
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/opt/OpenvStorage/ovs/lib/helpers/generic/scrubber.py", line 261, in _generate_scrub_work
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     if not vd.storagedriver_id:
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 348, in <lambda>
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     fget = lambda s: s._get_dynamic_property(dynamic)
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 417, in _get_dynamic_property
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     return self._backend_property(data_loader, dynamic)
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 1030, in _backend_property
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     dynamic_data = fct()
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:   File "/opt/OpenvStorage/ovs/dal/hybrids/vdisk.py", line 276, in _storagedriver_id
Aug 10 19:02:22 NY2SRV0003 ovs-workers[29462]:     vdisk_object = self.objectregistry
```

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/framework/pull/2159
Packaged in openvstorage-core_2.9.20-1_amd64.deb
Released in https://github.com/openvstorage/framework/releases/tag/2.9.20
