### ISSUE TITLE
alba/asd nodes can't show up 

### ISSUE THREAD

**Issue by yongshengma** [openvstorage/framework#2180]
ASD nodes can't show up in backend detail page.  Some errors on two nodes:

```
Sep  5 09:52:15 test-1 gunicorn: 2018-09-05 03:52:15 81600 +0200 - test-1 - 33468/140440024714448 - api/middleware.py - process_exception - 1955 - ERROR - An unhandled exception occurred: Invalid control character at: line 1 column 163 (char 162)
Sep  5 09:52:15 test-1 gunicorn: Traceback (most recent call last):
Sep  5 09:52:15 test-1 gunicorn: File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
Sep  5 09:52:15 test-1 gunicorn: response = wrapped_callback(request, *callback_args, **callback_kwargs)
Sep  5 09:52:15 test-1 gunicorn: File "/usr/lib/python2.7/site-packages/rest_framework/viewsets.py", line 78, in view
Sep  5 09:52:15 test-1 gunicorn: return self.dispatch(request, *args, **kwargs)
Sep  5 09:52:15 test-1 gunicorn: File "/usr/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
Sep  5 09:52:15 test-1 gunicorn: return view_func(*args, **kwargs)
Sep  5 09:52:15 test-1 gunicorn: File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 399, in dispatch
Sep  5 09:52:15 test-1 gunicorn: response = self.handle_exception(exc)
Sep  5 09:52:15 test-1 gunicorn: File "/usr/lib/python2.7/site-packages/rest_framework/views.py", line 396, in dispatch
Sep  5 09:52:15 test-1 gunicorn: response = handler(request, *args, **kwargs)
Sep  5 09:52:15 test-1 gunicorn: File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 591, in new_function
Sep  5 09:52:15 test-1 gunicorn: return_value = f(*args, **kwargs)
Sep  5 09:52:15 test-1 gunicorn: File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 87, in new_function
Sep  5 09:52:15 test-1 gunicorn: result = f(*args, **kw)
Sep  5 09:52:15 test-1 gunicorn: File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 337, in new_function
Sep  5 09:52:15 test-1 gunicorn: data = FullSerializer(object_type, contents=contents, instance=data_list, many=True).data
Sep  5 09:52:15 test-1 gunicorn: File "/usr/lib/python2.7/site-packages/rest_framework/serializers.py", line 571, in data
Sep  5 09:52:15 test-1 gunicorn: self._data = [self.to_native(item) for item in obj]
Sep  5 09:52:15 test-1 gunicorn: File "/usr/lib/python2.7/site-packages/rest_framework/serializers.py", line 349, in to_native
Sep  5 09:52:15 test-1 gunicorn: value = field.field_to_native(obj, field_name)
Sep  5 09:52:15 test-1 gunicorn: File "/usr/lib/python2.7/site-packages/rest_framework/fields.py", line 198, in field_to_native
Sep  5 09:52:15 test-1 gunicorn: value = get_component(value, component)
Sep  5 09:52:15 test-1 gunicorn: File "/usr/lib/python2.7/site-packages/rest_framework/fields.py", line 56, in get_component
Sep  5 09:52:15 test-1 gunicorn: val = getattr(obj, attr_name)
Sep  5 09:52:15 test-1 gunicorn: File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 349, in <lambda>
Sep  5 09:52:15 test-1 gunicorn: fget = lambda s: s._get_dynamic_property(dynamic)
Sep  5 09:52:15 test-1 gunicorn: File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 418, in _get_dynamic_property
Sep  5 09:52:15 test-1 gunicorn: return self._backend_property(data_loader, dynamic)
Sep  5 09:52:15 test-1 gunicorn: File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 1031, in _backend_property
Sep  5 09:52:15 test-1 gunicorn: dynamic_data = fct()
Sep  5 09:52:15 test-1 gunicorn: File "/opt/OpenvStorage/ovs/dal/hybrids/albanode.py", line 279, in _local_summary
Sep  5 09:52:15 test-1 gunicorn: for slot_id, slot_data in self.stack.iteritems():
Sep  5 09:52:15 test-1 gunicorn: File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 349, in <lambda>
Sep  5 09:52:15 test-1 gunicorn: fget = lambda s: s._get_dynamic_property(dynamic)
Sep  5 09:52:15 test-1 gunicorn: File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 418, in _get_dynamic_property
Sep  5 09:52:15 test-1 gunicorn: return self._backend_property(data_loader, dynamic)
Sep  5 09:52:15 test-1 gunicorn: File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 1031, in _backend_property
Sep  5 09:52:15 test-1 gunicorn: dynamic_data = fct()
Sep  5 09:52:15 test-1 gunicorn: File "/opt/OpenvStorage/ovs/dal/hybrids/albanode.py", line 128, in _stack
Sep  5 09:52:15 test-1 gunicorn: remote_stack = self.client.get_stack()
Sep  5 09:52:15 test-1 gunicorn: File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 129, in get_stack
Sep  5 09:52:15 test-1 gunicorn: data = self._call(requests.get, 'slots', timeout=5, clean=True)
Sep  5 09:52:15 test-1 gunicorn: File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 100, in _call
Sep  5 09:52:15 test-1 gunicorn: raise RuntimeError(error_message)
Sep  5 09:52:15 test-1 gunicorn: RuntimeError: Invalid control character at: line 1 column 163 (char 162)

```

```
Sep 05 10:40:16 test-3 python[34261]: Traceback (most recent call last):
Sep 05 10:40:16 test-3 python[34261]: File "/usr/lib/python2.7/site-packages/ovs_extensions/api/decorators.py", line 110, in new_functi
Sep 05 10:40:16 test-3 python[34261]: return_data = f(*args, **kwargs)
Sep 05 10:40:16 test-3 python[34261]: File "/opt/asd-manager/source/app/api.py", line 122, in get_slots
Sep 05 10:40:16 test-3 python[34261]: for disk in DiskList.get_usable_disks():
Sep 05 10:40:16 test-3 python[34261]: File "/opt/asd-manager/source/dal/lists/disklist.py", line 50, in get_usable_disks
Sep 05 10:40:16 test-3 python[34261]: for disk in DiskList.get_disks():
Sep 05 10:40:16 test-3 python[34261]: File "/opt/asd-manager/source/dal/lists/disklist.py", line 42, in get_disks
Sep 05 10:40:16 test-3 python[34261]: return DataList.query(Disk, "SELECT id FROM {table}")
Sep 05 10:40:16 test-3 python[34261]: File "/usr/lib/python2.7/site-packages/ovs_extensions/dal/datalist.py", line 62, in query
Sep 05 10:40:16 test-3 python[34261]: entries.append(object_type(row[0], locked=False))
Sep 05 10:40:16 test-3 python[34261]: File "/usr/lib/python2.7/site-packages/ovs_extensions/dal/base.py", line 67, in __init__
Sep 05 10:40:16 test-3 python[34261]: setattr(self, prop.name, Base._deserialize(prop.property_type, row[prop.name]))
Sep 05 10:40:16 test-3 python[34261]: File "/usr/lib/python2.7/site-packages/ovs_extensions/dal/base.py", line 197, in _deserialize
Sep 05 10:40:16 test-3 python[34261]: return json.loads(data) if data is not None else None
Sep 05 10:40:16 test-3 python[34261]: File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
Sep 05 10:40:16 test-3 python[34261]: return _default_decoder.decode(s)
Sep 05 10:40:16 test-3 python[34261]: File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
Sep 05 10:40:16 test-3 python[34261]: obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Sep 05 10:40:16 test-3 python[34261]: File "/usr/lib64/python2.7/json/decoder.py", line 381, in raw_decode
Sep 05 10:40:16 test-3 python[34261]: try:
Sep 05 10:40:16 test-3 python[34261]: ValueError: Invalid control character at: line 1 column 163 (char 162)


```

**Comment by JeffreyDevloo** [comment]
Hi @yongshengma 
My guess is that a control character slipped in either the 'partitions' or 'aliases' property of a disk on the ASD-Manager. (Either a `\n` or `\r` slipped in somewhere)
Could you provide me the output of `'lsblk' '--pairs' '--bytes' '--noheadings' '--exclude' '1,2,11' --output=KNAME,SIZE,MODEL,STATE,MAJ:MIN,FSTYPE,TYPE,ROTA,MOUNTPOINT,LOG-SEC,SERIAL` on that host?

As a work around: adjust the code within the `/usr/lib/python2.7/site-packages/ovs_extensions/dal/base.py` line 197 to json.loads(data, strict=False)
After applying this work-around: please provide the data in the disklist using the following code:
`ipython` to open the shell
```
import sys
sys.path.append('/opt/asd-manager/')
from source.dal.lists.disklist import DiskList
for disk in DiskList.get_disks():
     print disk.export()
```

**Comment by yongshengma** [comment]
Hi @JeffreyDevloo 

```
[root@test-3 ~]# 'lsblk' '--pairs' '--bytes' '--noheadings' '--exclude' '1,2,11' --output=KNAME,SIZE,MODEL,STATE,MAJ:MIN,FSTYPE,TYPE,ROTA,MOUNTPOINT,LOG-SEC,SERIAL
KNAME="sda" SIZE="238999830528" MODEL="MR9260-8i       " STATE="running" MAJ:MIN="8:0" FSTYPE="" TYPE="disk" ROTA="1" MOUNTPOINT="" LOG-SEC="512" SERIAL="600605b00a501a2022fab9a8210639e2"
KNAME="sda1" SIZE="238997733376" MODEL="" STATE="" MAJ:MIN="8:1" FSTYPE="ext4" TYPE="part" ROTA="1" MOUNTPOINT="/mnt/hdd1" LOG-SEC="512" SERIAL=""
KNAME="sdb" SIZE="238999830528" MODEL="MR9260-8i       " STATE="running" MAJ:MIN="8:16" FSTYPE="" TYPE="disk" ROTA="1" MOUNTPOINT="" LOG-SEC="512" SERIAL="600605b00a501a2022fab9a8210685d6"
KNAME="sdc" SIZE="3999999721472" MODEL="MR9260-8i       " STATE="running" MAJ:MIN="8:32" FSTYPE="" TYPE="disk" ROTA="1" MOUNTPOINT="" LOG-SEC="512" SERIAL="600605b00a501a2022fab9a82106cfef"
KNAME="sdc1" SIZE="1048576" MODEL="" STATE="" MAJ:MIN="8:33" FSTYPE="" TYPE="part" ROTA="1" MOUNTPOINT="" LOG-SEC="512" SERIAL=""
KNAME="sdc2" SIZE="1073741824" MODEL="" STATE="" MAJ:MIN="8:34" FSTYPE="xfs" TYPE="part" ROTA="1" MOUNTPOINT="/boot" LOG-SEC="512" SERIAL=""
KNAME="sdc3" SIZE="3998922833920" MODEL="" STATE="" MAJ:MIN="8:35" FSTYPE="LVM2_member" TYPE="part" ROTA="1" MOUNTPOINT="" LOG-SEC="512" SERIAL=""
KNAME="dm-0" SIZE="3983888351232" MODEL="" STATE="running" MAJ:MIN="253:0" FSTYPE="xfs" TYPE="lvm" ROTA="1" MOUNTPOINT="/" LOG-SEC="512" SERIAL=""
KNAME="dm-1" SIZE="4294967296" MODEL="" STATE="running" MAJ:MIN="253:1" FSTYPE="swap" TYPE="lvm" ROTA="1" MOUNTPOINT="[SWAP]" LOG-SEC="512" SERIAL=""
KNAME="dm-2" SIZE="10737418240" MODEL="" STATE="running" MAJ:MIN="253:2" FSTYPE="xfs" TYPE="lvm" ROTA="1" MOUNTPOINT="/home" LOG-SEC="512" SERIAL=""
KNAME="sdd" SIZE="3999999721472" MODEL="MR9260-8i       " STATE="running" MAJ:MIN="8:48" FSTYPE="" TYPE="disk" ROTA="1" MOUNTPOINT="" LOG-SEC="512" SERIAL="600605b00a501a2022fab9a82107199c"
KNAME="sdd1" SIZE="3999996575744" MODEL="" STATE="" MAJ:MIN="8:49" FSTYPE="xfs" TYPE="part" ROTA="1" MOUNTPOINT="/mnt/alba-asd/4M2p74SfRQb5L1xl" LOG-SEC="512" SERIAL=""
KNAME="sde" SIZE="3999999721472" MODEL="MR9260-8i       " STATE="running" MAJ:MIN="8:64" FSTYPE="" TYPE="disk" ROTA="1" MOUNTPOINT="" LOG-SEC="512" SERIAL="600605b00a501a2022fab9a821076368"
KNAME="sde1" SIZE="3999996575744" MODEL="" STATE="" MAJ:MIN="8:65" FSTYPE="xfs" TYPE="part" ROTA="1" MOUNTPOINT="/mnt/alba-asd/NzZBMFeAhDnw6vtQ" LOG-SEC="512" SERIAL=""

```

After modification to json.loads(data, strict=False),

```
In [1]: import sys

In [2]: sys.path.append('/opt/asd-manager/')

In [3]: from source.dal.lists.disklist import DiskList

In [4]: for disk in DiskList.get_disks():
   ...:          print disk.export()
   ...:     
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-e176b6bf6f6f> in <module>()
----> 1 for disk in DiskList.get_disks():
      2          print disk.export()
      3 

/opt/asd-manager/source/dal/lists/disklist.pyc in get_disks()
     40         Returns a list of all Disks
     41         """
---> 42         return DataList.query(Disk, "SELECT id FROM {table}")
     43 
     44     @staticmethod

/usr/lib/python2.7/site-packages/ovs_extensions/dal/datalist.pyc in query(object_type, query, parameters)
     60             result = cursor.execute(query, parameters)
     61             for row in result.fetchall():
---> 62                 entries.append(object_type(row[0], locked=False))
     63         return entries

/usr/lib/python2.7/site-packages/ovs_extensions/dal/base.py in __init__(self, identifier, locked)
     65                         raise ObjectNotFoundException()
     66                     for prop in self._properties:
---> 67                         setattr(self, prop.name, Base._deserialize(prop.property_type, row[prop.name]))
     68                     for relation in self._relations:
     69                         setattr(self, '_{0}'.format(relation[0]), {'id': row['_{0}_id'.format(relation[0])],

/usr/lib/python2.7/site-packages/ovs_extensions/dal/base.py in _deserialize(prop_type, data)
    195             return data
    196         if prop_type in [list, dict, None]:
--> 197             return json.loads(data, strict=False) if data is not None else None
    198         if prop_type in [bool]:
    199             return data == 1

/usr/lib64/python2.7/json/__init__.pyc in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    349     if parse_constant is not None:
    350         kw['parse_constant'] = parse_constant
--> 351     return cls(encoding=encoding, **kw).decode(s)

/usr/lib64/python2.7/json/decoder.pyc in decode(self, s, _w)
    364 
    365         """
--> 366         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    367         end = _w(s, end).end()
    368         if end != len(s):

/usr/lib64/python2.7/json/decoder.pyc in raw_decode(self, s, idx)
    380         """
    381         try:
--> 382             obj, end = self.scan_once(s, idx)
    383         except StopIteration:
    384             raise ValueError("No JSON object could be decoded")

ValueError: Unterminated string starting at: line 1 column 118 (char 117)

```

**Comment by JeffreyDevloo** [comment]
Hi @yongshengma 

Looks like the aliases might be corrupt as I found no issue when parsing the `lsblk` output.
To help us understand where it might have gone wrong: please provide the output of the following snippet:
```
from ovs_extensions.generic.sshclient import SSHClient
local_client = SSHClient('127.0.0.1', username='root')
name_alias_mapping = {}
alias_name_mapping = {}
for path_type in local_client.dir_list(directory='/dev/disk'):
    if path_type in ['by-uuid', 'by-partuuid']:  # UUIDs can change after creating a filesystem on a partition
        continue
    directory = '/dev/disk/{0}'.format(path_type)
    for symlink in local_client.dir_list(directory=directory):
        symlink_path = '{0}/{1}'.format(directory, symlink)
        link = local_client.file_read_link(path=symlink_path)
        if link not in name_alias_mapping:
            name_alias_mapping[link] = []
        name_alias_mapping[link].append(symlink_path)
        alias_name_mapping[symlink_path] = link
print name_alias_mapping
```

To recover from this, you will need to wipe your database of these corrupt disk entries.
If you do not have any asds, you can reinstall the asd-manager using: `asd-manager remove`
If you do have asds on this node, use the following script:
```
import json
from source.dal.objects.asd import ASD
from source.dal.lists.asdlist import ASDList
from source.dal.lists.disklist import DiskList
from source.controllers.disk import DiskController

#  Retrieve all ASDs and wipe their disk relation:
old_relation = {}  # This will be required to hook up the relation afterwards
for asd in ASDList.get_asds():
    old_relation[str(asd.id)] = {'name': asd.disk.name, 'serial': asd.disk.serial}
    asd.disk = None
    asd.save()
for disk in DiskList.get_disks():
    disk.delete()
# Write the relation to a file just in case
with open('/tmp/asd_relation.json', 'w') as relation_file:
    relation_file.write(json.dumps(old_relation))
print old_relation

# Sync disks to fill up the database
DiskController.sync_disks()
# Validate that the error no longer happens
disks = DiskList.get_disks()
disks_by_serial = dict((disk.serial, disk) for disk in disks)
for stringified_asd_id, disk_data in old_relation.iteritems():
    asd = ASD(int(stringified_asd_id))
    serial = disk_data['serial']
    disk = disks_by_serial.get(serial)
    if disk:
        asd.disk = disk
        asd.save()
    else:
        print 'No associated disk for ASD with ID {}'.format(asd.id)
```
Best regards

**Comment by yongshengma** [comment]
Hi @JeffreyDevloo 

All ASDs of all 3 nodes can not be displayed, but i find that ASDs of the other 2 nodes' can be displayed if this problem node 'test-3' is shutdown. 

Ran on node 'test-3',

```
In [1]: from ovs_extensions.generic.sshclient import SSHClient

In [2]: local_client = SSHClient('127.0.0.1', username='root')

In [3]: name_alias_mapping = {}

In [4]: alias_name_mapping = {}

In [5]: for path_type in local_client.dir_list(directory='/dev/disk'):
   ...:     if path_type in ['by-uuid', 'by-partuuid']: 
   ...:         continue
   ...:     directory = '/dev/disk/{0}'.format(path_type)
   ...:     for symlink in local_client.dir_list(directory=directory):
   ...:         symlink_path = '{0}/{1}'.format(directory, symlink)
   ...:         link = local_client.file_read_link(path=symlink_path)
   ...:         if link not in name_alias_mapping:
   ...:             name_alias_mapping[link] = []
   ...:         name_alias_mapping[link].append(symlink_path)
   ...:         alias_name_mapping[symlink_path] = link
   ...: print name_alias_mapping
   ...: 
{'/dev/sde1': ['/dev/disk/by-partlabel/scsi-3600605b00a501a2022fab9a8210763', '/dev/disk/by-path/pci-0000:02:00.0-scsi-0:2:4:0-part1', '/dev/disk/by-id/wwn-0x600605b00a501a2022fab9a821076368-part1', '/dev/disk/by-id/scsi-3600605b00a501a2022fab9a821076368-part1'], '/dev/sdc2': ['/dev/disk/by-path/pci-0000:02:00.0-scsi-0:2:2:0-part2', '/dev/disk/by-id/wwn-0x600605b00a501a2022fab9a82106cfef-part2', '/dev/disk/by-id/scsi-3600605b00a501a2022fab9a82106cfef-part2'], '/dev/sdc3': ['/dev/disk/by-path/pci-0000:02:00.0-scsi-0:2:2:0-part3', '/dev/disk/by-id/wwn-0x600605b00a501a2022fab9a82106cfef-part3', '/dev/disk/by-id/scsi-3600605b00a501a2022fab9a82106cfef-part3', '/dev/disk/by-id/lvm-pv-uuid-azs0CI-dxTv-OmbQ-Akqh-CrYZ-gZi0-xFpUJg'], '/dev/sdc1': ['/dev/disk/by-path/pci-0000:02:00.0-scsi-0:2:2:0-part1', '/dev/disk/by-id/wwn-0x600605b00a501a2022fab9a82106cfef-part1', '/dev/disk/by-id/scsi-3600605b00a501a2022fab9a82106cfef-part1'], '/dev/dm-2': ['/dev/disk/by-id/dm-uuid-LVM-3H2Q6RQ56xTd6oan5NeS5FHqMsJyoZucnUiu897BsY1jbHLYYFQ4SDBBF8WV22hp', '/dev/disk/by-id/dm-name-ovstest-home'], '/dev/sdd1': ['/dev/disk/by-partlabel/scsi-3600605b00a501a2022fab9a8210719', '/dev/disk/by-path/pci-0000:02:00.0-scsi-0:2:3:0-part1', '/dev/disk/by-id/wwn-0x600605b00a501a2022fab9a82107199c-part1', '/dev/disk/by-id/scsi-3600605b00a501a2022fab9a82107199c-part1'], '/dev/sdc': ['/dev/disk/by-path/pci-0000:02:00.0-scsi-0:2:2:0', '/dev/disk/by-id/wwn-0x600605b00a501a2022fab9a82106cfef', '/dev/disk/by-id/scsi-3600605b00a501a2022fab9a82106cfef'], '/dev/dm-0': ['/dev/disk/by-id/dm-uuid-LVM-3H2Q6RQ56xTd6oan5NeS5FHqMsJyoZuc2o9gHiVettWDXQzA0kRMcGi3T08Jh0D8', '/dev/disk/by-id/dm-name-ovstest-root'], '/dev/dm-1': ['/dev/disk/by-id/dm-uuid-LVM-3H2Q6RQ56xTd6oan5NeS5FHqMsJyoZucdG8NogdxbluRVJnDsrjiG4XKQfzLi9Xs', '/dev/disk/by-id/dm-name-ovstest-swap'], '/dev/sdd': ['/dev/disk/by-path/pci-0000:02:00.0-scsi-0:2:3:0', '/dev/disk/by-id/wwn-0x600605b00a501a2022fab9a82107199c', '/dev/disk/by-id/scsi-3600605b00a501a2022fab9a82107199c'], '/dev/sde': ['/dev/disk/by-path/pci-0000:02:00.0-scsi-0:2:4:0', '/dev/disk/by-id/wwn-0x600605b00a501a2022fab9a821076368', '/dev/disk/by-id/scsi-3600605b00a501a2022fab9a821076368'], '/dev/sdb': ['/dev/disk/by-path/pci-0000:02:00.0-scsi-0:2:1:0', '/dev/disk/by-id/wwn-0x600605b00a501a2022fab9a8210685d6', '/dev/disk/by-id/scsi-3600605b00a501a2022fab9a8210685d6'], '/dev/sda1': ['/dev/disk/by-partlabel/6a0a289c-4f5f-4861-a861-37ca3c1a8221', '/dev/disk/by-path/pci-0000:02:00.0-scsi-0:2:0:0-part1', '/dev/disk/by-id/wwn-0x600605b00a501a2022fab9a8210639e2-part1', '/dev/disk/by-id/scsi-3600605b00a501a2022fab9a8210639e2-part1'], '/dev/sda': ['/dev/disk/by-path/pci-0000:02:00.0-scsi-0:2:0:0', '/dev/disk/by-id/wwn-0x600605b00a501a2022fab9a8210639e2', '/dev/disk/by-id/scsi-3600605b00a501a2022fab9a8210639e2']}

In [6]: 

```

**Comment by JeffreyDevloo** [comment]
Hi @yongshengma 
I feel like the DB has corrupt entries. Both outputs looks fine... Have you tried the steps that I provided above on 'test-3'?

**Comment by yongshengma** [comment]
Could be corrupted as a weird network issue occurred, although not sure if they're related,  We just didn't know why 'test-3' lost network with any other nodes.  it resumed ok after rebooted.

**Comment by yongshengma** [comment]
I tried the steps that you provided above on 'test-3'.  It works.  ASDs show up.  Thanks!

**Comment by JeffreyDevloo** [comment]
Hi @yongshengma 
Not sure what caused the corruption but I'm glad that it got resolved :)
