### ISSUE TITLE
Could not determine the Arakoon master node

### ISSUE THREAD

**Issue by yongshengma** [openvstorage/framework#2199]
I shutdown all 3 nodes in an order of Node-3, Node-2 and then Node-1.  Then I powered on them in a reverse order with Node-1 as the first.  However I find ovs services can't start up on this host.  

```
Running processes
=================

ovs-arakoon-config           active  1883
ovs-support-agent            active  28981
ovs-vswitchd                 active  1389


Non-running processes
=====================

ovs-albaproxy_pool-1_0       activating
ovs-arakoon-mybackend-abm    activating
ovs-arakoon-mybackend-nsm_0  activating
ovs-arakoon-ovsdb            activating
ovs-arakoon-voldrv           activating
ovs-dtl_pool-1               inactive
ovs-scheduled-tasks          inactive
ovs-volumedriver_pool-1      inactive
ovs-volumerouter-consumer    inactive
ovs-watcher-config           activating
ovs-watcher-framework        activating
ovs-watcher-volumedriver     activating
ovs-webapp-api               inactive
ovs-workers                  inactive

```

```
Sep 26 10:02:43 Node-1 python: Traceback (most recent call last):
Sep 26 10:02:43 Node-1 python: File "/opt/OpenvStorage/ovs/extensions/generic/watcher.py", line 204, in <module>
Sep 26 10:02:43 Node-1 python: watcher = Watcher()
Sep 26 10:02:43 Node-1 python: File "/opt/OpenvStorage/ovs/extensions/generic/watcher.py", line 42, in __init__
Sep 26 10:02:43 Node-1 python: self._logger = Logger('extensions-generic')
Sep 26 10:02:43 Node-1 python: File "/opt/OpenvStorage/ovs/extensions/generic/logger.py", line 35, in __init__
Sep 26 10:02:43 Node-1 python: super(Logger, self).__init__(name, forced_target_type)
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/log/logger.py", line 99, in __init__
Sep 26 10:02:43 Node-1 python: handler = self.get_handler(forced_target_type=forced_target_type)
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/log/logger.py", line 120, in get_handler
Sep 26 10:02:43 Node-1 python: target_params = self._load_target_parameters(source=self.name, forced_target_type=forced_target_type, allow_override=True)
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/log/logger.py", line 216, in _load_target_parameters
Sep 26 10:02:43 Node-1 python: log_info = cls.get_logging_info()
Sep 26 10:02:43 Node-1 python: File "/opt/OpenvStorage/ovs/extensions/generic/logger.py", line 45, in get_logging_info
Sep 26 10:02:43 Node-1 python: return Configuration.get('/ovs/framework/logging')
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/generic/configuration.py", line 107, in get
Sep 26 10:02:43 Node-1 python: data = cls._get(key_entries[0], raw, **kwargs)
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/generic/configuration.py", line 303, in _get
Sep 26 10:02:43 Node-1 python: **kwargs)
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/generic/configuration.py", line 341, in _passthrough
Sep 26 10:02:43 Node-1 python: return getattr(instance, method)(*args, **kwargs)
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/db/arakoon/configuration.py", line 132, in get
Sep 26 10:02:43 Node-1 python: return client.get(key, **kwargs)
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 44, in new_function
Sep 26 10:02:43 Node-1 python: return f(self, *args, **kw)
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 76, in get
Sep 26 10:02:43 Node-1 python: return PyrakoonClient._try(self._identifier, self._client.get, key, consistency)
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/db/arakoon/pyrakoon/client.py", line 213, in _try
Sep 26 10:02:43 Node-1 python: return_value = method(*args, **kwargs)
Sep 26 10:02:43 Node-1 python: File "<update_argspec>", line 5, in get
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 160, in wrapped
Sep 26 10:02:43 Node-1 python: return fun(*args, **kwargs)
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 143, in wrapped
Sep 26 10:02:43 Node-1 python: return fun(*new_args)
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 265, in get
Sep 26 10:02:43 Node-1 python: return self._client.get(key,consistency = consistency_)
Sep 26 10:02:43 Node-1 python: File "<update_argspec>", line 5, in get
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/db/arakoon/pyrakoon/pyrakoon/client/utils.py", line 99, in wrapped
Sep 26 10:02:43 Node-1 python: return self._process(message) #pylint: disable=W0212
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1121, in _process
Sep 26 10:02:43 Node-1 python: connection = self._send_to_master(bytes_)
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1180, in _send_to_master
Sep 26 10:02:43 Node-1 python: self.determine_master()
Sep 26 10:02:43 Node-1 python: File "/usr/lib/python2.7/site-packages/ovs_extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 1223, in determine_master
Sep 26 10:02:43 Node-1 python: raise ArakoonNoMaster
Sep 26 10:02:43 Node-1 python: ovs_extensions.db.arakoon.pyrakoon.pyrakoon.compat.ArakoonNoMaster: Could not determine the Arakoon master node

```

Ovs services on the first host were not able to start up until I powered on the other 2 nodes.  It seems arakoon master node is on the 2nd or 3rd host.  

How can I check arakoon node status, such as master or slave, on each host?  and when the status can be switched? Maybe the host with arakoon master should be shutdown as the last and powered on as the first?

**Comment by toolslive** [comment]
first you can check if the arakoon processes are running using pgrep
```
$ pgrep -a arakoon
15779  /usr/bin/arakoon --node 54JvUoNRaeDhqqD3 -config arakoon://config/ovs/arakoon/ny1-hddbackend03-abm/config?ini=%2Fmnt%2Fssd1%2Farakoon%2Fexternal_arakoon_cacc.ini -autofix -start
...
```
then you can check the master with
```
$ arakoon --who-master -config <config>
hVEIul3TXTpCAWwg
```
There's also the possibility of inspecting the statistics:
```
arakoon --statistics -config <config>
{start: 1537959108.919052, last: 1537959108.919053,
avg_set_size: 0.000000,
avg_get_size: 0.000000,
avg_range_size: 0.000000,
avg_range_entries_size: 0.000000,
avg_rev_range_entries_size: 0.000000,
avg_prefix_size: 0.000000,
avg_del_prefix_size: 0.000000,
harvest_stats: (n:52 min: 1., max: 1., avg: 1., dev: n/a),
set_info: (n:0 min: n/a, max: n/a, avg: n/a, dev: n/a),
get_info: (n:0 min: n/a, max: n/a, avg: n/a, dev: n/a),
del_info: (n:0 min: n/a, max: n/a, avg: n/a, dev: n/a),
mget_info: (n:0 min: n/a, max: n/a, avg: n/a, dev: n/a),
mget_option_info: (n:0 min: n/a, max: n/a, avg: n/a, dev: n/a)
seq_info: (n:0 min: n/a, max: n/a, avg: n/a, dev: n/a),
tas_info: (n:0 min: n/a, max: n/a, avg: n/a, dev: n/a),
replace_info: (n:0 min: n/a, max: n/a, avg: n/a, dev: n/a),
range_info: (n:0 min: n/a, max: n/a, avg: n/a, dev: n/a),
range_entries_info: (n:0 min: n/a, max: n/a, avg: n/a, dev: n/a),
rev_range_entries_info: (n:0 min: n/a, max: n/a, avg: n/a, dev: n/a),
prefix_info: (n:0 min: n/a, max: n/a, avg: n/a, dev: n/a),
delete_prefix_info: (n:0 min: n/a, max: n/a, avg: n/a, dev: n/a),
ops_info: (n:0 min: n/a, max: n/a, avg: n/a, dev: n/a),
mem_allocated: 39173164559.671875 KB,
mem_maxrss: 5421464 KB,
mem_minor_collections: 917683,
mem_major_collections: 234992,
mem_compactions: 78345,
node_is: (FLM4OmtPuCivo528,158751182)(hVEIul3TXTpCAWwg,158751182)(54JvUoNRaeDhqqD3,158751182)(wZ4GAcmR2MZl5x7S,158751182)(N0RCG4vXgbP0w8LQ,158751182)}
```
the last line shows, for each node in the arakoon cluster, the I counter. Some nodes may be lagging.

**Comment by yongshengma** [comment]
It helps! Thanks!
