### ISSUE TITLE
[Develop] ClusterNotReachableException not shown in GUI

### ISSUE THREAD

**Issue by sjovdnbos** [openvstorage/framework#2211]
### Problem
When trying to make a vDisk on current develop, voldrv could not be reached. The Gui showed however:
![screenshot from 2018-10-29 09-51-19](https://user-images.githubusercontent.com/33058909/47638911-3eb20e80-db60-11e8-84da-766fd2adb4ad.png)

### Logging:
```Oct 29 09:35:55 svdb_01 ovs-workers[21002]: Traceback (most recent call last):
Oct 29 09:35:55 svdb_01 ovs-workers[21002]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
Oct 29 09:35:55 svdb_01 ovs-workers[21002]:     R = retval = fun(*args, **kwargs)
Oct 29 09:35:55 svdb_01 ovs-workers[21002]:   File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
Oct 29 09:35:55 svdb_01 ovs-workers[21002]:     return self.run(*args, **kwargs)
Oct 29 09:35:55 svdb_01 ovs-workers[21002]:   File "/opt/OpenvStorage/ovs/lib/vdisk.py", line 897, in create_new
Oct 29 09:35:55 svdb_01 ovs-workers[21002]:     req_timeout_secs=Configuration.get('ovs/volumedriver/timeouts|create_volume', default=30))
Oct 29 09:35:55 svdb_01 ovs-workers[21002]: ClusterNotReachableException:
```

This ticket is to tackle that the error handling should be shown in the GUI

**Comment by sjovdnbos** [comment]
#### Fixed by:
https://github.com/openvstorage/framework/pull/2217
 #### Package information:
openvstorage-webapps_2.13.4-dev.1542299609.9f2a9b3-1_amd64.deb
