### ISSUE TITLE
Stream has been closed - during scrubbing

### ISSUE THREAD

**Issue by jtorreke** [openvstorage/framework#2233]
As I've got no clue on how to start this, I'll park it here for future analysis. 

```
2018-12-25 16:59:39 08300 -0500 - NY1SRV0002 - 26454/140643737270016 - lib/generic tasks scrub - 1891 - INFO - Scrubber f36bf1f6-7a7e-405c-8efe-30d42337d714 - vPool data-ny1-07 - Unregister vDisk e138ba61-5c97-4f4e-a37e-e5cb02d542e6
2018-12-25 16:59:39 08500 -0500 - NY1SRV0002 - 26454/140643737270016 - lib/generic tasks scrub - 1892 - INFO - Scrubber f36bf1f6-7a7e-405c-8efe-30d42337d714 - vPool data-ny1-07 - Successfully unregistered vDisk e138ba61-5c97-4f4e-a37e-e5cb02d542e6
2018-12-25 16:59:39 08600 -0500 - NY1SRV0002 - 26454/140643695306496 - lib/generic tasks scrub - 1893 - INFO - Scrubber f36bf1f6-7a7e-405c-8efe-30d42337d714 - vPool data-ny1-07 - Unregistering vDisk eb7e2915-09f0-4d6c-80ed-7cebca96c50f - Executing the passed function
2018-12-25 16:59:39 08700 -0500 - NY1SRV0002 - 26454/140643737270016 - lib/generic tasks scrub - 1894 - ERROR - Scrubber f36bf1f6-7a7e-405c-8efe-30d42337d714 - vPool data-ny1-07 - StorageRouter NY1SRV1000 - Stack 0 - Scrubbing thread 0 - vDisk pcd_472679d8-873a-4a94-a808-10b69b338414 with volume id 2f7208c9-ec2d-433b-b6d2-def2dd52a421 - Scrubbing failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/helpers/generic/scrubber.py", line 581, in _execute_scrub
    vdisk = rem.VDisk(vdisk_guid)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 436, in sync_request
    seq = self._send_request(handler, args)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 234, in _send_request
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 229, in _send
    self._channel.send(data)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/channel.py", line 69, in send
    self.stream.write(buf)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/stream.py", line 202, in write
    count = self.sock.send(data[:self.MAX_IO_CHUNK])
  File "/usr/lib/python2.7/dist-packages/rpyc/core/stream.py", line 76, in __getattr__
    raise EOFError("stream has been closed")
EOFError: stream has been closed
2018-12-25 16:59:39 08800 -0500 - NY1SRV0002 - 26454/140643737270016 - lib/generic tasks scrub - 1895 - INFO - Scrubber f36bf1f6-7a7e-405c-8efe-30d42337d714 - vPool data-ny1-07 - Unregistering vDisk 59640a67-2bfe-44d4-bc3d-3cf64b19894b
2018-12-25 16:59:39 09100 -0500 - NY1SRV0002 - 26454/140643695306496 - lib/generic tasks scrub - 1896 - INFO - Scrubber f36bf1f6-7a7e-405c-8efe-30d42337d714 - vPool data-ny1-07 - Unregister vDisk eb7e2915-09f0-4d6c-80ed-7cebca96c50f
2018-12-25 16:59:39 09400 -0500 - NY1SRV0002 - 26454/140643695306496 - lib/generic tasks scrub - 1897 - INFO - Scrubber f36bf1f6-7a7e-405c-8efe-30d42337d714 - vPool data-ny1-07 - Successfully unregistered vDisk eb7e2915-09f0-4d6c-80ed-7cebca96c50f
2018-12-25 16:59:39 09400 -0500 - NY1SRV0002 - 26454/140643737270016 - lib/generic tasks scrub - 1898 - INFO - Scrubber f36bf1f6-7a7e-405c-8efe-30d42337d714 - vPool data-ny1-07 - Unregistering vDisk 59640a67-2bfe-44d4-bc3d-3cf64b19894b - Executing the passed function
2018-12-25 16:59:39 09500 -0500 - NY1SRV0002 - 26454/140643695306496 - lib/generic tasks scrub - 1899 - ERROR - Scrubber f36bf1f6-7a7e-405c-8efe-30d42337d714 - vPool data-ny1-07 - StorageRouter NY1SRV1000 - Stack 0 - Scrubbing thread 4 - vDisk IdentityManager32boot-flat_bff47341-3c94-4737-a38a-a43aa209a20b with volume id 4d3e5d23-54ae-4517-981e-fe8fbf7efcd6 - Scrubbing failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/helpers/generic/scrubber.py", line 581, in _execute_scrub
    vdisk = rem.VDisk(vdisk_guid)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 436, in sync_request
    seq = self._send_request(handler, args)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 234, in _send_request
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 229, in _send
    self._channel.send(data)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/channel.py", line 69, in send
    self.stream.write(buf)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/stream.py", line 202, in write
    count = self.sock.send(data[:self.MAX_IO_CHUNK])
  File "/usr/lib/python2.7/dist-packages/rpyc/core/stream.py", line 76, in __getattr__
    raise EOFError("stream has been closed")
EOFError: stream has been closed
2018-12-25 16:59:39 09700 -0500 - NY1SRV0002 - 26454/140643695306496 - lib/generic tasks scrub - 1900 - INFO - Scrubber f36bf1f6-7a7e-405c-8efe-30d42337d714 - vPool data-ny1-07 - Unregistering vDisk 96571102-a413-47ce-9340-f1802b34b4f7
2018-12-25 16:59:39 10000 -0500 - NY1SRV0002 - 26454/140643737270016 - lib/generic tasks scrub - 1901 - INFO - Scrubber f36bf1f6-7a7e-405c-8efe-30d42337d714 - vPool data-ny1-07 - Unregister vDisk 59640a67-2bfe-44d4-bc3d-3cf64b19894b
2018-12-25 16:59:39 10300 -0500 - NY1SRV0002 - 26454/140643737270016 - lib/generic tasks scrub - 1902 - INFO - Scrubber f36bf1f6-7a7e-405c-8efe-30d42337d714 - vPool data-ny1-07 - Successfully unregistered vDisk 59640a67-2bfe-44d4-bc3d-3cf64b19894b
```

**Comment by jtorreke** [comment]
I found the issue:

```
root@NY1SRV1000:~# uptime
 04:05:59 up 11:01,  2 users,  load average: 7.55, 8.67, 8.99
```

The scrubbing node was rebooted in the mean time.
