### ISSUE TITLE
failed to remove an unavailable asd

### ISSUE THREAD

**Issue by OVSchristophe** [openvstorage/framework#2237]
![image](https://user-images.githubusercontent.com/45066628/50452463-8673cd00-093a-11e9-83c2-64ade399e97a.png)

2018-12-26 18:33:48 76500 +0100 - ChristopheOVS_1 - 20882/140094905251584 - celery/celery.worker.strategy - 1735 - INFO - Received task: albanode.reset_asd[fcb8c6ce-beb9-46da-a7a8-6a06431a57e1]
2018-12-26 18:33:48 80300 +0100 - ChristopheOVS_1 - 13281/140094905251584 - lib/ensure single - 1734 - INFO - Ensure single CHAINED mode - ID 1545845628_8JRL1MAn9V - New task albanode.remove_asd with params {'node_guid': 'd7e81ed6-e74c-4051-9252-23d1f281bcf3', 'expected_safety': {u'good': 1, u'critical': 0, u'lost': 4}, 'asd_id': u'XDx4tbJ7IYuOWsQOd5u9oioRx16HpR3s'} scheduled for execution
2018-12-26 18:33:48 88900 +0100 - ChristopheOVS_1 - 20882/140094905251584 - celery/celery.worker.job - 1736 - ERROR - Task albanode.reset_asd[fcb8c6ce-beb9-46da-a7a8-6a06431a57e1] raised unexpected: RuntimeError(u'list index out of range',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albanode.py", line 368, in reset_asd
    expected_safety=expected_safety)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 461, in new_function
    output = f(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albanode.py", line 293, in remove_asd
    for alias, asd_ids in node.client.get_asds().iteritems():
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 179, in get_asds
    return self._call(requests.get, 'asds', clean=True)
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 107, in _call
    raise RuntimeError(error_message)
RuntimeError: list index out of range
2018-12-26 18:33:50 91900 +0100 - ChristopheOVS_1 - 20882/140094905251584 - celery/celery.worker.autoscale - 1737 - INFO - Scaling down -1 processes.
2018-12-26 18:34:02 05100 +0100 - ChristopheOVS_1 - 20882/140094905251584 - celery/celery.worker.strategy - 1738 - INFO - Received task: ovs.storagerouter.ping[7b5a0fd0-edae-4985-abff-f3cd6659e66b]
2018-12-26 18:34:02 05100 +0100 - ChristopheOVS_1 - 20882/140094905251584 - celery/celery.worker.autoscale - 1739 - INFO - Scaling up 1 processes.
2018-12-26 18:34:02 18000 +0100 - ChristopheOVS_1 - 20882/140094905251584 - celery/celery.worker.job - 1740 - INFO - Task ovs.storagerouter.ping[7b5a0fd0-edae-4985-abff-f3cd6659e66b] succeeded in 0.0562616050011s: None

**Comment by JeffreyDevloo** [comment]
Needs to be verified if it still occurs after https://github.com/openvstorage/framework-alba-plugin/issues/431
