### ISSUE TITLE
New config management ruins ovs config edit

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#2262]
```
root@jef-node01:~# ovs config get ovs/alba/backends/9a23f697-e8a8-4160-a980-c6dfab786427/maintenance/alba-maintenance_backend-nlkMBsTb1BNgCdO4/config
{u'albamgr_cfg_url': u'arakoon://config/ovs/arakoon/backend-abm/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Farakoon_cacc.ini', u'log_level': u'info', u'multicast_discover_osds': False, u'read_preference': [u'5zdFeKN1q7n9G4Ce']}

```

```
root@jef-node01:~# ovs config edit ovs/alba/backends/9a23f697-e8a8-4160-a980-c6dfab786427/maintenance/alba-maintenance_backend-nlkMBsTb1BNgCdO4/config
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/cli/entry.py", line 20, in <module>
    ovs()  # Invokes the ovs CLI
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/ovs_extensions/cli/commands.py", line 222, in main
    super(OVSCLI, self).main(args, prog_name, complete_var, standalone_mode, **extra)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/OpenvStorage/ovs/cli/commands.py", line 114, in invoke
    super(OVSCommand, self).invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/cli/config/config.py", line 37, in edit
    f.write(Configuration.get(path, raw=True))

```

The paramater raw=True has been ignored. It should still be specifiable for this example.

**Comment by sjovdnbos** [comment]
### Fixed by:
https://github.com/openvstorage/framework-extensions/pull/207
