### ISSUE TITLE
Scrubber crashes after a while: "stream has been closed"

### ISSUE THREAD

**Issue by KevinHun** [openvstorage/framework#2287]
Problem at gig. 
When doing scrubbing we get following stacktrace in the worker log:

`2019-04-10 14:19:15 23500 +0000 - mr4-stor-01 - 16074/140273606706944 - lib/generic tasks scrub - 1656 - INFO - Scrubber e7bd729c-4aa3-49d7-b3d6-77673fbf1a7d - vPool data01 - StorageRouter mr4-stor-04 - Stack 2 - Removing services ovs-albaproxy_data01_mr4-stor-04_e1d0801
7-2d88-4f83-9a6e-4ee7a875afc3_scrub_0
2019-04-10 14:19:17 09800 +0000 - mr4-stor-01 - 16074/140273606706944 - lib/generic tasks scrub - 1657 - INFO - Scrubber e7bd729c-4aa3-49d7-b3d6-77673fbf1a7d - vPool data01 - StorageRouter mr4-stor-04 - Stack 2 - Removed service ovs-albaproxy_data01_mr4-stor-04_e1d08017-
2d88-4f83-9a6e-4ee7a875afc3_scrub_0
2019-04-10 14:19:17 10500 +0000 - mr4-stor-01 - 16074/140273606706944 - lib/generic tasks scrub - 1658 - INFO - Scrubber e7bd729c-4aa3-49d7-b3d6-77673fbf1a7d - vPool data01 - StorageRouter mr4-stor-04 - Stack 2 - Removed services ovs-albaproxy_data01_mr4-stor-04_e1d08017
-2d88-4f83-9a6e-4ee7a875afc3_scrub_0
2019-04-10 14:19:17 10500 +0000 - mr4-stor-01 - 16074/140273053050624 - lib/generic tasks scrub - 1659 - INFO - Scrubber e7bd729c-4aa3-49d7-b3d6-77673fbf1a7d - vPool data01 - StorageRouter mr4-stor-02 - Stack 4 - Removing directory /mnt/ssd2/scrub_work_data01_mr4-stor-02
_6eb7aaf0-360c-481c-a697-f638c798004a
2019-04-10 14:19:19 33000 +0000 - mr4-stor-01 - 16074/140273053050624 - lib/generic tasks scrub - 1660 - INFO - Scrubber e7bd729c-4aa3-49d7-b3d6-77673fbf1a7d - vPool data01 - StorageRouter mr4-stor-02 - Stack 4 - Removing services ovs-albaproxy_data01_mr4-stor-02_6eb7aaf
0-360c-481c-a697-f638c798004a_scrub_0
2019-04-10 14:19:21 19700 +0000 - mr4-stor-01 - 16074/140273053050624 - lib/generic tasks scrub - 1661 - INFO - Scrubber e7bd729c-4aa3-49d7-b3d6-77673fbf1a7d - vPool data01 - StorageRouter mr4-stor-02 - Stack 4 - Removed service ovs-albaproxy_data01_mr4-stor-02_6eb7aaf0-
360c-481c-a697-f638c798004a_scrub_0
2019-04-10 14:19:21 20200 +0000 - mr4-stor-01 - 16074/140273053050624 - lib/generic tasks scrub - 1662 - INFO - Scrubber e7bd729c-4aa3-49d7-b3d6-77673fbf1a7d - vPool data01 - StorageRouter mr4-stor-02 - Stack 4 - Removed services ovs-albaproxy_data01_mr4-stor-02_6eb7aaf0
-360c-481c-a697-f638c798004a_scrub_0
2019-04-10 14:19:21 20400 +0000 - mr4-stor-01 - 16074/140273628477184 - lib/generic tasks scrub - 1663 - INFO - Scrubber e7bd729c-4aa3-49d7-b3d6-77673fbf1a7d - vPool data01 - StorageRouter mr4-stor-03 - Stack 1 - Removing directory /mnt/ssd2/scrub_work_data01_mr4-stor-03
_9b41e040-75b7-4bee-ace4-581a7a546a9d
2019-04-10 14:19:23 44000 +0000 - mr4-stor-01 - 16074/140273628477184 - lib/generic tasks scrub - 1664 - INFO - Scrubber e7bd729c-4aa3-49d7-b3d6-77673fbf1a7d - vPool data01 - StorageRouter mr4-stor-03 - Stack 1 - Removing services ovs-albaproxy_data01_mr4-stor-03_9b41e04
0-75b7-4bee-ace4-581a7a546a9d_scrub_0
2019-04-10 14:19:25 32400 +0000 - mr4-stor-01 - 16074/140273628477184 - lib/generic tasks scrub - 1665 - INFO - Scrubber e7bd729c-4aa3-49d7-b3d6-77673fbf1a7d - vPool data01 - StorageRouter mr4-stor-03 - Stack 1 - Removed service ovs-albaproxy_data01_mr4-stor-03_9b41e040-
75b7-4bee-ace4-581a7a546a9d_scrub_0
2019-04-10 14:19:25 32900 +0000 - mr4-stor-01 - 16074/140273628477184 - lib/generic tasks scrub - 1666 - INFO - Scrubber e7bd729c-4aa3-49d7-b3d6-77673fbf1a7d - vPool data01 - StorageRouter mr4-stor-03 - Stack 1 - Removed services ovs-albaproxy_data01_mr4-stor-03_9b41e040
-75b7-4bee-ace4-581a7a546a9d_scrub_0
^@2019-04-10 14:33:52 48300 +0000 - mr4-stor-01 - 16074/140273598314240 - lib/generic tasks scrub - 1667 - ERROR - Scrubber 75e4cb99-5749-4d06-9708-f7910bf9a2ec - vPool data01 - StorageRouter mr4-stor-05 - Stack 3 - Scrubbing thread 0 - vDisk volumes/volume_1427 with vol
ume id 28ff5166-db20-4fb0-88e5-c8c6addcce4e - Scrubbing failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/helpers/generic/scrubber.py", line 627, in _execute_scrub
    self._logger.info('{0} - No scrubbing required'.format(vdisk_log, vdisk.name))
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 210, in method
    return syncreq(_self, consts.HANDLE_CALLATTR, name, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 436, in sync_request
    seq = self._send_request(handler, args)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 234, in _send_request
    self._send(consts.MSG_REQUEST, seq, (handler, self._box(args)))
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 229, in _send
    self._channel.send(data)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/channel.py", line 69, in send
    self.stream.write(buf)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/stream.py", line 202, in write
    count = self.sock.send(data[:self.MAX_IO_CHUNK])
  File "/usr/lib/python2.7/dist-packages/rpyc/core/stream.py", line 76, in __getattr__
    raise EOFError("stream has been closed")
EOFError: stream has been closed
2019-04-10 14:33:52 48400 +0000 - mr4-stor-01 - 16074/140273598314240 - lib/generic tasks scrub - 1668 - INFO - Scrubber 75e4cb99-5749-4d06-9708-f7910bf9a2ec - vPool data01 - Unregistering vDisk fd58e0df-74fc-45fa-856b-c0b584b8a1cc
2019-04-10 14:33:52 48400 +0000 - mr4-stor-01 - 16074/140273598314240 - lib/generic tasks scrub - 1669 - INFO - Scrubber 75e4cb99-5749-4d06-9708-f7910bf9a2ec - vPool data01 - Unregistering vDisk fd58e0df-74fc-45fa-856b-c0b584b8a1cc - Executing the passed function
2019-04-10 14:33:52 48900 +0000 - mr4-stor-01 - 16074/140273598314240 - lib/generic tasks scrub - 1670 - INFO - Scrubber 75e4cb99-5749-4d06-9708-f7910bf9a2ec - vPool data01 - Unregister vDisk fd58e0df-74fc-45fa-856b-c0b584b8a1cc
2019-04-10 14:33:52 49000 +0000 - mr4-stor-01 - 16074/140273598314240 - lib/generic tasks scrub - 1671 - INFO - Scrubber 75e4cb99-5749-4d06-9708-f7910bf9a2ec - vPool data01 - Successfully unregistered vDisk fd58e0df-74fc-45fa-856b-c0b584b8a1cc
2019-04-10 14:33:52 49100 +0000 - mr4-stor-01 - 16074/140273598314240 - lib/generic tasks scrub - 1672 - INFO - Scrubber 75e4cb99-5749-4d06-9708-f7910bf9a2ec - vPool data01 - StorageRouter mr4-stor-05 - Stack 3 - Scrubbing thread 0 - Queue completely processed
2019-04-10 14:33:52 49200 +0000 - mr4-stor-01 - 16074/140273615099648 - lib/generic tasks scrub - 1673 - INFO - Scrubber 75e4cb99-5749-4d06-9708-f7910bf9a2ec - vPool data01 - StorageRouter mr4-stor-05 - Stack 3 - Unregistering usage of ovs-albaproxy_data01_mr4-stor-05_1fad22d8-3ce5-4a9e-aa97-d3388d964842_scrub_0
2019-04-10 14:33:52 49200 +0000 - mr4-stor-01 - 16074/140273615099648 - lib/generic tasks scrub - 1674 - INFO - Scrubber 75e4cb99-5749-4d06-9708-f7910bf9a2ec - vPool data01 - StorageRouter mr4-stor-05 - Stack 3 - Unregistering proxies ovs-albaproxy_data01_mr4-stor-05_1fad22d8-3ce5-4a9e-aa97-d3388d964842_scrub_0 - Executing the passed function
2019-04-10 14:33:52 49500 +0000 - mr4-stor-01 - 16074/140273615099648 - lib/generic tasks scrub - 1675 - INFO - Scrubber 75e4cb99-5749-4d06-9708-f7910bf9a2ec - vPool data01 - StorageRouter mr4-stor-05 - Stack 3 - Successfully unregistered proxies ovs-albaproxy_data01_mr4-stor-05_1fad22d8-3ce5-4a9e-aa97-d3388d964842_scrub_0
2019-04-10 14:33:52 49500 +0000 - mr4-stor-01 - 16074/140273615099648 - lib/generic tasks scrub - 1676 - INFO - Scrubber 75e4cb99-5749-4d06-9708-f7910bf9a2ec - vPool data01 - StorageRouter mr4-stor-05 - Stack 3 - Cannot remove services ovs-albaproxy_data01_mr4-stor-05_1fad22d8-3ce5-4a9e-aa97-d3388d964842_scrub_0 as it is still in use by others
2019-04-10 14:34:00 89900 +0000 - mr4-stor-01 - 16074/140273078228736 - lib/generic tasks scrub - 1677 - ERROR - Scrubber e7bd729c-4aa3-49d7-b3d6-77673fbf1a7d - vPool data01 - StorageRouter mr4-stor-05 - Stack 3 - Scrubbing thread 0 - vDisk volumes/volume_2090 with volume id 368d02d9-af5a-4c01-953c-4b0211e74f46 - Scrubbing failed
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/helpers/generic/scrubber.py", line 627, in _execute_scrub
`

**Comment by sjovdnbos** [comment]
Traced back to an automatic serverside closure of SSH sessions after 15 minutes.
