### ISSUE TITLE
vDisk is not attached to any StorageRouter

### ISSUE THREAD

**Issue by yongshengma** [openvstorage/framework#2337]
Want to try some luck on any reply.

I run mds_checkup and found some vdisks fail on ensure_safety.

```
2020-04-22 15:17:20 79300 +0800 - N06 - 25211/140050997880640 - lib/mdsservice.py - mds_checkup - 93 - ERROR - Ensure safety for vDisk isli-db2-9e25168a-402b-4d60-aaf7-2ce4ff023705 with guid 1b1212c0-d2fe-4da1-ba59-f817005e81d2 failed
Traceback (most recent call last):
  File "ovs/lib/mdsservice.py", line 410, in mds_checkup
    MDSServiceController.ensure_safety(vdisk_guid=vdisk.guid)
  File "/usr/lib/python2.7/site-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "ovs/lib/helpers/decorators.py", line 461, in new_function
    output = f(*args, **kwargs)
  File "ovs/lib/mdsservice.py", line 492, in ensure_safety
    raise SRCObjectNotFoundException('Cannot ensure MDS safety for vDisk {0} with guid {1} because vDisk is not attached to any StorageRouter'.format(vdisk.name, vdisk.guid))
ObjectNotFoundException: Cannot ensure MDS safety for vDisk isli-db2-9e25168a-402b-4d60-aaf7-2ce4ff023705 with guid 1b1212c0-d2fe-4da1-ba59-f817005e81d2 because vDisk is not attached to any StorageRouter

```

```
In [5]: vdisk.info['live_status']
Out[5]: 'RUNNING'

```

I tried to stop_object or restart_object but got :

```
In [6]: vdisk.storagedriver_client.stop_object(str(vdisk.volume_id), False)
---------------------------------------------------------------------------
ObjectNotFoundException                   Traceback (most recent call last)
<ipython-input-6-86cd6d5c3dad> in <module>()
----> 1 vdisk.storagedriver_client.stop_object(str(vdisk.volume_id), False)

ObjectNotFoundException: Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: volumedriverfs::ObjectNotRegisteredException
std::exception::what: std::exception
[volumedriverfs::tag_volume_id*] = 4386550c-2c5b-41e7-810a-34fa6c5d8a21

``` 

Any idea please?

**Comment by yongshengma** [comment]
How can I remove this vdisk? Its failure on safety check prevents snapshots from being scrubbed.
