### ISSUE TITLE
Any node should be able to SCRUB, currently only storagedrivers are able to scrub locally.

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#538]
In a previous ticket it is defined:

```
Scrubber should run on any node with a SRUB partition, regardless of where the celery beat is active + Add vpool should require at least one SCRUB partition on the cluster (but it is not required to be local)
```

Although defined in the code it is only possible for storagedrivers to SCRUB: https://github.com/openvstorage/framework/blame/master/ovs/lib/scheduledtask.py#L220

This means that the framework accepts that on a non-compute node a SCRUB role is defined. But It never uses it. 

This leads to: (and all volumes are never scrubbed)

```
[2016-05-20 05:00:00,262: INFO/Worker-255] Gather Scrub - Started
[2016-05-20 05:00:00,732: INFO/Worker-255] Ensure single DEFAULT mode - ID 1463713200_orPtxu0eTH - Deleting key ovs_ensure_single_ovs.scheduled.gather_scrub_work
ESC[1;31m[2016-05-20 05:00:00,871: ERROR/MainProcess] Task ovs.scheduled.gather_scrub_work[866dc31f-182c-43c7-98da-1dd11ba4e3f1] raised unexpected: RuntimeError('No scrub locations found',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 172, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/scheduledtask.py", line 234, in gather_scrub_work
    raise RuntimeError('No scrub locations found')
RuntimeError: No scrub locations foundESC[0m
```

**Comment by kinvaris** [comment]
PASSED:

Setup 4 nodes:
- 3 nodes held a vpool with scrub partition
- 1 node only held the scrub partition

Executed scrub: `ScheduledTaskController.execute_scrub()`

Saw this on the node with scrub partition:

```
OVS running processes
=====================

ovs-albaproxy_myvpool01_ovs-node04-1604_scrub  active
ovs-support-agent                              active
ovs-watcher-config                             active
ovs-watcher-framework                          active
ovs-workers                                    active
```

After the scrubwork was done, the service was deleted again.
