### ISSUE TITLE
celery crashes sometimes when creating a filesystem

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/framework#593]
When we reinstall the env and configure the roles on the nodes,
celery worker received a warm shutdown from the main process and killed all the running tasks.
Roles are not added to the disk and sometimes the disk doesn't have a filesystem.

@khenderick Can we have look tomorrow and see why the celery restart?
We cannot afford to lose a running task due to a warm shutdown...

```
2016-06-09 15:52:18 60100 +0200 - cmp03 - 16548/140236026070848 - lib/storagerouter - 50 - INFO - Starting make fs /dev/disk/by-id/wwn-0x5e83a97f7f1b6e77-part1

worker: Warm shutdown (MainProcess)
2016-06-09 15:53:42 26000 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 283 - DEBUG - | Worker: Closing Hub...
2016-06-09 15:53:42 26100 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 284 - DEBUG - | Worker: Closing Pool...
2016-06-09 15:53:42 26100 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 285 - DEBUG - | Worker: Closing Autoscaler...
2016-06-09 15:53:42 26100 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 286 - DEBUG - | Worker: Closing Consumer...
2016-06-09 15:53:42 26100 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 287 - DEBUG - | Worker: Stopping Consumer...
2016-06-09 15:53:42 26100 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 288 - DEBUG - | Consumer: Closing Connection...
2016-06-09 15:53:42 26100 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 289 - DEBUG - | Consumer: Closing Events...
2016-06-09 15:53:42 26100 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 290 - DEBUG - | Consumer: Closing Heart...
2016-06-09 15:53:42 26200 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 291 - DEBUG - | Consumer: Closing Mingle...
2016-06-09 15:53:42 26200 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 292 - DEBUG - | Consumer: Closing Gossip...
2016-06-09 15:53:42 26200 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 293 - DEBUG - | Consumer: Closing Tasks...
2016-06-09 15:53:42 26200 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 294 - DEBUG - | Consumer: Closing Control...
2016-06-09 15:53:42 26200 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 295 - DEBUG - | Consumer: Closing event loop...
2016-06-09 15:53:42 26200 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 296 - DEBUG - | Consumer: Stopping event loop...
2016-06-09 15:53:42 26200 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 297 - DEBUG - | Consumer: Stopping Control...
2016-06-09 15:53:42 30200 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 298 - DEBUG - | Consumer: Stopping Tasks...
2016-06-09 15:53:42 30300 +0200 - cmp03 - 16522/140236026070848 - celery/celery.worker.consumer - 299 - DEBUG - Cancelling task consumer...
2016-06-09 15:53:42 30500 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 300 - DEBUG - | Consumer: Stopping Gossip...
2016-06-09 15:53:42 31500 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 301 - DEBUG - | Consumer: Stopping Mingle...
2016-06-09 15:53:42 31500 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 302 - DEBUG - | Consumer: Stopping Heart...
2016-06-09 15:53:42 31600 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 303 - DEBUG - | Consumer: Stopping Events...
2016-06-09 15:53:42 31600 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 304 - DEBUG - | Consumer: Stopping Connection...
2016-06-09 15:53:42 31600 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 305 - DEBUG - | Worker: Stopping Autoscaler...
2016-06-09 15:53:42 31600 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 306 - DEBUG - | Worker: Stopping Pool...
ESC[1;31m[2016-06-09 15:53:43,317: ERROR/MainProcess] Process 'Worker-3' pid:30327 exited with 'signal 15 (SIGTERM)'ESC[0m
ESC[1;31m[2016-06-09 15:53:43,328: ERROR/MainProcess] Process 'Worker-1' pid:16548 exited with 'signal 15 (SIGTERM)'ESC[0m
2016-06-09 15:53:43 34200 +0200 - cmp03 - 16522/140236026070848 - celery/celery.worker.job - 307 - ERROR - Task ovs.storagerouter.configure_disk[5e42df83-48cd-4fdf-a0e3-2bee3c6aeb4a] raised unexpected: WorkerLostError('Worker exited prematurely: signal 15 (SIGTERM).',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/billiard/pool.py", line 1171, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 15 (SIGTERM).
2016-06-09 15:53:43 34300 +0200 - cmp03 - 16522/140236026070848 - celery/celery.worker.job - 308 - ERROR - Task ovs.storagerouter.configure_disk[13db166b-ef75-483d-b102-e189bfb5c109] raised unexpected: WorkerLostError('Worker exited prematurely: signal 15 (SIGTERM).',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/billiard/pool.py", line 1171, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 15 (SIGTERM).
2016-06-09 15:53:43 34400 +0200 - cmp03 - 16522/140236026070848 - celery/celery.bootsteps - 309 - DEBUG - | Worker: Stopping Hub...
....
```

![disks](https://cloud.githubusercontent.com/assets/2900612/15932878/b7b149ca-2e5d-11e6-8292-1cf2d7afdaec.png)

Testing, searching, reinstalling env (6.5h)

**Comment by wimpers** [comment]
Maybe recheck once https://github.com/openvstorage/framework/issues/749 is closed and a new celery was added?

**Comment by khenderick** [comment]
Celery is upgraded from `3.1.18` to `3.1.23-5`. Please validate.

**Comment by JeffreyDevloo** [comment]
### Information
The linked ticket #749 was closed due to not seeing the issue anymore on our testing environments.
We also did not encounter this issue anymore on our testing environments therefore I am closing this one as well.
