### ISSUE TITLE
Retrieving updates on env where no vpool was setup yet raises KeyError: 'voldrv'

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#602]
Clean install
Add backend only
GUI -> Administration -> Updates -> spinner does not disappear

ovs-workers.log shows:

```
2016-06-13 13:15:02 25900 +0200 - ovs54b - 24269/140715730085696 - celery/celery.worker.job - 726 - ERROR - Task ovs.storagerouter.get_update_status[99e7baa2-c4e7-40b2-a829-9d8993b99e1a] raised unexpected: KeyError('voldrv',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1657, in get_update_status
    output = function(root_client)
  File "/opt/OpenvStorage/ovs/lib/helpers/..//storagerouter.py", line 1771, in get_metadata_volumedriver
    sd_cluster_name = EtcdConfiguration.get('/ovs/framework/arakoon_clusters|voldrv')
  File "/opt/OpenvStorage/ovs/extensions/db/etcd/configuration.py", line 140, in get
    temp_data = temp_data[entry]
KeyError: 'voldrv'
```

**Comment by khenderick** [comment]
Was resolved by #617
