### ISSUE TITLE
Unable to create VM from template

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#627]
VPN tunnel  10.0.1.74 via 172.20.3.25

Cluster ID: vJvGFWHxdtWDy3UB

StorageRouters:
Storagerouter1: 54d6fsdTSPoaHCKZ  
Storagerouter2: feGHzX9DPnUdQoFZ  
Storagerouter3: 5yoL2lzwheSwwpkw 

ESXi details:-

HOST
192.168.17.201
192.168.17.202
192.168.17.203

OVSVSA
192.168.17.101
192.168.17.102
192.168.17.103

Versions:-
            "openvstorage-backend-core": "1.7.0-fargo.1-1",
            "alba": "0.9.9",
            "openvstorage-sdm": "1.6.0-fargo.1-1",
            "openvstorage-webapps": "2.7.0-fargo.1-1",
            "openvstorage-backend-webapps": "1.7.0-fargo.1-1",
            "openvstorage-core": "2.7.0-fargo.1-1",
            "openvstorage": "2.7.0-fargo.1-1",
            "openvstorage-cinder-plugin": "1.2.0-fargo.1-1",
            "openvstorage-backend": "1.7.0-fargo.1-1",
            "arakoon": "1.9.6"

Issue - Unable to create VM from template
- VM create from template failing with below error on ESXi node 1 

2016-06-17 18:29:29 59900 +0530 - Storagerouter1 - 16365/140372771022656 - celery/celery.worker.job - 4917 - ERROR - Task ovs.machine.create_from_template[9c1b4abd-53de-4e33-9ece-063b2f9fbb5b] raised unexpected: ValueError('StorageRouter Storagerouter1 for vDisk Hard disk 1-clone should be part of the primary domains and NOT be part of the secondary domains',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in protected_call
    return self.run(_args, *_kwargs)
  File "/opt/OpenvStorage/ovs/lib/vmachine.py", line 171, in create_from_template
    machineguid=new_vm.guid
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 167, in <lambda>
    call = lambda x, a, kw: x._get_current_object()(_a, *kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in protected_call
    return orig(self, args, *kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in call
    return self.run(_args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/vdisk.py", line 595, in create_from_template
    raise ex
ValueError: StorageRouter Storagerouter1 for vDisk Hard disk 1-clone should be part of the primary domains and NOT be part of the secondary domains
- On 2nd node when try to create vm from template it gives another error

2016-06-17 18:32:15 68400 +0530 - Storagerouter2 - 14265/139807384299328 - celery/celery.worker.job - 4743 - DEBUG - Task accepted: ovs.machine.delete[f7f16895-fe50-4d9e-afe9-f524d614fa8e] pid:10973
[2016-06-17 18:32:22,356: ERROR/Worker-208] <suds.sax.document.Document instance at 0x7f2753025bd8>
2016-06-17 18:32:22 43500 +0530 - Storagerouter2 - 10973/139807384299328 - celery/celery.redirected - 4737 - WARNING - 2016-06-17 18:32:22 43500 +0530 - Storagerouter2 - 10973/139807384299328 - extensions/file mutex - 4736 - WARNING - A lock on /var/lock/ovs_flock_hypervisor_192.168.17.202_root was kept for 6.73874807358 sec
2016-06-17 18:32:23 07300 +0530 - Storagerouter2 - 10973/139807384299328 - celery/celery.redirected - 4739 - WARNING - 2016-06-17 18:32:23 07300 +0530 - Storagerouter2 - 10973/139807384299328 - extensions/vmware sdk - 4738 - ERROR - SDK domain retrieve failed by nfs datastore info: Could not locate given file on the given datastore
2016-06-17 18:32:23 07500 +0530 - Storagerouter2 - 10973/139807384299328 - lib/vmachine - 4740 - DEBUG - Deleting vmachine Win2k8R2-Jetstress2 with guid 5a6b3570-d078-4747-87ff-d4bc514fd25f
2016-06-17 18:32:23 11800 +0530 - Storagerouter2 - 14265/139807384299328 - celery/celery.worker.job - 4744 - INFO - Task ovs.machine.delete[f7f16895-fe50-4d9e-afe9-f524d614fa8e] succeeded in 7.434523285s: None
- Please check further

**Comment by domsj** [comment]
Some findings:

```
2016-06-20 13:28:18 472487 +0530 - Storagerouter3 - 13717/0 - arakoon - 32 - info - Not copying /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/head.db to /mnt/ssd1/arakoon/backend1-nsm_0/db/5yoL2lzwheSwwpkw.db because target already exists
2016-06-20 13:28:24 715039 +0530 - Storagerouter3 - 13717/0 - arakoon - 33 - fatal - AUTOFIX: can't autofix this: (Failure;   "\"/mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6020.tlx\" starts with 1405207, which ain't higher than 1408230"); backtrace:; Raised at file "map.ml", line 117, characters 16-25; Called from file "src/core/lwt.ml", line 161, characters 4-40
2016-06-20 13:28:24 715081 +0530 - Storagerouter3 - 13717/0 - arakoon - 34 - fatal - going down: (Failure;   "\"/mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6020.tlx\" starts with 1405207, which ain't higher than 1408230"); backtrace:; Raised by primitive operation at file "src/zone.ml", line 690, characters 31-54
2016-06-20 13:28:24 715091 +0530 - Storagerouter3 - 13717/0 - arakoon - 35 - fatal - after pick
2016-06-20 13:28:24 715547 +0530 - Storagerouter3 - 13717/0 - arakoon - 36 - info - Crash log dumped
2016-06-20 13:28:24 795407 +0530 - Storagerouter3 - 13746/0 - arakoon - 0 - info - --- NODE STARTED ---
2016-06-20 13:28:24 795452 +0530 - Storagerouter3 - 13746/0 - arakoon - 1 - info - git_revision: tags/1.9.6-0-gea32319 
2016-06-20 13:28:24 795461 +0530 - Storagerouter3 - 13746/0 - arakoon - 2 - info - compile_time: 10/06/2016 13:21:09 UTC 
2016-06-20 13:28:24 795471 +0530 - Storagerouter3 - 13746/0 - arakoon - 3 - info - version: 1.9.6
2016-06-20 13:28:24 795481 +0530 - Storagerouter3 - 13746/0 - arakoon - 4 - info - NOFILE: 1024
```

Start i of .tlx files:
```
6000 => 1404602
6001 => 1404810
6010 => 1406431
6011 => 1406634
6012 => 1406827
6013 => 1407031
6014 => 1407226
6015 => 1407427
6016 => 1407629
6017 => 1407823
6018 => 1408027
6019 => 1408230
6020 => 1405207
6021 => 1405407
6022 => 1405609
```

disk was full, probably because collapsing failed due to the fuck up in the tlogs (6020.tlx has lower start i)

```
2016-06-17 17:58:10 625935 +0530 - Storagerouter3 - 25930/0 - arakoon - 84922 - info - save_tlog_file: first_i:1405207 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6004.tlx.tmp
2016-06-17 17:58:10 688960 +0530 - Storagerouter3 - 25930/0 - arakoon - 84929 - info - save_tlog_file: first_i:1405407 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6005.tlx.tmp
2016-06-17 17:58:10 772957 +0530 - Storagerouter3 - 25930/0 - arakoon - 84934 - info - save_tlog_file: first_i:1405609 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6006.tlx.tmp
2016-06-17 17:58:10 865643 +0530 - Storagerouter3 - 25930/0 - arakoon - 84941 - info - save_tlog_file: first_i:1405812 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6007.tlx.tmp
2016-06-17 17:58:10 947088 +0530 - Storagerouter3 - 25930/0 - arakoon - 84946 - info - save_tlog_file: first_i:1406034 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6008.tlx.tmp
2016-06-17 17:58:11 34121 +0530 - Storagerouter3 - 25930/0 - arakoon - 84955 - info - save_tlog_file: first_i:1406235 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6009.tlx.tmp
2016-06-17 17:58:11 145414 +0530 - Storagerouter3 - 25930/0 - arakoon - 84963 - info - save_tlog_file: first_i:1406431 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6010.tlx.tmp
2016-06-17 17:58:11 225089 +0530 - Storagerouter3 - 25930/0 - arakoon - 84970 - info - save_tlog_file: first_i:1406634 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6011.tlx.tmp
2016-06-17 17:58:11 334110 +0530 - Storagerouter3 - 25930/0 - arakoon - 84977 - info - save_tlog_file: first_i:1406827 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6012.tlx.tmp
2016-06-17 17:58:11 451056 +0530 - Storagerouter3 - 25930/0 - arakoon - 84984 - info - save_tlog_file: first_i:1407031 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6013.tlx.tmp
2016-06-17 17:58:11 537734 +0530 - Storagerouter3 - 25930/0 - arakoon - 84991 - info - save_tlog_file: first_i:1407226 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6014.tlx.tmp
2016-06-17 17:58:11 643316 +0530 - Storagerouter3 - 25930/0 - arakoon - 84996 - info - save_tlog_file: first_i:1407427 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6015.tlx.tmp
2016-06-17 17:58:11 720091 +0530 - Storagerouter3 - 25930/0 - arakoon - 85003 - info - save_tlog_file: first_i:1407629 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6016.tlx.tmp
2016-06-17 17:58:11 802635 +0530 - Storagerouter3 - 25930/0 - arakoon - 85010 - info - save_tlog_file: first_i:1407823 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6017.tlx.tmp
2016-06-17 17:58:11 908004 +0530 - Storagerouter3 - 25930/0 - arakoon - 85015 - info - save_tlog_file: first_i:1408027 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6018.tlx.tmp
2016-06-17 17:58:11 984177 +0530 - Storagerouter3 - 25930/0 - arakoon - 85022 - info - save_tlog_file: first_i:1408230 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6019.tlx.tmp
2016-06-17 17:58:16 260279 +0530 - Storagerouter3 - 25930/0 - arakoon - 85198 - info - save_tlog_file: first_i:1405207 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6020.tlx.tmp
2016-06-17 17:58:16 324018 +0530 - Storagerouter3 - 25930/0 - arakoon - 85205 - info - save_tlog_file: first_i:1405407 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6021.tlx.tmp
2016-06-17 17:58:16 436891 +0530 - Storagerouter3 - 25930/0 - arakoon - 85210 - info - save_tlog_file: first_i:1405609 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6022.tlx.tmp
2016-06-17 17:58:16 518537 +0530 - Storagerouter3 - 25930/0 - arakoon - 85217 - info - save_tlog_file: first_i:1405812 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6023.tlx.tmp
2016-06-17 17:58:16 636027 +0530 - Storagerouter3 - 25930/0 - arakoon - 85224 - info - save_tlog_file: first_i:1406034 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6024.tlx.tmp
2016-06-17 17:58:16 761284 +0530 - Storagerouter3 - 25930/0 - arakoon - 85231 - info - save_tlog_file: first_i:1406235 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6025.tlx.tmp
2016-06-17 17:58:16 846275 +0530 - Storagerouter3 - 25930/0 - arakoon - 85236 - info - save_tlog_file: first_i:1406431 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6026.tlx.tmp
2016-06-17 17:58:16 925307 +0530 - Storagerouter3 - 25930/0 - arakoon - 85243 - info - save_tlog_file: first_i:1406634 extension:.tlx in /mnt/ssd1/arakoon/backend1-nsm_0/tlogs/6027.tlx.tmp
```

So 6020.tlx was the result of a catchup and something must've gone wrong there.

**Comment by deepshirsath** [comment]
Detailed steps : - 
- Created fresh vm 'Win2k8R2-tmpl' on host 192.168.17.201 using Windows 2008 R2 ISO.
- Attached 2nd vDisk of 10 GB to the VM via vsphare client
- Installed VMware tools and basic software’s in the VM.
- After successful setup of the VM, did graceful shutdown of vm 'Win2k8R2-tmpl'
- From OVS gui, set vm as template.
- Navigated to template section on OVS gui and attempted to create VM from template which eventually failed with two different errors mentioned above.

**Comment by kvanhijf** [comment]
Code failed when no domains were present
Create from template should always have worked with Domains in place
