### ISSUE TITLE
Check whether libvirt-qemu user is in ovs group while adding vPool

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#643]
Environment:
172.20.52.252-250 - 3 node GRID - Fargo

Scenario:
- create backend + init + claim all disks on node 1
- add vpool
- create vm + set as template
- extend vpool on node 2 and node 3
- clone vm to 3 clones, one on each node

Result:
- only one succeeded (node 1), other 2 failed:

'''
2016-06-21 11:15:08 39200 +0200 - ovs52n251 - 84596/139692232316736 - extensions/sshclient - 2517 - ERROR - Command: "virt-install --connect qemu+ssh://root@172.20.52.250/system --name clone-2 --vcpus 1 --ram 512 --graphics vnc,listen=0.0.0.0 --disk /mnt/vp-template/clone-2_disk1-clone.raw,device=disk,bus=virtio --import --network network=default,mac=RANDOM,model=e1000" failed with output "
Starting install...
" and error "ERROR    internal error: process exited while connecting to monitor: qemu-system-x86_64: -drive file=/mnt/vp-template/clone-2_disk1-clone.raw,if=none,id=drive-virtio-disk0,format=raw: could not open disk image /mnt/vp-template/clone-2_disk1-clone.raw: Could not open '/mnt/vp-template/clone-2_disk1-clone.raw': Permission denied

Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu+ssh://root@172.20.52.250/system start clone-2
otherwise, please restart your installation.
"
2016-06-21 11:15:08 39200 +0200 - ovs52n251 - 84596/139692232316736 - celery/celery.redirected - 2519 - WARNING - 2016-06-21 11:15:08 39200 +0200 - ovs52n251 - 84596/139692232316736 - extensions/kvm sdk - 2518 - DEBUG - Disconnecting libvirt
2016-06-21 11:15:08 40300 +0200 - ovs52n251 - 84596/139692232316736 - celery/celery.redirected - 2520 - WARNING - Creation of vm clone-2 on hypervisor failed: Command 'virt-install --connect qemu+ssh://root@172.20.52.250/system --name clone-2 --vcpus 1 --ram 512 --graphics vnc,listen=0.0.0.0 --disk /mnt/vp-template/clone-2_disk1-clone.raw,device=disk,bus=virtio --import --network network=default,mac=RANDOM,model=e1000' returned non-zero exit status 1
2016-06-21 11:15:08 40300 +0200 - ovs52n251 - 84596/139692232316736 - lib/vmachine - 2521 - ERROR - Creation of vm clone-2 on hypervisor failed: Command 'virt-install --connect qemu+ssh://root@172.20.52.250/system --name clone-2 --vcpus 1 --ram 512 --graphics vnc,listen=0.0.0.0 --disk /mnt/vp-template/clone-2_disk1-clone.raw,device=disk,bus=virtio --import --network network=default,mac=RANDOM,model=e1000' returned non-zero exit status 1
2016-06-21 11:15:08 43300 +0200 - ovs52n251 - 25357/139692232316736 - celery/celery.worker.job - 2522 - ERROR - Task ovs.machine.create_from_template[46460faf-af4e-4472-8bae-d914e6f6fe0d] raised unexpected: CalledProcessError()
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in **protected_call**
    return self.run(_args, *_kwargs)
  File "/opt/OpenvStorage/ovs/lib/vmachine.py", line 182, in create_from_template
    name, source_vm, disks, target_storagedriver.storage_ip, target_storagedriver.mountpoint, wait=True
  File "/opt/OpenvStorage/ovs/extensions/hypervisor/hypervisors/kvm.py", line 46, in create_vm_from_template
    return self.sdk.create_vm_from_template(name, source_vm, disks, mountpoint)
  File "/opt/OpenvStorage/ovs/extensions/hypervisor/apis/kvm/sdk.py", line 58, in new_function
    return function(self, _args, *_kwargs)
  File "/opt/OpenvStorage/ovs/extensions/hypervisor/apis/kvm/sdk.py", line 486, in create_vm_from_template
    networks = networks)
  File "/opt/OpenvStorage/ovs/extensions/hypervisor/apis/kvm/sdk.py", line 538, in _vm_create
    self.ssh_client.run('{0} {1}'.format(command, ' '.join(options)))
  File "/opt/OpenvStorage/ovs/extensions/generic/sshclient.py", line 59, in inner_function
    return outer_function(self, _args, *_kwargs)
  File "/opt/OpenvStorage/ovs/extensions/generic/sshclient.py", line 241, in run
    raise CalledProcessError(exit_code, command, stderr)
CalledProcessError
libvirt: QEMU Driver error : Domain not found: no domain with matching name 'clone-3'
2016-06-21 11:15:08 49800 +0200 - ovs52n251 - 84825/139692232316736 - celery/celery.redirected - 2529 - WARNING - 2016-06-21 11:15:08 49800 +0200 - ovs52n251 - 84825/139692232316736 - extensions/kvm sdk - 2528 - ERROR - Domain not found: no domain with matching name 'clone-3'
2016-06-21 11:15:08 49900 +0200 - ovs52n251 - 84825/139692232316736 - celery/celery.redirected - 2531 - WARNING - 2016-06-21 11:15:08 49900 +0200 - ovs52n251 - 84825/139692232316736 - extensions/kvm sdk - 2530 - DEBUG - Disconnecting libvirt
2016-06-21 11:15:08 50900 +0200 - ovs52n251 - 84825/139692232316736 - celery/celery.redirected - 2533 - WARNING - 2016-06-21 11:15:08 50900 +0200 - ovs52n251 - 84825/139692232316736 - extensions/kvm sdk - 2532 - ERROR - SDK domain retrieve failed: Virtual Machine with id/name clone-3 could not be found.
2016-06-21 11:15:08 65600 +0200 - ovs52n251 - 84825/139692232316736 - celery/celery.redirected - 2535 - WARNING - 2016-06-21 11:15:08 65600 +0200 - ovs52n251 - 84825/139692232316736 - extensions/kvm sdk - 2534 - INFO - File on vpool deleted: /mnt/vp-template/clone-3_disk1-clone.raw
2016-06-21 11:15:08 65700 +0200 - ovs52n251 - 84825/139692232316736 - celery/celery.redirected - 2537 - WARNING - 2016-06-21 11:15:08 65700 +0200 - ovs52n251 - 84825/139692232316736 - extensions/kvm sdk - 2536 - DEBUG - Disconnecting libvirt
2016-06-21 11:15:08 65800 +0200 - ovs52n251 - 84825/139692232316736 - lib/vmachine - 2538 - DEBUG - Deleting disk disk1-clone with guid: 63d56e66-0a78-477c-92fa-7782339b447f
2016-06-21 11:15:08 78000 +0200 - ovs52n251 - 84825/139692232316736 - lib/vmachine - 2539 - DEBUG - Deleting vmachine clone-3 with guid 701a61eb-080a-40e0-b160-f981191c8587
'''

**Comment by khenderick** [comment]
The `domain` in this stacktrace is about kvm/qemu's domain, not the framework domain. The permission denied points towards the `libvirt-qemu` user not being in the `ovs` group. This is documented at https://openvstorage.gitbooks.io/openvstorage/content/Installation/kvm.html.

Can you verify this settings?

Further information received indicate everything looks ok at the vPool mountpoint:

```
root@ovs52n251:~# ls -la /mnt/vp*
total 43010060
drwxrwxr-x 1 ovs  ovs         4096 Jun 21 11:15 .
drwxr-xr-x 6 root root        4096 Jun 21 11:08 ..
drwxrwxr-x 1 ovs  ovs         4096 Jun 21 11:15 8ck2XdDqHgY3blZL
-rwxrwxr-x 1 ovs  ovs  22021144576 Jun 21 11:14 clone-1_disk1-clone.raw
-rwxrwxr-x 1 ovs  ovs  22021144576 Jun 21 10:34 disk1.raw
```

**Comment by khenderick** [comment]
After some discussions, this was caused by not following the docs, so the above user was indeed not added to the `ovs` group. A ticket will be created (or this one will be altered) to reflect the feature request to have the framework validate this.

**Comment by khenderick** [comment]
This ticket looks obsolete to me since we've decided that OVS won't handle/support hypervisors anymore.

**Comment by wimpers** [comment]
Re-open if required.
