### ISSUE TITLE
Main page doesn't show backends anymore although the backend page does.

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#675]
When loading the main front page we see can't see local or global backends. But when loading the backends page we can see the backends.

As seen here: https://s31.postimg.org/bqzm43juz/backends_fp_ns.png

**NOTE:** We saw this when a storage & compute node where offline.

**Comment by kinvaris** [comment]
This was caused because 1 arakoon did not return a master:

```
2016-06-28 10:44:12 05100 +0200 - ctrl-roub-01 - 27717/140621646272784 - extensions/albacli - 617 - DEBUG - Command: export LD_LIBRARY_PATH=/usr/lib/alba; /usr/bin/alba list
-all-osds --config=etcd://127.0.0.1:2379/ovs/arakoon/hdd_grav_abm/config --to-json 2> /dev/null
2016-06-28 10:44:12 05100 +0200 - ctrl-roub-01 - 27717/140621646272784 - api/middleware - 618 - ERROR - An unhandled exception occurred: Client_helper.MasterLookupResult.Err
or(_)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 78, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 399, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 396, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 427, in new_function
    return_value = f(*args, **kwargs)
  File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 73, in new_function
    return f(*args, **kw)
  File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 250, in new_function
    data = FullSerializer(object_type, contents=contents, instance=data_list, many=True).data
  File "/usr/lib/python2.7/dist-packages/rest_framework/serializers.py", line 571, in data
    self._data = [self.to_native(item) for item in obj]
  File "/usr/lib/python2.7/dist-packages/rest_framework/serializers.py", line 349, in to_native
    value = field.field_to_native(obj, field_name)
  File "/usr/lib/python2.7/dist-packages/rest_framework/fields.py", line 198, in field_to_native
    value = get_component(value, component)
  File "/usr/lib/python2.7/dist-packages/rest_framework/fields.py", line 56, in get_component
    val = getattr(obj, attr_name)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 339, in <lambda>
    fget = lambda s: s._get_dynamic_property(dynamic)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 408, in _get_dynamic_property
    return self._backend_property(data_loader, dynamic)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 898, in _backend_property
    dynamic_data = function()
  File "/opt/OpenvStorage/ovs/dal/hybrids/albabackend.py", line 536, in _local_summary
    for node_values in self.local_stack.itervalues():
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 339, in <lambda>
    fget = lambda s: s._get_dynamic_property(dynamic)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 408, in _get_dynamic_property
    return self._backend_property(data_loader, dynamic)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 898, in _backend_property
    dynamic_data = function()
  File "/opt/OpenvStorage/ovs/dal/hybrids/albabackend.py", line 165, in _local_stack
    for found_osd in AlbaCLI.run(command='list-all-osds', config=config, to_json=True):
  File "/opt/OpenvStorage/ovs/extensions/plugins/albacli.py", line 69, in run
    raise RuntimeError(output.get('error', {}).get('message'))
RuntimeError: Client_helper.MasterLookupResult.Error(_)
```

**Comment by kinvaris** [comment]
After restoring the problem on that arakoon, everything went back to normal

**Comment by wimpers** [comment]
Hence this one can be closed?

**Comment by wimpers** [comment]
Arakoon issue https://github.com/openvstorage/alba/issues/264
