### ISSUE TITLE
"Too many open files" connect during ASD claim on RDMA

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#707]
```
2016-07-07 05:06:50 29700 -0700 - sierra01 - 46010/139908410165056 - celery/celery.worker.job - 634 - ERROR - Task alba.add_units[4a10c6c
f-cbc9-4b83-aa87-cfd8857112c8] raised unexpected: RuntimeError(u'(Unix.Unix_error "Too many open files" connect "")',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albacontroller.py", line 119, in add_units
    AlbaCLI.run(command='claim-osd', config=config, long_id=osd_id, to_json=True)
  File "/opt/OpenvStorage/ovs/extensions/plugins/albacli.py", line 69, in run
    raise RuntimeError(output.get('error', {}).get('message'))
RuntimeError: (Unix.Unix_error "Too many open files" connect "")
```

**Comment by kinvaris** [comment]
Sometimes it works, sometimes it gives this error
