### ISSUE TITLE
IndexError: list index out of range when initializing ASDs

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#708]
```
2016-07-08 14:55:52 75800 +0200 - stor-01.be-gen8-2 - 31596/140261434885952 - celery/celery.worker.job - 285 - ERROR - Task albanode.initialize_disk[de879ad4-d7a1-418c-bf3e-330b0b4190da] raised unexpected: IndexError('list index out of range',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albanodecontroller.py", line 134, in initialize_disks
    partition = disk.partitions[0]
  File "/opt/OpenvStorage/ovs/dal/datalist.py", line 627, in __getitem__
    guid = self._guids[item]
IndexError: list index out of range
```

**Comment by khenderick** [comment]
Based on the very minimal logging snippet above, this should only happen if `DiskController.sync_with_reality(...)` would have failed, but I'm missing relevant logging for giving any more clues on what actually went wrong here. We'll only be able to fix it if we can somehow reproduce it.

**Comment by kinvaris** [comment]
Will reopen when reproduced.
