### ISSUE TITLE
Docker gives problems on OVS node

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#741]
I had to delete a docker bridge on my system because ovs cannot communicate through other nodes via docker.

Then got this error during partitioning:

```
2016-07-25 17:19:19 79200 +0200 - cmp04 - 4895/139806611666752 - celery/celery.worker.job - 188 - ERROR - Task ovs.storagerouter.configure_disk[2a27e8d2-9343-4f04-af38-cc4787fbc4b9] raised unexpected: OSError(13, 'Permission denied')
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 301, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1806, in configure_disk
    DiskController.sync_with_reality(storagerouter_guid)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 167, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 301, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/disk.py", line 169, in sync_with_reality
    partition_data['inode'] = rem.os.stat(mountpoint).st_dev
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
Exception: [Errno 13] Permission denied
```

Cannot sync with reality, same problem.

Saw this: 
`/dev/disk/by-uuid/45f0a981-6de7-403d-b3ca-cc972dfccf13 on /var/lib/docker/aufs type ext4 (rw,noatime,errors=remount-ro,data=ordered)`

umounted and stopped docker service:

```
root@cmp04:~# umount /var/lib/docker/aufs
root@cmp04:~# service docker stop
docker stop/waiting
```

Then it worked again...

**Comment by khenderick** [comment]
@kinvaris if you happen to see another occurrence of this issue, can you please check the access rights on `/var/lib/docker/aufs`? I wonder how readable that directory is for non-root users.

**Comment by wimpers** [comment]
Doesn't Docker require Weave to communicate between nodes? Maybe @dejonghb  can help.

**Comment by kinvaris** [comment]
@wimpers: why would we need docker on top of Open vStorage?

**Comment by kinvaris** [comment]
@wimpers: Docker needs weave indeed to communicate between nodes but this is irrelevant in this situation because we use Open vStorage in docker. In this case its a bare metal Open vStorage with docker problems.

**Comment by dejonghb** [comment]
Isn't this because all IP's were selected to use for communication between nodes? During setup there's those questions about which IP's to use which allows choosing 'all' to exclude private things (like docker).

With regards to weave: there's also a macvlan option since docker 1.12 that is a better mechanism now.

**Comment by wimpers** [comment]
@kinvaris can you explain the use case and setup/scenario as we are confused what you are trying to reach. Is this a docker issue or an ovs issue?

**Comment by kinvaris** [comment]
Its just a to be documented problem.
While performing a setup I had to remove the docker components like `/var/lib/docker/aufs` and docker bridge before being able to complete it.

**Comment by kinvaris** [comment]
After a dicussion with @dejonghb, we decided to split this ticket in 2 seperate tickets.
- OVS framework should ignore `Permission denied` and just skip those mount points.
- OVS framework should not ssh-keyscan on all ip addresses. Instead, ip addresses should be given.

**Comment by wimpers** [comment]
@kinvaris this one can be closed?
