### ISSUE TITLE
Configure_disk failed to partition disk

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#764]
```
- Ensure single CHAINED mode - ID 1470226924_OeVY6hdOKK - New task ovs.storagerouter.configure_disk
 with params {'partition_guid': None, 'roles': [], 'disk_guid': u'572f35ee-6448-4553-8024-e5e04f709
0bc', 'storagerouter_guid': 'f562bee9-bf82-4e0d-abfb-5aa4ae132dbb', 'offset': 0, 'size': 1000302428
16} scheduled for execution


2016-08-03 14:22:17 21900 +0200 - cmp02 - 22800/139687725451072 - celery/celery.worker.job - 9467 -
 ERROR - Task ovs.storagerouter.configure_disk[fe30cdb8-32f6-45fa-8375-9603316b404d] raised unexpec
ted: CalledProcessError()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call_
_
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 301, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1816, in configure_disk
    partition_size=size)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
Exception
```

We solved the error by re-adding a gpt label to the disk: `parted /dev/sdX -s mklabel gpt`

**Comment by kvanhijf** [comment]
Most likely fixed by https://github.com/openvstorage/framework/issues/792

**Comment by JeffreyDevloo** [comment]
### Information
We did not encounter this issue anymore on our automated testing environments.
