### ISSUE TITLE
In some cases, the framework doesn't "see" the root mountpoint

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/framework#792]
env: KLONE - cluster3

ovs-workers.log

```
2016-08-09 13:53:12 36600 +0200 - cmp03 - 5489/140148209542976 - celery/celery.worker.job - 359 - ERROR - Task ovs.storagerouter.add_vpool[cc60755c-63b1-421c-8b26-35f2fb7b1552] raised unexpected: ValueError('Errors validating the partition roles:\n - Mountpoint /mnt/ssd4 is not mounted',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 539, in add_vpool
    raise ValueError('Errors validating the partition roles:\n - {0}'.format('\n - '.join(set(error_messages))))
ValueError: Errors validating the partition roles:
 - Mountpoint /mnt/ssd4 is not mounted
2016-08-09 13:54:02 18800 +0200 - cmp03 - 5489/140148209542976 - celery/celery.worker.strategy - 360 - INFO - Received task: ovs.storagerouter.ping[7dac7aa5-40ae-4d2e-89c5-a315e507c070]

```

**Comment by khenderick** [comment]
Some observations:
- When a partition is mounted and has a role assigned, and the partition would be for whatever reason unmounted, a sync won't set the mountpoint to None again. The assign role won't in turn re-mount the partition because it thinks it's already mounted.
- Yet unknown; why isn't that partition mounted? The mountpoint in the model can only be filled if it was mounted at the end of the role assignment code.
- `/mnt/ssd4` as configured in `/etc/fstab` is actually pointing towards the root partition. So why did the sync or role assignment not see that this partition is `/`?

**Comment by khenderick** [comment]
Might have to do with blkid causing the code to not see the mounted root. Collected information:

cmp03 (has the issue)

```
root@cmp03:~# mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,relatime,size=65992844k,nr_inodes=16498211,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=13200820k,mode=755)
/dev/disk/by-uuid/dfec6c66-9379-4bfb-a4c2-c3d1a937f253 on / type ext4 (rw,noatime,errors=remount-ro,data=ordered)
none on /sys/fs/cgroup type tmpfs (rw,relatime,size=4k,mode=755)
none on /sys/fs/fuse/connections type fusectl (rw,relatime)
none on /sys/kernel/debug type debugfs (rw,relatime)
none on /sys/kernel/security type securityfs (rw,relatime)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
none on /run/shm type tmpfs (rw,nosuid,nodev,relatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,relatime,size=102400k,mode=755)
none on /sys/fs/pstore type pstore (rw,relatime)
/dev/sda1 on /boot type vfat (rw,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
rpc_pipefs on /run/rpc_pipefs type rpc_pipefs (rw,relatime)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,name=systemd)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
/dev/sdb1 on /mnt/ssd1 type ext4 (rw,noatime,discard,data=ordered,_netdev)
/dev/sdc1 on /mnt/ssd2 type ext4 (rw,noatime,discard,data=ordered,_netdev)
/dev/sdd1 on /mnt/ssd3 type ext4 (rw,noatime,discard,data=ordered,_netdev)
root@cmp03:~# cat /etc/fstab
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
proc            /proc   proc    defaults                0       0
sysfs           /sys    sysfs   defaults                0       0
devtmpfs        /dev    devtmpfs        rw      0       0
UUID=dfec6c66-9379-4bfb-a4c2-c3d1a937f253  / ext4 errors=remount-ro,noatime 0 1
UUID=ff0f0c16-5c40-4cde-bcda-286c047b92fb none swap sw 0 2
UUID=5CA2-4EA7 /boot/ vfat errors=remount-ro,noatime 0 3
# END OS Install
/dev/disk/by-id/wwn-0x50015178f35c53fb-part1    /mnt/ssd1         ext4    defaults,nobootwait,noatime,discard    0    2
/dev/disk/by-id/wwn-0x55cd2e4000004a39-part1    /mnt/ssd2         ext4    defaults,nobootwait,noatime,discard    0    2
/dev/disk/by-id/wwn-0x55cd2e4000004dc8-part1    /mnt/ssd3         ext4    defaults,nobootwait,noatime,discard    0    2
/dev/disk/by-id/wwn-0x5e83a97f418d9116-part3    /mnt/ssd4         ext4    defaults,nobootwait,noatime,discard    0    2
root@cmp03:~# blkid 
/dev/sda1: UUID="5CA2-4EA7" TYPE="vfat" 
/dev/sda2: UUID="ff0f0c16-5c40-4cde-bcda-286c047b92fb" TYPE="swap" 
/dev/sda3: UUID="dfec6c66-9379-4bfb-a4c2-c3d1a937f253" TYPE="ext4" 
/dev/sdb1: UUID="2a87cf43-b9e5-4293-ac8a-1521fb637970" TYPE="ext4" 
/dev/sdc1: UUID="f7f13ddf-0ee8-4c4b-9ad7-ac34bbd0cb42" TYPE="ext4" 
/dev/sdd1: UUID="9c2a4eae-bcb9-4951-91b4-3d1786057884" TYPE="ext4" 
```

cmp05 (doesn't have an issue)

```
root@cmp05:~# mount
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,relatime,size=65992836k,nr_inodes=16498209,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=13200820k,mode=755)
/dev/disk/by-uuid/1a0c9389-6516-4464-a561-5cce88b58847 on / type ext4 (rw,noatime,errors=remount-ro,data=ordered)
none on /sys/fs/cgroup type tmpfs (rw,relatime,size=4k,mode=755)
none on /sys/fs/fuse/connections type fusectl (rw,relatime)
none on /sys/kernel/debug type debugfs (rw,relatime)
none on /sys/kernel/security type securityfs (rw,relatime)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
none on /run/shm type tmpfs (rw,nosuid,nodev,relatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,relatime,size=102400k,mode=755)
none on /sys/fs/pstore type pstore (rw,relatime)
/dev/sda1 on /boot type vfat (rw,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
rpc_pipefs on /run/rpc_pipefs type rpc_pipefs (rw,relatime)
systemd on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,name=systemd)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,relatime,cpuset)
cgroup on /sys/fs/cgroup/cpu type cgroup (rw,relatime,cpu)
cgroup on /sys/fs/cgroup/cpuacct type cgroup (rw,relatime,cpuacct)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,relatime,memory)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls type cgroup (rw,relatime,net_cls)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,relatime,perf_event)
cgroup on /sys/fs/cgroup/net_prio type cgroup (rw,relatime,net_prio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,relatime,hugetlb)
/dev/sdb1 on /mnt/ssd1 type ext4 (rw,noatime,discard,data=ordered,_netdev)
/dev/sdc1 on /mnt/ssd2 type ext4 (rw,noatime,discard,data=ordered,_netdev)
/dev/sdd1 on /mnt/ssd3 type ext4 (rw,noatime,discard,data=ordered,_netdev)
root@cmp05:~# cat /etc/fstab
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
proc            /proc   proc    defaults                0       0
sysfs           /sys    sysfs   defaults                0       0
devtmpfs        /dev    devtmpfs        rw      0       0
UUID=1a0c9389-6516-4464-a561-5cce88b58847  / ext4 errors=remount-ro,noatime 0 1
UUID=194e8ecf-e15e-49da-b0d1-f2bd3824fb9d none swap sw 0 2
UUID=4432-F132 /boot/ vfat errors=remount-ro,noatime 0 3
# END OS Install
/dev/disk/by-id/wwn-0x50015178f35c5462-part1    /mnt/ssd1         ext4    defaults,nobootwait,noatime,discard    0    2
/dev/disk/by-id/wwn-0x5001517803db6afa-part1    /mnt/ssd2         ext4    defaults,nobootwait,noatime,discard    0    2
/dev/disk/by-id/wwn-0x5002538570001a8e-part1    /mnt/ssd3         ext4    defaults,nobootwait,noatime,discard    0    2
root@cmp05:~# blkid 
/dev/disk/by-uuid/1a0c9389-6516-4464-a561-5cce88b58847: UUID="1a0c9389-6516-4464-a561-5cce88b58847" TYPE="ext4" 
/dev/sda1: UUID="4432-F132" TYPE="vfat" 
/dev/sda2: UUID="194e8ecf-e15e-49da-b0d1-f2bd3824fb9d" TYPE="swap" 
/dev/sdb1: UUID="6e6f1043-ca5c-46d2-953d-bf748f569452" TYPE="ext4" 
/dev/sdc1: UUID="67c03616-a8bc-449d-bb58-c7e1126c9541" TYPE="ext4" 
/dev/sdd1: UUID="859e7889-f91f-4ba6-9e1f-ccc8aac4e508" TYPE="ext4" 
root@cmp05:~# 
```

**Comment by khenderick** [comment]
Increased to urgent as this basically allows you to mess up your root partition.

**Comment by kvanhijf** [comment]
As agreed with @khenderick , we will rework the `sync_with_reality` code and the `configure_disk` code in order to prevent these errors from happening again
Since we no longer have access to this environment, we cannot verify the logs anymore

**Comment by kvanhijf** [comment]
https://github.com/openvstorage/framework/pull/1005  --> openvstorage-2.7.4-rev.4123.ef930a7
https://github.com/openvstorage/alba-asdmanager/pull/127 --> openvstorage-backend-1.7.4-rev.756.088c2ee
https://github.com/openvstorage/framework-alba-plugin/pull/231 --> openvstorage-sdm-1.6.4-rev.386.8590475

All kind of devices should now be detected properly when hitting the 'Rescan' button in the GUI
All kind of devices should also be usable as ASDs
Clicking on dropdown of an AlbaDisk should show both usage and aliases for that disk

**Comment by JeffreyDevloo** [comment]
### Steps
- Setup latest cluster
- Checked disks
- Checked if mountpoint was in use

### Output

#### GUI

![selection_059](https://cloud.githubusercontent.com/assets/17570109/20354550/d0b7bc62-ac1e-11e6-9893-4f3c7aca72bc.png)

#### Mountpoint

```
root@ovs-node-1:~# lsblk
NAME                        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda                           8:0    0  4.9G  0 disk 
└─sda1                        8:1    0  4.9G  0 part /mnt/alba-asd/FfxdJCnDdL7C0fHF
sdb                           8:16   0  4.9G  0 disk 
└─sdb1                        8:17   0  4.9G  0 part /mnt/alba-asd/Cxy4xtRkzdM1px5q
sdc                           8:32   0  4.9G  0 disk 
└─sdc1                        8:33   0  4.9G  0 part /mnt/alba-asd/DDDmGVHl0Qt0BYzz
sdd                           8:48   0   50G  0 disk 
└─sdd1                        8:49   0   50G  0 part /mnt/hdd1
sde                           8:64   0  9.8G  0 disk 
└─sde1                        8:65   0  9.8G  0 part /mnt/hdd2
sdf                           8:80   0  9.8G  0 disk 
└─sdf1                        8:81   0  9.8G  0 part /mnt/hdd3
sdg                           8:96   0  9.8G  0 disk 
└─sdg1                        8:97   0  9.8G  0 part 
sr0                          11:0    1  667M  0 rom  
vda                         253:0    0 24.4G  0 disk 
├─vda1                      253:1    0  487M  0 part /boot
├─vda2                      253:2    0    1K  0 part 
└─vda5                      253:5    0   24G  0 part 
  ├─ovs--node--1--vg-root   252:0    0    8G  0 lvm  /
  └─ovs--node--1--vg-swap_1 252:1    0   16G  0 lvm  [SWAP]

for p in DiskPartitionList.get_partitions():
    if p.mountpoint == '/':
        print p.guid
        print p.aliases
   ...:         
33db4409-2a1c-435c-9e67-84cf69e66bd8
[u'/dev/disk/by-id/dm-uuid-LVM-zxDF2lkufgSKnydRxNLAcrO7VTKMY3Lh167g9fq8TAoehYZdPsSS5LHlBV7e4VpA', u'/dev/disk/by-id/dm-name-ovs--node--1--vg-root']
```

### Test result

Root mountpoint was detected without error.
Test passed.
