### ISSUE TITLE
Remove node: Could not acquire lock

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#798]
# Problem description

Got 'Could not acquire lock' when running ovs remove node
# Possible root of the problem

Memcache?
# Possible solution

None
# Temporary solution

None
# Additional information

Stacktrace:
The 39a27a50-5aac-408b-92c5-47b2640eb1b8 in   ovs_lock_ovs_dataversion_storagerouter_39a27a50-5aac-408b-92c5-47b2640eb1b8 is the GUID of the storage router that was going to be removed.
root@ovs-node1:~# ovs remove nodes 10.100.199.153

```

\++\+ Remove nodes started \++\+

WARNING: Some of these steps may take a very long time, please check the logs for more logging information

Following nodes with IPs will be removed from the cluster: \['10.100.199.153'\]

Creating SSH connections to remaining master nodes

Node with IP 10.100.199.153  successfully connected to

Node with IP 10.100.199.151  successfully connected to

Node with IP 10.100.199.152  successfully connected to

Starting removal of nodes

Cleaning up node with IP 10.100.199.153

Removing vPool vm-vpool from node

\++\+ Demoting node \++\+

Leaving Arakoon ovsdb cluster

Leaving Etcd cluster

Update configurations

Restarting master node services

Removing/unconfiguring RabbitMQ

\[10.100.199.153\] rabbitmq-server already halted

Removing services

Removing service memcached

\[10.100.199.153\] memcached stopped

Removing service rabbitmq-server

\[10.100.199.153\] rabbitmq-server already halted

Removing service scheduled-tasks

\[10.100.199.153\] scheduled-tasks stopped

Removing service snmp

\[10.100.199.153\] snmp stopped

Removing service webapp-api

\[10.100.199.153\] webapp-api stopped

Removing service volumerouter-consumer

\[10.100.199.153\] volumerouter-consumer stopped

Update existing vPools

Restarting services

\[10.100.199.151\] watcher-framework stopped

\[10.100.199.152\] watcher-framework stopped

\[10.100.199.153\] watcher-framework stopped

\[10.100.199.151\] memcached restarted

\[10.100.199.152\] memcached restarted

\[10.100.199.151\] watcher-framework started

\[10.100.199.152\] watcher-framework started

\[10.100.199.153\] watcher-framework started

\++\+ Running "demote" hooks \++\+

\++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\+

\++\+  An unexpected error occurred:                                                \++\+

\++\+  Could not acquire lock                                                       \++\+

\++\+  ovs_lock_ovs_dataversion_storagerouter_39a27a50-5aac-408b-92c5-47b2640eb1b8  \++\+

\++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\+
```

root@ovs-node1:~# less /var/log/ovs/lib.log

```
2016-08-10 09:48:34 62700 \+0200 - ovs-node1 - 2727/139632255706944 - lib/alba - 183 - INFO - Shrinking NSM for backend "vm-backend"

2016-08-10 09:48:34 65200 \+0200 - ovs-node1 - 2727/139632255706944 - lib/alba - 184 - INFO - * Shrink NSM cluster 0

2016-08-10 09:48:38 77000 \+0200 - ovs-node1 - 2727/139632255706944 - lib/alba - 194 - INFO - * Restarting NSM cluster 0

2016-08-10 09:48:56 31800 \+0200 - ovs-node1 - 2727/139632255706944 - lib/alba - 213 - INFO - * Remove old NSM node from model

2016-08-10 09:49:26 57000 \+0200 - ovs-node1 - 2727/139632255706944 - lib/setup - 215 - INFO -

2016-08-10 09:49:26 57100 \+0200 - ovs-node1 - 2727/139632255706944 - lib/setup - 216 - ERROR - An unexpected error occurred:

Traceback (most recent call last):

File "ovs/lib/setup.py", line 699, in remove_nodes

offline_nodes=storage_routers_offline)

File "ovs/lib/setup.py", line 1338, in \_demote_node

if SetupController._run_hooks('demote', cluster_ip, master_ip, offline_node_ips=offline_node_ips):

File "ovs/lib/setup.py", line 1655, in \_run_hooks

function(cluster_ip=cluster_ip, master_ip=master_ip, \**kwargs)

File "ovs/lib/helpers/..//storagedriver.py", line 108, in on_demote

if service.name == 'arakoon-voldrv' and service.is_internal is True:  # Externally managed arakoon cluster service does not have storage router

File "ovs/dal/dataobject.py", line 341, in <lambda>

fget = lambda s: s._get_dynamic_property(dynamic)

File "ovs/dal/dataobject.py", line 410, in \_get_dynamic_property

return self._backend_property(data_loader, dynamic)

File "ovs/dal/dataobject.py", line 904, in \_backend_property

dynamic_data = function()

File "ovs/dal/hybrids/service.py", line 41, in \_is_internal

return self.storagerouter is not None

File "ovs/dal/dataobject.py", line 318, in <lambda>

fget = lambda s: s._get_relation_property(relation)

File "ovs/dal/dataobject.py", line 360, in \_get_relation_property

self._objects\[attribute\] = descriptor.get_object(instantiate=True)

File "ovs/dal/helpers.py", line 110, in get_object

return cls(self._descriptor\['guid'\])

File "ovs/dal/dataobject.py", line 273, in \__init_\_

self._mutex_version.acquire(30)

File "ovs/extensions/generic/volatilemutex.py", line 77, in acquire

raise NoLockAvailableException('Could not acquire lock {0}'.format(self.key()))

NoLockAvailableException: Could not acquire lock ovs_lock_ovs_dataversion_storagerouter_9727df33-57c8-42bb-bb75-9bf548e54d1d

2016-08-10 09:49:26 57200 \+0200 - ovs-node1 - 2727/139632255706944 - lib/setup - 217 - ERROR - Could not acquire lock ovs_lock_ovs_dataversion_storagerouter_9727df33-57c8-42bb-bb75-9bf548e54d1d

Traceback (most recent call last):

File "ovs/lib/setup.py", line 699, in remove_nodes

offline_nodes=storage_routers_offline)

File "ovs/lib/setup.py", line 1338, in \_demote_node

if SetupController._run_hooks('demote', cluster_ip, master_ip, offline_node_ips=offline_node_ips):

File "ovs/lib/setup.py", line 1655, in \_run_hooks

function(cluster_ip=cluster_ip, master_ip=master_ip, \**kwargs)

File "ovs/lib/helpers/..//storagedriver.py", line 108, in on_demote

if service.name == 'arakoon-voldrv' and service.is_internal is True:  # Externally managed arakoon cluster service does not have storage router

File "ovs/dal/dataobject.py", line 341, in <lambda>

fget = lambda s: s._get_dynamic_property(dynamic)

File "ovs/dal/dataobject.py", line 410, in \_get_dynamic_property

return self._backend_property(data_loader, dynamic)

File "ovs/dal/dataobject.py", line 904, in \_backend_property

dynamic_data = function()

File "ovs/dal/hybrids/service.py", line 41, in \_is_internal

return self.storagerouter is not None

File "ovs/dal/dataobject.py", line 318, in <lambda>

fget = lambda s: s._get_relation_property(relation)

File "ovs/dal/dataobject.py", line 360, in \_get_relation_property

self._objects\[attribute\] = descriptor.get_object(instantiate=True)

File "ovs/dal/helpers.py", line 110, in get_object

return cls(self._descriptor\['guid'\])

File "ovs/dal/dataobject.py", line 273, in \__init_\_

self._mutex_version.acquire(30)

File "ovs/extensions/generic/volatilemutex.py", line 77, in acquire

raise NoLockAvailableException('Could not acquire lock {0}'.format(self.key()))

NoLockAvailableException: Could not acquire lock ovs_lock_ovs_dataversion_storagerouter_9727df33-57c8-42bb-bb75-9bf548e54d1d
```

root@ovs-node1:~# less /var/log/ovs/extensions.log

```
2016-08-10 11:08:12 04500 \+0200 - ovs-node1 - 10651/140198443030336 - extensions/volatile mutex - 187 - ERROR - Lock for ovs_lock_ovs_dataversion_storagerouter_39a27a50-5aac-408b-92c5-47b2640eb1b8 could not be acquired. 30.0031878948 sec > 30 sec

```
## Setup

Hyperconverged setup
- Three nodes with each three disks for the back-end
- All disks were initialized and claimed by a back-end
- All nodes were part of a vPool
## Package information
- ii  openvstorage                       2.7.1-fargo.2-1                                          amd64        openvStorage
- ii  openvstorage-backend               1.7.1-fargo.1-1                                          amd64        openvStorage Backend plugin
- ii  openvstorage-backend-core          1.7.1-fargo.1-1                                          amd64        openvStorage Backend plugin core
- ii  openvstorage-backend-webapps       1.7.1-fargo.1-1                                          amd64        openvStorage Backend plugin Web Applications
- ii  openvstorage-cinder-plugin         1.2.1-fargo.1-1                                          amd64        OpenvStorage Cinder plugin for OpenStack
- ii  openvstorage-core                  2.7.1-fargo.2-1                                          amd64        openvStorage core
- ii  openvstorage-hc                    1.7.1-fargo.1-1                                          amd64        openvStorage Backend plugin HyperConverged
- ii  openvstorage-sdm                   1.6.1-fargo.1-1                                          amd64        Open vStorage Backend ASD Manager
- ii  openvstorage-test                  2.7.1-fargo.2-1                                          amd64        openvStorage autotest suite
- ii  openvstorage-webapps               2.7.1-fargo.2-1                                          amd64        openvStorage Web Applications

**Comment by khenderick** [comment]
Due to the amount of reproductions by @JeffreyDevloo, I suspect that during service restart memcached stays unavailable for slightly too long, so we should build in some wait after restarting the services before we proceed.

**Comment by khenderick** [comment]
After discussion with @JeffreyDevloo, setting this one again on state_verification. This issue was created at the time a lot of `ovs remove node` related bugs were fixed, so it's likely to be resolved in the process, or being caused by side effects of these bugs. I removed nodes from a 4-node setup and did not encounter the reported issue.

**Comment by JeffreyDevloo** [comment]
### Steps
- Setup cluster
- Configured cluster
- Removed 2 of the 3 nodes

### Output
All the nodes were removed.

### Test result
Test passed.

### Packages
```
ii  openvstorage                                        2.7.9-rev.4463.0761b63-1       amd64                          openvStorage
ii  openvstorage-backend                                1.7.9-rev.889.63f8d79-1        amd64                          openvStorage Backend plugin
ii  openvstorage-backend-core                           1.7.9-rev.889.63f8d79-1        amd64                          openvStorage Backend plugin core
ii  openvstorage-backend-webapps                        1.7.9-rev.889.63f8d79-1        amd64                          openvStorage Backend plugin Web Applications
ii  openvstorage-core                                   2.7.9-rev.4463.0761b63-1       amd64                          openvStorage core
ii  openvstorage-hc                                     1.7.9-rev.889.63f8d79-1        amd64                          openvStorage Backend plugin HyperConverged
ii  openvstorage-sdm                                    1.6.9-rev.508.9903a29-1        amd64                          Open vStorage Backend ASD Manager
ii  openvstorage-webapps                                2.7.9-rev.4463.0761b63-1       amd64                          openvStorage Web Applications

```
