### ISSUE TITLE
MaxRedirectsExceededException: snapshotInfo

### ISSUE THREAD

**Issue by domsj** [openvstorage/framework#803]
Saw this error in api.log on OVH

```
2016-08-10 16:16:37 88000 +0200 - ctrl-roub-01 - 85656/140463931913552 - api/middleware - 3737 - ERROR - An unhandled exception occurred: snapshotInfo 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 78, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 399, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python2.7/dist-packages/rest_framework/views.py", line 396, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 443, in new_function
    return_value = f(*args, **kwargs)
  File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 79, in new_function
    return f(*args, **kw)
  File "/opt/OpenvStorage/webapps/api/backend/decorators.py", line 304, in new_function
    return Response(FullSerializer(object_type, contents=contents, instance=obj).data, status=status.HTTP_200_OK)
  File "/usr/lib/python2.7/dist-packages/rest_framework/serializers.py", line 573, in data
    self._data = self.to_native(obj)
  File "/usr/lib/python2.7/dist-packages/rest_framework/serializers.py", line 349, in to_native
    value = field.field_to_native(obj, field_name)
  File "/usr/lib/python2.7/dist-packages/rest_framework/fields.py", line 198, in field_to_native
    value = get_component(value, component)
  File "/usr/lib/python2.7/dist-packages/rest_framework/fields.py", line 56, in get_component
    val = getattr(obj, attr_name)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 341, in <lambda>
    fget = lambda s: s._get_dynamic_property(dynamic)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 410, in _get_dynamic_property
    return self._backend_property(data_loader, dynamic)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 904, in _backend_property
    dynamic_data = function()
  File "/opt/OpenvStorage/ovs/dal/hybrids/vdisk.py", line 123, in _snapshots
    snapshot = self.storagedriver_client.info_snapshot(volume_id, id)
MaxRedirectsExceededException: snapshotInfo 
```

Version: 2.7.1-fargo.2-1

**Comment by khenderick** [comment]
@redlicha, any idea what the `MaxRedirectsExceededException` would mean?

**Comment by khenderick** [comment]
We need volumedriver logs to see why it raised this `MaxRedirectsExceededException`. The maximum is set to 2 by default (not customisable) which should be sufficient (if we ask it to the wrong volumedriver, it should redirect it to the correct one). An offline node should raise an `NodeNotReachableException`.

Suggest to close and re-open if reproduced.

**Comment by wimpers** [comment]
Assigning to @redlicha for answers

**Comment by wimpers** [comment]
After discussion with @khenderick set to can't reproduce. If this happens again, please re-open and add the relevant voldrv logs.

**Comment by kvanhijf** [comment]
This error can occur when a volume is stopped, but has not been restarted. Why the volume was stopped is obviously impossible to check without logs
The errormessage however will from now on be more meaningful
Improved by https://github.com/openvstorage/framework/issues/1089
