### ISSUE TITLE
vPool re-creation failed: StorageDriver service failed to start

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#811]
Steps to reproduce:
1. Create vPool.
2. Delete it.
3. Recreate with same name.
4. result

```
2016-08-12 12:02:26 72400 +0200 - ctl02 - 31173/139693366105920 - celery/celery.worker.job - 9750 - ERROR - Task ovs.storagerouter.add_vpool[6afcfa49-6520-41ed-b847-8f08
4a06d853] raised unexpected: RuntimeError('StorageDriver service failed to start (service not running)',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 997, in add_vpool
    raise RuntimeError('StorageDriver service failed to start (service not running)')
RuntimeError: StorageDriver service failed to start (service not running)
```

```
2016-08-12 12:02:24 470872 +0200 - cmp02 - 22664/0x00007f5bbe657940 - volumedriverfs/volumedriver_fs - 000000000000010c -  fatal - operator(): caught exception: boost::filesystem::status: Transport endpoint is not connected: "/mnt/myvpool"
```

**Comment by kinvaris** [comment]
After some digging it appeared to be that the vpool directory under `/mnt` was not properly removed.

**Comment by wimpers** [comment]
@kinvaris QA does this scenario almost daily and they don't see this issue. We assume that the delete wasn't finished correctly. Do you have any logs available? Can you consistently reproduce this somehow?

**Comment by kinvaris** [comment]
@wimpers: Will retest this to verify the issue.

**Comment by kinvaris** [comment]
Issue failed to reproduce
