### ISSUE TITLE
`Disk None is not yet initialized` when removing ASD from missing disk

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#815]
```
2016-08-12 14:46:12 34400 +0200 - cmp02 - 20499/140263485323072 - celery/celery.worker.job - 11144 - ERROR - Task albanode.reset_asd[a4e7f233-2b4c-4171-b689-909623f44c15] raised unexpected: RuntimeError(u'Disk None is not yet initialized',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albanodecontroller.py", line 279, in reset_asd
    raise RuntimeError(result['_error'])
RuntimeError: Disk None is not yet initialized
```

After the error the ASD in question is gone.

**Comment by kvanhijf** [comment]
Most likely fixed by https://github.com/openvstorage/framework/issues/792

**Comment by JeffreyDevloo** [comment]
### Information
Verified when I was verifying https://github.com/openvstorage/framework-alba-plugin/issues/174.
ASDS can be removed from a missing disk.
