### ISSUE TITLE
unknown osd but still claimed in GUI

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#822]
- Unclaimed ASD, took a long time. 
- Refreshed. 
- ASD is still present but in `unavailable`
- ASD process is still present

```
ASD Manager running processes:

alba-asd-MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B start/running, process 25858
```
- Stopped the ASD process, was able to remove it via GUI. But disk safety was being calculated. Then saw this error:

```
2016-08-18 15:03:43 62600 +0200 - cmp05 - 20292/139676040619840 - celery/celery.worker.job - 460 - ERROR - Task alba.calculate_safety[62e53b34-0212-487f-81c7-7b610cd5670a] raised unexpected: RuntimeError(u'(Failure "unknown osd MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B")',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albacontroller.py", line 959, in calculate_safety
    safety_data = AlbaCLI.run(command='get-disk-safety', config=config, to_json=True, extra_params=extra_parameters)
  File "/opt/OpenvStorage/ovs/extensions/plugins/albacli.py", line 103, in run
    raise RuntimeError(output['error']['message'])
RuntimeError: (Failure "unknown osd MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B")
```

Delete of ASD is seen here:

```
2016-08-18 14:55:44 18900 +0200 - cmp05 - 20292/139676040619840 - celery/celery.worker.job - 327 - DEBUG - Task accepted: albanode.reset_asd[1d63a9c6-7a9e-4bce-8bbc-101f72bd012f] pid:1425
2016-08-18 14:55:44 26300 +0200 - cmp05 - 1425/139676040619840 - lib/scheduled tasks - 326 - INFO - Ensure single CHAINED mode - ID 1471524944_dRqUwGDdXR - New task albanode.remove_asd with params 
{'node_guid': '8503e317-59ba-4954-b1b6-fd2c46cec9d7', 'asd_id': u'MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B', 'expected_safety': {u'good': 0, u'critical': 0, u'lost': 0}} scheduled for execution
2016-08-18 14:55:44 26900 +0200 - cmp05 - 1425/139676040619840 - lib/albanode - 327 - DEBUG - Removing ASD MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B at node 172.19.12.203
[2016-08-18 14:55:44,291: INFO/Worker-13] Starting new HTTPS connection (1): 172.19.12.203
2016-08-18 14:55:45 06400 +0200 - cmp05 - 1425/139676040619840 - celery/celery.redirected - 329 - WARNING - 2016-08-18 14:55:45 06400 +0200 - cmp05 - 1425/139676040619840 - extensions/albacli - 328
 - ERROR - Error: Client_helper.MasterLookupResult.Error(_)
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/extensions/plugins/albacli.py", line 103, in run
    raise RuntimeError(output['error']['message'])
RuntimeError: Client_helper.MasterLookupResult.Error(_)
2016-08-18 14:55:45 06500 +0200 - cmp05 - 1425/139676040619840 - celery/celery.redirected - 331 - WARNING - 2016-08-18 14:55:45 06500 +0200 - cmp05 - 1425/139676040619840 - extensions/albacli - 330
 - DEBUG - Command: /usr/bin/alba get-disk-safety --config=etcd://127.0.0.1:2379/ovs/arakoon/mybackend-abm/config --to-json --include-decommissioning-as-dead --long-id=MJm8UJ1LUbyemRWh8gvi2GToCZ0XS
B1B
2016-08-18 14:55:45 06500 +0200 - cmp05 - 1425/139676040619840 - celery/celery.redirected - 333 - WARNING - 2016-08-18 14:55:45 06500 +0200 - cmp05 - 1425/139676040619840 - extensions/albacli - 332
 - DEBUG - stderr: 2016-08-18 14:55:44 869832 +0200 - cmp05 - 1437/0 - alba/cli - 0 - info - ETCD: etcdctl --peers=127.0.0.1:2379 get --quorum ovs/arakoon/mybackend-abm/config
2016-08-18 14:55:45 06600 +0200 - cmp05 - 1425/139676040619840 - celery/celery.redirected - 335 - WARNING - 2016-08-18 14:55:45 06500 +0200 - cmp05 - 1425/139676040619840 - extensions/albacli - 334
 - DEBUG - stdout: 
{"success":false,"error":{"message":"Client_helper.MasterLookupResult.Error(_)","exception_type":"unknown","exception_code":0}}
2016-08-18 14:55:45 09600 +0200 - cmp05 - 20292/139676040619840 - celery/celery.worker.job - 328 - ERROR - Task albanode.reset_asd[1d63a9c6-7a9e-4bce-8bbc-101f72bd012f] raised unexpected: RuntimeEr
ror(u'Client_helper.MasterLookupResult.Error(_)',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albanodecontroller.py", line 274, in reset_asd
    disk_id = AlbaNodeController.remove_asd(node_guid, asd_id, expected_safety)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 167, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 301, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albanodecontroller.py", line 232, in remove_asd
    final_safety = AlbaController.calculate_safety(alba_backend.guid, [asd_id])
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 167, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albacontroller.py", line 959, in calculate_safety
    safety_data = AlbaCLI.run(command='get-disk-safety', config=config, to_json=True, extra_params=extra_parameters)
  File "/opt/OpenvStorage/ovs/extensions/plugins/albacli.py", line 103, in run
    raise RuntimeError(output['error']['message'])
RuntimeError: Client_helper.MasterLookupResult.Error(_)
```

After that:

```
2016-08-18 15:02:27 66500 +0200 - cmp05 - 20292/139676040619840 - celery/celery.worker.strategy - 429 - INFO - Received task: alba.calculate_safety[e8471310-bf53-4230-a7ea-21da1f315b92]
2016-08-18 15:02:27 66600 +0200 - cmp05 - 20292/139676040619840 - celery/celery.pool - 430 - DEBUG - TaskPool: Apply <function _fast_trace_task at 0x7f08d8398758> (args:('alba.calculate_safety', 'e8471310-bf53-4230-a7ea-21da1f315b92', ('21d8d890-1686-4b1f-a241-5a8883a774ce', [u'MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B']), {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': ('21d8d890-1686-4b1f-a241-5a8883a774ce', [u'MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B']), 'retries': 0, u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'generic.#', u'exchange': u'generic'}, 'expires': None, u'hostname': 'celery@cmp05', 'task': 'alba.calculate_safety', 'callbacks': None, u'correlation_id': u'e8471310-bf53-4230-a7ea-21da1f315b92', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': u'ea9d2407-a86e-30d0-b38d-7c9a9a40b4b4', 'id': 'e8471310-bf53-4230-a7ea-21da1f315b92', u'headers': {}}) kwargs:{})
2016-08-18 15:02:27 66700 +0200 - cmp05 - 20292/139676040619840 - celery/celery.worker.job - 431 - DEBUG - Task accepted: alba.calculate_safety[e8471310-bf53-4230-a7ea-21da1f315b92] pid:2486
2016-08-18 15:02:27 80700 +0200 - cmp05 - 2486/139676040619840 - celery/celery.redirected - 427 - WARNING - 2016-08-18 15:02:27 80600 +0200 - cmp05 - 2486/139676040619840 - extensions/albacli - 426 - ERROR - Error: (Failure "unknown osd MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B")
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/extensions/plugins/albacli.py", line 103, in run
    raise RuntimeError(output['error']['message'])
RuntimeError: (Failure "unknown osd MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B")
```

Config seems available in ETCD: 

```
root@ctl03:~# etcdctl ls ovs/alba --recursive | grep MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B
/ovs/alba/asds/MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B
/ovs/alba/asds/MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B/config

root@ctl03:~# etcdctl get /ovs/alba/asds/MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B/config
{
    "ips": [
        "172.19.12.203"
    ], 
    "asd_id": "MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B", 
    "node_id": "HoExzz5IIIOPhKhuwC8EROrWckZGmzOl", 
    "capacity": 1499566829568, 
    "home": "/mnt/alba-asd/I6NBxeQNgYibtJnY/MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B", 
    "log_level": "info", 
    "rocksdb_block_cache_size": 366105183, 
    "port": 8628, 
    "transport": "rdma", 
    "rora_port": 8629
}

```

**Comment by kinvaris** [comment]
Removed the ASD by the following steps:
- Remove from Etcd:

```
root@ctl03:~# etcdctl rm /ovs/alba/asds/MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B/config
PrevNode.Value: {
    "ips": [
        "172.19.12.203"
    ], 
    "asd_id": "MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B", 
    "node_id": "HoExzz5IIIOPhKhuwC8EROrWckZGmzOl", 
    "capacity": 1499566829568, 
    "home": "/mnt/alba-asd/I6NBxeQNgYibtJnY/MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B", 
    "log_level": "info", 
    "rocksdb_block_cache_size": 366105183, 
    "port": 8628, 
    "transport": "rdma", 
    "rora_port": 8629
}
root@ctl03:~# etcdctl rmdir /ovs/alba/asds/MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B
```
- Search OSD in ovsdb model and delete the object. Now you can removed the disk.

```
from ovs.dal.lists.albabackendlist import AlbaBackendList
a = AlbaBackendList.get_albabackends()[0]
osds = a.osds
broken_osd =  osds[2]
broken_osd.delete()
```
- Remove it in the GUI
- stop process: `stop alba-asd-MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB1B`
- unmount it on the storage node: `umount /mnt/alba-asd/I6NBxeQNgYibtJnY`
- remove `/etc/init/alba-asd-MJm8UJ1LUbyemRWh8gvi2GToCZ0XSB.conf`
- remove from `/etc/fstab`
- remove partition from disk: `parted /dev/sdh -s mklabel gpt`

**Comment by khenderick** [comment]
@kinvaris, please re-validate due to changes in the disk management and the various fixes in the ASD removal logic.

**Comment by wimpers** [comment]
Closed by PM.
