### ISSUE TITLE
Creating multiple backends at once causes them all to fail

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#828]
## Problem description

I was adding multiple backends at once and after a while only the first was installed. I investigated the issue and found the following:
In /var/log/upstart/ovs-workers.log:

```
2016-08-19 15:41:25 99500 +0200 - ovs-node1 - 2935/140020444075840 - celery/celery.worker.strategy - 296 - INFO - Received task: alba.add_cluster[5057bb1a-f247-420b-b2e6-58c7ac51aa0a]
2016-08-19 15:41:25 99500 +0200 - ovs-node1 - 2935/140020444075840 - celery/celery.pool - 297 - DEBUG - TaskPool: Apply <function _fast_trace_task at 0x7f59082da758> (args:('alba.add_cluster', '5057bb1a-f247-420b-b2e6-58c7ac51aa0a', ('b5ddfce9-3bf6-4ab8-aaad-aaa9ef431ce8',), {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': ('b5ddfce9-3bf6-4ab8-aaad-aaa9ef431ce8',), 'retries': 0, u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'generic.#', u'exchange': u'generic'}, 'expires': None, u'hostname': 'celery@ovs-node1', 'task': 'alba.add_cluster', 'callbacks': None, u'correlation_id': u'5057bb1a-f247-420b-b2e6-58c7ac51aa0a', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': u'5da4bb9e-e471-3234-881d-b5992486b235', 'id': '5057bb1a-f247-420b-b2e6-58c7ac51aa0a', u'headers': {}}) kwargs:{})
2016-08-19 15:41:25 99600 +0200 - ovs-node1 - 2935/140020444075840 - celery/celery.worker.job - 298 - DEBUG - Task accepted: alba.add_cluster[5057bb1a-f247-420b-b2e6-58c7ac51aa0a] pid:14357
2016-08-19 15:41:25 99700 +0200 - ovs-node1 - 14357/140020444075840 - lib/scheduled tasks - 251 - INFO - Ensure single DEFAULT mode - ID 1471614085_fDM9Sbkff5 - Execution of task alba.alba_arakoon_checkup discarded
2016-08-19 15:41:26 06700 +0200 - ovs-node1 - 14357/140020444075840 - celery/celery.redirected - 253 - WARNING - 2016-08-19 15:41:26 06600 +0200 - ovs-node1 - 14357/140020444075840 - extensions/albacli - 252 - ERROR - Error: Arakoon_etcd.ProcessFailure(_)
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/extensions/plugins/albacli.py", line 103, in run
    raise RuntimeError(output['error']['message'])
RuntimeError: Arakoon_etcd.ProcessFailure(_)
2016-08-19 15:41:26 06800 +0200 - ovs-node1 - 14357/140020444075840 - celery/celery.redirected - 255 - WARNING - 2016-08-19 15:41:26 06700 +0200 - ovs-node1 - 14357/140020444075840 - extensions/albacli - 254 - DEBUG - Command: /usr/bin/alba get-alba-id --attempts=5 --config=etcd://127.0.0.1:2379/ovs/arakoon/test19-abm/config --to-json
2016-08-19 15:41:26 06800 +0200 - ovs-node1 - 14357/140020444075840 - celery/celery.redirected - 257 - WARNING - 2016-08-19 15:41:26 06800 +0200 - ovs-node1 - 14357/140020444075840 - extensions/albacli - 256 - DEBUG - stderr: 2016-08-19 15:41:26 41934 +0200 - ovs-node1 - 21790/0 - alba/cli - 0 - info - ETCD: etcdctl --peers=127.0.0.1:2379 get --quorum ovs/arakoon/test19-abm/configError:  100: Key not found (/ovs/arakoon/test19-abm) [897]
2016-08-19 15:41:26 06800 +0200 - ovs-node1 - 14357/140020444075840 - celery/celery.redirected - 259 - WARNING - 2016-08-19 15:41:26 06800 +0200 - ovs-node1 - 14357/140020444075840 - extensions/albacli - 258 - DEBUG - stdout: 
{"success":false,"error":{"message":"Arakoon_etcd.ProcessFailure(_)","exception_type":"unknown","exception_code":0}}
2016-08-19 15:41:26 07400 +0200 - ovs-node1 - 2935/140020444075840 - celery/celery.worker.job - 299 - ERROR - Task alba.add_cluster[5057bb1a-f247-420b-b2e6-58c7ac51aa0a] raised unexpected: RuntimeError(u'Arakoon_etcd.ProcessFailure(_)',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albacontroller.py", line 288, in add_cluster
    alba_backend.alba_id = AlbaCLI.run(command='get-alba-id', config=config, to_json=True, attempts=5)['id']
  File "/opt/OpenvStorage/ovs/extensions/plugins/albacli.py", line 103, in run
    raise RuntimeError(output['error']['message'])
RuntimeError: Arakoon_etcd.ProcessFailure(_)
```

Due to this error I am left with a list of backends that are stuck on the installing status. You cannot remove these from your list. (Deleting them via Albabackend.delete() doensn't help aswell)
![selection_032](https://cloud.githubusercontent.com/assets/17570109/17812241/7f169088-6626-11e6-8515-1083dd3245a2.png)
![selection_033](https://cloud.githubusercontent.com/assets/17570109/17812297/bff18bbc-6626-11e6-9750-feb9c2953d67.png)
### Setup

Hyperconverged setup
- Three nodes with each three disks for the back-end
### Package information
- openvstorage                       2.7.2-rev.3859.42b3488-1   amd64        openvStorage
- openvstorage-backend               1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin
- openvstorage-backend-core          1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps       1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin         1.2.2-rev.32.948a8c1-1 amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                  2.7.2-rev.3859.42b3488-1   amd64        openvStorage core 
- openvstorage-hc                    1.7.2-rev.675.37ca5b8-1    amd64        openvStorage Backend plugin HyperConverged
- openvstorage-health-check          2.0.0-rev.117.3212ea9-1    amd64        Open vStorage HealthCheck
- openvstorage-sdm                   1.6.2-rev.330.f06c8de-1    amd64        Open vStorage Backend ASD Manager
- openvstorage-test                  2.7.2-rev.980.0dbc80f-1    amd64        openvStorage autotest suite
- openvstorage-webapps               2.7.2-rev.3859.42b3488-1   amd64        openvStorage Web Applications

**Comment by khenderick** [comment]
Can we rename this ticket to "Etcd issue number 1.329.461.222" or something similar? Basically anything can fail if etcd doesn't work, so it doesn't make much sense to report - eventually if we use etcd long enough - every single line of code where we do a call to etcd.

**Comment by wimpers** [comment]
We should block the creation of a backend when another backend is  being created.

We will not fix the underlying problem so you can create multiple backends concurrently.

**Comment by khenderick** [comment]
@wimpers, concurrent backend creation should (already) be possible; it's just that sometimes etcd can't cope with the load and fails. But this is identical for almost all code that uses etcd.

**Comment by domsj** [comment]
The way I understand this ticket it has nothing fundamentally to do with creating multiple backends concurrently, so blocking that is besides the point.

The problem is that once in a while some operations might temporarily fail (such as storing something in etcd, or in alba or in arakoon or ...).
The question is what do you do in case of this sort of failure/unavailability?
- fail, and leave whatever it was doing in a half baked state
- retry right then and there, if it fails again roll back
- register the intent of the global action in an arakoon first, if that succeeds keep on retrying until it eventually succeeds

In my opinion the only correct option is something along the lines of my last suggestion, anything else will just lead to more similar tickets.

**Comment by khenderick** [comment]
@wimpers, as you scheduled this ticket for the Gilbert release and that one doesn't use Etcd, I assume that you want @domsj's comment (which is basically a full featured rollback) implemented?

**Comment by wimpers** [comment]
@kinvaris , @JeffreyDevloo  do we still see issues with creating multiple backends at once now that we use arakoon instead of etcd.

**Comment by wimpers** [comment]
Moved away from etcd and should not happen anymore.

**Comment by khenderick** [comment]
This ticket got closed, but one of the last discussions was not yet resolved. I've extracted it into a new ticket: #1370
