### ISSUE TITLE
Traceback when arakoon collapse failed

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#835]
Traceback in ovs-workers when arakoon collapse failed.

openvstorage: 2.7.1-rev.3769.d0e7b4e-1
arakoon: version: 1.9.8

```
2016-08-22 10:12:06 06900 +0200 - ovs-01.be-gen8-2 - 9182/140488436619072 - lib/scheduled tasks - 334276 - ERROR - Error during collapsing cluster ovsdb node jNkeV9q1hhm8IGRk
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/scheduledtask.py", line 411, in collapse_arakoon
    client.collapse(str(node), 2)
  File "<update_argspec>", line 5, in collapse
  File "/opt/OpenvStorage/ovs/extensions/db/arakoon/pyrakoon/pyrakoon/compat.py", line 152, in wrapped
    raise new_exception
ArakoonException: unknown failure
```

```
2016-08-22 10:12:06 69962 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249810 - info - 10.103.2.21:client_service:session=11 connection=10.103.2.21:client_service_52722 socket_address=ADDR_INET 10.103.2.21,40886
2016-08-22 10:12:06 70009 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249811 - info - connection=10.103.2.21:client_service_52722 COLLAPSE_TLOGS: n=2
2016-08-22 10:12:06 70019 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249812 - info - ... Start collapsing ... (n=2)
2016-08-22 10:12:06 70028 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249813 - info - Starting collapse
2016-08-22 10:12:06 70039 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249814 - info - Creating local store at /opt/OpenvStorage/db/arakoon/ovsdb/tlogs/head.db (lcnum=16384) (ncnum=8192)
2016-08-22 10:12:06 70101 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249815 - info - returning assuming no I "/opt/OpenvStorage/db/arakoon/ovsdb/tlogs/head.db": (Failure success); backtrace:; Raised by primitive operation at file "hotc.ml", line 63, characters 12-24; Called from file "src/node/local_store.ml", line 49, characters 2-62; Called from file "src/node/local_store.ml", line 277, characters 2-41; Called from file "src/node/batched_store.ml", line 57, characters 4-34; Called from file "src/node/store.ml", line 159, characters 4-48; Called from file "src/node/collapser.ml", line 183, characters 7-131; Called from file "src/core/lwt.ml", line 686, characters 20-24
2016-08-22 10:12:06 70127 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249816 - info - Going to collapse 212 tlogs
2016-08-22 10:12:06 70171 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249817 - info - Creating db clone at /opt/OpenvStorage/db/arakoon/ovsdb/tlogs/head.db.clone (throttling:0.000000)
2016-08-22 10:12:06 70257 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249818 - info - copy_file /opt/OpenvStorage/db/arakoon/ovsdb/tlogs/head.db /opt/OpenvStorage/db/arakoon/ovsdb/tlogs/head.db.clone (overwrite=true,throttling=0.000000)
2016-08-22 10:12:06 70311 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249819 - info - Unlinking "/opt/OpenvStorage/db/arakoon/ovsdb/tlogs/head.db.clone.tmp"
2016-08-22 10:12:06 70358 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249820 - info - Unlink of "/opt/OpenvStorage/db/arakoon/ovsdb/tlogs/head.db.clone.tmp" failed with ENOENT
2016-08-22 10:12:06 108716 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249821 - info - done: copy_file
2016-08-22 10:12:06 146538 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249822 - info - rename /opt/OpenvStorage/db/arakoon/ovsdb/tlogs/head.db.clone.tmp -> /opt/OpenvStorage/db/arakoon/ovsdb/tlogs/head.db.clone
2016-08-22 10:12:06 161616 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249823 - info - Creating local store at /opt/OpenvStorage/db/arakoon/ovsdb/tlogs/head.db.clone (lcnum=16384) (ncnum=8192)
2016-08-22 10:12:06 161676 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249824 - error - Exception during client request ((Failure success)) => rc:ff msg:unknown failure
2016-08-22 10:12:06 161724 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249825 - info - 10.103.2.21:client_service_52722: closing
2016-08-22 10:12:06 769047 +0200 - ovs-01.be-gen8-2 - 13425/0 - arakoon - 249826 - info - exiting session (11) connection=10.103.2.21:client_service_52721: End_of_file; backtrace:; Raised at file "src/core/lwt_sequence.ml", line 95, characters 10-15; Called from file "src/core/lwt_condition.ml", line 54, characters 21-47
```

**Comment by wimpers** [comment]
@matthiasdeblock  why did you create this ticket? The arakoon exception is 'unknown failure'.  What should the framework do?

**Comment by matthiasdeblock** [comment]
@wimpers The collapse (that failed) was triggered by the Framework. This trace was the output and this should be fixed.

**Comment by wimpers** [comment]
Nothing to be done on the Framework as it displays the error as presented by Arakoon. This has been tackled on the Arakoon side.
