### ISSUE TITLE
Ignore `Permission denied` during sync with reality

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#844]
In continuation of #741: OVS framework should ignore `Permission denied` and just skip the mount points during `sync with reality` or `configure_disk`. This because its possible that you experience these problems not only with Docker but also with other side applications.

```
2016-07-25 17:19:19 79200 +0200 - cmp04 - 4895/139806611666752 - celery/celery.worker.job - 188 - ERROR - Task ovs.storagerouter.configure_disk[2a27e8d2-9343-4f04-af38-cc4787fbc4b9] raised unexpected: OSError(13, 'Permission denied')
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 301, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1806, in configure_disk
    DiskController.sync_with_reality(storagerouter_guid)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 167, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 439, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 301, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/disk.py", line 169, in sync_with_reality
    partition_data['inode'] = rem.os.stat(mountpoint).st_dev
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/dist-packages/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
Exception: [Errno 13] Permission denied
```

**Comment by khenderick** [comment]
Most likely be fixed by #792

**Comment by kvanhijf** [comment]
Fixed by https://github.com/openvstorage/framework/issues/792

**Comment by wimpers** [comment]
Closed by PM.
