### ISSUE TITLE
`list index out of range` during `albanode.initialize_disk`

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#869]
While trying to initialize the alba disks we got this error: (happens alot)

```
2016-09-02 14:51:32 73800 +0200 - ovs-node2 - 23901/140523719677760 - celery/celery.worker.job - 288 - ERROR - Task albanode.initialize_disk[3293c372-d954-45db-a0b9-9ee6eb0604d0] raised unexpected: IndexError('list index out of range',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albanodecontroller.py", line 134, in initialize_disks
    partition = disk.partitions[0]
  File "/opt/OpenvStorage/ovs/dal/datalist.py", line 627, in __getitem__
    guid = self._guids[item]
IndexError: list index out of range
```

**Comment by wimpers** [comment]
@kinvaris is there a workaround?
