### ISSUE TITLE
KeyError during alba.checkup_maintenance_agents

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#898]
Backend seemed to be added but we cannot claim disks due to no maintenance agents present.
After looking in the logs we saw these:

```
2016-09-14 11:00:00 17600 +0200 - stor-202.be-gen8-1 - 11548/140561438689088 - lib/scheduled tasks - 350 - INFO - Ensure single CHAINED mode - ID 1473843600_SrqAyNDzVJ - New task alba.checkup_maintenance_agents with default params scheduled for execution
2016-09-14 11:00:00 19700 +0200 - stor-202.be-gen8-1 - 11548/140561438689088 - lib/alba - 351 - INFO - Loading maintenance information
2016-09-14 11:00:00 29900 +0200 - stor-202.be-gen8-1 - 11548/140561438689088 - lib/alba - 352 - INFO - Generating service worklog for mybackend-ssd
2016-09-14 11:00:00 32300 +0200 - stor-202.be-gen8-1 - 19559/140561438689088 - celery/celery.worker.job - 352 - ERROR - Task alba.checkup_maintenance_agents[ebc27251-eb3a-40b9-9f4f-103e799fbecd] raised unexpected: KeyError('<ovs.dal.hybrids.albanode.AlbaNode object at 0x7fd6ec0f64d0>',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/helpers/decorators.py", line 301, in new_function
    output = function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/albacontroller.py", line 1603, in checkup_maintenance_agents
    to_add[all_nodes[0]].append(service_name)
KeyError: <ovs.dal.hybrids.albanode.AlbaNode object at 0x7fd6ec0f64d0>
```

Apparently a known bug: https://github.com/openvstorage/framework-alba-plugin/pull/203

**Comment by kinvaris** [comment]
PASSED:

After patching the code and re-running: 

```
In [1]: from ovs.lib.albacontroller import AlbaController
In [2]: AlbaController.checkup_maintenance_agents()
```

They seemed to be present: `alba-maintenance_mybackend-hdd-P6Hof4myrotRLT0b start/running, process 12676`

Also restarted the `ovs-watcher-framework`, just to be sure.

Also as seen in the logs:

```
2016-09-14 11:17:55 01200 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 1 - INFO - Loading maintenance information
2016-09-14 11:17:55 07500 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 2 - DEBUG - * Maintenance QR4IZgELAlHklatb for mybackend-ssd on 10.106.2.33
2016-09-14 11:17:55 07600 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 3 - DEBUG - * Maintenance l9GNwVbRBQHbFpeO for mybackend-hdd on 10.106.2.33
2016-09-14 11:17:55 17500 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 4 - INFO - Generating service worklog for mybackend-ssd
2016-09-14 11:17:55 17500 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 5 - DEBUG - * Candidates for removal (unused node): [u'alba-maintenance_mybackend-ssd-QR4IZgELAlHklatb'] on 10.106.2.33
2016-09-14 11:17:55 17600 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 6 - DEBUG - * Candidate add (not enough services): alba-maintenance_mybackend-ssd-qqTB8N0wcSwndgbO on 10.106.2.13
2016-09-14 11:17:55 17600 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 7 - DEBUG - * Candidate add (not enough services): alba-maintenance_mybackend-ssd-hVriKr1Jl0hvGtjo on 10.106.2.11
2016-09-14 11:17:55 17600 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 8 - INFO - Applying service worklog for mybackend-ssd
2016-09-14 11:17:55 26700 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 9 - INFO - * Removed service alba-maintenance_mybackend-ssd-QR4IZgELAlHklatb on 10.106.2.33: OK
2016-09-14 11:17:55 41100 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 10 - INFO - * Added service alba-maintenance_mybackend-ssd-qqTB8N0wcSwndgbO on 10.106.2.13: OK
2016-09-14 11:17:55 53100 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 11 - INFO - * Added service alba-maintenance_mybackend-ssd-hVriKr1Jl0hvGtjo on 10.106.2.11: OK
2016-09-14 11:17:55 53100 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 12 - INFO - Finished service worklog for mybackend-ssd
2016-09-14 11:17:55 53200 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 13 - INFO - Generating service worklog for mybackend-hdd
2016-09-14 11:17:55 53300 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 14 - DEBUG - * Candidates for removal (unused node): [u'alba-maintenance_mybackend-hdd-l9GNwVbRBQHbFpeO'] on 10.106.2.33
2016-09-14 11:17:55 53300 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 15 - DEBUG - * Candidate add (not enough services): alba-maintenance_mybackend-hdd-P6Hof4myrotRLT0b on 10.106.2.34
2016-09-14 11:17:55 53300 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 16 - INFO - Applying service worklog for mybackend-hdd
2016-09-14 11:17:55 63600 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 17 - INFO - * Removed service alba-maintenance_mybackend-hdd-l9GNwVbRBQHbFpeO on 10.106.2.33: OK
2016-09-14 11:17:55 75700 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 18 - INFO - * Added service alba-maintenance_mybackend-hdd-P6Hof4myrotRLT0b on 10.106.2.34: OK
2016-09-14 11:17:55 75800 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/alba - 19 - INFO - Finished service worklog for mybackend-hdd
2016-09-14 11:17:55 75800 +0200 - stor-202.be-gen8-1 - 12201/139797088307008 - lib/scheduled tasks - 20 - INFO - Ensure single CHAINED mode - ID 1473844674_vXThbiK7sq - Task alba.checkup_maintenance_agents finished successfully
```
