### ISSUE TITLE
Post upgrade action failed with error: type object 'Upstart' has no attribute 'list_service_files'

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#938]
```
10.106.2.34    : Executing action upgrade_sdm
10.106.2.34    : Post upgrade action failed with error: type object 'Upstart' has no attribute 'list_service_files'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/tmp/tmp.SL0HnbeVWO/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/tmp/tmp.SL0HnbeVWO/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/opt/OpenvStorage/ovs/lib/helpers/..//albacontroller.py", line 1216, in upgrade_sdm
    version_info = node.client.get_update_information()
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 187, in get_update_information
    return self._call(requests.get, 'update/information', timeout=120, clean=True)
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 82, in _call
    raise RuntimeError(data.get('_error', 'Unknown exception: {0}'.format(data)))
RuntimeError: type object 'Upstart' has no attribute 'list_service_files'

10.106.2.33    : Executing action restart_arakoon_clusters
10.106.2.33    : Executing action restart_arakoon_clusters completed
10.106.2.33    : Executing action upgrade_alba_plugin
10.106.2.33    : Executing action upgrade_alba_plugin completed
10.106.2.33    : Executing action upgrade_sdm
10.106.2.33    : Post upgrade action failed with error: type object 'Upstart' has no attribute 'list_service_files'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/tmp/tmp.9AOLePZfUB/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/tmp/tmp.9AOLePZfUB/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict(kwargs))
  File "/opt/OpenvStorage/ovs/lib/helpers/..//albacontroller.py", line 1216, in upgrade_sdm
    version_info = node.client.get_update_information()
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 187, in get_update_information
    return self._call(requests.get, 'update/information', timeout=120, clean=True)
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 82, in _call
    raise RuntimeError(data.get('_error', 'Unknown exception: {0}'.format(data)))
RuntimeError: type object 'Upstart' has no attribute 'list_service_files'
```

**Comment by kinvaris** [comment]
Also seeing this problem during method: `ovs.storagerouter.get_update_status`

```
2016-09-21 18:06:43 04700 +0200 - stor-202.be-gen8-1 - 30178/139947926800192 - celery/celery.worker.job - 248 - ERROR - Task ovs.storagerouter.get_update_status[0bc16649-5d5d-4314-a2b7-b55fa7b853f7] raised unexpected: RuntimeError(u"type object 'Upstart' has no attribute 'list_service_files'",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1533, in get_update_status
    output = function(root_client)
  File "/opt/OpenvStorage/ovs/lib/helpers/..//albacontroller.py", line 1119, in get_metadata_sdm
    candidate = node.client.get_update_information()
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 187, in get_update_information
    return self._call(requests.get, 'update/information', timeout=120, clean=True)
  File "/opt/OpenvStorage/ovs/extensions/plugins/asdmanager.py", line 82, in _call
    raise RuntimeError(data.get('_error', 'Unknown exception: {0}'.format(data)))
RuntimeError: type object 'Upstart' has no attribute 'list_service_files'
```

**Comment by khenderick** [comment]
Duplicates openvstorage/alba-asdmanager#109 (which is already fixed)
