### ISSUE TITLE
RuntimeError: got fault response volumeCreate during creation of vdisk

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/framework#955]
## Problem description

During creation of a vdisk I encountered the following error for **_every vdisk_** I was trying to create.
Stacktrace: 

```
2016-09-23 20:28:07 79500 +0200 - cmp02 - 14516/139881865062208 - lib/vdisk - 565 - ERROR - Caught exception during clone, trying to delete the volume. got fault 
response volumeCreate
2016-09-23 20:28:07 80600 +0200 - cmp02 - 30789/139881865062208 - celery/celery.worker.job - 571 - ERROR - Task ovs.vdisk.create_new[5531d84d-3184-43f1-b578-26fcb
01da677] raised unexpected: RuntimeError('got fault response volumeCreate',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/vdisk.py", line 562, in create_new
    node_id=str(storagedriver.storagedriver_id))
RuntimeError: got fault response volumeCreate
```

The vdisk were made in the model but not on the mountpoints of the vpool.
## Temporary solution

Removed all vdisks from the model

```
from ovs.dal.lists.vdisklist import VDiskList
for d in VDiskList.get_vdisks():
   ...:     d.delete()
```

Truncuated the volumes manually:

```
for i in $(ls | grep myvpool); do for j in `seq 1 5`; do truncate -s 10G /mnt/${i}/jonas${j}.raw; done; done
```
### Setup

Hyperconverged setup
- 10 vpools
### Package information
- openvstorage                          2.7.3-rev.4022.59fbd9b-1                                 amd64        openvStorage
- openvstorage-backend                  1.7.3-rev.713.f2fab03-1                                  amd64        openvStorage Backend plugin
- openvstorage-backend-core             1.7.3-rev.713.f2fab03-1                                  amd64        openvStorage Backend plugin core
- openvstorage-backend-webapps          1.7.3-rev.713.f2fab03-1                                  amd64        openvStorage Backend plugin Web Applications
- openvstorage-cinder-plugin            1.2.2-rev.38.dcc3b76-1                                   amd64        OpenvStorage Cinder plugin for OpenStack
- openvstorage-core                     2.7.3-rev.4022.59fbd9b-1                                 amd64        openvStorage core
- openvstorage-hc                       1.7.3-rev.713.f2fab03-1                                  amd64        openvStorage Backend plugin HyperConverged
- openvstorage-sdm                      1.6.3-rev.372.0cfe8a2-1                                  amd64        Open vStorage Backend ASD Manager
- openvstorage-webapps                  2.7.3-rev.4022.59fbd9b-1                                 amd64        openvStorage Web Applications

**Comment by JeffreyDevloo** [comment]
The output of the manual truncuate was truncate: cannot open ‘/mnt/myvpool01/jonas1.raw’ for writing: Input/output error.
Not the fault of framework.
