### ISSUE TITLE
The add_vpool logic cannot be executed in parallel

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/framework#958]
Propable race condition when creating first 2 vpools really quick makes `add_vpool` crash:

```
2016-09-26 18:22:04 96400 +0200 - cmp02 - 10257/140002619791168 - extensions/sshclient - 145 - ERROR - Command "service ovs-watcher-volumedriver start" failed with output "" and error "start: Job is already running: ovs-watcher-volumedriver"
2016-09-26 18:22:04 96400 +0200 - cmp02 - 10257/140002619791168 - extensions/servicemanager - 146 - ERROR - Start ovs-watcher-volumedriver failed, 
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/extensions/services/upstart.py", line 188, in start_service
    client.run('service {0} start'.format(name))
  File "/opt/OpenvStorage/ovs/extensions/generic/sshclient.py", line 59, in inner_function
    return outer_function(self, *args, **kwargs)
  File "/opt/OpenvStorage/ovs/extensions/generic/sshclient.py", line 256, in run
    raise CalledProcessError(exit_code, command, output)
CalledProcessError: Command 'service ovs-watcher-volumedriver start' returned non-zero exit status 1
2016-09-26 18:22:05 06700 +0200 - cmp02 - 30983/140002619791168 - celery/celery.worker.job - 162 - ERROR - Task ovs.storagerouter.add_vpool[496ef768-e1dd-4bce-a437-12cf44273be5] raised unexpected: RuntimeError('Start ovs-watcher-volumedriver failed. ',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 565, in add_vpool
    ServiceManager.start_service(watcher_volumedriver_service, client=root_client)
  File "/opt/OpenvStorage/ovs/extensions/services/upstart.py", line 192, in start_service
    raise RuntimeError('Start {0} failed. {1}'.format(name, output))
RuntimeError: Start ovs-watcher-volumedriver failed. 
```

**Comment by wimpers** [comment]
@kinvaris can you remove the vPools or are you stuck with non-working vPools?

**Comment by khenderick** [comment]
Reverted change chaining the tasks, as it turns out running these tasks in parallel should be supported. To be checked/locked:
- Data usage or free space
- Services start/stop
- Getting free ports

In the meantime, I'd advise to be careful when running them in parallel, @kinvaris.

**Comment by wimpers** [comment]
QA requires support for multiple vPools being deployed at the same time.  They are currently already doing so and are afraid that not running them in parallel will atke to much time.

@kinvaris do you have a timing of how long the vPool creation takes in your tests?

**Comment by JeffreyDevloo** [comment]
A fresher ticket has been updated with all necessary information https://github.com/openvstorage/framework/issues/1575
Closing this one.
