### ISSUE TITLE
'NoneType' object has no attribute 'storagedriver'

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/framework#967]
Install: Unstable

After clicking upgrade 'storage driver' in the GUI, we get the following error:

```
2016-09-29 16:21:21 98400 +0200 - perf-grav-05 - 92915/140380291651392 - celery/celery.worker.strategy - 97970 - INFO - Received task: ovs.storagerouter.get_update_status[1edc736f-606d-4dd6-a32c-3bf37a39f570]

2016-09-29 16:21:21 98500 +0200 - perf-grav-05 - 92915/140380291651392 - celery/celery.pool - 97971 - DEBUG - TaskPool: Apply <function _fast_trace_task at 0x7faccfcf66e0> (args:('ovs.storagerouter.get_update_status', '1edc736f-606d-4dd6-a32c-3bf37a39f570', (u'172.20.20.31',), {}, {'utc': True, u'is_eager': False, 'chord': None, u'group': None, 'args': (u'172.20.20.31',), 'retries': 0, u'delivery_info': {u'priority': None, u'redelivered': False, u'routing_key': u'generic.#', u'exchange': u'generic'}, 'expires': None, u'hostname': 'celery@perf-grav-05', 'task': 'ovs.storagerouter.get_update_status', 'callbacks': None, u'correlation_id': u'1edc736f-606d-4dd6-a32c-3bf37a39f570', 'errbacks': None, 'timelimit': (None, None), 'taskset': None, 'kwargs': {}, 'eta': None, u'reply_to': u'5e472792-7eeb-3ccf-bdfe-3424ae370858', 'id': '1edc736f-606d-4dd6-a32c-3bf37a39f570', u'headers': {}}) kwargs:{})

2016-09-29 16:21:21 98600 +0200 - perf-grav-05 - 92915/140380291651392 - celery/celery.worker.job - 97972 - DEBUG - Task accepted: ovs.storagerouter.get_update_status[1edc736f-606d-4dd6-a32c-3bf37a39f570] pid:2287

2016-09-29 16:21:22 23700 +0200 - perf-grav-05 - 2287/140380291651392 - lib/scheduled tasks - 97965 - INFO - Send data task scheduling started

2016-09-29 16:21:23 64600 +0200 - perf-grav-05 - 92915/140380291651392 - celery/celery.worker.job - 97973 - ERROR - Task ovs.storagerouter.get_update_status[1edc736f-606d-4dd6-a32c-3bf37a39f570] raised unexpected: AttributeError("'NoneType' object has no attribute 'storagedriver'",)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/storagerouter.py", line 1549, in get_update_status
    output = function(root_client)
  File "/opt/OpenvStorage/ovs/lib/helpers/..//storagerouter.py", line 1669, in get_metadata_volumedriver
    alba_downtime.append(('ovs', 'proxy', service.alba_proxy.storagedriver.vpool.name))
AttributeError: 'NoneType' object has no attribute 'storagedriver'
```

**Comment by khenderick** [comment]
Caused by an incorrect manual "cleanup"
